### ISSUE TITLE
Types: breakText won't accept undefined height

### ISSUE THREAD

**Issue by gricey432** [clientIO/joint#1002]
[breakText](https://github.com/clientIO/joint/blob/6a22e207f9f66bc044be6fc99bf11e5538187d56/src/core.js#L432) allows [undefined height](https://github.com/clientIO/joint/blob/6a22e207f9f66bc044be6fc99bf11e5538187d56/src/core.js#L580) however the [types](https://github.com/clientIO/joint/blob/6a22e207f9f66bc044be6fc99bf11e5538187d56/types/joint.d.ts#L2022) use `dia.Size` which doesn't allow an undefined height.

**Comment by kumilingus** [comment]
Thanks @gricey432 . Fixed in `v2.2.1`.
