### ISSUE TITLE
Namespaces missing in typescript definitions

### ISSUE THREAD

**Issue by jucowic** [clientIO/joint#1011]
Hi!

I'm unable to find **joint.shapes.html**. I found this when i tried the html template example: https://resources.jointjs.com/tutorial/html-elements.

Namespace is missing from joint.d.ts

It is possible to create html templated elements when js-files are added as is to the project and you use them 'blind', but in my case that is not possible. I would need the features imported (import * as joint from 'jointjs')

Jointjs version 2.2.1

**Comment by kumilingus** [comment]
`joint.shapes.html` is not part of JointJS (it was only mentioned in the tutorial). You have to define the typescript definition on your side. You can import `joint.shapes.html.ElementView` separately and pass it to the paper via `elementView` option.
