### ISSUE TITLE
pointerclick event doesn't always fire

### ISSUE THREAD

**Issue by chipit24** [clientIO/joint#1017]
Here is a minimal JSFiddle example that reproduces the issue: http://jsfiddle.net/69akf85t/13.

To see the bug, click one of the rectangles, then click the other rectangle. You will notice that as you click back and forth between the two rectangles, the `pointerclick` event handler doesn't always run.

I've tested this in Chrome 70 and Safari 12, and in both browsers it seems that on average, I have to click the rectangle twice for it to highlight.

![pointerclick_bug](https://user-images.githubusercontent.com/7561061/49387437-d373d300-f6ef-11e8-81ff-a16b52cb384e.gif)

**Comment by chipit24** [comment]
We're currently working around this bug by listening to `pointerdown` instead of `pointerclick`.

**Comment by kumilingus** [comment]
Please try to set `paper.options.clickThreshold = 10` and test again. It's probably because there is a `mousemove` event between `mousedown` and `mouseup`.

**Comment by chipit24** [comment]
Thanks! I was testing with `2.1.4` locally, but using `2.2.1` with `clickThreshold` works well.
