### ISSUE TITLE
 Is there a way to let the element's port listen to whether it is already linked?

### ISSUE THREAD

**Issue by wangsen1989** [clientIO/joint#1025]
When the element's port is being connected and connected, I want to change the port's style.【for example: As shown in the figure below】
 is there any way to make the port monitor its connection status?
The version of jointjs that  I am using   is  2.2.0.
Thank you!

![image](https://user-images.githubusercontent.com/24807073/50438513-41936a80-0929-11e9-8663-faa429bb51d8.png)

**Comment by kumilingus** [comment]
You can listen to `link:connect` and `link:disconnect` paper event.
```
paper.on('link:connect', function(linkView, evt, elementViewConnected, magnet, arrowhead) {});
```
https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#dia.Paper.events

**Comment by wangsen1989** [comment]
> You can listen to `link:connect` and `link:disconnect` paper event.
> 
> ```
> paper.on('link:connect', function(linkView, evt, elementViewConnected, magnet, arrowhead) {});
> ```
> https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#dia.Paper.events


Thank you !

The method ```paper.on('link:connect', function() {});```can not be triggered when I use
  ```
 const link = new joint.dia.Link({
        source: { id: sourceCellId, port: "pBottom" },
        target: { id: targetCellId, port: "pTop" },
        ...defaultLinkCfg
  }); 
  this.graph.addCell(link);

```
It only works when I manually connect a line to another port.

But I solved it in another way.

![image](https://user-images.githubusercontent.com/24807073/50578397-9a588b00-0e74-11e9-96fd-7af11e4a59a9.png)

![image](https://user-images.githubusercontent.com/24807073/50578393-844aca80-0e74-11e9-90b5-026e8b79cee1.png)
