### ISSUE TITLE
toJSON omit the default attributes and they are not implicitly reconstructable by the cell 'type'

### ISSUE THREAD

**Issue by Renhj90520** [clientIO/joint#1026]
Hi, I created a custom shape by extending the joint.dia.Element, and set its type, then I called toJSON to save the graph, when I restored it by fromJSON, some attributes were missing.
I found a comment in joint.dia.cell.js as following:
// omit the default attributes as they are implicitly reconstructable by the cell 'type'. 
Apperantly they were not reconstructed. 
Then I changed joint.dia.Element.extend to joint.dia.Element.define, the problem was solved.
Could you please explain the differences between extend and define, and why default attributes can't be reconstructed by its cell type when using extend. 
Thank you.

**Comment by kumilingus** [comment]
Hi, I think the way you had used `extend` was not correct. `define` is just syntactic sugar for `extend`,  that make sure the shape `type` is correctly set on the model and attributes are merged with the parent class.

https://github.com/clientIO/joint/blob/master/src/joint.dia.cell.js#L719-L729

**Comment by Renhj90520** [comment]
@kumilingus  Hi, thank you for your reply, I notice that the method define has this line:
joint.util.setByPath(joint.shapes, type, Cell, '.');
Maybe this is the key. And my code using extend is as following, is there something wrong?
import * as joint from 'jointjs';
export const IconShape = joint.dia.Element.extend({
  markup: [
    '<g class="rotatable">',
    '<rect class="body"/>',
    '<image class="icon"/><text class="label"/>',
    '</g>'
  ].join(''),
  portMarkup: '<circle class="port-body"/>',
  portLabelMarkup: '<text class="port-label"/>',
  defaults: joint.util.defaultsDeep(
    {
      type: 'grid.Component',
      size: { width: 60, height: 60 },
      inPorts: [],
      outPorts: [],
      isDropped: false,
      ports: {
        groups: {
          in: {
            position: { name: 'left' },
            attrs: {
              '.joint-port-label': {
                fill: '#65717a',
                'font-size': 12,
                'letter-spacing': '0.01em'
              },
              '.joint-port-body': {
                fill: '#fff',
                stroke: '#263743',
                'stroke-width': 2,
                r: 5.5,
                magnet: 'passive'
              }
            },
            label: { position: { name: 'left', args: { y: 10 } } }
          },
          out: {
            position: { name: 'right' },
            attrs: {
              '.joint-port-label': {
                fill: '#65717a',
                'font-size': 12,
                'letter-spacing': '0.01em'
              },
              '.joint-port-body': {
                fill: '#263743',
                stroke: '#fff',
                'stroke-width': 2,
                r: 5.5,
                magnet: true
              }
            },
            label: { position: { name: 'right', args: { y: 10 } } }
          },
          items: []
        }
      },
      attrs: {
        '.': {
          magnet: false
        },
        '.body': {
          stroke: '#bfccdd',
          'stroke-opacity': 1,
          'stroke-width': 0,
          fill: 'white',
          filter: {
            name: 'dropShadow',
            args: { dx: 1, dy: 2, blur: 8, color: '#000', opacity: 0.1 }
          },
          'ref-width': '100%',
          'ref-height': '100%',
          rx: '50%',
          ry: '50%'
        },
        text: { 'pointer-events': 'none' },
        '.label': {
          text: 'Component',
          'ref-x': 0.5,
          'ref-y': 80,
          ref: '.body',
          'text-anchor': 'middle',
          fill: '#a0a7ad',
          'letter-spacing': '0.02em',
          'font-size': 15
        },
        '.icon': {
          width: 25,
          height: 25,
          'ref-x': 0.5,
          'ref-y': 0.5,
          ref: '.body',
          'x-alignment': 'middle',
          'y-alignment': 'middle',
          'clip-path': 'url(#icon-clip)'
        }
      }
    },
    joint.dia.Element.prototype.defaults
  ),
  initialize() {
    this.on('change:icon', this.onChangeIcon, this);
    this.on('change:label', this.onChangeLabel, this);
    this.on('change:isDropped', this.onChangeIsDropped, this);
    this.onChangeIcon();
    this.onChangeLabel();
    this.onChangeIsDropped();
    joint.dia.Element.prototype.initialize.apply(this, arguments);
  },
  isDropped() {
    return this.get('isDropped');
  },
  onChangeIcon() {
    const icon = this.get('icon');
    this.attr('.icon/xlink:href', icon);
  },
  onChangeLabel() {
    const label = this.get('label');
    this.attr('.label/text', label);
  },
  onChangeIsDropped() {
    const isDropped = this.get('isDropped');
    if (isDropped) {
      this.attr('.body/rx', '50%');
      this.attr('.body/ry', '50%');
      const portsIn = this.get('portsIn') || [];
      const portsOut = this.get('portsOut') || [];
      const ins = this.createPortItems('in', portsIn);
      const outs = this.createPortItems('out', portsOut);
      this.prop(
        'ports/items',
        ins.concat(outs),
        joint.util.assign({ rewrite: true })
      );
    } else {
      this.attr('.body/rx', 2);
      this.attr('.body/ry', 2);
      this.prop('ports/items', []);
    }
  },
  createPortItem(group, name) {
    return {
      id: name + group,
      group,
      attrs: { text: { text: name } }
    };
  },
  createPortItems(group, names) {
    return joint.util.toArray(names).map(this.createPortItem.bind(this, group));
  }
});

**Comment by kumilingus** [comment]
When you use `extend` make sure to store the class under the path based on the type.

type: **"standard.Rectangle"** -->  namespace: joint.shapes.**standard.Rectangle** = joint.dia.Element.extend(/* .. /*)

If you are using TS and `extend` you will have to create your own namespace and pass it to the graph and paper via `cellNamespace` resp. `cellViewNamespace` options.

**Comment by Renhj90520** [comment]
@kumilingus  I got it. Thank you very much.
