### ISSUE TITLE
[Rappid 2.4.0] Problem with backwards compatiblity events?

### ISSUE THREAD

**Issue by wbombardellis** [clientIO/joint#1040]
On the `joint.dia.ElementView.dragLinkStart` method, the `joint.dia.CellView.prototype.pointerdown` method is called sending all current arguments to it. (rappid.js:14425)

It turns out that `arguments` is an array containing the magnet on position 1, but `joint.dia.CellView.prototype.pointerdown` expects the value for `x` on position 1 (rappid.js:13298). So, `joint.dia.CellView.prototype.pointerdown` goes on with the wrong value assigned to `x`.

I guess this should be corrected, or am I missing something?

**Comment by kumilingus** [comment]
Thanks, this is indeed a bug. 

https://github.com/clientIO/joint/blob/master/src/joint.dia.element.js#L1043

Should be changed to `joint.dia.CellView.prototype.pointerdown.apply(linkView, evt, x, y);`
