### ISSUE TITLE
Is there a way to add a pointerclick event for a port in JointJS?

### ISSUE THREAD

**Issue by rohit-ravikoti** [clientIO/joint#1041]
Hello!
I'm creating a UML-like diagram using JointJS and want to start adding some custom interactions.

This is mainly for detecting when a port has been clicked. I've tried a couple of things:

* Use the cell:mouseover event to find the DOM element for the port that is being hovered added an eventListener for "click". That didn't work and never fires the event.
```
paper.on("cell:mouseover", (cell, evt) => {
    ...
    let activePort = getHoveredPort(cell, evt);
    if (activePort) {
        const el = document.elementFromPoint(evt.clientX, evt.clientY);
        el.addEventListener("click", () => {
            // my code here
        })
    }
});
```
* I tried extending joint.dia.Paper and add the following to events:
```
'mousedown .joint-port [event]': 'onevent',
'touchstart .joint-port [event]': 'onevent',
```

Ideally, I would like to be able to create a custom event handler for ports so I can use it like so:
```
paper.on("port:pointerclick", (cell, port, evt) => {
    // my logic here
})
```

**Comment by kumilingus** [comment]
There is a built-in event for magnets - `element:magnet:pointerclick` (https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#dia.Paper.events).

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/3967880/52162577-9ec3ce00-26d6-11e9-9318-f96d80faff40.png">

**Comment by rohit-ravikoti** [comment]
Okay perfect! I was able to use that event to detect if it was clicked. How about `mouseover` a magnet?

**Comment by kumilingus** [comment]
```
paper.on('element:mouseover', function(view, evt) {
  var port = view.findAttribute('port', evt.target);
  if (port) {
    console.log(port)
  }
});
```

**Comment by rohit-ravikoti** [comment]
Okay, makes sense. Thanks!
