### ISSUE TITLE
Custom port layout can't account for ports in other groups

### ISSUE THREAD

**Issue by candronikos** [clientIO/joint#1044]
I am creating nodes that have a custom layout. What I'm trying to do is create input and output ports that are stacked vertically. The problem is, the port layout function can't see how many ports of the other groups have been added already so the input and output ports are overlapped.

If the port layout function could access the attributes of it's respective nodes, I could accommodate for this. All we have are the input arguments `ports, elBBox and opt`.

Is there a way to update `opt` when calling `model.addPort()`?

**Comment by vtalas** [comment]
I'd suggest the `absolute` port layout for this scenario.
I'm having an element with groups `greens` and `blacks`

set the `absolute` positioning in the group definition 
```
green: {
    position: 'absolute',
},
blacks: {
    position: 'absolute',
},

```

catch the event when a port(s) is added
```
graph.on('ports:add', function(element, addedPorts) {

    // get desired groups, sort the output if necessary
    const inputs = element.getPorts().filter(function(item) {
        return item.group === 'greens' || item.group ==='blacks';
    });

    const size = element.size();
    let elBBox = g.Rect(0, 0, size.width, size.height);

    // use the port layout function
    const positions = joint.layout.Port.line(inputs, elBBox, { start: elBBox.origin(), end: elBBox.topRight() });

    positions.forEach(function(port) {
        element.portProp(port.id, 'args', {
            x: port.x,
            y: port.y
        })
    })
});
```
then, you should see ports from both groups evenly distributed on the top of the element after calling the `elements.addPorts([{group:'blacks'},{group:'greens'}])`

**Comment by candronikos** [comment]
Hi @vtalas, that worked.

Is there an analogous event like `ports:add` on a node model I can add in the node definition block? Would be easier if I need to add libraries of nodes that add ports in different ways.

**Comment by vtalas** [comment]
most likely you need the `graph.on('add' ... )`.

Small debugging hint: with `paper.on('all', console.log)` or `graph.on('all', console.log)` you'll be able to catch all events.
