### ISSUE TITLE
Link inspector is not working on Angular6 implementation.

### ISSUE THREAD

**Issue by exonianp** [clientIO/joint#1046]
![image](https://user-images.githubusercontent.com/6937118/52891192-0af00880-3192-11e9-8428-436b8696a1d6.png)

Successfully installed the Angular6 version of KitchenSink.

Yet, the inspector is not working for the links in this version. Any  help will be greatly appreciated.

I noticed that initialisation of the links in the inspector is actually missing.

e.g.

In the "static version" we have:

`    initializeToolsAndInspector: function() {

            this.paper.on({

                'element:pointerup': function(elementView) {

                    var element = elementView.model;

                    if (this.selection.collection.contains(element)) return;

                    new joint.ui.FreeTransform({
                        cellView: elementView,
                        allowRotation: false,
                        preserveAspectRatio: !!element.get('preserveAspectRatio'),
                        allowOrthogonalResize: element.get('allowOrthogonalResize') !== false
                    }).render();

                    new joint.ui.Halo({
                        cellView: elementView,
                        handles: App.config.halo.handles
                    }).render();

                    this.selection.collection.reset([]);
                    this.selection.collection.add(element, { silent: true });

                    this.paper.removeTools();

                    this.createInspector(element);
                },

                'link:pointerup': function(linkView) {

                    var link = linkView.model;

                    var ns = joint.linkTools;
                    var toolsView = new joint.dia.ToolsView({
                        name: 'link-pointerdown',
                        tools: [
                            new ns.Vertices(),
                            new ns.SourceAnchor(),
                            new ns.TargetAnchor(),
                            new ns.SourceArrowhead(),
                            new ns.TargetArrowhead(),
                            new ns.Segments,
                            new ns.Boundary({ padding: 15 }),
                            new ns.Remove({ offset: -20, distance: 40 })
                        ]
                    });

                    this.selection.collection.reset([]);
                    this.selection.collection.add(link, { silent: true });

                    var paper = this.paper;
                    joint.ui.Halo.clear(paper);
                    joint.ui.FreeTransform.clear(paper);
                    paper.removeTools();

                    linkView.addTools(toolsView);

                    this.createInspector(link);
                },

                'link:mouseenter': function(linkView) {

                    // Open tool only if there is none yet
                    if (linkView.hasTools()) return;

                    var ns = joint.linkTools;
                    var toolsView = new joint.dia.ToolsView({
                        name: 'link-hover',
                        tools: [
                            new ns.Vertices({ vertexAdding: false }),
                            new ns.SourceArrowhead(),
                            new ns.TargetArrowhead()
                        ]
                    });

                    linkView.addTools(toolsView);
                },

                'link:mouseleave': function(linkView) {
                    // Remove only the hover tool, not the pointerdown tool
                    if (linkView.hasTools('link-hover')) {
                        linkView.removeTools();
                    }
                }

            }, this);

            this.graph.on('change', function(cell, opt) {

                if (!cell.isLink() || !opt.inspector) return;

                var ns = joint.linkTools;
                var toolsView = new joint.dia.ToolsView({
                    name: 'link-inspected',
                    tools: [
                        new ns.Boundary({ padding: 15 }),
                    ]
                });

                cell.findView(this.paper).addTools(toolsView);

            }, this)
        },`

Whereas in the angular6 version we only have:

`   initializeHaloAndInspector() {

        this.paper.on('element:pointerup link:options', (cellView: joint.dia.CellView) => {

            const cell = cellView.model;

            if (!this.selection.collection.contains(cell)) {

                if (cell.isElement()) {

                    new joint.ui.FreeTransform({
                        cellView,
                        allowRotation: false,
                        preserveAspectRatio: !!cell.get('preserveAspectRatio'),
                        allowOrthogonalResize: cell.get('allowOrthogonalResize') !== false
                    }).render();

                    this.haloService.create(cellView);
                    this.selection.collection.reset([]);
                    this.selection.collection.add(cell, { silent: true });
                }

                this.inspectorService.create(cell);
            }
        });
    }`

Thanking you in advance.

**Comment by vtalas** [comment]
Hi, 
TS versions of KitchenSink (KitchenSinkTS, KitchenSinkReact, KitchenSinkAngular6) are missing some pieces. That's actually a bug and it will be fixed in the following release. 

Meanwhile, you can update your app using this gist: https://gist.github.com/vtalas/70820bcbf65fabe5e45b20a79f41b016
