### ISSUE TITLE
Custom "HeaderedRectangle" Shapes

### ISSUE THREAD

**Issue by exonianp** [clientIO/joint#1048]
![screenshot 2019-02-21 at 11 15 20](https://user-images.githubusercontent.com/6937118/53157409-214ef780-35ca-11e9-9363-9a38d704a5be.png)

I am wondering how we can use joint.js/rappid to create shapes that behave as rectangles with headers but are not rectangles (have edges, are cylindrical etc) as seen in this picture. 

Adding them as svg images it is the easiest option yet "image" has to be extended in order to allow for overlay of title and description over the image. 

Is there a way to modify the standard.HeaderedRectangle  so that it can cater for such a need?

**Comment by vtalas** [comment]
shapes like `standard.Polyline` or `standard.Path` in the `joint.shapes` namespace may fit your needs perfectly. Get some inspiration from the demo solutions e.g. here https://github.com/clientIO/joint/blob/v2.2.1/demo/shapes/src/standard.js

**Comment by exonianp** [comment]
Thank you but perhaps, I failed to make myself clear:
One can easily overload the standard.image and standard.cylinder, body with refD and have an svg path in the body.

e.g. you can copy paste the standard.image rename it to standard.path as follows:

` {
                     type: 'standard.Path',
                     size: { width: 100, height: 100 },
                     attrs: {
                         root: {
                             tabindex: 4,
                             dataTooltipPosition: 'left',
                             dataTooltipPositionSelector: '.joint-stencil'
                         },
                         body: {
                             fill: 'transparent',
                             fillOpacity: 0.5,
                             refD: 'M 0 5 10 0 C 20 0 20 20 10 20 L 0 15 Z'
                         },
                         label: {
                             text: 'Path',
                             fontFamily: 'Roboto Condensed',
                             fontWeight: 'Normal',
                             fontSize: 11,
                             fill: '#c6c7e2',
                             
                         }
                     }
                 },`

And you get the shape as defined in the refD.

Similarly you can do the same for cylinder:

`{
                     type: 'standard.Cylinder',
                     size: { width: 40, height: 45 },
                     attrs: {
                         
                         root: {
                             dataTooltip: 'Cylinder',
                             dataTooltipPosition: 'left',
                             dataTooltipPositionSelector: '.joint-stencil'
                         },
                         body: {
                             fill: 'transparent',
                             stroke: '#31d0c6',
                             strokeWidth: 2,
                             strokeDasharray: '0',
                             refD: 'M 0 5 10 0 C 20 0 20 20 10 20 L 0 15 Z'
                         },
                         top: {
                             
                             fill: 'transparent',
                             stroke: '#31d0c6',
                             strokeWidth: 0,
                             strokeDasharray: '0'
                         },
                         label: {
                             text: 'cylinder',
                             fill: '#c6c7e2',
                             fontFamily: 'Roboto Condensed',
                             fontWeight: 'Normal',
                             fontSize: 11,
                             strokeWidth: 0
                         },
                     }
                 }
             ],`


But you cannot do this in rectangle/headeredrectangle.

So the key is to go to say...

`interface HeaderedRectangleSelectors {
            root?: attributes.SVGAttributes;
            body?: attributes.SVGPathAttributes;
           // body?: attributes.SVGRectAttributes;
            header?: attributes.SVGPathAttributes;
            headerText?: attributes.SVGTextAttributes;
            bodyText?: attributes.SVGTextAttributes;
        }

        class HeaderedRectangle extends dia.Element {
            constructor(
                attributes?: dia.Element.GenericAttributes<HeaderedRectangleSelectors>,
                opt?: dia.Graph.Options
            )
        }`

But this doesn't work as well because there is no support for refD in the core for the rectangular shape.

Can we have it please?

**Comment by kumilingus** [comment]
No, you can't do this with the `HeaderedRectangle`, because the body of this shape is an SVGRectangle (`<rect/>` element won't recognize `d` attribute).

Create a custom element based on the `HeaderedRectangle` instead.

You need to take the source code of the `standard.HeaderedRectangle`, copy it, rename it to e.g. `standard.HeaderedPath`, change the `markup` so the body is an `SVGPath`,  define TS for this shape. Now you can use `refD` attribute within the shape.

We have currently no plans adding this element to the standard namespace.

**Comment by exonianp** [comment]
Thank you very much Roman. Thank you for the solution; this is what we are going to do. 
We will post our code here if you like so that others may use it as well; it ought to be a great addition to the project.
