### ISSUE TITLE
Select and drag to create shape

### ISSUE THREAD

**Issue by Supamiu** [clientIO/joint#1049]
When using rappid and jointjs, it could be nice to have a way to drag to create, in order to provide a different UX for our users, so they don't have to drag a shape inside the paper and then resize it.

Here is a gif to explain my idea, as I don't think it's explained properly ^^
![2019-02-22_15-35-37](https://user-images.githubusercontent.com/11519203/53249155-bd0a6180-36b7-11e9-840e-85fdc38b15b4.gif)

I couldn't find a way inside the docs or inside the tutorials to achieve something like this. I tried to hook on `blank:pointerdown` to create a shape, but couldn't find a way to resize it after.

Do we have a simple way to achieve this that I missed or is it something that could be added?

**Comment by kumilingus** [comment]
Hi @Supamiu,
yeah, using `blank:pointerdown` is the right way to go. Please check out the code below.
```js
paper.on({
    'blank:pointerdown': function(evt, x, y) {
        var graph = this.model;
        var origin =  new g.Point(x, y);
        var element = new joint.shapes.standard.Rectangle();
        graph.startBatch('add_element');
        element.position(x, y);
        element.resize(1, 1);
        element.addTo(graph);
        evt.data = { origin: origin, element: element };
    },
    'blank:pointermove': function(evt, x, y) {
        var origin = evt.data.origin;
        var element = evt.data.element;
        var current = new g.Point(x, y);
        var diff = current.difference(origin);
        var bbox = element.getBBox();
        if (diff.x > 0) {
            bbox.width = diff.x;
        } else if (diff.x < 0) {
            bbox.x = origin.x + diff.x;
            bbox.width = -diff.x;
        }
        if (diff.y > 0) {
            bbox.height = diff.y;
        } else if (diff.y < 0) {
            bbox.y = origin.y + diff.y;
            bbox.height = -diff.y;
        }
        element.set({
            position: { x: bbox.x, y: bbox.y },
            size: { width: bbox.width, height: bbox.height }
        });
    },
    'blank:pointerup': function() {
        this.model.stopBatch('add_element');
    }
});
```
