### ISSUE TITLE
ERROR TypeError: Cannot read property 'addTools' of undefined

### ISSUE THREAD

**Issue by oceanmanish** [clientIO/joint#1052]
i am implementing jointjs in ionic framework v4
i dont know why i am getting  "Cannot read property 'addTools' of undefined" .
And other thing is working fine
 
this is my code 

this.graph = new joint.dia.Graph();
    this.paper = new joint.dia.Paper({
      el: document.getElementById('myMap'),
      width: 800,
      height: 600,
      gridSize: 1,
      model: this.graph,
      perpendicularLinks: true,
      restrictTranslate: true
    });
  
    this.paper.on({
      'element:pointerdown': function(elementView, evt) {
          evt.data = elementView.model.position();
      },

      'element:pointerup': function(elementView, evt, x, y) {

          var coordinates = new g.g.Point(x, y);
          var elementAbove = elementView.model;
          var elementBelow = this.model.findModelsFromPoint(coordinates).find(function(el) {
              return (el.id !== elementAbove.id);
          });
        
          // If the two elements are connected already, don't
          // connect them again (this is application-specific though).
          this.graph = new joint.dia.Graph();
          
          if (elementBelow && this.graph.getNeighbors(elementBelow).indexOf(elementAbove) === -1) {
              
              // Move the element to the position before dragging.
              elementAbove.position(evt.data.x, evt.data.y);

              // Create a connection between elements.
              var link = new joint.shapes.standard.Link();
              link.source(elementAbove);
              link.target(elementBelow);
              link.addTo(this.graph);
              // Add remove button to the link.
              var tools = new joint.dia.ToolsView({
                  tools: [new joint.linkTools.Remove()]
              });
            
              link.findView(this).addTools(tools);  // **### getting error here** 
          }
      }
  });

**Comment by kumilingus** [comment]
You're adding a link to a graph, which is not connected to any paper. That's why no `linkView` is rendered and could be found.

Specifically, you should not do this `this.graph = new joint.dia.Graph();`
You should do something like that `link.addTo(this.model);`
