### ISSUE TITLE
How to change the grid pattern?

### ISSUE THREAD

**Issue by nusudoers** [clientIO/joint#1059]
I am using the drawgrid function with JointJS version 2.2.1 and am wondering how to use different patterns like mesh or doubleMesh. I tried with the given documentation but I always end up having "dot" on the canvas.
Is there some specific version of JointJs that it supports?
I have a toggle button which enables or disables the grid on the screen. I would like to have a doubleMesh pattern but unable to render it.While looking at the demoes here https://resources.jointjs.com/demos/paper; it looks pretty straightforward.
self.paper.drawGrid({
    name: 'doubleMesh',
    args: [
        { color: 'red', thickness: 1 }, // settings for the primary mesh
        { color: 'green', scaleFactor: 5, thickness: 5 } //settings for the secondary mesh
]});
Any help would be appreciated.

**Comment by vtalas** [comment]
Hi, setting the grid dynamically is not straightforward, indeed. 
You need to call the `setGrid` and also the `drawGrid` aftewards. Where `setGrid` arguments follow the `options.drawGrid` structure (https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#dia.Paper.prototype.options.drawGrid )

so, for example:

```
paper.setGrid('doubleMesh').drawGrid();
```
or with an extra args:
```
paper.setGrid({
    name: 'doubleMesh',
    args: [
        { color: 'red' },
        { color: 'green', thickness: 10, scaleFactor: 8 }
    ]
}).drawGrid();
```
Note, that you can define your own pattern, for inspiration check the built-in patterns implementations at `joint.dia.Paper.gridPatterns` namespace
