### ISSUE TITLE
[bug][inspector] valueRegExp is broken

### ISSUE THREAD

**Issue by revhelix** [clientIO/joint#1062]
Hello,

I've been looking at using the valueRegExp key in the demo and in my own project.

With the demo and my own project, the regex is failing miserably.

It seems the data item becomes complete garbage and doesn't present an alert. And the underlying data structure has "$1somethingsomething$3" and after a bit it has a series of $1's and $3's.

For example in the demo (KitchenSinkTS) the rectangle (standard.rectangle) has a regex on the "Text" input item in the group "Text", the regex only allows for letters, no spaces or any other characters.

This is clearly manipulating the text on the rectangle object, and I see the following: 
<img width="481" alt="Screen Shot 2019-04-04 at 7 53 50 PM" src="https://user-images.githubusercontent.com/1694339/55595790-6d39a400-5713-11e9-817e-f4c7d34ea522.png">

**Comment by kumilingus** [comment]
Hi, `valueRegExp`is meant to be used along with `defaultValue`. e.g.

```
transform: {
  type: 'range',
  min: 1,
  max: 5,
  unit: 'x scale',
  defaultValue: 'scale(1)',
  valueRegExp: '(scale\\()(.*)(\\))',
  group: 'marker-target',
  index: 1
}
```

What are you trying to achieve? Could you share the `label/text` inspector definition? Thanks

**Comment by revhelix** [comment]
As I stated in my original message, you need not look any further than the demos that come with the 2.4 package, Look at the Demo KitchenSinkTs:



`"standard.Rectangle": {
        inputs: {
          attrs: {
            label: {
              text: {
                type: "content-editable",
                label: "Tooltipped",
                defaultValue: "Letters",
                valueRegExp: "[a-zA-Z]{0,}",
                overwrite: true,
                group: "text",
                index: 1,
                attrs: {
                  label: {
                    "data-tooltip": "inputs.attrs.label.text",
                    "data-tooltip-position": "right",
                    "data-tooltip-position-selector": ".joint-inspector"
                  }
                }
              },`
```

**Comment by kumilingus** [comment]
Thanks for providing the actual regex you have used. What are you trying to achieve?

**Comment by revhelix** [comment]
I am trying to achieve some form of error state to tell the user to put something in correctly.

Either way, the rectangle box in the demo should not be displaying "$1GobblyGook$3".

**Comment by kumilingus** [comment]
Sure, I agree. We'll look into this.

Note, there is a demo showing how to validate the inspector fields and give the user some feedback.
https://resources.jointjs.com/docs/rappid/v2.4/ui.html#ui.Inspector.validation
