### ISSUE TITLE
Mouse events are ignored when trying to use react-select

### ISSUE THREAD

**Issue by TBoonX** [clientIO/joint#1067]
Mouse events are ignored when trying to use react-select.
In my app I use jointJS+Rappid and sometimes I open a modal (generic modal, also used without jointJS but the same content) in which a select from react-select is used.
In this select the mouse events are partly-working: to open the options of the select it works (gets focus), but selecting one value has no effect (no onClick or something) - no handler is triggered - not even in JointJS.
I tested 1.x and 2.x of react-select. I am using rappid 2.4.0 and jointjs 2.2.1

How do I disable the stealing of mouse click events?

**Comment by kumilingus** [comment]
Hi, any chance providing a JSFiddle or send us a demo so we can debug it?
