### ISSUE TITLE
How to disable callback?

### ISSUE THREAD

**Issue by JeroenWang** [clientIO/joint#1069]
some times I only want to remove a link, but I don't want to trigger  
 graph.on('remove', function(){ 
console.log()}
)
how can I to do?

**Comment by kumilingus** [comment]
Hi, you can't or at least should not prevent triggering events. There is the Backbone `{ silent: true }` option you can pass to prevent triggering events, but in that case, the view of the link would not be removed from the paper (DOM).

Here's a solution.
```
graph.on('remove', function(cell, opt) {
  if (opt.noAction) return;
  // do you action
}

link.remove({ noAction: true });
```
