### ISSUE TITLE
Click event triggered on dragging an element

### ISSUE THREAD

**Issue by sourabhrajendu** [clientIO/joint#1074]
Hi,

On dragging an element, click event is triggered which should't be the case ideally. Is this a known issue or i am missing something? Demo : https://jsfiddle.net/rajendu/x3z0avrf/19/

Also, double click is considered as two single clicks.

**Comment by kumilingus** [comment]
There was most likely a bug in version `2.1.0`. Try to run the JSFiddle using `https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.2.1/joint.js`.

**Comment by sourabhrajendu** [comment]
I tried the same with version 2.1.1 but the issue still persists.
https://jsfiddle.net/rajendu/x3z0avrf/27/

**Comment by sourabhrajendu** [comment]
Thanks @kumilingus . This solved the drag issue but doubleclick still triggers the click event. Is there a fix for that?

**Comment by kumilingus** [comment]
> Also, double click is considered as two single clicks.

This just mimics the browser behaviour. I do not consider this as a bug.

![image](https://user-images.githubusercontent.com/3967880/57541160-af778600-734e-11e9-9682-e549a19c3f12.png)

You can differentiate this on the application level (https://stackoverflow.com/questions/5497073/how-to-differentiate-single-click-event-and-double-click-event).

**Comment by sourabhrajendu** [comment]
Thanks for the help again, @kumilingus .
