### ISSUE TITLE
How to set larger paper inside smaller div with scrolling feature?

### ISSUE THREAD

**Issue by sourabhrajendu** [clientIO/joint#1075]
Hi,

I want to set fixed width and height for my drawing canvas and a larger paper inside it which can be navigated by scrolling over the div.

I tried doing it here -- https://jsfiddle.net/rajendu/x3z0avrf/58/

But the div css seems to be overridden by the paper dimensions. How can I restrict the paper inside the div and use scroll for overflowing part?

**Comment by kumilingus** [comment]
Use a wrapper element and set `overflow: scroll;` on that.
`<div class="paper-container" style="overflow: scroll;"><div class="paper"/></div>`

**Comment by sourabhrajendu** [comment]
I tried what you suggested. https://jsfiddle.net/rnp3sLyh/18/
This doesn't work.

**Comment by kumilingus** [comment]
It seems you had a typo in CSS.
```
#paper-container {
  width: 300px;
  height: 300px;
  overflow: scroll;
  border: 1px solid green;
}
```

**Comment by sourabhrajendu** [comment]
Oops! This was a blunder. Thanks btw.

**Comment by kumilingus** [comment]
You are welcome.
