### ISSUE TITLE
3 Requests: onConnect(), onDisconnect() and removal of unconnected links

### ISSUE THREAD

**Issue by jankazemier** [clientIO/joint#108]
I have 3 requests:
1) add a onConnected
I now have to look for id's (i.e. link.get('source').id && link.get('target').id) to see if it is connected.  Also, this is already true before a mouseUp event, so it is already connected on snapping (i.e. magnet), in stead of when releasing the mouse.

2) add a onDisconnect
Same as above, except now for removing a link

3) removal of unconnected links
I don't like unconnected links, so I would like to automatically remove links when a source or target is missing on a mouseUp event. I now have worked around it, and hacked this into my project combining the above check for connectedness and a pointerup event. Would be nice to have in the library itself.

**Comment by ColinFrick** [comment]
I have the same requests. With 0.9.3 released just released, any ETA for 1.0?

**Comment by kumilingus** [comment]
For 3.: implemented in 63c0616abc3aa011d87fa08db1d52e82bc80f50f. Please check the `linkPinning` paper option. When set to `false` no unconnected links are permitted.

We're about to release `v0.9.5` next week.
We're planning to come out with `v1.0` this year.

**Comment by elyas-bhy** [comment]
+1
