### ISSUE TITLE
Publish a new minor version to update jquery version?

### ISSUE THREAD

**Issue by hsandovalskytap** [clientIO/joint#1086]
Hello,

our tooling let us know about a [CVE regarding jquery](https://www.npmjs.com/advisories/796) in Jointjs. Now, you guys already have the jquery version (3.4.1) that fix this problem in `package.json` but the latest published version (2.2.1) does not reference it. 

Are you guys to publish this soon? Would it be possible to publish a minor version with this change?

Thanks for all the great work!

**Comment by SimplyCorey** [comment]
This would be great if this could happen.  Right now we can not fully upgrade to 3.x and would like to close the CVE issue.
