### ISSUE TITLE
`element: magnet :pointerclick` event not triggered

### ISSUE THREAD

**Issue by wyzgo** [clientIO/joint#1118]
element:magnet:pointerclick event will not trigger when ``interactive.addLinkFromMagnet = false`` is set. Or is there any other way to get the magnet?

**Comment by wyzgo** [comment]
I am not sure if it is the right way. My solution to this problem is:

**Comment by kumilingus** [comment]
Hi @wyzgo, this is a nice workaround for sure. It's still a bug though. Thanks for reporting this.

**Comment by kumilingus** [comment]
Fixed in #2110.
