### ISSUE TITLE
[Bug][Version 3.0.0]ReferenceError: joint is not defined when using manhattan

### ISSUE THREAD

**Issue by jmesa-sistel** [clientIO/joint#1119]
When moving a cell using manhattan with links I get and error in manhattan.mjs in the line [#92](https://github.com/clientIO/joint/blob/ef8c5059aa65d513f6223ef15417edbaaead8e80/src/routers/manhattan.mjs#L92)
ERROR ReferenceError: joint is not defined
    at Object.fallbackRouter ...
    at router ...
    at child.manhattan .....
    at child.findRoute ....
    at child.updateConnection ....
    at child.update ....
    at child.confirmUpdate ....
    at child.updateView .....
    at child.updateViewsBatch .....
    at child.updateViews .....

@kumilingus Can you check it before release 3.0.1?
I think import joint is missing in manhattan.mjs or something similar
Maybe you can import routers only like in LinkView.mjs

**Comment by vtalas** [comment]
Thank you for pointing this out, it's great someone is already playing with the ES6 joint. It's fixed by the #1120
