### ISSUE TITLE
Jointjs v3 problem with import

### ISSUE THREAD

**Issue by lciolecki** [clientIO/joint#1125]
Hi,

I have updated jointjs to version 3.0.1 and after that I have some error like `Uncaught TypeError: Cannot read property 'shapes' of undefined`.  It look likes problem with import.. I use webpack with npm configuration:`"jointjs": "^3.0.1",` and in my jsx file I import jointjs by `import joint from 'jointjs/index'`.

**Comment by vtalas** [comment]
hi , there is no default import, you need to import all
`import * as joint from 'jointjs'`  - imports whole package, with plugins, shapes ...
or  you can import just some parts you actually need e.g :
`import { Cell, Paper, Graph } from 'jointjs/src/dia/index.mjs';`

for further inspiration follow the source codes in this demo: https://github.com/clientIO/joint/tree/master/demo/layout

**Comment by lciolecki** [comment]
Thanks, it works!
