### ISSUE TITLE
Unable to set grid with JointJS v3

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/joint#1130]
Creating a paper with parameter 'drawGrid' seems to be ignored in v3.
Tried both `{ drawGrid: 'mesh' }` and `{ drawGrid: {  name: 'mesh' } }`  without success.
This was working fine in v2.

**Comment by kumilingus** [comment]
What `gridSize` do you have? i.e. `paper.options.gridSize`

**Comment by JoseGoncalves** [comment]
10

**Comment by kumilingus** [comment]
This works for me. Do you mind sharing some code with us? Thank you.
```
new joint.dia.Paper({
    gridSize: 10,
    drawGrid: { name: 'mesh' }
});
```

**Comment by JoseGoncalves** [comment]
Humm... I'm using JointJS ESM with a Vue.js app. Maybe something related with ESM?
Nevertheless, I will recheck and, if I still have the issue I will share the code with you.

**Comment by JoseGoncalves** [comment]
Rechecked my code and everything seems OK.
Please check it at https://github.com/JoseGoncalves/vue-jointjs

**Comment by kumilingus** [comment]
It seems there is no `joint.css` loaded. So the paper grid has no size.

**Comment by JoseGoncalves** [comment]
Oops... just noticed my problem... forgot to import the JointJS CSS.
Fixed in the repository.

**Comment by JoseGoncalves** [comment]
BTW, Is there any other way to do the JointJS import in order to get a minimal image?
I ask this because my simple Vue.js demo when built for production has a 712KB image size, while the same demo with JointJS v2 has a size of 608KB.

**Comment by kumilingus** [comment]
You can cherry-pick files from jointjs `src`, that you need. This one worked for me.
```
import * as joint from 'jointjs/src/core.mjs';
import * as standard from 'jointjs/src/shapes/standard.mjs';
joint.shapes = { standard };
```

**Comment by JoseGoncalves** [comment]
Thanks. That works but webpack gives a warning:
```
"export 'shapes' (imported as 'joint') was not found in 'jointjs/src/core.mjs'
 @ ./src/main.js
```
This works better for me (without warnings) and generates a 620KB package:
```
import * as joint from 'jointjs/dist/joint.core';
```

**Comment by vtalas** [comment]
> import * as joint from 'jointjs/src/core.mjs';
> import * as standard from 'jointjs/src/shapes/standard.mjs';
> joint.shapes = { standard };

hi, for some reason this piece shouldn't be there: `joint.shapes = { standard };` it works fine without it, resulting in the **478KiB** bundle.

Please note you need to be careful with the `cellViewNamespace` for the `dia.Paper` and `cellNamespace`  option for the `dia.Graph` in this setup. Otherwise, you could encounter the `main.js:47 Uncaught Error: dia.ElementView: markup required` error`

this is the right way how to sort this out 
```

**Comment by JoseGoncalves** [comment]
@vtalas I managed to import a minimal JointJS to my Vue.js plugin by cherry picking in the sources, and without the need to fiddle with namespaces, in this way:
```javascript
import 'jointjs/dist/joint.core.css';

import { dia } from 'jointjs/src/core.mjs';
import * as standard from 'jointjs/src/shapes/standard.mjs';

export default {
	install: function (Vue) {
		let joint = { dia };
		joint.shapes = { standard };
		Object.defineProperty(Vue.prototype, '$joint', { value: joint });
	}
};
```
In this way I get a Vue.js+JointJS JS bundle with **552 KiB** and a CSS bundle with **44.9 KiB**:
![Screenshot from 2019-07-03 10-41-31](https://user-images.githubusercontent.com/3037740/60581786-71f80d80-9d7f-11e9-9fb9-79ab435f2d52.png)

**Comment by JoseGoncalves** [comment]
Complementing my previous info, here is a graphical vizualization of the bundle given by [Webpack Bundle Analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer):

![Screenshot from 2019-07-03 11-26-48](https://user-images.githubusercontent.com/3037740/60584901-52b0ae80-9d86-11e9-9101-708d82054be5.png)
