### ISSUE TITLE
Element click events freeze browser when graph generated from large JSON

### ISSUE THREAD

**Issue by 1silvertiger** [clientIO/joint#1131]
When I try to render a graph with 1000 elements using `graph.fromJSON()`, the element click events freeze the browser for about 20 seconds (latest version of Chrome) and then run. I don't have this problem when rendering the graph from an adjacency list. I have a [codepen](https://codepen.io/silvertiger/pen/dBKzQz?editors=1111) to demonstrate. *Note: it takes forever (upward of several minutes) to load*. The adjacency list and raw JSON are [here](https://gist.github.com/1silvertiger/dd0852a1efd6670879374e84ac97e9ca). Any idea why this is happening?

**Comment by kumilingus** [comment]
Hi, please see the comments inline.

```js
// 1. The Mahnattan router is not meant to be used with large graphs
joint.routers.manhattan = joint.routers.normal;
// 2. The Jumpover connector is not meant to be used with large graphs
joint.connectors.jumpover = joint.connectors.normal;

var graph = new joint.dia.Graph();
var paper = new joint.dia.Paper({
    el: document.getElementById('paper'),
    width: 800,
    height: 600,
    model: graph,
    async: true,
    sorting: joint.dia.Paper.sorting.APPROX
});

fetch('https://gist.githubusercontent.com/1silvertiger/dd0852a1efd6670879374e84ac97e9ca/raw/bc9f86b84399b5405c613ce6354d0ca96f798799/jointjs.json').then(response => {
    response.json().then(graphJSON => {

        // 3. The graph json is invalid (there is a cell with id=100 missing but some of the links referring it)
        graphJSON.graph.cells.push({ id: 100, type: 'standard.Rectangle', size: { width: 50, height: 50 }});

        graph.fromJSON(graphJSON.graph);
        paper.fitToContent({ useModelGeometry: true, allowNewOrigin: 'any', padding: 50 });
    });
});
```

We can improve the performance of `manhattan` router and `jumpover` connector by adding some 2d hash maps of cells. I am not sure whether this helps with such a huge graphs (6k cells) though.

**Comment by hijoncon** [comment]
@kumilingus @1silvertiger is there a method to show "loader" when the dom is still rendering?

**Comment by kumilingus** [comment]
You can use `progress` option of [paper.unfreeze()](https://resources.jointjs.com/docs/jointjs/v3.2/joint.html#dia.Paper.prototype.unfreeze) method.

Here's an example of a simple loader (https://github.com/clientIO/joint/blob/master/demo/performance/async.js#L72-L103)
and how to update it (https://github.com/clientIO/joint/blob/master/demo/performance/async.js#L193-L207).

In the demo, try to change `batchSize` to `1` and see the loader.

**Comment by hijoncon** [comment]
@kumilingus is there a better way to create a group/cluster? I work fine but grouping them the browser still freezes. I think because I basically adding each node into a group, this approach `[...1000].forEach(data => this.group.embed(data));`
