### ISSUE TITLE
JointJS  > 3.0 Incorrect work of the export method when the joint variable is not initialized

### ISSUE THREAD

**Issue by kafnevod** [clientIO/joint#1132]
Hi there!
In order to implement the link-to-link connection mechanism in our project, we are moving from version 2. to version 3.0.2 and faced with a problem.
We use in the Ember  environment
During initialization:
```
_(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('backbone'), require('lodash'), require('jquery')) :
    typeof define === 'function' && define.amd ? define(['exports', 'backbone', 'lodash', 'jquery'], factory) :
    (global = global || self, factory(global.joint = {}, global.Backbone, global._, global.$));
}(this, function (exports, Backbone, _, $) { 'use strict';_
```
...
factory is called as 

`factory(exports, require('backbone'), require('lodash'), require('jquery')`

not as
`(global = global || self, factory(global.joint = {}, global.Backbone, global._, global.$))`

In this case global variable joint remain unitialized and not linked with exports variable
and not initialized in lines 28156-28157:
```
exports.layout = layout$1;
exports.format = format$1;
exports.version = version;
exports.shapes = index$4;
...
```

In method define() of Cell object (lines 11437-11449) 
```
           if (typeof joint !== 'undefined' && has(joint, 'shapes')) {
                setByPath(joint.shapes, type, Cell, '.');
            }
```
method` setByPath() `is not called 
and  `define() `method in our Ember-project
`joint.shapes.basic.Generic.define(...)`
works incorrectly

I resolve this problem by adding operator
`var joint = exports;`
if factory method of jointjs:
```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('backbone'), require('lodash'), require('jquery')) :
    typeof define === 'function' && define.amd ? define(['exports', 'backbone', 'lodash', 'jquery'], factory) :
    (global = global || self, factory(global./*joint*/ = {}, global.Backbone, global._, global.$));
}(this, function (exports, Backbone, _, $) { 'use strict';
    **var joint = exports;**
    Backbone = Backbone && Backbone.hasOwnProperty('default') ? Backbone['default'] : Backbone;
```
**But not sure that this is the right decision.

What do you recommend in this case?**

**Comment by kumilingus** [comment]
Please see https://github.com/clientIO/joint/issues/1133#issuecomment-509155062.
