### ISSUE TITLE
HTML in JointJS using ES6 import

### ISSUE THREAD

**Issue by samnb** [clientIO/joint#1134]
Hi guys. Thanks for creating and publishing of such a useful toll. I am just getting started with [Html elements tutorial](https://resources.jointjs.com/tutorial/html-elements). With libraries from CDN it works. But if I try to import the libs from node_modules using ES6 import, the html elements aren't rendered, although I installed the exact same versions of jquery, lodash, backbone and jointjs.

<hr>

**Using CDN**

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.4.0/backbone-min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jointjs/3.0.2/joint.min.js">
</script>
```
<img src="https://user-images.githubusercontent.com/22834492/60769120-5b79eb00-a0cc-11e9-828f-0695289dd8cc.png" target="_" width="600">

<hr>

**Using ES6 import**

```js
import "jointjs/dist/joint.min.css";
import "./styles.css";

import * as $ from 'jquery';
import * as _ from 'lodash';
import * as Backbone from 'backbone';
import * as joint from 'jointjs';

/*
// alternatively
import $ from 'jquery';
import _ from 'lodash';
import Backbone from 'backbone'; 
import * as joint from 'jointjs';
*/
```

<img src="https://user-images.githubusercontent.com/22834492/60769043-a7786000-a0cb-11e9-8405-afc75a9362cb.png" target="_" width="600">

<hr>

I've checked out already the issues #198 #201 #757 and #907 

 Any thoughts ?

**Comment by samnb** [comment]
A workaround solution regarding to this it to add jointjs into window object after importing.

```js
import * as joint from 'jointjs';
window.joint = joint;
```

**Comment by kumilingus** [comment]
It seems it is related to https://github.com/clientIO/joint/issues/1133.

**Comment by samnb** [comment]
@kumilingus Thanks a lot

**Comment by yfwz100** [comment]
This can be fixed by specifying `cellViewNamespace`:

```js
new joint.dia.Paper({
  el: this.$el,
  model: this.graph,
  width: '100%',
  height: '100%',
  cellViewNamespace: joint.shapes,
})
```

**Comment by samnb** [comment]
@yfwz100 Thanks a lot
