### ISSUE TITLE
Failed to compile with create-react-app due to a missing library in jointjs

### ISSUE THREAD

**Issue by konekoya** [clientIO/joint#1135]
Hi there,

I'm trying to use jointjs with react (initialized with create-react-app) but have come across a problem

After creating a fresh react app with CRA. I then installed joinjs with yarn and created a hello world example. But when I run `yarn start`, the CLI is giving me the following error:

```
Failed to compile.

./node_modules/joinjs/lib/index.js
Module not found: Can't resolve 'fs-base' in '/Users/joshua/Desktop/dev/sanbox/react-with-joint-js/node_modules/joinjs/lib'
```

I'm not quite sure what is actually going on here. Any help would be greatly appreciated! Thanks. 

A reproducible example can be found [here](https://github.com/konekoya/jointjs-with-cra)

And a question while I'm trying to integrate joinjs with React. Is there an official docs section which documents how to do so? I've googled a couple of times today and the other day but without luck

**Comment by samnb** [comment]
@konekoya Try to add the latest jointjs version

``` 
yarn add jointjs@3.0.2
```

**Comment by konekoya** [comment]
Thanks, @samnb! This is so embarrassing but I've installed the wrong package... Sorry about the trouble. What a Monday 😅
