### ISSUE TITLE
Security issue for Lodash

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/joint#1138]
There is a [security issue with Lodash < 4.17.12](https://www.npmjs.com/advisories/1065).
Because JointJS specifies a fixed Lodash version of 4.17.11, it't impossible to fix this security issue with the command "npm audit fix".
Please upgrade Lodash in package.json or, what I think is better, set the JointJS dependencies to allow for automatic patch upgrades, i.e.:

```json
  "dependencies": {
    "backbone": "~1.4.0",
    "dagre": "~0.8.4",
    "graphlib": "~2.1.7",
    "jquery": "~3.4.1",
    "lodash": "~4.17.12"
  },
```

**Comment by kumilingus** [comment]
Fixed with 47b3d570d08fc240adaddc6a8d98705810009645.

**Comment by JoseGoncalves** [comment]
@kumilingus When will be released a new version with this fix?

**Comment by kumilingus** [comment]
`v3.0.3` is out now.
