### ISSUE TITLE
Problem building angular app with jointjs on IE11

### ISSUE THREAD

**Issue by jmesa-sistel** [clientIO/joint#1154]
Hello
I have a problem with angular using your library
I created the next issue in angular/cli [angular issue #15233](https://github.com/angular/angular-cli/issues/15233#issuecomment-517715120) but they point me that the problem is in your side.
Can you take a look?

**Comment by kumilingus** [comment]
Does this help https://github.com/clientIO/joint/pull/1153?

**Comment by jmesa-sistel** [comment]
@kumilingus Yes, It works. Should I close it?

**Comment by kumilingus** [comment]
Thanks, I am closing it now. Fixed in `v3.0.4`.
