### ISSUE TITLE
Calling dia.Paper.cancelRenderViews causes error

### ISSUE THREAD

**Issue by JCook21** [clientIO/joint#1161]
The documentation for the project states that dia.Paper should have a cancelRenderViews method and this method does exist in the types files in the project. It does not appear to exist in the Paper file and trying to call the method results in an error. Should this method be present or has it been removed and the documentation hasn't been updates?

**Comment by kumilingus** [comment]
Hi, right. It's a leftover. The `cancelRenderViews` has been removed from the paper in favour of `paper.freeze()`. I'll update the documentation and TS. Thanks.
