### ISSUE TITLE
How to connect the middle of two images ？

### ISSUE THREAD

**Issue by lunjingjie** [clientIO/joint#1162]
![image](https://user-images.githubusercontent.com/30899997/63732459-0033d000-c8a7-11e9-9abc-bc0564e4ab94.png)

the problem like the image in webpack environment , i want to connect the middle of two images，thanks！

**Comment by kumilingus** [comment]
Please, provide more info on this (JSFiddle, source code). There should be no difference whether you connecting an image or circle.
