### ISSUE TITLE
Type definition Cell.remove is missing "ui"

### ISSUE THREAD

**Issue by Sorin314** [clientIO/joint#1165]
Hey,

I've got a problem with Rappid 3.0.1 using TypeScript.

Documentation about LinkTools.Remove:
https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#linkTools.Remove

```
function(evt) {
    this.model.remove({ ui: true, tool: this.cid });
}
```

Using the follow code, is not compliant to the type definition:

```
action: function(evt, view) {
      view.model.remove({ui: true});
    }
```
> "Argument of type '{ui: boolean; }' is not assignable to paramter of type 'DisconnectableOptions"

If I change the type definition to `(opt? : any)` instead of `(opt?: Cell.DisconnectableOptions)` and use the `{ui: true}` option, my tool action is working like expected.

Am I missing a cruical point in the documentation or is the missing {ui: true} option really the source of the problem?

**Comment by kumilingus** [comment]
You've done well. The `DisconnectableOptions` options should allow adding any custom properties along with the `disconnectLinks` option.
```ts
interface DisconnectableOptions extends Options {
   disconnectLinks?: boolean;
}
```
