### ISSUE TITLE
Selection and LinkTools are not removed for invalid link, when linkPinning equals false

### ISSUE THREAD

**Issue by EduardHuck** [clientIO/joint#1167]
Hello,

I am using Rappid 3.0.1 with TypeScript and currently working on the `linkPinning `Option of the `joint.dia.Paper`.

**Problem:**
If you drop the answer on a blank space inside the paper, the selection and tools are not removed, despite the link being automatically removed.

**Expected Behaviour:**
If you drop the answer on a blank space inside the paper, the selection and tools are removed with the removal of the link.

![LinkPinning_Selection_Bug](https://user-images.githubusercontent.com/54625464/63850533-909c0e80-c994-11e9-9b5a-9939ab1c3550.gif)

I already compared my App to the kitchensink and I can find no difference regarding the selection, halo and tools.

Unfortunately I cannot reproduce this behaviour inside the KitchenSink DemoApp.

Any idea what I am missing or which other parts of Joint/Rappid I need to look at, for using linkPinning == false

**The code I use:**

Paper: 
```
{
    width: 1591,
    height: 871,
    gridSize: 30,
    drawGrid: { name: 'mesh' },
    model: graph,
    defaultRouter: {
      name: 'metro',
      args: {
        step: 30
      }
    },
    defaultConnector: {
      name: 'jumpover',
      args: {
        size: 10
      }
    },
    linkPinning: false
  }
```
Halo-Handle:
```
{
  name: 'link-answer',
  position: joint.ui.Halo.HandlePosition.SE,
  icon: 'assets/svgs/Answer.svg',
  events: { pointerdown: 'startLinking', pointermove: 'doLink', pointerup: 'stopLinking' },
  attrs: {
    '.handle': {
      'data-tooltip-class-name': 'small',
      'data-tooltip': 'Drag to create an answer',
      'data-tooltip-position': 'left',
      'data-tooltip-padding': 15
    }
  }
}

```

Selection Service:
```
    this.paper.on('link:pointerup', (linkView: joint.dia.LinkView) => {
      const link = linkView.model;

      const ns = joint.linkTools;
      const toolsView = new joint.dia.ToolsView({
        name: 'remove',
        tools: [new ns.Boundary({ padding: 15 }), new ns.Remove({ offset: -20, distance: 40 })]
      });

      this.selection.collection.reset([]);

      this.selection.collection.add(link, { silent: true });

      const paper = this.paper;
      joint.ui.Halo.clear(paper);
      paper.removeTools();

      linkView.addTools(toolsView);
    });
```

**Comment by EduardHuck** [comment]
I further investigated this issue and compared the events on the paper and graph.

**KitchenSinkAngularDemo:**
![KitchenSinkAngularDemoEvents](https://user-images.githubusercontent.com/54625464/63868091-4035a880-c9b6-11e9-9468-03e0e0df06a5.JPG)

**My Application:**
![CustomAppEvents](https://user-images.githubusercontent.com/54625464/63868086-3ca22180-c9b6-11e9-8e32-f7c2203bebcf.JPG)

The only difference is the missing `render:done` Event in my App. 

I'm not using `joint.ui.FreeTransform`.
Initially the KitchenSinkDemo uses `joint.ui.FreeTransform({...}).render()`, which was my first guess for the missing `render:done` Event, but even after the removal of `joint.ui.FreeTransform` the `render:done` Event is still triggered

**Comment by EduardHuck** [comment]
I have found a solution to this issue.

Using the `async: true` option for my `joint.dia.Paper` led to a `render:done` event, and thus to the expected behaviour.

I am not sure which side effects this has, but for now this solves my problem.

**Comment by kumilingus** [comment]
I don't think this is a bug. What happened is that you were adding a link tool after the linkView was removed from the paper. You can check whether the linkView is still in the paper at the time of `link:pointerup` event as shown below.

```js
    this.paper.on('link:pointerup', (linkView: joint.dia.LinkView) => {
      const link = linkView.model;
      const paper = this.paper;
       if (!paper.findViewByModel(link)) {
         // view has been removed from the paper
         return;
      }

      const ns = joint.linkTools;
      const toolsView = new joint.dia.ToolsView({
        name: 'remove',
        tools: [new ns.Boundary({ padding: 15 }), new ns.Remove({ offset: -20, distance: 40 })]
      });

      this.selection.collection.reset([]);

      this.selection.collection.add(link, { silent: true });

      joint.ui.Halo.clear(paper);
      paper.removeTools();

      linkView.addTools(toolsView);
    });
```

**Comment by EduardHuck** [comment]
Thanks for your reply.

Your suggestion works just fine.
