### ISSUE TITLE
Uncaught Error: dia.ElementView: markup required with Vue.js

### ISSUE THREAD

**Issue by msteller-connyun** [clientIO/joint#1169]
Hey,

I use the approach from @JoseGoncalves (https://github.com/clientIO/joint/issues/1130#issuecomment-508025033) to integrate JointJS with Vue.js

I only added additionally the petri extension and own element (which works fine).

```
import 'jointjs/dist/joint.core.css';

import { dia } from 'jointjs/src/core.mjs';
import * as standard from 'jointjs/src/shapes/standard.mjs';
import * as pn from 'jointjs/src/shapes/pn.mjs';
import * as custom from '../jointjs_plugin/action_square';

export default {
  install: function(Vue) {
    const joint = { dia };
    joint.shapes = { standard, pn: {...pn, ...custom},  };
    Object.defineProperty(Vue.prototype, '$joint', { value: joint });
  },
};
```

But as soon I safe and reload the graph I get the famous `Uncaught Error: dia.ElementView: markup required` error.

```
const data = graph.toJSON()
graph.fromJSON(data) // -> ElementView.mjs:137 Uncaught Error: dia.ElementView: markup required
```

Any idea how to fix that?

Using jointjs 3.0.4.

**Comment by JoseGoncalves** [comment]
@msteller-connyun Have you setup namespaces when creating graph and paper?

Check https://github.com/JoseGoncalves/vue-jointjs/commit/3abc2269666eed2fba08ede3e0bcae7813cfd693 in my [vue-jointjs](https://github.com/JoseGoncalves/vue-jointjs) template project.

**Comment by msteller-connyun** [comment]
@JoseGoncalves

Yes, it was the namespacing!
I tried it in an earlier try with namespacing, but I did wrong 🤦‍♂  ;-)
After I did it correctly, it’s working ;-)

However, I thought namespacing in this solution is not required?

Thank for your help.

**Comment by JoseGoncalves** [comment]
Namespace setting is required if you use custom shapes, i.e., shapes that you provide or that you import from [Rappid](https://resources.jointjs.com/docs/rappid/v3.0/index.html).
If you use only shapes from the core JointJS, there is no need for it.
