### ISSUE TITLE
toJson contain Design information

### ISSUE THREAD

**Issue by msteller-connyun** [clientIO/joint#1175]
Maybe I don’t understand the concept right.

I want to store a jointjs graph in database in the backend.
The data generated by `toJSON()` contains design information, like the `stroke` color, `stroke-width` or the `fill-color`.

Is this not a bad concept, aber design information should only come from the widget?

Let’s say I save a graph wenn widget A has the fill color red. Later I refcator and change the widget from red to green. But I load the old graph from the backend, the color will be still red?

**Comment by kumilingus** [comment]
Hi, there is a difference in where you define your color.

1. On Class - `attrs` won't be present in the JSON output
```
var MyShape = joint.dia.Element.define('MyShape', {
  attrs: { body: { fill: 'red' }}
});
var myShape = new MyShape();
console.log(myShape.toJSON()); // => { attrs: {}, position: { x: 0, y: 0 }, ..  }
```

2. On Instance - it will be present in the JSON if it differs from the Class defaults
```
var myShape = new MyShape({
  attrs: { body: { fill: 'blue' }}
});
console.log(myShape.toJSON()); // => { attrs: { body: { fill: 'blue' }}, position: { x: 0, y: 0 }, ..  }
```

If this behaviour does not work for you, you can always override `toJSON()` method for you elements. For instance:
```
var MyShape = joint.dia.Element.define('MyShape', {
  attrs: { body: { fill: 'red' }}
}, {
  toJSON: function() {
       var json = joint.dia.Element.prototype.toJSON.call(this);
       delete json.attrs;
       return json;
  }
});
```

**Comment by msteller-connyun** [comment]
@kumilingus 

Hey Roman, thank you so much for the fast response... that was very helpful.
