### ISSUE TITLE
Bulk Selection events don't show the changes applied

### ISSUE THREAD

**Issue by ArthurWietzorek** [clientIO/joint#1188]
I have been implementing some custom logic around the joint.ui.Selection and tried to listen to the bulk selection initiated by Selection.startSelecting() to add objects selected that way to my logic as well. When listening to 'action:selecting:pointerup', only the jQuery event is passed, but no information on which elements were selected is given. 

`this.selection.on('action:selecting:pointerup', evt => console.log(evt));`

In addition to that, the collection hasn't updated yet, when the event handler is run:

`this.selection.on('action:selecting:pointerup', (evt) => console.log(this.selection.collection));`

This always delivers the value of the collection before the bulk selection. Is there a way to get access to the selected elements?

**Comment by kumilingus** [comment]
Right, this event is triggered before the elements are added to the collection. You can either use `setTimeout` (should be safe when it is a reaction to the user interaction) or listen to the collection instead.

```js
this.selection.collection.on('reset', (collection, opt) => {
  if (opt.ui) { /* the selection has been changed by the user interaction */}
});
```

**Comment by ArthurWietzorek** [comment]
Thank you a lot, it worked. I think that the events that are triggered on `selection.collection` might be worth adding to the documentation, too.

**Comment by kumilingus** [comment]
JointJS/Rappid is built on top of Backbone. For the documentation please refer to their [docs](https://backbonejs.org). Selection collection is a `Backbone.Collection`.
