### ISSUE TITLE
Update the template of custom elements

### ISSUE THREAD

**Issue by samnb** [clientIO/joint#1192]
The example from the html tutorial (https://resources.jointjs.com/tutorial/html-elements) works pretty well. I'd like additionally to change/update the template of the custom element dynamically. I have already tried to re-render the ElementView, but without success. Below is the code snippet:

```javascript
var html = joint.shapes.html = {};

html.Element = joint.shapes.devs.Model.extend({
  defaults: { ... },
  template: '<div> initial value </div>' 
});

html.ElementView = dia.ElementView.extend({
  initialize: function () {
    // ...
   this.listenTo(this.model, 'change:template', this.templateOnUpdate);
  },
  templateOnUpdate: function () {
     console.log('templateOnUpdate fired: ', this.model.get('template'));
     this.render();
   },
 // ...
});

var elem = new html.Element();
console.log( elem.get('template') );
// the console logs:  '<div> initial value </div>'

elem.set('template', '<span> a new updated value</span>');
// the console logs: 'templateOnUpdate fired:  <span> a new updated value</span>'
```
Although the function `templateOnUpdate` gets fired, the DOM element remains the same.

**Comment by kumilingus** [comment]
I suggest using another HTML ElementView example [here](https://github.com/clientIO/joint/blob/master/demo/shapes/src/html.js). The one from the tutorials is archived and it's not showing the best practices.

Please raise your question on JointJS Google Group instead.
