### ISSUE TITLE
Types: incorrenct jquery interface for the event object

### ISSUE THREAD

**Issue by CaselIT** [clientIO/joint#1194]
I think that the interface used for the event object in the typing of jointjs use the wrong jquery interface: `JQuery.Event` instead of `JQuery.TriggeredEvent`

reference stackoverflow https://stackoverflow.com/questions/55931254/typescript-jquery-event-in-handler-has-not-properties-target-and-current

The `JQuery.Event` interface does not have the `target`, `data`, and some other useful properties, that make working with it annoying

I think the problem lays mainly in the naming choice in the jquery typing that is confusing.

I can make a PR if the type is indeed not correct

**Comment by kumilingus** [comment]
Good catch. Please do create a PR. Perhaps you can create an alias type `Event` for `jQuery.TriggeredEvent` under the `dia` namespace and use that. Thanks!

**Comment by CaselIT** [comment]
Will do.

> Perhaps you can create an alias type Event for jQuery.TriggeredEvent under the dia namespace and use that

That is what I was thinking too
