### ISSUE TITLE
Unexpected addPort behaviour

### ISSUE THREAD

**Issue by snehal96** [clientIO/joint#1197]
Hey, I was trying to add ports dynamically to a jointjs standard rectangle element using bootstrap modal. I get the port added dynamically if I just add the port, but when I try to hide the modal menu and then again try to add a port, it adds incremental number of ports instead of a single one in the element.

I reproduced the issue here:
https://codepen.io/sunny_96/pen/JjjYPNM

drag any element from stencil to yellow paper, right click for the menu options on the element.

The same thing happens, if i try to close menu with escape also.

**Comment by kumilingus** [comment]
I've just added `$('contextmenu').off()` and it works.
https://codepen.io/kumilingus/pen/MWWaaRz

**Comment by snehal96** [comment]
Ahh, thank you, i was passing click as an argument with off which seemed to tip it off.

One more thing is there any way to overload functions like addPort or removePort??

**Comment by kumilingus** [comment]
Why do you need to overload them? You can just create your own methods, which will be calling `addPort()` (`removePort()`).

```js
joint.dia.Element.define('my.Rectangle', {
 /* attributes */
}, 
  /* prototype */
  myAddPort: function() {
     this.addPort(arg1);
  }
}, {
  /* static */
});
```
