### ISSUE TITLE
joint.shapes.devs.min.js - "Cannot read property 'define' of undefined"

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1198]
joint.shapes.devs.min.js:10 Uncaught TypeError: Cannot read property 'define' of undefined
    at joint.shapes.devs (joint.shapes.devs.min.js:10)
    at joint.shapes.devs.min.js:182

`var o = e.Generic.define("devs.Model", {...`

e.Generic is undefined.
I suggest to add e.basic.Generic

**Comment by kumilingus** [comment]
Duplicate of https://github.com/clientIO/joint/issues/1170.
