### ISSUE TITLE
Selective features importing

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1208]
Hi!

We're using Rappid version 3.0.1.

I'm trying to reduce the webapp bundle size by importing only those features which are required.

As suggested on the "Docs/Rappid" page, instead of including the whole `rappid.js` I picked only `joint.js` and `joint.shapes.bpmn.js` (+ others).

But it turned out that all the entities from `joint.shapes.bpmn.js` were imported into `joint.shapes` namespace instead of nesting to `joint.shapes.bpmn`. Check the screenshot.

![image](https://user-images.githubusercontent.com/14068189/67570458-1ee50480-f73a-11e9-8c59-d397bc2f7705.png)

**Comment by vtalas** [comment]
import just the "core" instead, as the `jointjs` is a complete bundle including all shapes. 

the core doesn't contain any shape (nor the `DirectedGraph` layout):
 `import * as joint from 'jointjs/src/core.mjs';
