### ISSUE TITLE
Problem with highlighter after updating the joint js to the latest version!

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1211]
- I have added a highlighter on cell selection on the paper.
- Below there is the code for that action:

**html + css**:
```
<script id='highlighter' type="text/template">
     <rect class="highlighter" />
</script>
```

```
.highlighter{
    width: 75px;
    height: 75px;
    stroke: #0000ff;
    stroke-width: 2px;
    fill: transparent;
    pointer-events: none;
    transform: translate(-5px, -5px);
}

```
**js**:
```
function highlightElement(element){
        element.innerHTML = document.getElementById('highlighter').innerHTML + element.innerHTML;
    }
```

- The problem is that I cannot connect the links from a source to a target and it behaves like it doesn't find the target model or the target port.
- But if I comment the line above in js function, the highlighter gets disappear and the connection is fixed. Please notice that I am using v0.9.6 and I want to upgrade to the latest version.
- Thanks in advance

**Comment by kumilingus** [comment]
Hi,

the ElementViews/LinkViews are now caching all the SVGElements they are built from. You can NOT replace the SVGElements of a CellView directly (without changing the `markup` attribute). Note, using `innerHTML = ...` will create new SVGElements.

You can still dynamically add a rectangle to a view like this:
```
function highlightElement(element){
    V(element).prepend(V('rect', { 'class': 'highlighter' }));
}
```

**Comment by Taulant1992** [comment]
Thank you, it worked :)
