### ISSUE TITLE
Why paper overrides my custom html divs?

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1212]
- I have this html:

```
<div class='paper-container' id="wrapper">
    <div class='paper' id="paper" style='margin-bottom: 0px; margin-right: 0px;'>
        <div id='linkMenu'>
          <ul id='linkMenu-items'>
            <li class='contextOption' name='deleteLink'>Delete link</li>
            <li class='contextOption' name='showStart'>Show link start</li>
            <li class='contextOption' name='showEnd'>Show link end</li>
          </ul>
        </div>
    </div>
</div>
```
- After application renders and reach this point:
```
var paper = new joint.dia.Paper({
        el: $("#paper"),
        width: PAPER_WIDTH,
        model: graph,
        ...
   )};
```

- Before rendering:
![bfrendering](https://user-images.githubusercontent.com/32356248/68769351-6f0e0300-0624-11ea-9c39-271dcda2ccf9.png)

- **After rendering:**
![aftrendering](https://user-images.githubusercontent.com/32356248/68769408-88af4a80-0624-11ea-879d-c48a38cce3b1.png)

- I don't have the possibility to catch the div of contextmenus for the links after the application renders.

- It seems that joint js overrides my html with its own.

- I am using the 0.9.6 version and I want to upgrade the version to the last one.
Thanks in advance

**Comment by kumilingus** [comment]
True, the instantiating a paper now empties the `el` element  before rendering. You gonna need to append the `linkMenu` element after the paper is rendered.

**Comment by Taulant1992** [comment]
Actually I did in this way when I faced this situation but I was not sure if it was the right solution.
Thank you :)

**Comment by kumilingus** [comment]
Great! We do the same stuff (appending an HTML to the paper element) with `Halo` and `Selection` plugins in Rappid ;)
