### ISSUE TITLE
Problem for moving the target arrow in another source target

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1214]
- I cannot change the direction of the target arrow and connect that with another cell on the paper.

- In the older version, on mouseover on the link, the stroke changes its state and I was able to change the arrow target into another arrow source on the paper.

This is during the older version of joint js:
![img](https://user-images.githubusercontent.com/32356248/68861604-30dc1680-06ec-11ea-8278-4940bb372b3e.PNG)

- The older markup:
```
{
			"attrs": {
				".connection": {
					"stroke": "black",
					"stroke-width" : "1"
				},
				".marker-target": {
					"fill": "black",
					"stroke": "black",
					"d": "M 10 0 L 0 5 L 10 10 L 7 5 L 10 5 L 7 5 z"
				}
			}
}
```

**After updgrading into the latest version:**
![img2](https://user-images.githubusercontent.com/32356248/68862631-13a84780-06ee-11ea-9558-680bc548d2b3.PNG)

- The markup of the link is as below:
```
{
	"attrs": {
                "line": {
                    "connection": "true",
                    "stroke": "black",
                    "strokeWidth" : "1",
                    "strokeLinejoin": "round",
                    "targetMarker": {
                        "type": "path",
                        "d": "M 10 -5 0 0 10 5 z"
                    }
                },
                "wrapper": {
                    "connection": "true",
                    "strokeLinejoin": "round",
                    "strokeWidth" : "10"
                }
            }
}
```

- Also the functionality on hover over the link is broken.
Thank in advance.

**Comment by Taulant1992** [comment]
- After some efforts i tried to get somehow the same functionality (with some differences) by relying on this tutorial of the joint js documentation.
[https://resources.jointjs.com/tutorials/joint/tutorials/js/link-tools-all.js](url)

**Comment by Taulant1992** [comment]
Today, I noticed that joint js library was recently updated at 28 October and I see that I can maintain the same old behaviour on hover with some minor changes in newjoint.css (see the first image above). 
Please notice that I am still using joint.Dia.Link to maintain the old behaviour but I still have the problem for changing the target arrow into another source port on the paper. 
Is there any way to fix this issue or should I use the joint.shapes.standard.Link instead?

Thanks in advance @kumilingus

**Comment by kumilingus** [comment]
No, we keep the `joint.dia.Link` backwards compatible. Any chance creating a JSFiddle or give me an access to your app to see what's wrong?

**Comment by Taulant1992** [comment]
This was a problem of mine on how I was killing the events.
The problem is solved.
Thank you so much :)
