### ISSUE TITLE
Why right click event won't fire in cell:pointerup and in blank:pointerdown?

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1215]
- I have these lines of code that do some actions:
```
paper.on('blank:pointerdown', function(evt, x, y){
        _x = x; _y = y;
        handle(function doSmth(), evt);
});
```
```
paper.on('cell:pointerup', function(cellView, evt, x, y){
        _cellView = cellView;
        _x = x; _y = y;
        handle(function doSmth(), evt);
});
```

- Before upgrading to the latest version, the right click event fired correctly but now that I want to upgrade to the last version it won't work.

- Can someone please provide me with a proper solution about this issue?
Thanks in advance

**Comment by kumilingus** [comment]
It's `blank:contextmenu` and `cell:contextmenu` (`element:contextmenu`/`link:contextmenu`) events to catch right-click actions now.

**Comment by Taulant1992** [comment]
Hi Roman, does this change relates with not being able to open inspect element when clicking on the blank paper? I can make the inspect element on the other sections but i cannot do it directly on paper.

**Comment by kumilingus** [comment]
No, it's disabled by default now. To enable this use `preventContextMenu = false`. https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#dia.Paper.prototype.options.preventContextMenu

**Comment by Taulant1992** [comment]
Thank you Roman, it worked :)
