### ISSUE TITLE
this.updatePortsAttrs is not a function

### ISSUE THREAD

**Issue by fjxfirst** [clientIO/joint#1217]
I can not see plugins in 3.0.4
but in 2.2.1,I can see plugins/shapes/joint.shapes.basic.js.
there is a function  updatePortsAttrs in the plugins/shapes/joint.shapes.basic.js.

**Comment by kumilingus** [comment]
Right, it has been removed in version 3.0. Please use the Element Port API.
Changelog: https://github.com/clientIO/joint/releases/tag/v3.0.0
