### ISSUE TITLE
Microsoft Edge toJPEG() bug

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1218]
Hi!
When we try to save dia to jpeg with `paper.toJPEG()` for Microsoft Edge it draws link tools too.
And in general, it loses a lot of formatting, but the main issue is rendering link tools.
For Chrome, FF, Opera - it works just fine.
Any suggestions / hints?

![image](https://user-images.githubusercontent.com/14068189/69153751-6ff0da00-0ae7-11ea-998e-3813c3b5fd67.png)

**Comment by kumilingus** [comment]
I assume you are using `joint.dia.Link` with link tools as part of the markup (as opposed to https://resources.jointjs.com/tutorial/link-tools).
Do you call the method with any options? And is the code below hides the link tools for you?
```
paper.toJPEG(() => {}, { stylesheet: '.link-tools{display:none;}' });
```

**Comment by GeorgiyZhuravlev** [comment]
> I assume you are using joint.dia.Link with link tools as part of the markup

We use both approaches:
1) extend `joint.shapes.bpmn.Flow` with `toolMarkup` to slightly change positions/icons. 
We've recently migrated from Rappid 1.7, so this was inherited. 
Is it a bad approach for v3?
2) on `link:pointerup` we add more with `linkView.addTools`
```
            tools: [
              new ns.SourceAnchor(),
              new ns.TargetAnchor(),
              new ns.Segments(),
              new ns.Boundary({padding: 15}),
            ]
```

>Do you call the method with any options? 

only `{quality: 1}`

> And is the code below hides the link tools for you? ` { stylesheet: '.link-tools{display:none;}' }`

I will try, thanks! 
(need to find Edge :), issue reported by client )

**Comment by GeorgiyZhuravlev** [comment]
The client has updated the browser and withdrawn his report.

**Comment by kumilingus** [comment]
> extend joint.shapes.bpmn.Flow with toolMarkup to slightly change positions/icons.
> We've recently migrated from Rappid 1.7, so this was inherited.
> Is it a bad approach for v3?

It's ok. Using the `dia.linkTools` is faster though - especially for large graphs.

> The client has updated the browser and withdrawn his report.

Great, most likely a bug in Edge Browser then. Thanks!
