### ISSUE TITLE
Is it possible to avoid clicking/dragging the background graph when two graphs are overlapping

### ISSUE THREAD

**Issue by konekoya** [clientIO/joint#1220]
In the "[USING HTML IN JOINTJS ELEMENTS](https://resources.jointjs.com/tutorial/html-elements)" tutorial, if two graphs overlapped, the mouse could click on the background graph instead of the foreground graph. The behavior is very weird... just wanted to know if there's a way to work around this. Thank you!

**Comment by konekoya** [comment]
Turns out that the `z-index` was causing the problem. Setting different z-index values for these elements effectively fixed the issue. I think you might consider updating your tutorial source :)

**Comment by kumilingus** [comment]
Hi Joshua, I am not quite sure what the issue was. Why do you have 2 graphs overlapping each other? Is this demo also suffering from the same issue https://github.com/clientIO/joint/blob/master/demo/shapes/src/html.js (note that HTML tutorial has been moved to archive)?

**Comment by konekoya** [comment]
@kumilingus Thanks for replying. Nope, the issue doesn't appear in this demo. Too bad, I didn't know the HTML tutorial was no longer maintained...
