### ISSUE TITLE
graph.fromJSON(graph.toJSON()) fails with error: dia.ElementView: markup required

### ISSUE THREAD

**Issue by Priyansh121096** [clientIO/joint#1221]
Hi, 

I'm trying to load a graph from a serialized version like below:
```
joint.layout.DirectedGraph.layout(this.graph, {
                nodeSep: 30,
                edgeSep: 30,
                rankDir: 'LR',
                ranker: 'network-simplex',
                marginX: 30,
                marginY: 25
            });
          
this.graph.fromJSON(this.graph.toJSON());
```

It fails with the following error:
`error: dia.ElementView: markup required`

FYI, this is my graph and paper initializations (inside a react component):
```
componentDidMount() {
        const namespace = joint.shapes;
        this.graph = new joint.dia.Graph({
            cellNamespace: namespace,
        });
        this.paper = new joint.dia.Paper({
            el: this.canvas.current,
            width: PAPER_WIDTH,
            height: PAPER_HEIGHT,
            model: this.graph,
            gridSize: 1,
            cellViewNamespace: namespace,
        });
```

What could be the issue here? Any help is much appreciated.

**Comment by kumilingus** [comment]
Does `const namespace = joint.shapes;` contain all the shape types (even custom ones - added by you)?

**Comment by Priyansh121096** [comment]
> Does `const namespace = joint.shapes;` contain all the shape types (even custom ones - added by you)?

I believe so, yes. Here is the way I'm defining my nodes
```
new joint.shapes.basic.TextBlock({
            size: {
                width: NODE_WIDTH,
                height: NODE_HEIGHT
            },
            content: `${ReactDOMServer.renderToStaticMarkup(NodeElem)}`,
});
```

where `NodeElem` is a react component.

**Comment by kumilingus** [comment]
Could you debug it? Please put a breakpoint at `componentDidMount` function and check what is the `namespace` variable. Did you add any custom shapes (not the built-in shapes)? If you stop the code just before the exception what was the `this.model.get('type')`?

**Comment by Priyansh121096** [comment]
> Please put a breakpoint at componentDidMount function and check what is the namespace variable.

Below is the namespace variable in componentDidMount.
```
namespace
basic: {Generic: ƒ, Rect: ƒ, TextView: ƒ, Text: ƒ, Circle: ƒ, …}
chess: {KingWhite: ƒ, KingBlack: ƒ, QueenWhite: ƒ, QueenBlack: ƒ, RookWhite: ƒ, …}
devs: {Model: ƒ, Atomic: ƒ, Coupled: ƒ, Link: ƒ}
erd: {Entity: ƒ, WeakEntity: ƒ, Relationship: ƒ, IdentifyingRelationship: ƒ, Attribute: ƒ, …}
fsa: {State: ƒ, StartState: ƒ, EndState: ƒ, Arrow: ƒ}
logic: {Gate: ƒ, IO: ƒ, Input: ƒ, Output: ƒ, Gate11: ƒ, …}
org: {Member: ƒ, Arrow: ƒ}
pn: {Place: ƒ, PlaceView: ƒ, Transition: ƒ, Link: ƒ}
standard: {Rectangle: ƒ, Circle: ƒ, Ellipse: ƒ, Path: ƒ, Polygon: ƒ, …}
uml: {Class: ƒ, ClassView: ƒ, Abstract: ƒ, AbstractView: ƒ, Interface: ƒ, …}
__proto__: Object
```

> Did you add any custom shapes (not the built-in shapes)?

No. I only add `Elements` of `joint.shapes.basic.TextBlock` and `Links` of `joint.shapes.standard.Link` to my graph.

> If you stop the code just before the exception what was the this.model.get('type')?

The code in `./node_modules/jointjs/dist/joint.min.js` seems minified and so I'm having difficulty reading it. Could you please suggest a way in which I can put breakpoints in `src` instead?

**Comment by kumilingus** [comment]
> The code in ./node_modules/jointjs/dist/joint.min.js seems minified and so I'm having difficulty reading it. Could you please suggest a way in which I can put breakpoints in src instead?

You can open the web inspector, have `Don't pause on exception` disabled and run the application. It should stop the code execution just before the exception. Then you can use the web console to get the model's type.

**Comment by Priyansh121096** [comment]
```
> this.model.get('type')
"basic.TextBlock"
```

Please let me know if any other information is needed.

**Comment by kumilingus** [comment]
I am not sure here. Please try run `this.model instanceof joint.shapes.basic.TextBlock` at the same point.

Also, you said you were trying to load a serialized version of a graph. How do you do that? The code does not show how you parsed it.

If you comment out calling of the DirectedGraph layout, does it work?

Note, that it is not necessary to reset graph after the layout. A better approach would be something like shown below.
```
paper.freeze();
graph.fromJSON(JSON.parse(serializedGraph));
joint.layout.DirectedGraph.layout(graph);
paper.unfreeze();
```
