### ISSUE TITLE
release 3.1.x is not available on CDNs like https://cdnjs.com/libraries/jointjs

### ISSUE THREAD

**Issue by amg0** [clientIO/joint#1222]
release 3.1.x is not available on CDNs like https://cdnjs.com/libraries/jointjs

**Comment by kumilingus** [comment]
It seems `v3.1.1` was already added 25 days ago (https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jointjs).

**Comment by amg0** [comment]
I do not get it ,  https://cdnjs.com/libraries/jointjs. list them up to 3.0.4 nothing else.
what is the CDN url we are supposed to use to get to the 3.1.x versions ?

**Comment by kumilingus** [comment]
I don't know why is it not showing on the web. This link works for me though - https://cdnjs.cloudflare.com/ajax/libs/jointjs/3.1.1/joint.js

**Comment by kumilingus** [comment]
It shows the latest version now.
