### ISSUE TITLE
Problems with "resize" function

### ISSUE THREAD

**Issue by emiliojoseav** [clientIO/joint#1224]
Hi folks! I found an issue using the JointJS `resize` function, and trying to join port links. After using this function on a shape object with ports, I'm not able to create links between the out/in resized shapes.
For example:
`cell.resize(50, 50);`

But, If instead of using the "resize" function, I use "prop", everything goes perfectly well.
For example:
```
cell.prop('size/width', 50);
cell.prop('size/height', 50);
```

Kind regards, Emilio.

**Comment by kumilingus** [comment]
Hi Emilio, could you please post here a video or an example? I am not sure what do you mean by "join port links" and "create links between the out/in resized shapes" (do you mean from the UI by dragging the port?). Thank you.

**Comment by emiliojoseav** [comment]
Yes "kumilingus", It means just what you said.

Greetings.

**Comment by kumilingus** [comment]
In that case, I am not able to reproduce. What shapes do you use and how you define ports? Do you use async rendering? Thank you.

**Comment by emiliojoseav** [comment]
Ignoring the creation of the "paper" and other JointJS staff, basically, this is the sequence:
1. Create Shapes:
```
var shapeA = new joint.shapes.devs.Model(shapeObjectA);
var shapeB = new joint.shapes.devs.Model(shapeObjectB);
```

2. Add ports to shapes:
```
shapeA.addInPort('in');
shapeB.addInPort('in');
shapeA.addOutPort('out');
shapeB.addOutPort('out');
```

3. Resize shapes:
```
shapeA.resize(50, 50);
shapeB.resize(50, 50);
```

After all of this, the ports are not able to link each other.

Greetings.

**Comment by kumilingus** [comment]
Still can't reproduce. Tested on https://github.com/clientIO/joint/tree/master/demo/devs.

**Comment by emiliojoseav** [comment]
Where do you resize the shapes? I dont see in the code any use of JointJS "resize" function, of course you can not reproduce the problem.

**Comment by kumilingus** [comment]
I edited the code. I used it as a boilerplate for the test. I had to replace "Ignoring the creation of the paper and other JointJS staff" with something, right? Please stop wasting everyone's time and provide us with some test case. Apparently, the issue is not as simple as described.   

Here's a JSFiddle with the code you've provided - https://jsfiddle.net/kumilingus/geo71c4h/. Feel free to fork the fiddle and modify it. Thanks.

**Comment by emiliojoseav** [comment]
wow Kumilingus, take it easy please, It is not my intention to waste anybody's time. You use your time in the way you want tu use it. I'm not forcing anyone, I just exposed a problem. If you want to work on it, great, and if you dont, also great. OK?

As I said, I solved the problem using "prop", enstead of "resize". So, for me the problem is solved, but probabily JointJS has a bug with "resize", and I only want to help the developers team to debug this awesome library. Maybe ¿if I found a bug, you prefer that I don´t say it? ... I don't think so ... We are all in the same boat.

I'll check your jsfiddle code and give you my feedback.

**Comment by kumilingus** [comment]
I might have overreacted it slightly. I do appreciate when you report a bug. It is important to report a bug with all the information needed to reproduce it or provide it when asked though. Otherwise, it is not helping. Creating a JSFiddle to show the problem is usually the best way how to help us to resolve any issue. Cheers.

**Comment by emiliojoseav** [comment]
Yep, you are right, It's more complex than that, aparently your JSFiddle code shuldn't work, but it does. Let me work on it, in a way to reproduce the bug, without showing you exactly my app code, that I can't because It's my bussniess code, not mine... you know ...
Thank you!

**Comment by kumilingus** [comment]
Sure, that's fine. Is `paper.options.validateMagnet` called when the user clicks on a port after the resizing? Do ports DOM Elements have `magnet="true"` attribute after the resizing?

**Comment by emiliojoseav** [comment]
No to both questions.
`validateMagnet` is only called on the paper creation. 
And `magnet="true"` it's never assigned.
