### ISSUE TITLE
How to override the default properties of joint.dia.link on hover?

### ISSUE THREAD

**Issue by Taulant1992** [clientIO/joint#1230]
Hi, I have this default view on hover over the link.
![image](https://user-images.githubusercontent.com/32356248/70922316-2e8c1580-2026-11ea-8588-fbcdca4be768.png)

Is there any chance to change the cursor into another type and disable the default behavious?
Thanks in advance

**Comment by kumilingus** [comment]
Hi, it's recommended to use `joint.shapes.standard.Link` (a link without tools) and `joint.linkTools`. It's faster when you render a lot of links and you can customize it easier by extending specific linkTools classes.

**Comment by Taulant1992** [comment]
Hi @kumilingus for your fast response.
I tried to use the ` joint.shapes.standard.Link` but it gives me some drawbacks on other functionalities and that's why it am sticking to `joint.dia.Link`.
Is there any chance to do change the default behavious?
Thanks in advance

**Comment by kumilingus** [comment]
The cursor can be changed in CSS (e.g. `cursor: pointer`). Changing the default behaviour is possible only by extending the LinkView and overriding some of its methods. What do you need to change specifically?

**Comment by Taulant1992** [comment]
For now changing the cursor would be ok. The suggestion worked.
Thank you :)
