### ISSUE TITLE
Custom Element View Error - Default renderMarkup is Still Called 

### ISSUE THREAD

**Issue by sysdevmike** [clientIO/joint#1241]
Running into `Error: dia.ElementView: markup required`, even after namespace, and custom view is set correctly.

After upgrading to 3.X, and using ES6 modules, I've set the namespaces for the cells/views and it looks like the right custom view is being found.

``` 
dia.ElementView.extend({
...
 renderMarkup: function () {
     ...
     console.log('Called custom renderMarkup()');
    },
})
```

However, console still shows. 

![image](https://user-images.githubusercontent.com/11449462/71897476-0feaeb80-319a-11ea-8a8a-4bfe0489119b.png)

**Comment by kumilingus** [comment]
Hi Mike, I am going to need more info on this, I am afraid. It seems that the model is missing markup. If you debug the `renderMarkup` method (just before the exception) what is the model instance of? How do you instantiate your graph? How do you define your shape? Thanks.

**Comment by kumilingus** [comment]
Have you resolved this?

**Comment by sysdevmike** [comment]
Yeah, sorry for the lateness. Just ended up importing everything as a workaround.
