### ISSUE TITLE
[Question] Is there a way to bind custom events on custom HTML element?

### ISSUE THREAD

**Issue by konekoya** [clientIO/joint#1242]
Hi @kumilingus,

I'm trying to add a custom event on my custom HTML element using official demo from here
https://github.com/clientIO/joint/blob/master/demo/shapes/html.html 
https://github.com/clientIO/joint/blob/master/demo/shapes/src/html.js

I've only made a few tweaks like the following:

in __html.html__
```css
.my-html-element input,
.my-html-element button {
  pointer-events: auto;
}
```

In the __html.js__
- Added a button element to the existing template
```js
template: [
    '<div class="my-html-element">',
    '<label data-attribute="mylabel"></label>',
    '<input data-attribute="myinput" type="text"/>',
    '<button>Custom button</button>',
    '</div>'
].join(''),
```

- Binding the events in paper
```js
paper.on('element:pointerdown', (event) => {
    console.log('clicked on the element!');
});

paper.on('element:button:pointerdown', (event) => {
    console.log('clicked on the button');
});
```

A repro sample:
https://codepen.io/JoshuaMilton/pen/povZpzv?editors=1111

Now, if you click on the element, the regular event will be triggered and logged out "clicked on the element!" But if you click on the button I added, the custom event won't trigger. The problem here is _I don't know how to correctly bind these custom events on my custom HTML elements_. I've googled and searched everything that I can possibly find but still cannot figure out how to do so 😅 

Thank you for the help!

**Comment by kumilingus** [comment]
Here's how we bind events (listening to a change of the `<input>` field): https://github.com/clientIO/joint/blob/master/demo/shapes/src/html.js#L66

So you could do similar with the button.
```
// `onRender()` method
$box.find('button').on('click', function() {
  console.log('button clicked');  
});
```

**Comment by konekoya** [comment]
> So you could do similar with the button.

Sorry @kumilingus that I didn't make this clear enough, my bad.

So we're able to add event listener on the button. But how do we bind (or call?) the event from paper?

I have tried this
```js
paper.on("element:button:pointerclick", event => {
  console.log("clicked on the button! You are calling it from paper event!");
});
```

I've updated the the sample code to include the listener: https://codepen.io/JoshuaMilton/pen/MWYqMaq?editors=0011

Basically, what I'm trying to do is like binding an event on an element like this:
https://github.com/clientIO/joint/blob/master/tutorials/js/events-event-attribute.js#L80

And then, reference the event in the paper:
https://github.com/clientIO/joint/blob/master/tutorials/js/events-event-attribute.js#L94

This seems to be working on SVG element. But I don't know how to do this in custom HTML elements.

Thank you :)

**Comment by kumilingus** [comment]
I see. The simplest way would be this:
```js
// onRender();
// `this` is an elementView
$box.find('button').on('click', function() {
  this.notify('element:button:pointerclick', evt);
}.bind(this));

// later
paper.on('element:button:pointerclick', (elementView, evt) => {});
```

Note, this solution is fine as long as you don't have thousands of elements. If there is a lot of elements in the graph, then there is also a lot of event handlers in memory. In that case, it is better to bind a single event handler.
```js
var MyPaper = joint.dia.Paper.extend({

  events: Object.assign({
     'click button': 'onButtonClick'
   }, joint.dia.Paper.prototype.events)

  onButtonClick: function(evt) {
    // find view from evt.target
    // trigger `element:button:pointerclick` on the paper
  }
});
```

For the built-in `event` attribute, you need to add `event` attribute to your markup first `<button event="element:button:pointerclick">Custom button</button>`. It does not work though, I guess, it is because it is guarded by `paper.options.guard`.  I need to investigate it.

**Comment by konekoya** [comment]
Thanks for the reply @kumilingus! Will give this a try once I get back to work from the holidays 😃

**Comment by konekoya** [comment]
@kumilingus Thank you so much for the help. This works perfectly 👍 💯
