### ISSUE TITLE
Apply dia.CellView.prototype.highlight to a part of a dia.Element

### ISSUE THREAD

**Issue by Priyansh121096** [clientIO/joint#1245]
Hi,

Is there a way to highlight part of an element instead of the whole element?

Use-case:
I have a tree like structure of custom rect elements in which there is a delete (x) button on top of the rect in each element. When a user hovers over a particular element, I highlight the path from root of the tree to the element being hovered upon. 

The issue is that the highlighted rectangular portion includes the the delete button which makes it look kinda ugly. If there was a way to say to the highlight method to only highlight the rect instead of the entire element, that'd make the node look much better.

Please let me know if this is feasible.

Regards,
Priyansh

**Comment by kumilingus** [comment]
Hi, you can highlight a specific subnode of a `dia.Element`.

```js
cellView.highlight('rect'); // selector
cellView.highlight(cellView.el.querySelector('rect')); // SVGElement
```
For more info please see docs (https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#highlighters.intro).

Also jigsaw demo uses highlighters (https://github.com/clientIO/joint/tree/master/demo/puzzle).


You can also create a custom highlighter like this.
```js
// create a separate layer for highlighters
var highlightersGroupVel = V('g');
highlightersGroupVel.appendTo(paper.layers);

// highlight an element
var element = graph.getElements()[0];
var bbox = element.getBBox();
var highlighterVel = V('rect', bbox.toJSON()).attr({ fill: 'none', stroke: 'red' });
highlightersGroupVel.append(highlighterVel);

// unhighlight
highlighterVel.remove(); // remove a specific highlighter
highlightersGroupVel.empty(); // remove all highlighters
```

**Comment by Priyansh121096** [comment]
Works like a charm! :)

Thank you for the prompt response,
Priyansh
