### ISSUE TITLE
Fast Paper

### ISSUE THREAD

**Issue by sourabhrajendu** [clientIO/joint#1247]
Hi,

I was going through the fast paper implementation given here - https://jsfiddle.net/kumilingus/e3m4kjqa/ . But, it doesn't work with jointJs v3.1.1 . Is it not straight-forward to use Document Fragments in this version? Is there some way to achieve the same fastness for the above mentioned version of JointJs ?

**Comment by kumilingus** [comment]
Hi, here's the demo, that works in the latest JointJS.
https://github.com/clientIO/joint/blob/master/demo/performance/conveyor.js

**Comment by sourabhrajendu** [comment]
Thanks @kumilingus . So, basically, using sorting.APPROX serves as the fast paper implemented in the above jsfiddle link?

**Comment by kumilingus** [comment]
Right, this and the improved `async` paper mode.
```js
new joint.dia.Paper({
  sorting: joint.dia.Paper.sorting.APPROX,
  async: true
});
```

**Comment by sourabhrajendu** [comment]
Great! Thanks @kumilingus :)
