### ISSUE TITLE
resize element in jointJs (Transform element)

### ISSUE THREAD

**Issue by umaire313** [clientIO/joint#125]
Hi,
i am new in joint.js and i need help.
i want to resize the elment same as in this link

http://jointjs.com/rappid#2b1874b1-ff72-4d97-ae8e-6ad978369b3e

click on rectangle rectangle become in editable form user can resize it rotate it draw link etc

**Comment by kumilingus** [comment]
Please use Google Groups or Stackoverflow in order to get an advice on this. Cheers.
