### ISSUE TITLE
Segment Link Tools not sending a link:pointerdown event 

### ISSUE THREAD

**Issue by speleothem** [clientIO/joint#1250]
I'm listening to pointerdown events on links, however the event does not trigger when clicking on vertices or segments. The vertices support the stopPropagation option, however, as far as I can tell this isn't supported for segments. Am I missing something here or is there no way to get a link:pointerdown event on segments at this time?

**Comment by kumilingus** [comment]
Hi, you will need to extend the `joint.linkTools.Segments` view and override some of its methods in `v3.1.1` (For more info please see PR  https://github.com/clientIO/joint/pull/1251).
```
const mySegments = joint.linkTools.Segments.extends({
  //... override some methods
});
```

**Comment by speleothem** [comment]
Thanks for the help, I was able to get the extend to work using the changes in that pr.
