### ISSUE TITLE
Link highlight doesn't follow link when dragged

### ISSUE THREAD

**Issue by speleothem** [clientIO/joint#1256]
Hello again, this may not be supported as I didn't see any example in the docs/demos, but I noticed if I highlight a link using the highlighter, and then drag the link, the highlight will not follow along with the link, it will just stay in the same place. Any idea if I'm doing something wrong, or how I'd be able to extend something to provide this feature? 

thanks!

**Comment by speleothem** [comment]
Wait I just realized I could simply change the color of the entire link

**Comment by kumilingus** [comment]
Perhaps, you could use `addClass` highlighter and set the color of the link via CSS (If you do not want to change the link's model). 

https://resources.jointjs.com/docs/jointjs/v3.1/joint.html#highlighters.addClass

**Comment by speleothem** [comment]
So I'm giving this a go as I agree its a better solution but I can't quite get it to work, I believe that I'm not selecting it correctly with css. Would you mind looking this over? 

js: 
```
const linkHighlighter = {                                                                                            
      highlighter: {                                                                                                   
          name: 'addClass',                                                                                            
          options: {                                                                                                   
              className: 'highlighted-link',                                                                           
          },                                                                                                           
      },                                                                                                               
  };           
view.highlight(null, linkHighlighter);
```

css class: 
```
highlighted-link.joint-link [joint-selector='line'] {
    stroke: #e59700;
}
```

I also tried `highlighted-link`, `highlighted-link.joint-link`, and `highlighted-link [joint-selector='line]`

If nothing sticks out to you then its probably just an error in my project somewhere. 

Thanks for your time btw!

**Comment by kumilingus** [comment]
Hi, it seems like you were missing a dot at the beginning of the selector.
```
.highlighted-link.joint-link [joint-selector='line'] {
    stroke: #e59700;
}
```

**Comment by speleothem** [comment]
whoops, yea. Works now, and got rid of some bugs that were popping up from changing the model. Thanks again
