### ISSUE TITLE
Adding a link via graph.addCell() directly with its attributes adds an element instead

### ISSUE THREAD

**Issue by DrMarkEy** [clientIO/joint#1258]
In my code I've been removing and re-adding a link like this:
```

graph.on('add', function(view)
{        
      console.log(view.isLink());
});    

var attrs = link1.attributes;
link1.remove();
graph.addCell(attrs);


```
In jointjs v2 this worked flawlessly and the console message would be "true", but since i upgraded to jointjs v3 the console message reads "false" which means the link is classified as an element after re-adding.

**Comment by kumilingus** [comment]
Hi, I am not able to reproduce the issue (tested on `devs` and `links` demo). How do you create the link1? What is the value of `link1.toJSON()`? A JSFiddle, that demonstrates the issue would be perfect. Thank you.

**Comment by DrMarkEy** [comment]
I create the link via

```
var link = new standard.Link();
    link.source(fromNode, {port: fromPort});
    link.target(toNode);
    link.addTo(graph);
```

The value of link1.toJSON before it is destroyed is
`{"type":"standard.Link","source":{"port":"casePort0","id":"440fbfbf-ed0a-42ac-a41a-15c66589d946"},"target":{"id":"bc5f90de-6a18-4694-9433-5cff00eef9e4"},"id":"bf4c3e18-3d25-46b7-88a3-e5ad6c0d0275","z":7,"attrs":{}}`

I also evaluated view.toJSON() in the graph.on('add') - callback:
`{"position":{"x":0,"y":0},"size":{"width":1,"height":1},"angle":0,"type":"standard.Link","source":{"port":"casePort0","id":"6e0e5a85-ee96-49e3-952b-b7370cb10957"},"target":{"id":"4c1bd682-d238-4fb8-911a-8a451538d713"},"id":"92f07f2e-12d4-4ef2-8b73-6a1c346fdddf","z":7,"attrs":{"line":{"connection":true,"stroke":"#333333","strokeWidth":2,"strokeLinejoin":"round","targetMarker":{"type":"path","d":"M 10 -5 0 0 10 5 z"}},"wrapper":{"connection":true,"strokeWidth":10,"strokeLinejoin":"round"}}}`

Also I've found out that re-adding the link via
```
		var link = new standard.Link(outboundLinks[i]);
		var cell = this.node.graph.addCell(link);
```
circumvents the problem.

**Comment by kumilingus** [comment]
Please try to create a new graph and add the cell into it. See if there is any difference when you pass the `cellNamespace` option and when not.
```
const graph2 = new joint.dia.Graph({}, { cellNamespace: joint.shapes });
graph2.addCell(link1.toJSON());
console.log(graph2.getCell(link1.id).isLink())
```

**Comment by kumilingus** [comment]
Any news?
