### ISSUE TITLE
Paper's blank:pointermove event doesn't get triggered

### ISSUE THREAD

**Issue by rohitk710** [clientIO/joint#1261]
I am a dragging a shape from Stencil (using licensed Rappid) and when that shape enters the Paper I am expecting paper.on('blank:pointermove') event to get triggered but it doesn't. paper.on('element:mouseenter') works fine if I am entering an already dropped cell while dragging.

**Comment by kumilingus** [comment]
Hi, the `blank:pointermove` events are triggered after the user clicks the blank area of the paper (after `blank:pointerdown` event). The element being dragged from the stencil is not part of the main paper.
What are you trying to achieve?

**Comment by rohitk710** [comment]
What I am trying to do is once I start dragging a shape from Stencil to Paper and the newly dragged shape (still in drag mode) is near to some existing shape on the paper (let's say within it's magnetic field), I want to highlight the ports of the existing shapes nearby.
I checked onDrag method of stencil but sadly it's protected and secondly it's a mousemove event so even after drag stop it just keeps getting triggered.

**Comment by rohitk710** [comment]
Though the explanation for as to why `blank:pointermove` doesn't work make sense, I don't see why can't it be made like rest of the paper events which works fine irrespective of start point. You do have `paper:mouseenter` event.

**Comment by kumilingus** [comment]
> I checked onDrag method of stencil but sadly it's protected **(1)** and secondly it's a mousemove event so even after drag stop it just keeps getting triggered **(2)**.

1. You can override the `onDrag` method of the Stencil

```js
const MyStencil = joint.ui.Stencil.extend({
   onDrag: function() { /* your own code */ }
});
```

We could trigger an event on the Stencil itself though. For instance:
```js
stencil.on('element:drag', (elementView, evt, x, y) => {});
```

2. It's a bug. We need to call `this.undelegateDocumentEvents();` inside the `onDragEnd()` method. We'll fix for the next release.

> Though the explanation for as to why blank:pointermove doesn't work make sense, I don't see why can't it be made like rest of the paper events which works fine irrespective of start point. You do have paper:mouseenter event.

We can. It would not be called `blank:pointermove` event but `paper:pointermove` though.

```js
paper.$el.on('mousemove', function(evt) {
   const normalizedEvt = joint.util.normalizeEvent(evt);
   const { x, y } = paper.clientToLocalPoint(normalizedEvt.clientX, normalizedEvt.clientY);
   paper.trigger('paper:pointermove', normalizedEvt, x, y);
});
```
