### ISSUE TITLE
Port labels overlap each other

### ISSUE THREAD

**Issue by sourabhrajendu** [clientIO/joint#1262]
Hi,

First of all, thanks for a wonderful library!

I am using the jointjs shapes as a node with inputs and outputs. Each input and output is represented by ports and every port has a label. The inports are on the left side of the node and the outports on the right. Due to this design, the input and output labels on the same line overlap each other.

Example : https://jsfiddle.net/rajendu/fjh8v0bo/139/

I want to use the port key for some purpose later on, so I cannot shorten it on case by case basis.

Could anyone please help me out here? Is there a way to fix the width for port-label and use ellipsis for overflowing part? 

Thanks in advance!

**Comment by kumilingus** [comment]
If you upgrade JointJS to the latest, you can use `textWrap` attribute instead of `text`.

`{ attrs: { label: { textWrap: { text: text, width: 150, ellipsis: true }}}}`
