### ISSUE TITLE
Is it possible to create a mind map from RDBMS?

### ISSUE THREAD

**Issue by greenTea2Codes** [clientIO/joint#1269]
Hi, 

I am searching for a diagramming library for our research project, which needs to create a mind map from some tables in a postgres database and the changes in the graph, e.g. editing the title of an organization would be updated to the corresponding row in the organization table. Is JointJS capable of doing that? I could not find information about interaction with a RDBMS, therefore I asked the question here. Thank You!

**Comment by kumilingus** [comment]
Sure, you can render elements representing the tables and show relationships between them, use an automatic layout to position them and listen to any changes made to the graph and send them to your back-end, which will then modify the database.

https://resources.jointjs.com/tutorial/events
https://resources.jointjs.com/tutorial/serialization

**Comment by greenTea2Codes** [comment]
Thank you very much.
