### ISSUE TITLE
non-jquery jointjs

### ISSUE THREAD

**Issue by timoxley** [clientIO/joint#127]
Do you think there's a place on the roadmap for a jointjs that removes the dependency on jquery?

**Comment by chill117** [comment]
I think if such a thing would be done, the best way to start would be to first create a shim that includes only the jQuery methods that joint uses (in core, plug-ins, and tests).

**Comment by chill117** [comment]
This is on the road-map for this year.

**Comment by timoxley** [comment]
@chill117 great :sparkles:

**Comment by waszqba** [comment]
Hi guys, it's 2019 and I think it might not be a such a bad idea to bump this thread, especially with 3.0 being recently published. Don't you think it would be nice to replace jQuery with standard commands?
I'd love to contribute if there's such an option, but I want to know first if you are wiling to move away from jQuery?

**Comment by waszqba** [comment]
@chill117 what do you think?

**Comment by chill117** [comment]
Hello! Might be better to ask @kumilingus about this one.

**Comment by kumilingus** [comment]
Hi @waszqba,  sorry for the late reply.

Few notes here. The users are not forced to use any jQuery API while using JointJS. There are a few exceptions where we still expose a jQuery object/features.
 - `jQuery.Event` in paper event handlers (e.g. `evt.data` mechanism)
 -  jQuery Sizzle non-standard CSS Selectors in cell's definition e.g. `attrs: { 'circle:odd': { fill: 'red' }}` (this can be deprecated in favour of JSON Markup Selectors/standard CSS Selectors)
 - Backbone.View (depends on jQuery) - `events` bindings (https://backbonejs.org/#View-events), events namespaces (https://api.jquery.com/event.namespace/)
- replacing addClass/removeClass jQuery API and similar it's not an issue here
- I might have missed something

Yes, we're keen to finally get rid of the jQuery. We prefer do it gently though :) So the users/us don't suffer from the breaking changes to much.

**Comment by waszqba** [comment]
Thanks for answer @kumilingus, is there any way I can support you (or at least try to do so) with the transition? I see you are deeply integrated with jQuery, but I believe there might be some way to ditch it easily (not quickly tho).

**Comment by kumilingus** [comment]
That would greatly appreciated :) Here's a list of tasks we might start working on (I'll be adding more items soon).

- [ ] **joint.mvc.View:** Events Delegating and Namespaces - e.g similar to [this](https://github.com/oneuijs/oui-dom-events)
- [ ] replace jQuery `find()` with `querySelectorAll()` e.g [here](https://github.com/clientIO/joint/blob/master/src/dia/LinkView.mjs#L1980)
- [ ] replace jQuery methods with native - inspiration [here](https://github.com/nefe/You-Dont-Need-jQuery#query-selector) (we can add such a method to `util`)

**Comment by timoxley** [comment]
Still relevant I think.

**Comment by timoxley** [comment]
Bump

**Comment by timoxley** [comment]
Bump

**Comment by timoxley** [comment]
Bump

**Comment by timoxley** [comment]
bump

**Comment by timoxley** [comment]
Whoo congratulations
