### ISSUE TITLE
Issue with LinkTools + CommandManager

### ISSUE THREAD

**Issue by luis-carlos-campos** [clientIO/joint#1270]
Hi everyone,

I'm not sure if this is a BUG or if it's working as expected.
I was trying to prepare a code pen... however I need CommandManager...

I have a link with tool options (event = link:options).

![Screen Shot 2020-04-16 at 1 24 01 PM](https://user-images.githubusercontent.com/13797951/79481215-8e4ef900-7fe5-11ea-8566-c43404fdc3c9.png)

Whenever I click on options icon...
It'll trigger a poiterdown event (starting a new batch CellView.pointerdown)...
However, since pointerup is never called, we end up with an endless batch command.

Rappid: v3.1.1

**Comment by kumilingus** [comment]
Hi @luis-carlos-campos, could you share some code with us? What exactly do you do on `link:options` event?

**Comment by luis-carlos-campos** [comment]
Hi @kumilingus, I'm not doing anything... I removed all code so as to make sure my code was not causing this issue... There's a single alert() on it right now.

`this.get("paper").on('link:options', (cellView, evt, x, y) => {
            alert("hey");
        });`

LinkView
`        onevent: function(evt, eventName, x, y) {
            // Backwards compatibility
            var linkTool = joint.V(evt.target).findParentByClass('link-tool', this.el);
            if (linkTool) {
                // No further action to be executed
                evt.stopPropagation();

                // Allow `interactive.useLinkTools=false`
                if (this.can('useLinkTools')) {
                    if (eventName === 'remove') {
                        // Built-in remove event
                        this.model.remove({ ui: true });
                        // Do not trigger link pointerdown
                        return;

                    } else {
                        // link:options and other custom events inside the link tools
                        this.notify(eventName, evt, x, y);
                    }
                }
                this.notifyPointerdown(evt, x, y);

            } else {
                CellView.prototype.onevent.apply(this, arguments);
            }
        },`


Whenever I click the options it goes all the way to: `this.notifyPointerdown(evt, x, y);`
which opens a batch, however no pointer up is called so as to stop the batch command.

Remove does work fine since we have a return statement preventing pointerdown from being fired.

**Comment by kumilingus** [comment]
It's a bug then. I'll look into it and let you know. I think triggering `link:pointerdown`  and `cell:pointerdown`after `link:options` is there to keep it backwards compatible.

**Comment by luis-carlos-campos** [comment]
Understood.
Thanks Roman.
I appreciate your time.

**Comment by luis-carlos-campos** [comment]
It's repproducable on [BPMN](https://resources.jointjs.com/demos/bpmn)

![joint-issue](https://user-images.githubusercontent.com/13797951/79500456-d16b9500-8002-11ea-9225-c03de1f3e261.gif)
