### ISSUE TITLE
Typescript error on dia.Paper.prototype.options.validateMagnet

### ISSUE THREAD

**Issue by JadsonBruno** [clientIO/joint#1271]
I get an error when trying to use the **validateMagnet** and **validateConnection** of paper attribute with typescript. 

`
validateMagnet: function (cellView: jointjs.dia.CellView,
                                          magnet: SVGElement): boolean
 {
     return magnet.getAttribute('magnet') !== 'passive';
 },
`

Error: 
> Property 'getAttribute' does not exist on type 'SVGElement'.

It seems that the magnet attribute has an incorrect type, as the getAttribute method is used in one of the jointjs [tutorials](https://resources.jointjs.com/tutorial/ports).

**Comment by kumilingus** [comment]
Do you have `dom` in your TS config? 
```
"lib": [ "dom" ]
```
`SVGElement` extends `Element` and `Element` defines public method `getAttribute`.
https://github.com/microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L12944

**Comment by JadsonBruno** [comment]
I didn't have it, the problem was solved. Thank you very much.
