### ISSUE TITLE
Potential XSS vulnerability in jQuery

### ISSUE THREAD

**Issue by postatum** [clientIO/joint#1276]
Hi.

Currently used jQuery version causes a security issue.

For more details see: https://github.com/advisories/GHSA-jpcq-cgw6-v4j6

**Comment by elinskytap** [comment]
Hello @kumilingus,

Will you have a release soon for the jquery upgraded?

**Comment by elinskytap** [comment]
Hi @kumilingus, thanks for letting me know. Do you have ETA for the new release?

**Comment by kumilingus** [comment]
Hi @elinskytap, I'm heading for this week. If you really need just a version without the security issue, you can fork the `v3.1.1`, change `package.json` and then, in your app, just load the JointJS via [dependecy url](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

**Comment by kumilingus** [comment]
Fixed in `v3.2.0`.
