### ISSUE TITLE
JSONMarkup.attributes does not allow "special" attributes

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1277]
E.g. the following does not work as expected:
```javascript
const Test = joint.shapes.basic.Generic.define('Test', {}, {
    markup: [{
        tagName: 'text',
        className: 'test',
        attributes: {
            text: '',
            refX: .5, refDy: 3,
            xAlignment: 'middle',
            fill: 'black'
        }
    }]
});
```
while this does:

```javascript
const Test = joint.shapes.basic.Generic.define('Test', {
    attrs: {
        'text.label': {
            text: '',
            refX: .5, refDy: 3,
            xAlignment: 'middle',
            fill: 'black'
        }
}, {
    markup: [{
        tagName: 'text',
        className: 'test'
    }]
});
```

Is there any specific reason for that or am I just doing something wrong?

**Comment by kumilingus** [comment]
Hi @ialokim, that's a good question.
Anything in the `markup` is evaluated only once at the cell view creation (the DOM elements and their attributes).
Anything in the `attrs` attribute is evaluated on every change of the model (e.g. resize or `attrs` change). The value of special attributes usually depends on the current state of the model (`size`, `attrs`, `angle`).
Here's what I suggest.
- Add SVG attributes that do not change throughout the runtime of the application into the `markup`.
- Add SVG attributes to the `attrs`, when these are modified at some point in the application (e.g. user changes the color of the element).
- Special attributes need to be always inside the `attrs`.

**Comment by ialokim** [comment]
Nice explanation. Thanks a lot!
