### ISSUE TITLE
Ports without labels

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1278]
I really like the ports feature and I'm using it to provide a custom complex port markup with several port labels. Thus, I would like to remove the port label, that is always automatically added because of https://github.com/clientIO/joint/blob/b93aa6980624a792856ab33abd7546d6987e9c13/src/dia/ports.mjs#L521.

Is there a way to prevent the port label to be added at all or are there any plans to support ports without labels? I know that without setting a label text, the svg text element will not be visible but I would prefer to not have it in the SVG tree at all.

**Comment by kumilingus** [comment]
Right now we throw an exception when no markup was provided https://github.com/clientIO/joint/blob/master/src/dia/ports.mjs#L724.
Allowing no port labels should be easy to implement though.
