### ISSUE TITLE
Where is jointjs's run command ?

### ISSUE THREAD

**Issue by Natsu-LB** [clientIO/joint#1285]
I con't run jointjs's source code ! I couldn't find the command of running ... Can you tell me how to run the jointjs . please ...

**Comment by kumilingus** [comment]
Please see https://github.com/clientIO/joint/blob/master/README.md#setup.
It depends what you want to do next. You can for instance start browsing the demos https://github.com/clientIO/joint/tree/master/demo.

**Comment by Natsu-LB** [comment]
It has been solved !  First ，run the 'grunt' command . Then direct access to static pages in the / jointjs-master/demo directory .
