### ISSUE TITLE
the paper.scale() call erases `translate` parameters in viewport

### ISSUE THREAD

**Issue by leungwensen** [clientIO/joint#129]
when viewport element is like:

```html
    <g id="v-3" class="viewport" transform="translate(84,301) scale(0.6,0.6)">
```
paper.scale(1) call will erase the `tranlate` parameters, the viewport element ends up like:

```html
    <g id="v-3" class="viewport" transform="scale(1,1)">
```

and if I did the same thing using the following method, it had no problem:

```javascript
V($('svg .viewport')[0]).scale(1);
```

**Comment by chill117** [comment]
Manipulating the viewport SVG element directly should be avoided. Instances of `joint.dia.Paper` store the origin internally and when you use the `paper.scale()` method to set the scale of the paper, the origin might also need to be scaled. In this case, the internally stored origin are used and will overwrite the translate property that has already been set on the viewport element.
