### ISSUE TITLE
Layout: Customize nodeSep for specific elements

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1292]
It would be nice if specific elements could be laid out considering space for ports. I guess some sort of new `Element.layoutSize()` function could be added which would return `Element.size()` as default but could be overridden e.g. to account for extra space for ports. This function could be called in https://github.com/clientIO/joint/blob/master/src/layout/DirectedGraph/DirectedGraph.mjs#L10 then. Is there perhaps any better way to account for extra space when computing the layout? If not, I would try to make a PR with the above proposed changes.

**Comment by kumilingus** [comment]
Could  you try to pass the `exportElement` callback to the layout function (https://github.com/clientIO/joint/blob/master/src/layout/DirectedGraph/DirectedGraph.mjs#L115)?
```js
{
  rankDir: 'TB',
  exportElement: (element) => {
     const size = element.size();
     size.height + 20;
     return size;     
  }
}
```

If that works, we can add it to the documentation. Thank you.

**Comment by ialokim** [comment]
Thanks a lot, this worked for me. I passed a custom `exportElement` and a custom `setPosition` callback to the layout function which handles my special needs.

**Comment by kumilingus** [comment]
Perfect, please keep the issue open until we add this to the documentation and Typescript.
