### ISSUE TITLE
Angular Component decorator's scss files are not included in jointjs

### ISSUE THREAD

**Issue by elinake** [clientIO/joint#1294]
If I add styles to an external scss files which are included in angular.json, they are included in my JointJS component.

If I do component decorator:
```
@Component({
    selector: 'app-diagram',
    templateUrl: './diagram.component.html',
    styleUrls: ['./diagram.component.scss'],
})
```
or
```
@Component({
    selector: 'app-diagram',
    templateUrl: './diagram.component.html',
    styles: [],
})
```
The styles are not included in JointJS diagram.

What I was trying to do was

```
element.highlight(null, {
            highlighter: {
              name: 'addClass',
              options: {
                className: 'disabled'
              }
            }
          });
```

And the css looks like this:

```
g {
    .disabled {
        opacity: 0.5 !important;
    }
}
```

Angular: 8.1.0.
JointJS: 3.1.

**Comment by cezarylos-neo** [comment]
Hi @elinake,
Have you tried to set ViewEncapsulation to None in this component?
https://angular.io/api/core/ViewEncapsulation#members
Cheers!

**Comment by jmesa-sistel** [comment]
@elinake Probably you should break the encapsulation using ng-deep.
For example:
```
:host ::ng-deep #jointobject .aclass {
    min-width: 0;
    .....
}
```

**Comment by elinake** [comment]
@jmesa-sistel  ng-deep is deprecated, and it's not necessarily exactly what I want, if I want css classes be encapsulated within a component. 

@cezarylos-neo That is the exact opposite of my problem, I want Angular's encapsulation, but I don't have it for JointJS when I'm doing things standard way.

**Comment by jmesa-sistel** [comment]
@elinake ng-deep will be removed when the big companies (google, apple, microsoft, mozilla, etc) decide how to propagate css changes to inner/outer components, at now your css in a component can be only encapsulated using an emulation mode which make that only your **template** in the component is affected by your css but you are using jointjs which is a external object so it is not compiled using you css, you have to break that encapsulation so your css in your component will affect the joint object using ng-deep, in my example the css will affect only to #jointobject so it will not affect other external components. At now this is the only way to do it or you will have to use a global css (styles.scss in angular app)

**Comment by elinake** [comment]
@jmesa-sistel Thank you for the explanation, seems like this is the best option.
