### ISSUE TITLE
Moderate Vulnerability in 3.1.1

### ISSUE THREAD

**Issue by alenela** [clientIO/joint#1295]
Run yarn audit shows a vulnerability with level MODERATE. 

$ yarn audit --level moderate

moderate: Cross-Site Scripting
Package: jquery
Patched in: >=3.5.0
Dependency of: jointjs
Path: jointjs > jquery
More info: https://www.npmjs.com/advisories/1518

**Comment by kumilingus** [comment]
Fixed here: https://github.com/clientIO/joint/pull/1279
