### ISSUE TITLE
GetSelector can select wrong elements

### ISSUE THREAD

**Issue by TrueBrain** [clientIO/joint#130]
When you enable inPorts and outPorts, the getSelector in joint.dia.cell.js can select the wrong element. For example, if I have 1 inPort and 1 outPort, and drag a line from the outPort, the selector looks like this:

    g:nth-child(1) g:nth-child(3) g:nth-child(1) circle:nth-child(1)

This appears to be because getSelector starts from the cell. The problem is that the viewport above him is also a g tag. In result, this not only selects the outPort (because of g:nth-child(3)), but also the third cell with _all_ his ports.

In result you cannot connect an outPort of the third cell to any inPort if you have a validate function in place to disallow connecting inPorts to inPorts. This is because the first item of the selector is used to base the validation on. This is the inPort, where you are linking from the outPort.

What I think the intentions are, and how it is implemented in joint.shapes.basic.js, is to use:

    g:nth-child(1) > g:nth-child(3) > g:nth-child(1) > g:nth-child(1)

This does select the right element. Basically, changing (joint.dia.cell.js:921):

    selector = el.tagName + ':nth-child(' + (index + 1) + ')' + ' ' + (selector || '');

into:

    selector = el.tagName + ':nth-child(' + (index + 1) + ')' + ' ' + (selector ? '> ' + selector : '');

Applying the above change does fix my issues. This is possible related to issue #126 too.

PS: applying a CSS statement:

    g:nth-child(1) g:nth-child(3) g:nth-child(1) g:nth-child(1) {
        stroke-color: red;
    }

will show you very nicely what the querySelector will return.

Tnx for your time and effort into this library. It is freakinglish awesome :D

**Comment by TrueBrain** [comment]
Oops, didn't see #120. This is also a way to fix the issue, by using JQuery, as he does seem to start from the cell itself, instead of from the root element (what querySelector seems to do). In my opinion, the fix I suggest is better, as that is the intention (using DIRECT children, not ANY children). But I am sure you guys know much better what you meant :)

**Comment by TrueBrain** [comment]
Some more fiddling why JQuery does work as intended, and querySelector doesn't, I finally figured out what happens. querySelector does something different than I expected:

It runs the CSS selector you give (from the ROOT document, not based on the element itself!). Then it finds a child within the selector that is also a child of the element you run it from.

Example to demonstrate the non-expected behavior (but possible how it was intended etc):

http://jsfiddle.net/fco3c75b/

Hopefully that makes it a bit more clear why this happens and why it is broken :)

**Comment by kumilingus** [comment]
Thanks for finding this out. You've done a good job here! We'll start working on this soon.
Based on what are saying the safest way might be to make selectors in the following way:

    [model-id="ID"] > g:nth-child(1) > g:nth-child(3) > g:nth-child(1) > g:nth-child(1)

And keep in mind that these selectors are meant to be used with `querySelector` only (not jQuery).
(We'd like to get rid of jQuery dependency eventually anyway)

Using pseudo-class `:scope` would be also an interesting solution.  Unfortunately it's not supported across all browsers yet.

     :scope > g:nth-child(1) > g:nth-child(3) > g:nth-child(1) > g:nth-child(1)

**Comment by kumilingus** [comment]
Fixed in 96ff19fe9c781a534ca487476206f2e479b8a55d.
