### ISSUE TITLE
joint.util.breakText option for ellipsis produce exception

### ISSUE THREAD

**Issue by DerMichel** [clientIO/joint#1308]
I have a shape that I used to present a text to a user.
The user can resize the shape.
I try to use the ellipsis feature with the textWrap attribute that the user can see if the text is too long for the shape:
`text: {
                        'fill': '#000000',
                        'ref-x': 10,
                        'ref-y': 10,
                        'font-size': '0.8em',
                        'font-weight': 'normal',
                        'text-align': 'left',
                        'font-family': 'monospace',
                        'textWrap': {
                            text: '',
                            width: -15, // reference width minus 15
                            height: '100%',
                            ellipsis: true,
                        },
                    },
`

However, if I have a text with two linebreaks and a resize the shape I get the following exception:
at line 13611: var k = lastLine.length;
`
TypeError: Cannot read property 'length' of undefined
`
Same behavior if I use breakText directly.
I can see in the jointjs code that the error line is not executed if the ellipsis property is set to false
I am using rappid 3.1.1 which includes the breakText of jointjs

**Comment by kumilingus** [comment]
Hi @DerMichel, how did you call the `breakText()` function? It's most likely already fixed in JointJS master (https://github.com/clientIO/joint/blob/master/src/util/util.mjs#L434-L674).

If this the case, you could fix it locally by overriding `joint.util.breakText=function() { /* master*/ }` function.

**Comment by DerMichel** [comment]
Hi @kumilingus thank you for the fix hint in the master. As you recommended, I overridden the current master version of the `breakText()` function into my local rappid package.
This new version do not show any problems. So it seems to me that this issue has been already fixed in the master.
Thank you for your help 👍
