### ISSUE TITLE
Connection points for bpmn.Event | bpmn.Gateway

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1321]
Hi!

Could you give us a hint of how paper options should be set to avoid moving the link's end depending on the presence/absence of the element's label?
Here's a screenshot from your bpmn-playground (https://resources.jointjs.com/demos/bpmn)

No labels:
<img width="568" alt="1" src="https://user-images.githubusercontent.com/14068189/84032612-470b3600-a9a0-11ea-8e6d-c868e7ec22cb.png">

With labels:
<img width="547" alt="2" src="https://user-images.githubusercontent.com/14068189/84032667-5b4f3300-a9a0-11ea-8192-b118e37bcd64.png">

The behavior we'd like to get from Flow - it ignores those elements labels (Event and Gateway), so always positioned the same way, as if no labels exist.

Here's `paper` options fragment we're using now:
```
defaultLink: new joint.shapes.bpmn.Flow,
defaultConnectionPoint: {name: 'boundary', args: {sticky: true, stroke: true}},
defaultAnchor: {name: 'perpendicular'},
```
They produce the same behavior as for bpmn-playground.

**Comment by GeorgiyZhuravlev** [comment]
UPD:

I've found only this way so far:

```
joint.shapes.bpmn.GatewayView = joint.dia.ElementView.extend({
  getNodeBBox: function(magnet) {
    // "el" will be used instead of params "magnet" in the calls below
    var el = joint.V(magnet).findOne('.rotatable'); 
    // the rest is original "CellView.getNodeBBox"
    var rect = this.getNodeBoundingRect(el);
    var magnetMatrix = this.getNodeMatrix(el);
    var translateMatrix = this.getRootTranslateMatrix();
    var rotateMatrix = this.getRootRotateMatrix();
    return V.transformRect(rect, translateMatrix.multiply(rotateMatrix).multiply(magnetMatrix));
  },
});
```
So, `GatewayView` got a modified `getNodeBBox` function, which omits text-related elements.

Can this be considered as an ok-ish solution for the described task? 
Or it can have unpredictable (bad) consequences?

**Comment by GeorgiyZhuravlev** [comment]
@kumilingus 

Thank you for the response!
```
joint.shapes.bpmn.Gateway({
  '.': { magnet: false },
  '.body': { magnet: true }
});
```
This solution works, but has some flaws:

1. With this setup, we have to be very precise when connecting shapes.
Otherwise, the arrow just ends somewhere inside the shape. 
Check the screencast: 
![screencast](https://user-images.githubusercontent.com/14068189/84368758-a9ea1080-abde-11ea-8031-d78513e436af.gif)

2. It doesn't modify the look of all the previously created diagrams, with Event/Gateway on them. So, only new diagrams will look nice, created after the change was deployed.

We'll try to live with `getNodeBBox` for now and observe.

**Comment by kumilingus** [comment]
1. Try to set `pointer-events: none` on `image`.
2. Right, you would need to modify the JSON before importing it to the `graph`.

What you really need here, is a custom `perpendicular` anchor. One that calculates the perpendicular point from the model (not from the view). I will deliver soon.

**Comment by kumilingus** [comment]
JointJS `v3.3` introduces `magnetSelector` and `highlighterSelector`. This should make the issue easy to resolve.

```js
el.attr({ root: { magnetSelector: '.body', highlighterSelector: '.body'  }});
```

Please see [documentation](https://resources.jointjs.com/mmap/joint.html) for more info.
