### ISSUE TITLE
DoubleLinkTools with new linkTools API

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1322]
I want to achieve a similar result to what has been possible before by setting
```js
options: joint.util.defaults({
    doubleLinkTools: true,
}, joint.dia.LinkView.prototype.options)
```
on a custom linkView type using the new linkTools API.

I thought of different solutions how to handle the additional buttons for longer links, but I'm not sure if they are possible and what would be considered best practice:
- hide and show a single linkTool using `linkTool.hide/.show()` depending on the link's length inside an `UPDATE` cycle
- add or remove a single linkTool, e.g. Remove button, after setting the toolsView for the link by manipulation the toolsView's tools array
- for each mouseover, create a completely new toolsView containing new (?) tools depending on how long the link is currently (this is how it was done in the [link demo](https://github.com/clientIO/joint/blob/master/demo/links/src/links.js))

Also another related question: Is it also possible to change some options, e.g. the `distance` of a `Button`, after tool creation s.th. it would be possible to move them depending on the link's length?

**Comment by kumilingus** [comment]
Resolved in `v4.1`:

```ts
new dia.ToolsView({
    tools: [
        new linkTools.Remove({
            distance: (linkView) => linkView.getConnectionLength() > 200 ? 40 : '50%'
        }),
        new linkTools.Remove({
            distance: -40,
            visibility: (linkView) => linkView.getConnectionLength() > 200
        })
    ]
});
```
