### ISSUE TITLE
Arrowhead linktool: prevent other linkTools from being displayed after mouseleave

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1334]
Currently, the mouseleave event is not sent after dragging the arrowhead of a link to a position where it doesn't stick, e.g. because the position is not valid or because we want to snap to the boundary. The problem can be observed in the [Link tools tutorial](https://resources.jointjs.com/tutorial/link-tools), part "interaction": After snapping the targetArrowhead to the "World!" cell, only the arrowhead tool is hidden, all others still remain shown despite the mouse pointer being outside the link.

![grafik](https://user-images.githubusercontent.com/18088991/87558720-b7048e80-c6b9-11ea-93a7-3df4ef340c2e.png)

**Comment by ialokim** [comment]
I have to correct myself, it seems `mouseleave` is indeed called, but because of `this.blur()` on pointerup in https://github.com/clientIO/joint/blob/master/src/linkTools/index.mjs#L678, the other tools are shown again.

**Comment by ialokim** [comment]
Any ideas on how this might be circumvented?

**Comment by kumilingus** [comment]
Hi, this works for me.
```js
    paper.on('link:mouseenter', function(linkView) {
        linkView.addTools(toolsView);
        linkView.showTools();
    });

    paper.on('link:mouseleave', function(linkView) {
        linkView.removeTools();
    });
```
 i.e. instead of toggling the visibility -> add/remove the tool. Anyway we need to look into this.

**Comment by kumilingus** [comment]
Resolved by https://github.com/clientIO/joint/commit/bd30bf87613d44c2c932341c86eb881f7b5c4d22.
