### ISSUE TITLE
Trigger magnet on mouse hold

### ISSUE THREAD

**Issue by skalidindi** [clientIO/joint#1336]
I have a ```element:magnet:pointerclick``` event listener which selects the magnet, highlights it and populates an associated form. However, a mouse click also triggers the magnet interaction (a draggable arrow to connect to another element). I only want this magnet interaction enabled on mouse hold rather than mouse click. Any way to achieve this?

**Comment by kumilingus** [comment]
Does `paper.options.magnetThreshold = 'onleave' does the trick?
