### ISSUE TITLE
graph.toJSON doesn't contain markup 

### ISSUE THREAD

**Issue by sadikmd5** [clientIO/joint#1339]
Hi,

I've the following setup in jointjs:

```
joint.shapes.project = {};
joint.shapes.project.aNode = joint.shapes.basic.Generic.extend({...});
joint.shapes.project.bNode = joint.shapes.project.aNode.extend({
    markup: '...',
    defaults: joint.util.deepSupplement({
        type: 'project.bNode'
    })
    ...
});
```

For shapes defined like this, graph.toJSON output doesn't contain markup data. This causes an issue when I try to load the shapes using graph.fromJSON method:

```
Error: dia.ElementView: markup required
    at child.renderMarkup 
    at child.render
    at child.protoProps.render 
    at child.confirmUpdate
    at child.updateView 
    at child.updateViewsBatch
    at child.updateViews
    at child.unfreeze
    at child.resetViews
    at child.onGraphReset 
    at triggerEvents
    at triggerApi
    at eventsApi
    at child.Events.trigger
    at triggerEvents
    at triggerApi 
    at eventsApi 
    at child.Events.trigger 
    at child.reset
    at child.resetCells
    at child.resetCells
    at child.set
    at child.fromJSON
```

Could you please help me with this issue? Do I need to change the custom shape creation code to use some other jointjs API like  joint.dia.Element.define instead of  joint.shapes.basic.Generic.extend?

**Comment by kumilingus** [comment]
Hi, sorry for late reply. The shape definition seems ok. It could be the namespace issue: https://github.com/clientIO/joint/issues/1133#issuecomment-509155062
