### ISSUE TITLE
Connector disappers if .link-tools display == none and dropshadow filter applied

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#134]
Consider the following connector:
	var myLink = joint.dia.Link.extend({
	    defaults: joint.util.deepSupplement({
	    	type: 'myType',
	        attrs: {
	        	'.': { filter: { name: 'dropShadow', args: { dx: 1, dy: 1, blur: 2 } } },
	        	'.connection': { 'stroke-width': 10, 'stroke-linecap': 'round' },	        	
	        	'.marker-vertices': { display : 'none' },
	        	'.marker-arrowheads': { display: 'none' },
	        	'.connection-wrap': { display: 'none' },
	        	'.tool-options': { display: 'none' },
//	        	'.link-tools': {display: 'none'}
	        },
	    	connector: { name: 'normalDimFix' }
	    }, joint.dia.Link.prototype.defaults)
	});

It appears.
Now uncomment the ''.link-tools': {display: 'none'}" line and connector would disappear. There is some sort of a problem with 'dropshadow' filter when link has 0-size "link-tools" group element.

**Comment by kumilingus** [comment]
Can not reproduce. Can you create a JSFiddle?
