### ISSUE TITLE
Visual Studio Code or Eclipse Theia extension

### ISSUE THREAD

**Issue by pankaj-gupta-74** [clientIO/joint#1344]
Is there extension available for Visual Studio Code or Eclipse Theia for joinjs or rappid?

**Comment by kumilingus** [comment]
Hi, what would like this extension to do for you?

**Comment by pankaj-gupta-74** [comment]
We are working on a solution that will have configurable workflow embedded in it. Having extension will help us in having features like debugging, display it in project explorer & menu bar etc.
