### ISSUE TITLE
need a proper implementation of joint.util.measureText

### ISSUE THREAD

**Issue by cecilwei** [clientIO/joint#1345]
We are implementing a shape that allows text to be scaled by freeTransform tool. And it seems that an initial size is required for the shape according to the text before we add the shape onto the paper.

We checked the implementation of measureText in the example of "Question Answer Dialogs" but it has 3 problems.

1. Font family is not specified.
2. Font size is not used in textNode and thus the getComputedTextLength() doesn't return correct text width.
3. Font height is calculated with a magic multiplier 1.2.

Please advise a proper way to defined a shape that allows text to be transformed with FreeFransform tool or a proper implementation of joint.util.measureText.

Thank you

**Comment by kumilingus** [comment]
Hi @cecilwei ,

here's an example that takes font-family, font-size and font-height into account.

```js
var maxWidth = 100;
var padding = 5;
var text = 'Activity 123 (Some Name)';
var rect = new joint.shapes.standard.Rectangle();
var bbox = measureText(text, rect.attr('label'));
rect.prop({
    size: { width: bbox.width + 2 * padding, height: bbox.height + 2 * padding },
    attrs: {
        label: {
            text: text,
            textWrap: {
                width: - 2 * padding
            }
        }
    }
});

rect.addTo(graph);

function measureText(text, attrs) {
    var fontAttrs = {
        'font-size': attrs.fontSize,
        'font-family': attrs.fontFamily
    };
    var svgDocument = V('svg');
    var textElement = V('text');
    svgDocument.append(textElement);
    document.body.appendChild(svgDocument.node);
    textElement.text(text, fontAttrs);
    var bbox = textElement.getBBox();
    if (bbox.width > maxWidth) {
        var wrapText = joint.util.breakText(text, { width: maxWidth }, fontAttrs);
        textElement.text(wrapText, fontAttrs);
        bbox = textElement.getBBox();
    }
    svgDocument.remove();
    return bbox;
}
```
