### ISSUE TITLE
toFront and toBack don't know work on HTML element

### ISSUE THREAD

**Issue by konekoya** [clientIO/joint#1353]
Hi @kumilingus, 

When using `toFront()` or `toBack()` to change an HTML element's stacking order, the underlying SVG element will have the correct `z` value set and so move to the correct stacking order (front or back). But the HTML element will not and will always be visible just like it hasn't been changed at all. I've tested this with the [html](https://github.com/clientIO/joint/tree/master/demo/html) demo. Could you please take a look?

Thanks!

**Comment by kumilingus** [comment]
Hi @konekoya, it's just a demo. It does not support all the features.

- `z` indexes do not work.
- ports are always under the HTML Element views
- it can not be exported to SVG/PNG

And perhaps more.

You'd need to sort the elements inside the `htmlContainer` (https://github.com/clientIO/joint/blob/master/demo/html/src/html.js#L25) based on the order of elements in the graph (`graph.getElements()`). For that, you can use `util.sortElements()` (https://github.com/clientIO/joint/blob/master/src/util/util.mjs#L904) whenever the `sort` event is triggered on the graph.

**Comment by kumilingus** [comment]
Hi @konekoya, I've  had a second thought about the sorting. We can take advantage of `z-index` CSS property in HTML. There were also a few issues with pointer events after sorting I didn't realise before.

Here's a PR: https://github.com/clientIO/joint/pull/1362

**Comment by konekoya** [comment]
Thank you so much for this :)
