### ISSUE TITLE
With a link "strokeWidth" of 2,graph.toJSON() cannot read the property

### ISSUE THREAD

**Issue by leekbillow** [clientIO/joint#1355]
```javascript
//add a link,strokeWidth==2
new joint.shapes.standard.Link().prop({source:{x:0,y:0},target:{x:100,y:100}}).attr({line:{strokeWidth:2}}).addTo(graph)
//return {},no data
graph.toJSON().cells[0].attrs
```
```javascript
//add a link,strokeWidth!=2
new joint.shapes.standard.Link().prop({source:{x:0,y:0},target:{x:100,y:100}}).attr({line:{strokeWidth:3}}).addTo(graph)
//return 3
graph.toJSON().cells[0].attrs.line.strokeWidth
```

**Comment by kumilingus** [comment]
Hi, it's a feature. Not a bug.

We don't include default `attrs` in the resulting JSON (https://github.com/clientIO/joint/blob/master/src/shapes/standard.mjs#L599).

You can override the `toJSON()` to return all the attributes (or extend the Link or create a Link without default attributes)
```js
joint.dia.Cell.prototype.toJSON = function() { return joint.util.cloneDeep(this.attributes); }
```

**Comment by leekbillow** [comment]
> Hi, it's a feature. Not a bug.
> 
> We don't include default `attrs` in the resulting JSON (https://github.com/clientIO/joint/blob/master/src/shapes/standard.mjs#L599).
> 
> You can override the `toJSON()` to return all the attributes (or extend the Link or create a Link without default attributes)
> 
> ```js
> joint.dia.Cell.prototype.toJSON = function() { return joint.util.cloneDeep(this.attributes); }
> ```

Okay, although I don't understand why it was designed that way, right

**Comment by kumilingus** [comment]
To remove redundant info from the resulting JSON. Suppose you have 1000 default links. Every link in the JSON would export the same attributes.

Are you trying to render the graph in a different client? Or do you use presentation (visual) attributes as an input for your business logic? (if stroke width has a certain meaning, I'd suggest introduce a top level attribute with this semantic value e.g. `link.set('noOfTokens', 1000);` vs `link.attr('line/strokeWidth', 20)`)

Perhaps we could add an option to `toJSON()` e.g. `graph.toJSON({ explicit: true })` which would lead to exporting the default values too.

**Comment by leekbillow** [comment]
> To remove redundant info from the resulting JSON. Suppose you have 1000 default links. Every link in the JSON would export the same attributes.
> 
> Are you trying to render the graph in a different client? Or do you use presentation (visual) attributes as an input for your business logic? (if stroke width has a certain meaning, I'd suggest introduce a top level attribute with this semantic value e.g. `link.set('noOfTokens', 1000);` vs `link.attr('line/strokeWidth', 20)`)
> 
> Perhaps we could add an option to `toJSON()` e.g. `graph.toJSON({ explicit: true })` which would lead to exporting the default values too.

I also think the optional configuration is a better choice. When there is only one default value attribute, it will return undefined instead of {}, requiring extra judgment when reading to prevent error
