### ISSUE TITLE
Connector jumpover leading cell selection slow.

### ISSUE THREAD

**Issue by asahu132** [clientIO/joint#1356]
Hi Team,
I am facing an issue while using **jumpover** connector it is attaching one more extra listner on event **cell:pointerup** which is making over app slow to select a cell when the graph size gets increase.

**Comment by abhisheksahu132** [comment]
@kumilingus are you guys working on this performance issue?
 This issue has been fixed in #1357

**Comment by kumilingus** [comment]
Hi @asahu132, I haven't started yet. We'll definitely look into it before the next release. At this point I am not sure if listening to `batch:stop` is the best solution (it seems better than `cell:pointerup` though 👍 ).

**Comment by kumilingus** [comment]
Fixed by https://github.com/clientIO/joint/commit/42d7f86a274fbabcabda87e8bcd4c1988ef54c71.
