### ISSUE TITLE
Can you break the binding between lodash and backbone?

### ISSUE THREAD

**Issue by leekbillow** [clientIO/joint#1359]
Jointjs requires "backbone" to replace "underscore" with "lodash", but there are differences between them, so the plugin that needs "underscore" cannot be used. Is there any solution?

**Comment by kumilingus** [comment]
Hi, does this answer your question https://stackoverflow.com/questions/29139075/using-lodash-instead-of-underscore-in-backbone-js-application?

**Comment by kumilingus** [comment]
Note, once we implement all these methods (https://github.com/clientIO/joint/blob/master/src/util/util.mjs#L1587-L1663) we can get rid of the Lodash dependency completely.

**Comment by leekbillow** [comment]
> Note, once we implement all these methods (https://github.com/clientIO/joint/blob/master/src/util/util.mjs#L1587-L1663) we can get rid of the Lodash dependency completely.

If It was JoinJS that introduced Lodash instead of backbone, it wouldn't be an issue,maybe it's more difficult to implement

**Comment by kumilingus** [comment]
JointJS supports Lodash `v3.10.1`. This older version should be compatible with `underscore`, right?

**Comment by leekbillow** [comment]
> JointJS supports Lodash `v3.10.1`. This older version should be compatible with `underscore`, right?

Yes, I haven't found any problems with this version yet, but I'm not sure if there are any potential problems
