### ISSUE TITLE
Having trouble in using the api of joint.ui library

### ISSUE THREAD

**Issue by slakena** [clientIO/joint#1365]
I am using Jointjs with react.
And I want to use **Joint.ui.dialog** in my app, but I am getting below error

TypeError: jointjs_index__WEBPACK_IMPORTED_MODULE_3___default.a.ui.Dialog is not a constructor.

How can I use **joint.ui**  API's in my react app?

**Comment by kumilingus** [comment]
Are you referring to JointJS (open source) or Rappid (commercial)?
The `ui` plugins are part of Rappid only (https://www.jointjs.com/rappid-comparison).

**Comment by slakena** [comment]
I am using joint js (open source).

**Comment by kumilingus** [comment]
You would need to purchase the Rappid license if you want to use `ui`, `format` and other plugins.
Here's a link for a free trial (https://www.jointjs.com/rappid-trial).
