### ISSUE TITLE
[TypeScript] Is it possible that the GenericAttributes interface misses an attrs type?  

### ISSUE THREAD

**Issue by konekoya** [clientIO/joint#1366]
Hi @kumilingus,

We're migrating our project to TypeScript and run into a typing related issue which is somewhat troublesome:

Following is a React and TS based component in which we render a standard rectangle with jointjs along with some extra HTML markup:

```ts
const shapeOptions = {
  // Binding a custom event and so we can later use in Paper
  attrs: {
    '.element-menu': {
      event: 'element:menu:pointerclick',
    },
  },
  ...otherOptions,
};

// Creating the Rect with some custom attributes
const rect = new joint.shapes.standard.Rectangle({
  ...shapeOptions,
  markup:
    `<rect stroke-width="${strokeWidth}" stroke="${strokeColor}" fill="${fillColor}" width="${width}" height="${height}"></rect>` +
    htmlMarkup,
});
```

This used to work perfectly in plain JS, but now TypeScript is complaining about:
```
Argument of type '{ markup: string; id: string | undefined; position: Coordinates | undefined; z: number | undefined; size: Size; settings: { kind: Kind | undefined; displayName: string; shapeType: ShapeType | undefined; imageUrl: string; }; attrs: { ...; }; }' is not assignable to parameter of type 'GenericAttributes<RectangleSelectors>'.
  Types of property 'attrs' are incompatible.
    Type '{ '.element-menu': { event: string; }; }' has no properties in common with type 'RectangleSelectors'.ts(2345)
```

After some digging, we found it would work if we added the type definition of `attrs` in the `joint.d.ts` under the section of `GenericAttributes` interface:
```ts
interface GenericAttributes<T> extends Cell.GenericAttributes<T> {
    markup?: string | MarkupJSON;
    position?: Point;
    size?: Size;
    angle?: number;
    ports?: {
        groups?: { [key: string]: PortGroup},
        items?: Port[]
    }
    attrs?: {[key:string]: any} // 👈  this type
} 
```

Not sure if this is a missing type in jointjs or just we're not correctly typing the component?

Thank you!

**Comment by kumilingus** [comment]
It says the types of property `attrs` are incompatible.
```
    Type '{ '.element-menu': { event: string; }; }' has no properties in common with type 'RectangleSelectors'.ts(2345)
```
There is no `.element-menu` selector defined for `standard.Rectangle`. Are you adding a menu button to the markup at some point?

**Comment by konekoya** [comment]
Thanks for the quick reply 🙏 

Yes. We have some custom HTML in the `markup` attribute wrapping in a `foreignObject` tag:

```ts
const htmlMarkup = `<foreignObject class="shape-wrapper" width="${width}" height="${height}">
      <div class="element-title" xmlns="http://www.w3.org/1999/xhtml" contenteditable="true">${newDisplayName}</div>
      <div class="element-menu" xmlns="http://www.w3.org/1999/xhtml">
        <div class="element-menu-inner" xmlns="http://www.w3.org/1999/xhtml">
          <button class="element-menu-link" xmlns="http://www.w3.org/1999/xhtml">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">${linkIcon}</svg>
          </button>
          <button class="element-menu-remove" xmlns="http://www.w3.org/1999/xhtml">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">${removeIcon}</svg>
          </button>
        </div>
      </div>
  </foreignObject>`;
```

Hmm, but I'm still not sure how to extend the type of `joint.shapes.standard.Rectangle`. Could you shed some light this?

**Comment by kumilingus** [comment]
I would define a custom element (instead of changing the markup of `standard.Rectangle`) .

1. Extend `dia.Element` or `standard.Rectangle`
e.g. https://github.com/clientIO/joint/blob/master/demo/ts-demo/custom.ts#L4-L48

2. Add TS definition for the new shape with the `RectangleSelectors` constraint removed/changed.
e.g. https://github.com/clientIO/joint/blob/master/types/joint.d.ts#L1422-L1433

**Comment by konekoya** [comment]
Thanks for the help @kumilingus. I will give this a shot and report back if I'm not able to get it working :)

**Comment by konekoya** [comment]
I'm closing this issue as our Project is unfortunately suspended due to the company policy 🙁  And it's unlikely I will spend time testing this out. Thanks for the help @kumilingus 🙏
