### ISSUE TITLE
Error using JointJS with Angular 9

### ISSUE THREAD

**Issue by nikuelias** [clientIO/joint#1368]
Hey!

I have added the JointJS to my project, and I'm seeing this error:

`joint.js:9994 Uncaught TypeError: Cannot read property 'assign' of undefined
    at joint.js:9994
    at joint.js:11
    at joint.js:12`

The chart is rendered anyway, but I would like to know why its happening. Looks like a problem with the lodash.
My imports on the package.json are:

`
...
"lodash": "^4.17.10",
"jointjs": "3.2.0",
`

and on devDependencies:

`
"@types/backbone": "1.3.42",
"@types/jquery": "^3.3.32",
"install": "^0.13.0",
"jquery": "^3.5.1",
"npm": "^6.14.8",
`

I don't know if anything Is missing or what...

I have also added "skipLibCheck": true, to the tsconfig.json

If you have any recommendations please let me know

Thanks!

**Comment by kumilingus** [comment]
Please, try to install `@types/lodash` dev dependency too. (https://github.com/clientIO/joint/blob/master/demo/ts-demo/package.json#L17)

**Comment by hijoncon** [comment]
@nikuelias @kumilingus I suggest you put all the dependencies in scripts.
```
"scripts": [
  "node_modules/jquery/dist/jquery.js",
  "node_modules/lodash/lodash.js",
  "node_modules/backbone/backbone.js",
  "node_modules/dagre/dist/dagre.js",
  "node_modules/graphlib/dist/graphlib.js",
  "node_modules/jointjs/dist/joint.js",
],
```
