### ISSUE TITLE
Gird not being drawn

### ISSUE THREAD

**Issue by chipit24** [clientIO/joint#1385]
Link to reproduction on CodeSandbox: https://codesandbox.io/s/jolly-bhaskara-op6c8?file=/src/App.vue.

I set up a paper object with the following options:
```js
new joint.dia.Paper({
  el: this.$refs["paper-el"],
  model: graph,
  drawGrid: true,
  gridSize: 10,
  width: 500,
  height: 500,
});
```

Despite setting [`drawGrid`](https://resources.jointjs.com/docs/jointjs/v3.2/joint.html#dia.Paper.prototype.options.drawGrid) to `true`, I don't see the grid being draw:
<img width="490" alt="Screen Shot 2020-10-23 at 12 10 49 AM" src="https://user-images.githubusercontent.com/7561061/96955707-36c5a480-14c4-11eb-84e5-199a46b2721c.png">

I'm using jointjs v3.2.0. Is this a bug or am I missing an option or function call?

**Comment by kumilingus** [comment]
You are missing `joint.css`? Specifically https://github.com/clientIO/joint/blob/master/css/layout.css#L16-L24.

**Comment by chipit24** [comment]
Yes, I was, oops 🤦🏻‍♂️ thank you!
