### ISSUE TITLE
fromJSON() with vertices. Can't move the loaded vertices

### ISSUE THREAD

**Issue by 3tt1** [clientIO/joint#1389]
To reproduce the bug: 
- load a flowchart with vertices with the function fromJSON()
- move a vertice 
=> the vertice move but the line/link don't follow

If you move the line after, it will catch up with the previously moved vertice

**Comment by kumilingus** [comment]
Hi, those are not steps to reproduce the issue. It works as expected. Could you create a JSFiddle that shows exactly the issue?

**Comment by 3tt1** [comment]
You're right. I did a fiddle and it works as expected. I probably did something wrong with my code. Thanks for your response

**Comment by kumilingus** [comment]
I would check how you set the vertices. A vertex has to be a plain object (not an instance of `g.Point`).

```js
const point = new g.Point(100, 200);

// wrong
link.set('vertices', [point]);

// correct
link.set('vertices', [point.toJSON()])
```
