### ISSUE TITLE
Performance: Browser freezes when added 1000 of elements in a group (embed)

### ISSUE THREAD

**Issue by hijoncon** [clientIO/joint#1400]
Hi,

Is there a better way to add a group that will be part of the paper.unfreeze? It seems that adding a group is bypassing the batchSize. Here is my code.

```
const GROUP_RED = this.makeGroup();
const GROUP_GREEN = this.makeGroup();
const GROUP_YELLOW = this.makeGroup();

RED.forEach(data => GROUP_RED.embed(data));
GREEN.forEach(data => GROUP_GREEN.embed(data));
YELLOW.forEach(data => GROUP_YELLOW.embed(data));

this.graph.resetCells([
  ...[GROUP_RED, GROUP_GREEN, GROUP_YELLOW],
  ...REDS,
  ...GREENS,
  ...YELLOWS,
  ...EDGES
]);

joint.layout.DirectedGraph.layout(this.graph, {
  rankDir: 'LR',
  // align: 'UR',
  edgeSep: 0,
  rankSep: 120,
  nodeSep: 20
});

paper.unfreeze({
  batchSize: 50,
  progress: (done, current, total) => {
    var progress = current / total;
    console.log(Math.round(progress * 100) + '%');
    if (done) {
      paper.unfreeze();
    }
  }
});
```

**Comment by kumilingus** [comment]
Hi,

I don't think I understand. Adding an element to a container (embedding or un-embedding) is not visual. It does not trigger/require an update on paper. It is only used when the user drags the parent later, for parent/child API, and similar.

In your example, the `batchSize` makes sure that the `progress` callback is called after each `50` updates (render/update an element or link), each in a separate `requestAnimationFrame`.

**Comment by hijoncon** [comment]
Hi @kumilingus,

Thanks for checking my issue. Sorry I didn't give you more information. For your question yes the `paper.options.async` is enabled.

Here is the process that I have, I am getting 1000+ elements and I need to group all reds, yellows, and greens into clusters.

```
this.graph.resetCells([
  ...[GROUP_RED, GROUP_GREEN, GROUP_YELLOW], // This line where the freeze happen.
```

Here the screenshot: (gif)

![Screen Recording 2020-12-07 at 3 56 44 PM](https://user-images.githubusercontent.com/556139/101419596-33844d80-38a5-11eb-9ef5-896fc5ba3596.gif)

I think the progress callback works expected or maybe I am not using the right way.

Any idea?

**Comment by kumilingus** [comment]
Are you saying that if you do not group elements into clusters it won't freeze?
Are you using the `manhattan` router? Is it freezing if you don't?

Here's a demo where you can render 10k elements and 10k links: https://github.com/clientIO/joint/blob/master/demo/performance/async.js 
Perhaps, you could inspire there. The demo is using sort of a virtual rendering (rendering elements and links in the viewport - visible to user - only).

Unless you would be able to share the code with me, I am not sure If I can help here 100%.

**Comment by hijoncon** [comment]
@kumilingus yes if I don't group them it won't freeze and yes I am using `manhattan` router.
I have investigated the async in the demo. I will produce the issue using jsFidlle today and link it here. Thanks
