### ISSUE TITLE
Polygon: attributes refWidth and refHeight not working correct

### ISSUE THREAD

**Issue by Bloeffy** [clientIO/joint#1401]
When using a "ref" for a polygon i cant use the attributes refWidth and refHeight like i use them for example in a Rectangle. 

It automaticly uses the width and height from the "ref" (in my case the label). But i cant make it bigger by a few pixels like i do it in Rectangles. 

```javascript
// custom element for signal outputs
    joint.shapes.examples.SignalOutput = joint.shapes.standard.Polygon.define('examples.SignalOutput', {
        attrs: {
            // root: {
            //     magnet: true
            // },
            label: {
                text: 'Test'+ `\n`+ 'newLine'+ `\n`+ 'newLine',
                fill: 'black',
                fontSize: 13,
                textAnchor: 'middle',
                textVerticalAnchor: 'middle' 
            },
            body: {
                ref: 'label',
                refX: 0,
                refY: 0,
                refWidth: 20,
                refHeight: 20,
                fill: 'lightgray',
                strokeWidth: 1,
                refPoints: '0,20 0,0 20,0 25,10 20,20'
            },
        }
    }, {
        markup: [{
            tagName: 'polygon',
            selector: 'body',
        }, {
            tagName: 'text',
            selector: 'label'
        }]
    })
```

**Comment by tinhnt2272** [comment]
I have same problem then I try:
joint.shapes.examples.SignalOutput = joint.shapes.standard.Polygon.define('examples.SignalOutput', {
        attrs: {
            label: {
                text: 'Test'+ `\n`+ 'newLine'+ `\n`+ 'newLine',
                fill: 'black',
                fontSize: 13,
                textAnchor: 'middle',
                textVerticalAnchor: 'middle' 
            },
            body: {
                ref: 'wrapper',
                refX: 0,
                refY: 0,
                fill: 'lightgray',
                strokeWidth: 1,
                refPoints: '0,20 0,0 20,0 25,10 20,20'
            },
            wrapper: {
                ref: 'label',
                refWidth: '100%',
                refHeight: '100%',
                refWidth2: 20
            }
        }
    }, {
        markup: [
            {
            tagName: 'polygon',
            selector: 'body',
        }, 
        {
            tagName: 'rect',
            selector: wrapper,
        }
        {
            tagName: 'text',
            selector: 'label'
        }
        ]
    })
It's work for me

**Comment by kumilingus** [comment]
The `refWidth` sets the `width` attribute on the SVG node. `width` is not a valid attribute for `<polygon/>`.
In `v3.4.0` you can use `points` attribute with `calc()` expression.

```js
refX: 0,
refY: 0,
points: '-10,0 0,-10 calc(w),-10 calc(w+10),0 calc(w+10),calc(h) calc(w),calc(h+10) 0,calc(h+10) -10,calc(h)',
```
