### ISSUE TITLE
Manhattan router should exclude invisible(collapsed) elements

### ISSUE THREAD

**Issue by yfwz100** [clientIO/joint#1412]
JointJS 3.3.0 has included a new demo showing how to collapse/expand elements with paper viewport setting. However, invisible(collapsed) elements could still block the routes of link.

**Comment by yfwz100** [comment]
I also noticed the performance issue of manhattan router. There should be a performance boost If the invisible elements((either collapsed by embedding elements or outside viewport) are excluded.

I suggest a excluding function to be provided as a customizable option.

**Comment by candersony** [comment]
I think this would be a great enhancement for the router. Looking at the manhattan router source, it currently creates an [`ObstacleMap`](https://github.com/clientIO/joint/blob/891418932dea160d7d23260b33e79fb41769eff1/src/routers/manhattan.mjs#L775) internally. 

Perhaps the obstacle map could be a parameter to the router, then we could take full control of what is considered an obstacle.

e.g.
```js
const paper = new dia.Paper({
  defaultRouter: (vertices, opt, linkView) => {
    const obstacleMap = createObstacleMap();

    return routers.manhattan(vertices, { ...opt, obstacleMap }, linkView);
 }
})
```

**Comment by kumilingus** [comment]
@candersony I totally agree. This could also help the performance if the obstacle map is created once and only updated on certain graph changes (size, position, angle, add, remove). Currently, the map is built from scratch on each link update.

```js
const obstacles = new Obstacles({ graph });
const paper = new dia.Paper({
  defaultRouter: (vertices, opt, linkView) => {
    return routers.manhattan(vertices, {
      ...opt,
      obstacleMap: () => obstacles.getMap()
    }, linkView);
 }
});
```

@yfwz100 it would help in your case too. The invisible elements could be removed from the obstacle map.

**Comment by yfwz100** [comment]
Yes, it will surely help the case. To make it work, I have overridden the obstracle map internally in my project but it'll be great if it's built into the core.

**Comment by kumilingus** [comment]
There was `isPointObstacle` option added in `v3.4.0`.  The design of the obstacle map is completely up to user.

```js
const obstacleMap = createObstacleMap(); // any implementation of the obstacle map
const paper = new dia.Paper({
  /* ... */
  defaultRouter: (vertices, opt, linkView) => {
    const isPointObstacle = (point) => obstacleMap.isPointObstacle(point);
    return routers.manhattan(vertices, { ...opt, isPointObstacle }, linkView);
 }
});
```
