### ISSUE TITLE
[TypeScript] Type definitions for event handlers?

### ISSUE THREAD

**Issue by Ladas125** [clientIO/joint#1418]
Is there any documentation about which TS types of function params are the event handlers called with?
The JointJS resources only tell the name of the params and I am not sure if I have guessed the types properly.

![image](https://user-images.githubusercontent.com/15906447/106729917-4c438200-660e-11eb-8bfd-18c3ed3b8719.png)

For example parameter called cellView can be easily guessed to type joint.dia.CellView but not all params have such descriptive names.

**Comment by kumilingus** [comment]
Fixed in #1596.
