### ISSUE TITLE
Cannot get 0.9.3 Joint JS via Bower

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#142]
I have a dependency on Joint JS 0.9.3 and recently I started getting this error when building my app:
bower joint#0.9.3                  ENORESTARGET No tag found that was able to satisfy 0.9.3

Something hapenned to 0.9.3 tag... Can you fix that please?

**Comment by chill117** [comment]
Should work again now. You may need to run the following to clear your bower cache:
```
bower cache clean
```
