### ISSUE TITLE
Element and Link pointerclick doesnt work in FullScreen mode on Chrome

### ISSUE THREAD

**Issue by Bloeffy** [clientIO/joint#1424]
When pressing f11 the Element- /Link-Views doesnt show up in Chrome Browser. The element:pointerclick and link:pointerclick event doesnt recognize the click interaction. Dragging the Elements still works

In Firefox: I implemented, that i can drag links from shape to shape. That doesnt work in firefox fullscreen mode.

Does someone ever had this Problems?

**Comment by kumilingus** [comment]
Hi, is this reproducible in any of our online demos? https://resources.jointjs.com/demos

**Comment by Bloeffy** [comment]
No i cant reproduce it with you examples. Is it possible that this happens because i am using JointJs insite a Vue.js app?

**Comment by kumilingus** [comment]
I don't know. Do you see any errors in the console? Is your application accessible from web? Could you perhaps create a JSFiddle with the issue?

**Comment by Bloeffy** [comment]
I reworked the funktionality to drag links from shape to shape and deleted an event that delets all redundant vertices whenever the vertices on a link change and now it works fine in f11 for both browsers. 

I dont fully understand why this blocked the onclick event on elements, but as long as it works now i am happy. 

But thanks for trying to help, its not an open projekt so i wasnt able to share the projekt and an JSFiddle would have been to complex, its a quite large projekt.

**Comment by kumilingus** [comment]
Ok, I am glad you have managed to resolve it. Feel free to reopen this if it comes back and we have a reproducible scenario.
