### ISSUE TITLE
Example Custom Shape does not work as specified in Documentation.

### ISSUE THREAD

**Issue by rayhoffmann-ANSYS** [clientIO/joint#1426]
Hi, I'm trying to use the CustomRectangle example as in this link: https://resources.jointjs.com/tutorial/custom-elements

I copied things to my code as follow:

`import * as joint from '@clientio/rappid';
import _ from 'lodash';
import V from 'jquery';

var graph;
var paper;

export function InitializeJoint(paperEl) {
    graph = new joint.dia.Graph({}, {cellNamespace: joint.shapes.custom});

    paper = new joint.dia.Paper({
        cellViewNamespace: joint.shapes.custom,
        el: paperEl,
        width: 500,
        height: 500,
        origin: { x: 600, y: 600 },
        gridSize: 10,
        linkPinning: false,
        drawGrid: true,
        background: {
            color: '#fafafa'
        },
        model: graph
    });

    joint.shapes.examples = {};
    joint.shapes.standard.Rectangle.define('examples.CustomRectangle', {
        attrs: {
            body: {
                rx: 10, // add a corner radius
                ry: 10,
                strokeWidth: 1,
                fill: 'cornflowerblue'
            },
            label: {
                textAnchor: 'left', // align text to left
                refX: 10, // offset text from right edge of model bbox
                fill: 'white',
                fontSize: 18
            }
        }
    }, {
        // inherit joint.shapes.standard.Rectangle.markup
    }, {
        createRandom: function() {

            var rectangle = new this();

            var fill = '#' + ('000000' + Math.floor(Math.random() * 16777215).toString(16)).slice(-6);
            var stroke = '#' + ('000000' + Math.floor(Math.random() * 16777215).toString(16)).slice(-6);
            var strokeWidth = Math.floor(Math.random() * 6);
            var strokeDasharray = Math.floor(Math.random() * 6) + ' ' + Math.floor(Math.random() * 6);
            var radius = Math.floor(Math.random() * 21);

            rectangle.attr({
                body: {
                    fill: fill,
                    stroke: stroke,
                    strokeWidth: strokeWidth,
                    strokeDasharray: strokeDasharray,
                    rx: radius,
                    ry: radius
                },
                label: { // ensure visibility on dark backgrounds
                    fill: 'black',
                    stroke: 'white',
                    strokeWidth: 1,
                    fontWeight: 'bold'
                }
            });

            return rectangle;
        }
    });
    var rect3 = joint.shapes.examples.CustomRectangle.createRandom();
    rect3.position(50, 225);
    rect3.resize(500, 50);
    rect3.attr({
        label: {
            text: 'shapes.examples.CustomRectangle.createRandom()'
        }
    });
    rect3.addTo(graph);
}
`

This is the error  I get: 
`
core.js:6241 ERROR TypeError: Cannot read property 'createRandom' of undefined

    at Module.InitializeJoint (schematicElements.js:111)

    at SchematicViewComponent.ngOnInit (schematic-view.component.ts:93)

    at callHook (core.js:4726)

    at callHooks (core.js:4690)

    at executeInitAndCheckHooks (core.js:4630)

    at refreshView (core.js:12026)

    at refreshComponent (core.js:13458)

    at refreshChildComponents (core.js:11729)

    at refreshView (core.js:12064)

    at renderComponentOrTemplate (core.js:12142)
`

What is missing from the Examples?  What is the correct way of doing this?

**Comment by kumilingus** [comment]
When you load Rappid as ESM this don't work. `joint.shapes` will not get modified.

Use this instead:
```js
const CustomRectangle = joint.shapes.standard.Rectangle.define('examples.CustomRectangle', /* ... */);
const rect = CustomRectangle.createRandom();
```

And define your shape namespace this way:
```js
Object.assign(joint.shapes, {
  examples: {
     CustomRectangle
  }  
});

const graph = new joint.dia.Graph({}, { cellNamespace: joint.shapes }});
const paper = new joint.dia.Paper({  cellViewNamespace: joint.shapes /* ... */ });
```

**Comment by rayhoffmann-ANSYS** [comment]
Thanks for this @kumilingus, your suggestion does help!

Is there something similar that needs to be done to allow extending ElementView to work?  I get errors saying things like `dia.ElementView: markup required` when I try to extend ElementView for a custom shape.  Tracing through the code, the markup I supply in the ElementView (as examples in the docs and online show) just never seems to be found.

**Comment by kumilingus** [comment]
Have you added to the namespace?
```js
Object.assign(joint.shapes, {
  examples: {
     CustomRectangle,
     CustomRectangleView
  }  
});

const graph = new joint.dia.Graph({}, { cellNamespace: joint.shapes }});
const paper = new joint.dia.Paper({  cellViewNamespace: joint.shapes /* ... */ });
```

**Comment by kumilingus** [comment]
Here's a tutorial that might help: https://resources.jointjs.com/tutorial/ts-shape
