### ISSUE TITLE
Updated Dependencies List

### ISSUE THREAD

**Issue by stap123** [clientIO/joint#1429]
Is there an updated list of dependencies and their versions? Your installation document [here](https://resources.jointjs.com/tutorial/installation) is still listing 2.1.0 dependencies are there any changes? Do all of the updated versions of lodash/backbone work?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.1.0/joint.js"></script>
```

**Comment by kumilingus** [comment]
Here's a list of recommended versions https://www.jointjs.com/opensource (at the bottom of the page).
The tutorial needs updating. Thanks!

**Comment by stap123** [comment]
Awesome, thanks :) keep up the good work.

Do you want me to leave this open for the tutorial update tracking?

**Comment by kumilingus** [comment]
Yes, please :)
