### ISSUE TITLE
Issue within Browser view less or greater than 100% in shapes.standard.TextBlock

### ISSUE THREAD

**Issue by hijoncon** [clientIO/joint#1433]
I found a weird issue in `shapes.standard.TextBlock` when the browser zoom is less or greater than 100% initial load of the chart lines looks funky. I also tried to use `shapes.standard.Rectangle` with a markup that contains `foreignObject` I got the same issue. Do you have any idea how can we solve this?

Current version: `"jointjs": "^3.3.1"`

![screen shot](https://user-images.githubusercontent.com/556139/107556605-799fab00-6b8d-11eb-8b53-ba6853d1e20b.png)

**Comment by kumilingus** [comment]
It seems like a bug in Chrome. It's not happening in Firefox.

This should fix the issue (`v3.3+`).
```js
// Let links connect the SVGRectangle instead of the root SVGGroup
// (and measure the size of the rectangle only - not the size of the group that includes ForeignObject)
textBlock.attr('root/magnetSelector', 'body');
```
