### ISSUE TITLE
Start and End Connection Directions Do not work with Ports

### ISSUE THREAD

**Issue by umesh-timalsina** [clientIO/joint#1436]
Hello, I am using the Manhattan router to Programitically add Links between elements with Ports. I see that there are options to include `startDirections` and `endDirections` for a Link when using the `Manhattan` [router](https://resources.jointjs.com/docs/jointjs/v3.3/joint.html#routers.manhattan). However, it looks like the arguments are for the element itself rather than its ports. Is there a way to specify links between two elements with `Ports` such that the link never overlaps the element itself?

Case in Point. Consider the logic domain example. I want to avoid situations like these where the links overlap the element itself.

![image](https://user-images.githubusercontent.com/11476842/108733070-c2dbed00-74f3-11eb-9509-e0d91ae2777d.png)

**Comment by umesh-timalsina** [comment]
@kumilingus Any resolution for this? I see that there's a connection strategy that might solve this problem? Can we specify connection strategies programmitcally?

**Comment by kumilingus** [comment]
In the logic demo, when I set the manhattan router I don't see the issue.
```js
const paper = new joint.dia.Paper({
    defaultLink: () => {
        return new joint.shapes.logic.Wire({
            router: {
                name: 'manhattan',
                args: {
                    startDirections: ['right'],
                    endDirections: ['left']
                }
            }
        });
    }
});
 ```

Note, that `defaultRouter` option will have no effect in this demo, since `logic.Wire` has router set explicitly on the [model](https://github.com/kumilingus/joint/blob/master/src/shapes/logic.mjs#L142).

**Comment by umesh-timalsina** [comment]
The similar setup doesn't work for me. I have attached a MWE in this [pen](https://codepen.io/umesh-timalsina/pen/eYBbJjr) to reproduce this issue. 
What is rendered?
![image](https://user-images.githubusercontent.com/11476842/110717929-9d2b3500-81cf-11eb-8f8e-5b1248d3ee8a.png)



What I ideally want:
![image](https://user-images.githubusercontent.com/11476842/110717758-43c30600-81cf-11eb-8703-0f7b4d3ce551.png)
![image](https://user-images.githubusercontent.com/11476842/110718039-d794d200-81cf-11eb-8e38-ea8b1fcb4eb7.png)

**Comment by marty0678** [comment]
@umesh-timalsina did you ever find a solution to this? I'm encountering the same issue where the start and end directions appear to not apply to the port. Thanks!

**Comment by kumilingus** [comment]
In this case, the end port was placed too deep inside the element, so the path could not be found because the element itself presented an obstacle. See updated [CodePen](https://codepen.io/jointjs/pen/ExQbPOK/5a711837b551e38a64f6f63f17321de8).

Do not treat the source and target elements as obstacles:
```js
link.router('manhattan', {
  startDirections: ['left'],
  endDirections: ['bottom'],
  excludeEnds: ['source', 'target'],
});
```

**Comment by marty0678** [comment]
Interesting, thanks for the suggestion. That does technically work for the arrows, but the routes become quite undesirable of course now that they are going through their parent elements.

And the routing ends up having the line go straight up/down then 180ing to go back the other way after the padding pixels are finished which is a bit odd.

I'll keep playing around with it. Thanks!

**Comment by kumilingus** [comment]
There is a several issues with Manhattan router that we are trying to address in the #1647.

If you don't want to exclude ends, you have move the ports closer to the edge of the shape (increasing the manhattan `padding` option might also help).
