### ISSUE TITLE
Typescript - Property 'translate' does not exist on type 'Cell'.

### ISSUE THREAD

**Issue by Joebayld** [clientIO/joint#1437]
I'm trying to use this library and copied the code from the getting starting tutorial. However I'm getting this issue when using the example code. 

I can confirm I have `@types/backbone"` installed. 

Any ideas?

![image](https://user-images.githubusercontent.com/9399317/109441929-97716a80-79eb-11eb-8dd9-d3ee5d163a05.png)

**Comment by Joebayld** [comment]
An update: If i cast the cloned object to a rect it works. 
` const rect2 = rect.clone() as joint.shapes.standard.Rectangle;`.

Shouldn't the clone function return the same type?

**Comment by HighTide** [comment]
I have come across the same issue when following the tutorial on https://resources.jointjs.com/tutorial.

`const rect2 = rect.clone() as joint.shapes.standard.Rectangle;`
I can confirm that @Joebayld solution of casting to a rectangle solves the issue.

**Comment by kumilingus** [comment]
We could set the return value to `this` [here](https://github.com/clientIO/joint/blob/master/types/joint.d.ts#L268-L269). Does anyone know if this is a good practice in TS? The method does not return the same object instance but a new one.

For instance, Microsoft DOM API Typescript definition for [cloneNode()](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L10901) also return `Node` (not `this`).
