### ISSUE TITLE
Dynamically set data to insperctor cell

### ISSUE THREAD

**Issue by tayfunyilmas** [clientIO/joint#1444]
Hello,
**Inspector;**
`"app.Link": {
            inputs: {
                linkCondition: {
                    type: 'list',
                    group: 'setting',
                    label: 'Rules',
                    index: 2,
                    item: {
                        type: 'object',
                        properties: {
                            sourceOptions: {
                                type: 'select-button-group',
                                group: 'setting',
                                label: 'Source',
                                index: 1,
                                multi: true,
                                options: 'sourceOptionValues'                              
                            },
                            targetOptions: {
                                type: 'select-button-group',
                                group: 'setting',
                                label: 'Target',
                                index: 2,
                                options: [],
                                multi: true
                            }
                        }
                    }
                }
            },
            groups: {
                setting: {
                    label: 'Rules',
                    index: 1
                }
            }`
**main.js;**
`'link:pointerup': function (linkView) {
                        cell.set('sourceOptionValues', [{ value: 'Deneme1', content: 'Deneme 1' }, { value: 'Deneme2', content: 'Deneme 2' }])
                        console.log('CHANGE PROPS:', this.graph.getCell(cell.id).toJSON());
                        this.inspector.updateCell();
                    }
                }`

The above mentioned method, such as dynamic data with **cell.set** set'l it can not be made.

  I cannot use this method in versions higher than 3.2. *. Is this a bug or is there an alternative method?

**Comment by kumilingus** [comment]
Hi, it's a bug. It throws an unhandled exception now.

To prevent the error please patch the inspector method as shown below.
```js
    joint.ui.Inspector.prototype.updateBindings = function(path) {
        var slaves = Object.keys(this._bound).reduce(function(result, slave) {
            var master = this._bound[slave];
            if (path.indexOf(master) === 0) result.push(slave);
            return result;
        }.bind(this), []);
        if (!joint.util.isEmpty(slaves)) {
            slaves.forEach(function(slave) {
                var options = this.flatAttributes[slave];
                if (!options) return;
                this.renderTemplate(null, options, slave, { replace: true });
            }, this);
            this.afterPartialRender();
        }
    };
   ```
This fix or similar will be part of the next Rappid patch version.

Another issue is that this dynamic binding for the select-button-group does not work when the attribute is inside a list. It never worked actually - that's why you had to call `updateCell()` explicitly.

**Comment by tayfunyilmas** [comment]
Hi,

Thank you for your answer. When I patched the code you transmitted, the problem was fixed.
