### ISSUE TITLE
Performance improvement manhatten router

### ISSUE THREAD

**Issue by daniatic** [clientIO/joint#1447]
I have found a bottle neck in the performance of the manhattan router.  It is the isEqual method that gets called very often and slows down the algorithm a lot. After further investigation I found out that the isEqual method belongs to underscore and does a lot of edge case and type checking, which is totally over the point for the situation in the findRoute method. 

The following solution is totally sufficient and much more performant:

````
                var samePoints = startPoints.length == endPoints.length;
                if (samePoints) for (var i = 0; i < startPoints.length; i++) {
                    if (!startPoints[i].equals(endPoints[i])) {
                        samePoints = false;
                        break;
                    }
                }
                // instead of at line 18266 of JointJS v3.2.0:
                // var samePoints = isEqual(startPoints, endPoints); 

````

I would be happy if you could solve this issue or implement the solution above it into your code base. Please reach out to me for further questions.

**Comment by kumilingus** [comment]
Hi @daniatic, that looks good. Can you create a PR with this?

**Comment by daniatic** [comment]
Here you are: https://github.com/clientIO/joint/pull/1448

**Comment by kumilingus** [comment]
Thanks! :)
