### ISSUE TITLE
Adding Custom Icon to a Link

### ISSUE THREAD

**Issue by santoshiter** [clientIO/joint#1454]
Hello,

I am using RappidJS Chatbot in my application. 

We have a requirement where users need to debug each block/Task by adding a breakpoint on each outport link, for that we need to provide a debugger icon and a tooltip message on hovering of each outport link. 

All this Functionality will be enabled only when the user clicks on the debugger button. Please refer to the attached video for better understanding and kindly let me know how to achieve this.

Any help would be greatly appreciated.

Best Regards,
Santosh Kumar Panigrahy

https://user-images.githubusercontent.com/9346632/114665932-3f809000-9d1b-11eb-853e-3342d6acd4db.mov

**Comment by kumilingus** [comment]
I would use the link tools for this (https://resources.jointjs.com/tutorial/link-tools). A link tool `Button` with a custom markup to be specific.

```js
const button = new joint.linkTools.Button({
    markup: [{
        tagName: 'circle',
        selector: 'button',
        attributes: {
            'r': 7,
            'stroke': 'blue',
            'stroke-width': 3,
            'fill': 'blue',
            'cursor': 'pointer'
        }
    }, {
        tagName: 'text',
        textContent: 'i',
        selector: 'icon',
        attributes: {
            'fill': 'white',
            'font-size': 10,
            'text-anchor': 'middle',
            'font-weight': 'bold',
            'pointer-events': 'none',
            'y': '0.3em'
        }
    }],
    distance: -7,
    action: function() {
        // do nothing
    }
});

link.findView(paper).addTools(
    new joint.dia.ToolsView({
        tools: [button]
    })
);
```
