### ISSUE TITLE
React + Typescript custom elements usage issue 

### ISSUE THREAD

**Issue by pe7r** [clientIO/joint#1455]
I am using an open source JointJs v3.3.1 in React 16.9 + Typescript version ^3.8.0 app and I faced the issue with creating custom elements.
My import of jointjs in the file - **import {dia, shapes} from "jointjs";**

 I do it as on example (https://resources.jointjs.com/tutorial/custom-elements) but when I try to use my custom element method **_create_** Typescript returns error **Property 'create' does not exist on type 'Constructor<Element>'.**

![image](https://user-images.githubusercontent.com/42834373/114694317-13690d00-9d23-11eb-9127-5c3f2492a266.png)

![image](https://user-images.githubusercontent.com/42834373/114694792-94c09f80-9d23-11eb-8870-d3d7e2d122f9.png)

I've found only example for typescript module declaring https://github.com/clientIO/joint/blob/master/demo/ts-demo/custom.ts, but when I tried to use it, error did not fix. 

![image](https://user-images.githubusercontent.com/42834373/114695818-b1a9a280-9d24-11eb-88d1-ea6e5bd7f4f7.png)

Can you please help me and say what I am doing wrong and how to fix it?

P.S. it would be great if you'd do the React/Typescript/JointJs code example with some custom elements to provide example on correct TS integration, because currently docs doesn't include any typescript integration info.

**Comment by kumilingus** [comment]
I guess that the `create()` method is meant to be `static`.
```js
class Role extends shapes.standard.Rectangle {
  static create(name: string): Role;
}
```

You can also define shapes with class syntax. That way you won't have to define TypeScript separately.
https://github.com/clientIO/joint/blob/master/demo/ts-demo/shape.ts
