### ISSUE TITLE
Shapes position on Y-Axis not correct?

### ISSUE THREAD

**Issue by AlexHauskrecht** [clientIO/joint#1456]
I am new to JointJS. I produced a HTML-Page with a paper placed in a div-container and many Shapes.

For some shapes, the position on the y-axis seem to be not correct. In the example below, I have 2 shapes, one with an y-Position of 920, one with 1020. Surprisingly, the Shape with Pos 1020 is shown above the Shape with y-coordinates of 0920.
This appears in Firefox and Chrome (could not test Edge in my environment).

Any idea what I am doing wrong here?

The sample html code below has the css- and javascript-libraries used in directories on the same tree level as the page itself.
` <!DOCTYPE html>
<html>
<head>
<link rel='stylesheet' type='text/css'
 href='./../css/joint.css'
/>
<title>
IMPACT
</title>
</head>
<body>

<div style='width:700px; height:500px; overflow: scroll;'
id='grafik'></div>

<script src='./../js/jquery.js'></script>
<script src='./../js/lodash.js'></script>
<script src='./../js/backbone.js'></script>
<script src='./../js/joint.js'></script>

<script type='text/javascript'>
        var graph = new joint.dia.Graph;
        var paper = new joint.dia.Paper({
             el: document.getElementById('grafik'),
             model: graph,
             width: 2000,
             height:
09000
,
             gridsize:1,
             interactive: true
             });

var DS00019=
new joint.shapes.standard.Rectangle();
DS00019.resize(100,50);
DS00019.position(500,00920);
DS00019.attr({body: { rx: 5, ry: 5}});
DS00019.attr('label/text',
'DATGM02\nPOS_0920');
DS00019.attr('body/fill','blue');
DS00019.addTo(graph);

var DS00021=
new joint.shapes.standard.Rectangle();
DS00021.resize(100,50);
DS00021.position(500,01020);
DS00021.attr({body: { rx: 5, ry: 5}});
DS00021.attr('label/text',
'DATGM02\nPOS_1020');
DS00021.attr('body/fill','blue');

DS00021.addTo(graph);
</script>
</body>
</html>`
Thanks a lot in advance,
kind regards,
Alexander

**Comment by kumilingus** [comment]
That's because `00920 > 01020` in JavaScript.

`00920` - is `920` parsed as decimal
`01020` - parsed as octal in non-strict mode (`528` in decimal)

**Comment by AlexHauskrecht** [comment]
Ah, I did not know this - thanks a lot and sorry for opening this issue ...
