### ISSUE TITLE
joint.shapes.standard.HeaderedRecord.define

### ISSUE THREAD

**Issue by Jean-Jacques-Nuoan** [clientIO/joint#1458]
what does it means in rappid demo ?
`joint.shapes.standard.HeaderedRecord.define('mapping.Record', {`

**Comment by kumilingus** [comment]
It creates a new shape class, which inherits from `standard.HeaderedRecord`.
Documentation: https://resources.jointjs.com/docs/jointjs/v3.3/joint.html#dia.Cell.define
