### ISSUE TITLE
JointJs + React + IE11 -> not working

### ISSUE THREAD

**Issue by kayb-proxora** [clientIO/joint#1462]
Hello,

We have issues with JointJS >= 3.2.0 running in IE11. It's failing because of 

`const { start, end } = l;`

in this file https://github.com/clientIO/joint/blame/master/src/g/index.mjs.

We are using JointJs in a React app.

Does anybody have an idea how we can solve this?

**Comment by kayb-proxora** [comment]
As a temporary workaround, I'm importing it from dist folder now:

`import * as joint from "jointjs/dist/joint"`

**Comment by kumilingus** [comment]
It's matter of `babel` configuration. The JointJS source files have to be transpiled to ES5.

**Comment by kayb-proxora** [comment]
Normally, we don't transpile files in `node_modules`, only our own sources. Is it somehow possible to fix it in JointJs?
