### ISSUE TITLE
Angular 11 build bundle size

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1463]
Hi!

We've added rappid to our project following the instructions
https://resources.jointjs.com/tutorial/angular9

so, the package.json has these
```
    "@clientio/rappid": "file:vendors/rappid/rappid.tgz",   (taken from rappid_v3_3_0.zip > build > package)
    "backbone": "1.4.0",
    "jquery": "3.4.1",
    "lodash": "4.17.11",
```
(`lodash` is used in our project too, where `jquery` is added for rappid only)

After building source maps I see this picture:

<img width="1426" alt="222" src="https://user-images.githubusercontent.com/14068189/116532934-7d6bdf80-a8e9-11eb-8913-c444c7b8c17d.png">

Could you give us a hint on how to avoid adding these dependencies multiple times?

**Comment by kumilingus** [comment]
There is a minimal recommended version in JointJS `package.json`.
```
  "dependencies": {
    "backbone": "~1.4.0",
    "dagre": "~0.8.5",
    "graphlib": "~2.1.8",
    "jquery": "~3.5.1", // later
    "lodash": "~4.17.20" // later
  }
  ```
You need to use a later version in your `package.json` or do not mention the dependencies at all.
```
  "@clientio/rappid": "file:vendors/rappid/rappid.tgz",
    "backbone": "1.4.0",
    "jquery": "3.5.1",
    "lodash": "4.17.20",
```
Or
```
  "@clientio/rappid": "file:vendors/rappid/rappid.tgz",
```
