### ISSUE TITLE
`cellView._V.linkTools` stopped working

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1466]
Hi!

We're migrating our app that uses BPMN shapes.
We're going to extend it with the recently introduced BPMN2 set as well as Vision export/import (awesome feature!).

We use a "floating box" that is positioned on paper next to the selected shape to set its properties.
And where "usual" shapes (activities/events etc) have clear boundaries we can rely on to calculate position, then for flows it's different. But we managed to position it next to the "gear" tool using the following technic:

```js
      // cellView from link
      const getToolsPoint = () => {
        const linkTools = cellView._V.linkTools;
        const bb = linkTools.getBBox();
        const gearPoint = {
          x: bb.x + bb.width,
          y: bb.y + bb.height,
        };
        return this.paperScroller.localToBackgroundPoint(gearPoint.x, gearPoint.y);
      };
```
(old link, `bpmn.Flow`)
![image](https://user-images.githubusercontent.com/14068189/117046358-46e2fa00-ad19-11eb-999b-7bcd41c05166.png)

Now, that we've changed our flows to `bpmn2.Flow` it stopped working.
`Uncaught TypeError: Cannot read property 'getBBox' of undefined...`

Could you give us a piece of advice on how to resolve this for the new Rappid version?
Or, probably, more precise: how to get the bounding box of the link tools from `cellView` of the `bpmn2.Flow`

**Comment by kumilingus** [comment]
I suppose you use [LinkTools](https://resources.jointjs.com/docs/jointjs/v3.3/joint.html#linkTools) now.
```js
var toolsView = new joint.dia.ToolsView({
    tools: [
        new joint.linkTools.Button({
            offset: 0,
            distance: 40,
            markup: [{
                tagName: 'circle',
                selector: 'button',
                attributes: {
                    'r': 7,
                    'fill': '#FF1D00',
                    'cursor': 'pointer'
                }
            }],
            action: function(_evt, linkView, toolView) {
                const { paper } = linkView;
                const localPoint = toolView.vel.getBBox({ target: paper.viewport }).bottomRight();
                console.log(localPoint);
            }
        })
    ]
});
```

**Comment by GeorgiyZhuravlev** [comment]
Works great, thank you!

> I suppose you use LinkTools now.

Yes. Btw, the question here:
It's not very convenient to define it "in-place", when we create `ToolsView` for the link.
I saw in [Tutorials](https://resources.jointjs.com/tutorial/link-tools) the example of extending `joint.linkTools` namespace:
```js
joint.linkTools.InfoButton = joint.linkTools.Button.extend({...});
```
but for our environment (Angular/TS) it doesn't work.

I also saw the trick with `Object.assign` that we use for our slightly modified old bpmn shapes:
```js
    Object.assign(joint.shapes, {
      bpmn: {
        ...joint.shapes.bpmn,
        Activity, // our, const Activity = joint.shapes.bpmn.Activity.extend(...)
      }
    });
```
but wasn't able to implement this for `joint.linkTools`. Could you give us a hint about this, please?

---

Also, about Flows.
In the new version of the app, we're going to add new shapes. And since they come from the new namespace (`bpmn2`) they won't conflict with older shapes. But for links/flows it's different. I feel like I need to "preprocess" diagram JSON and change the type for these (to let people set `flowType` for the already drawn links). Am I right about it? And is it safe/enough to just change the `type` only to be the `bpmn2.Flow`? I mean, will all the data about vertices/labels/others survive this change?

**Comment by kumilingus** [comment]
Hi @GeorgiyZhuravlev,

You don't have to define `InfoTools` inside the namespace.
```js
const InfoButton = joint.linkTools.Button.extend({...});
```

The namespaces need to be used only for shapes. So we can later create actual shapes from a JSON.

Plus, you don't have to extend the existing namespace for shapes. Feel free to create a new one and add only the shapes (models and views) that you use.

```js
const namespace = { bpmn: { ...joint.shapes.bpmn, MyShape1, MyShape2 }};
// tell the graph where to find model constructors
const graph = new dia.Graph({}, { cellNamespace: namespace });
// tell the paper where to find view constructors
const paper = new dia.Paper({ cellViewNamespace: namespace });
```
---

It should be safe to change just the `type`. There will be some left-over `attrs` pointing to non-existing subelements (e.g. `.marker-source: { d: 'M 0 5 L 20 5 M 20 0 L 10 10', fill: 'none' })`) which won't apply to the new links.
I would personally read the `flowType` attribute and map the legacy links to `bpmn2` links (and cherry pick `source`, `target`, `vertices`).

**Comment by GeorgiyZhuravlev** [comment]
Thank you!
