### ISSUE TITLE
Remove support for IE9 polyfill for XHR object

### ISSUE THREAD

**Issue by RuslanZavacky** [clientIO/joint#1469]
This polyfill seems to be quite old, as library itself states that it support IE11+.

Also, due to this polyfill, there is a problem to use this library in the same time with Pretender.js. Pretender is "faking" the XMLHttp object, so it can intercept requests, and this polyfill can't detect that, as response is not on the object of pretender. [Reference 1 - FakeXmlHttpRequest](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/src/fake-xml-http-request.js) [Reference 2 - Pretender.js](https://github.com/pretenderjs/pretender/blob/ddca21671e3e7c69b0be673eb3cd66007931a379/src/pretender.ts)

I'll prepare a PR to remove this polyfill, is there any objections to do so?

Thank you in advance!

**Comment by kumilingus** [comment]
Removed in https://github.com/clientIO/joint/pull/1470.
