### ISSUE TITLE
Make `bpmn2.Pool` lane "transparent" for mouse events

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [clientIO/joint#1474]
Hi!

Please check the screencast. 
Top Pool is an old `bpmn.Pool`. Its lanes ignore mouse events letting us move `paperScroller` or do selection like shown.

We're looking for the same functionality for the `bpmn2.Pool` shape. 
Ideally, toggle its behavior on certain conditions (like `Shift` key modifier in the screencast) or set always off (like for view mode eg, to let "panning"). 
Even more ideally :) - only for the lane, not for the header (`joint-selector="header_0"`) we are using to set lane's props.

![___screencast](https://user-images.githubusercontent.com/14068189/119027279-d55caa00-b9ae-11eb-9fba-e687da8a4db2.gif)

**Comment by dawidKrynicz** [comment]
Hi, this can be achieved with `pointer-events: none`,  like this:
```
pool.attr('body/pointer-events', 'none');
pool.attr('lanes/pointer-events', 'none');
```
`lanes` is a group selector for lane rect's, so the headers will still be clickable.

And to disable both lanes and headers you can use:
```
pool.attr('body/pointer-events', 'none');
pool.attr('laneGroups/pointer-events', 'none');
```

**Comment by GeorgiyZhuravlev** [comment]
@dawidKrynicz 

thank you!
