### ISSUE TITLE
 Type 'undefined' does not satisfy the constraint 'Model<any

### ISSUE THREAD

**Issue by TiagoMartiins** [clientIO/joint#1476]
Can someone help me when trying to integrated angular 11 with jointjs

The imports of lodash, query, backbone in package.json ->

"@types/backbone": "^1.4.10",
    "@types/jasmine": "~3.6.0",
    "@types/jointjs": "^2.0.0",
    "@types/jquery": "^3.5.5",
    "@types/lodash": "^4.14.170",
    "@types/node": "^12.11.1",
    "backbone": "^1.4.0",
    "codelyzer": "^6.0.0",
    "install": "^0.13.0",
    "jasmine-core": "~3.7.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jointjs": "^2.2.1",
    "jquery": "^3.6.0",

The error when i just imported the library of jointjs -> on Component

import { Component } from '@angular/core';
import * as _ from 'lodash';
import * as $ from 'backbone';
import * as jQuery from 'jquery'
import * as joint from 'jointjs'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'integrated-jointjs';

  constructor() {
  }
}

Angular.json ->

"styles": [
              "src/styles.css",
              "./node_modules/jointjs/css/layout.css",
              "./node_modules/jointjs/css/themes/material.css",
              "./node_modules/jointjs/css/themes/default.css"
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.js",
              "./node_modules/lodash/index.js",
              "./node_modules/backbone/backbone.js",
              "./node_modules/jointjs/dist/joint.js"
            ]
          },

The error when i execute the ng serve ->

Error: node_modules/jointjs/dist/joint.d.ts:2124:37 - error TS2344: Type 'undefined' does not satisfy the constraint 'Model<any, ModelSetOptions, {}>'.

2124     class ToolView extends mvc.View<undefined> {

**Comment by kumilingus** [comment]
Try to use `skipLibCheck: true` option (https://www.typescriptlang.org/tsconfig#skipLibCheck).

**Comment by kumilingus** [comment]
I have replaced all *(6 occurrences)* `<undefined` with `<any` in `joint.d.ts` and run `tsc build/joint.d.ts --strict true` and it complained no more. The question is if Backbone typings should support creating views without the model.

e.g. this:
```ts
  interface Options extends mvc.ViewOptions<undefined, SVGElement> {
      layer?: dia.Paper.Layers | string | null;
  }
```
was changed to:
```ts
  interface Options extends mvc.ViewOptions<any, SVGElement> {
      layer?: dia.Paper.Layers | string | null;
  }
```

**Comment by thomaspeugeot** [comment]
@kumilingus , thks for your answer.

- I am not familiar with Backbone at all and not a typescript expert, therefore I cannot answer your question
- I am currently with 2.0.0 but I can try to upgrade to 3.4.4 then use wathever branch you indicate to test wether it works for me.

**Comment by muhamedkarajic** [comment]
What am I supposed to do I still have the issue even after installing all latest verions.

**Comment by jamesgeorgewilliams** [comment]
> What am I supposed to do I still have the issue even after installing all latest verions.

As mentioned here, we will release a new version of `JointJS` very soon which will address this issue. 
https://github.com/clientIO/joint/issues/873#issuecomment-1465798266

The current recommendation is to continue using `skipLibCheck: true` in your tsconfig for the moment. In the upcoming release, the type error should be resolved.
