### ISSUE TITLE
Directed graph layout stopped working after upgrade to 0.9.3

### ISSUE THREAD

**Issue by jerryyanmj** [clientIO/joint#148]
I have the directed graph example running under jointjs 0.6.0.  After I upgraded to 0.9.3, the graph is not generated correctly.
![image](https://cloud.githubusercontent.com/assets/1474981/8369531/5ad9df7e-1b89-11e5-9f66-393765553af4.png)

**Comment by chill117** [comment]
Could you create a [JSFiddle](https://jsfiddle.net/) with your sample code that isn't working?

**Comment by kumilingus** [comment]
Make sure you have all the DirectedPlugin dependencies included. i.e. `graphlib` & `dagre`.
