### ISSUE TITLE
[Question] JointJS + SVG foreignObject + React nodes = OK?

### ISSUE THREAD

**Issue by fab-mindflow** [clientIO/joint#1484]
Hi,

For a number of reasons, our team would like to adopt full React(+Redux) approach for the design of the nodes in our diagrams. As far as we understand, we may need to use SVG foreignObject along with JointJS.

However, we are not yet sure to encounter issues. There is mention of this in the page here: https://resources.jointjs.com/tutorial/html-elements. There is also a small utility wrapper in GH here.

Question - we haven't tested it yet: as of today, in latest browser versions, do you still see strong limitations or bugs (ex: dynamic width/height, events like drag & drop, etc..) in the usage of foreignObject with latest version of Rappid/JointJS? Would you recommend it?

Feedback would be super valuable to us.

Cheers,
Fabrice

_Note: I've also posted to JointJS Google Groups and Rappid support - sorry for cross-posting, I'll take care to close the issue as needed_

**Comment by kumilingus** [comment]
Why do you want to use the `foreignObject`? Are you planning to render HTMLElements (HTMLInput, HTMLTextArea) as part of your shapes? I assume React Component can render SVGElements (or arbitrary XML namespace).

I think one have to be still cautious when  using `foreignObject` and test the code in all browsers.

Here's a relatively simple `foreignObject` example that extends a JointJS [demo](https://github.com/clientIO/joint/blob/master/demo/shapes/src/foreign-object.js).

https://jsfiddle.net/kumilingus/rpw5u8mq

When tested in Chrome/FF everything is ok.

![image](https://user-images.githubusercontent.com/3967880/122638427-4e593980-d0f4-11eb-9e03-971375d075c3.png)
![image](https://user-images.githubusercontent.com/3967880/122638443-67fa8100-d0f4-11eb-97b0-7aa368a57afe.png)

When tested in Safari:

- `getClientBoundingRect()` does not take `x` and `y` into account.

![image](https://user-images.githubusercontent.com/3967880/122638383-09cd9e00-d0f4-11eb-99e3-b4345bfd9334.png)

- `opacity` does not work (this seems to be related to `x` and `y`),

![image](https://user-images.githubusercontent.com/3967880/122638395-21a52200-d0f4-11eb-941c-f3fb4be05b9a.png)

Even though [Here](https://caniuse.com/?search=foreignObject) it says, that `x` and `y` properties were supported in Safari, it is only a partial support.

Normally, there is a workaround for any issue that you might encounter.
e.g in this case `x` and `y` can be replaced with `transform="translate(x,y)"`
From my experience setting a specific CSS style sometimes helps.

**Comment by saadflow** [comment]
Hi @kumilingus !
Thanks a lot for this demo it rocks 👍 

> Why do you want to use the foreignObject? Are you planning to render HTMLElements (HTMLInput, HTMLTextArea) as part of your shapes? 

Exactly, we want our cells to be react components. This way they can hold forms for example, or use some of react's apis like context, hooks, etc. 

I have found an other way of using html in your [demos](https://github.com/clientIO/joint/tree/master/demo/html), using the htmlMarkup key in the shape definition and creating a custom view. I think foreignObject is more straightforward than extending the cellView, but do you have any thoughts on this ? 

> I assume React Component can render SVGElements (or arbitrary XML namespace).

Well this option didn't cross my mind ! Thanks for bringing it up, it might be useful some day. For now I think two major drawbacks of this approach would be forms, and the ability to reuse components from elsewhere in our app.

> I think one have to be still cautious when using foreignObject and test the code in all browsers.

Agreed. I think its only responsibility should be to be a wrapper around HTML. This should reduce the area for unforeseeable bugs and cross browser issues as it's the most basic of its features. No attributes at all.

> Normally, there is a workaround for any issue that you might encounter.

That's reassuring ! Have you encountered this use case with other users before ? 

Here is a [fork of the fiddle you posted](https://jsfiddle.net/4tydvjLe/4/), with a workaround, tested on chrome, safari, firefox and edge. 

Thank's a lot !

**Comment by kumilingus** [comment]
Hi @saadflow ,

> I have found an other way of using html in your demos, using the htmlMarkup key in the shape definition and creating a custom view. I think foreignObject is more straightforward than extending the cellView, but do you have any thoughts on this ?

Using the `foreignObject` should be the way to go.
The other demo uses an approach (a workaround) to support all browsers. The HTMLElements in the demo are positioned above the paper SVG element and transformed based on the current paper transformation. It's a valid use-case and it's fine in many scenarios, but it breaks some of the features of JointJS (some of them can be implemented, some of them not).
- stacking order (links can not be rendered above the elements - links are the original SVG paths)
- the paper can not be exported to SVG/bitmap on the client side (you'd need e.g a server with puppeteer)
- by default, the ports will be partially hidden by the HTMLElement (one would have to render HTMLElement for each port to fix it)
- custom [highlighters](https://github.com/kumilingus/svg2pdf/blob/master/index.js) might be needed to highlight an HTMLElement.

Here's a VueJS component showing the same approach: https://github.com/clientIO/joint/tree/master/demo/vuejs

> That's reassuring ! Have you encountered this use case with other users before ?

No, I did not see anyone using it in production yet... We did some experimenting/testing in past. There is also a shape `standard.TextBlock` that uses `foreignObject` which is standard part of JointJS with fallback to SVG (https://github.com/clientIO/joint/blob/master/src/shapes/standard.mjs#L509-L591).

**Comment by saadflow** [comment]
> Using the foreignObject should be the way to go.
After some experimenting I definitely agree. It has it tradeoffs, but like you said earlier, there are easy workarounds for any issue we might encounter.

Thanks again for your time and your detailed answer, it helped a lot 😄
