### ISSUE TITLE
Shape text attribute not updating

### ISSUE THREAD

**Issue by nawrasg** [clientIO/joint#1487]
Hi everyone,

I recently bought the Rappid License and trying to integrate the Kitchen Sink app into an Angular app.
Everything seems to work fine except one element: shape's text attribute is not updating when I modify it!

The online demo (on Client.IO website) works fine, the JS app demo in the Rappid folder works fine but not in my Angular app.

I haven't succeeded running the Angular9 demo app that comes with Rappid so I don't know if it's a known problem or not.

Thank you for your help,

**Comment by kumilingus** [comment]
Please try to remove jQuery dependency from the `package.json` (or updated to the latest) and run `npm i` again. 

It installed 2 versions of jQuery (Rappid package.json requires a newer one). One is used by Rappid and other by the Application. It is currently causing this bug.

**Comment by nawrasg** [comment]
I assume you're talking about the Anguarl app's `package.json` ?
If so, neither updating nor removing jQuery dependency is solving the problem.

Any other idea?

**Comment by kumilingus** [comment]
I am pretty sure that is the issue (the content-editable field of the inspector does not work).

Have you removed `package-lock.json`, `rm -rf node_modules`, `npm cache clean --force` before `npm install` (just to make sure there is no caching)?

Can you check the bundle? Does it have only a single version of jQuery?

If this won't help, please drop me an email and we can schedule a short call to debug it.

**Comment by nawrasg** [comment]
It seems to work :) 
Thank you very much for your help!

And thanks for the whole team for this product!
