### ISSUE TITLE
node-webkit incompatibility

### ISSUE THREAD

**Issue by JanisGruzis** [clientIO/joint#150]
HI,

I try to load joint.js (v0.9.3 release) in node-webkit and simply in browser. While browser version does work the node-webkit version doesnt work because of error in library.

    [16979:0630/215152:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'each' of undefined
    at file:///home/janis_gruzis/machines/bomberman/sites/gramma/dist/Linux64/app.nw/node_modules/jointjs/dist/joint.min.js:11:17052
    at file:///home/janis_gruzis/machines/bomberman/sites/gramma/dist/Linux64/app.nw/node_modules/jointjs/dist/joint.min.js:11:14950
    at file:///home/janis_gruzis/machines/bomberman/sites/gramma/dist/Linux64/app.nw/node_modules/jointjs/dist/joint.min.js:11:14994

Seems like lodash doesnt initialize in that case. Will feedback more on this problem If will find a workaround or proper way to use jointjs, but weird.

I load library as simple js.

    <script src="node_modules/jointjs/dist/joint.min.js"></script>

**Comment by JanisGruzis** [comment]
So what I found out was that node-webkit has two global variables window(from browsers) and global(from node.js). What happens is there is chance that libraries will go mad and assign their variable to window or global and its not standartized. Each library does as it wishes. It happened so that lodash sets its _ on global and other libraries set their variables on window. Since I primarily use window I used clear joint.js version and assigned window._ = global._

    <script src="node_modules/lodash/dist/lodash.min.js"></script>
        <script>
            if (global) {
                 window._ = global._;
            }
    </script>

**Comment by chill117** [comment]
When using joint as a node module, you should include the main `index.js` file like this:
```html
<script src="node_modules/jointjs/index.js"></script>
```
I will try a test integration of node-webkit tomorrow and report back my results here.

**Comment by chill117** [comment]
Unfortunately, the latest version of jointjs will not work with node-webkit because issues with lodash 2.x and node-webkit. Lodash 3.x fixes the node-webkit problems, but there will need to be substantial changes to jointjs to get it to work with lodash 3.x.

**Comment by JanisGruzis** [comment]
Yes. But dirty fix in my previous post worked for me (joint v0.9.3). Will wait for compatibility fix in future. :) But for others this can be a workaround till then.

**Comment by kumilingus** [comment]
Fixed in 8cb951e391781812e574d9558d979aeea52e75b8.
