### ISSUE TITLE
Element positioning right-aligned

### ISSUE THREAD

**Issue by ialokim** [clientIO/joint#1508]
I'm not sure if I miss something very simple, but I failed to find a way to specify the position of an element not by the top-left edge, but, i.e., by the top-right edge or the middle-center. I know there are the `x/yAlignment` attributes but I think they only work relative to the element's bounding box, right?

**Comment by kumilingus** [comment]
What kind of element you are trying to align?

For `<text>` use `textAnchor` and `textVerticalAnchor`

For `<g>` use `xAlignment`, `yAlignment`.

For other `SVGGeometryElements` use attributes
`<rect x="-100" width="100", height="20" y="-20">`
`<circle r="5" cx="-5" cy="5">`
`<path d="M -5 0 0 0 0 5 -5 5 z">`
