### ISSUE TITLE
update npm released version?

### ISSUE THREAD

**Issue by tw0517tw** [clientIO/joint#151]
It's version 0.8.0 on npm so when I `npm install jointjs` I get 0.8.0.
Will you put newer version on npm?

**Comment by chill117** [comment]
The npm module needs to be updated to the latest release. Hopefully this is something I can do today.

**Comment by chill117** [comment]
I am currently blocked from doing this by a few outstanding issues. Will keep this issue updated.

**Comment by chill117** [comment]
The [jointjs](https://www.npmjs.com/package/jointjs) npm module has now been updated to the latest version (0.9.4).
