### ISSUE TITLE
The clientToLocalPoint function does not return the correct graph coordinates (in Firefox)

### ISSUE THREAD

**Issue by ascotr** [clientIO/joint#1516]
The function instead returns the original client coordinates. Possibly related to this firefox issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1446011

**Comment by kumilingus** [comment]
Do you have a test case? Many features would not work in FF if that was a true (they work).

**Comment by kumilingus** [comment]
Feel free to re-open if you can provide a reproducible scenario.
