### ISSUE TITLE
Typescript PositionType missing Custom Layout Function type option

### ISSUE THREAD

**Issue by deefdragon** [clientIO/joint#1540]
A port group's position (dia.Element.PositionType) can not be set to a custom function without an `<any>` prefix like this
```typescript
<any>function (portsArgs: Array<object>, elBBox: g.Rect, opt: any): Array<g.Point> {
    ...
    return [...]
},
```
because PositionType is 
```ts
type PositionType = string | {
    name?: string,
    args?: { [key: string]: any }
}
```
which is missing the function type.

**Comment by kumilingus** [comment]
Hi, isn't this already fixed in the [latest version](https://github.com/clientIO/joint/blob/master/types/joint.d.ts#L363)?

**Comment by deefdragon** [comment]
I Thought I was up to date, but was not. Thanks for the correction. This is indeed fixed.
