### ISSUE TITLE
"cell:mousewheel" callback takes the cell as first argument and not evt

### ISSUE THREAD

**Issue by ammar-t0** [clientIO/joint#1557]
https://resources.jointjs.com/docs/jointjs/v1.0/joint.html#dia.Paper.events

**Comment by jamesgeorgewilliams** [comment]
Hi, thanks for reporting. The link you provided is for `v1.0` of our documentation, and the error has since been corrected in the latest version.

You can find the latest version (`v3.4`) of our documentation here:
https://resources.jointjs.com/docs/jointjs/v3.4/joint.html#dia.Paper.events
