### ISSUE TITLE
Hi David, I would really appreciate if you could answer this question in the link. Thanks

### ISSUE THREAD

**Issue by tahirnawaz** [clientIO/joint#156]
http://stackoverflow.com/questions/31368160/joint-js-custom-ports-with-path-class-for-custom-elements

**Comment by tahirnawaz** [comment]
Hi, I will really appreciate if any one could answer this question?

**Comment by tahirnawaz** [comment]
or at least tell me its possible or not.

**Comment by tahirnawaz** [comment]
at least this question deserves some kind of discussion?

**Comment by chill117** [comment]
I have added a comment to your stackoverflow question. I will close the issue now, as there is no content here.
