### ISSUE TITLE
Can not remove element when drag to the paper.

### ISSUE THREAD

**Issue by ITfanheng** [clientIO/joint#1565]
Hi.
I drag the cell to the paper, but the `elementTools.Remove()` don't work, and i try to call `elementView.model.remove()` when `element:contextmenu` is fired. But it still not work. 
`ElementView.remove()` worked, but graph still has this cell。
First element add to the graph when paper initialized.
![2021-11-05 下午3 12 16](https://user-images.githubusercontent.com/75559678/140473348-a7c4e1b5-75e7-4d94-8dc4-9e6c3f438358.gif)

**Comment by kumilingus** [comment]
Is there any error in the browser console? How do you add the cell to the paper? Please provide some code.

**Comment by ITfanheng** [comment]
Thank you for your reply。No error console in browser. The code is on the company's computer，I will provide some code In the last few days。

**Comment by ITfanheng** [comment]
The example. https://codesandbox.io/s/determined-panka-6beqy?file=/src/index.tsx

**Comment by ITfanheng** [comment]
> The example. https://codesandbox.io/s/determined-panka-6beqy?file=/src/index.tsx
I solved it. But it's a little strange. https://codesandbox.io/s/xcw5h

**Comment by kumilingus** [comment]
You added an element to the graph and immediately removed it.
```
circuitPaper.model.addCell(cloneCell);
cloneCell.remove();
```
I suppose the `circuitPaper.model` graph was not the same a `cloneCell.graph`.

Do not  add the same model instance to more than one graph. Every element has a reference to the graph. It can not have 2 references. You need to clone it.
```
const clone = el.clone();
clone.set('id', el.id);
```
If you don't clone element an unexpected behaviour can be encountered.

**Comment by ITfanheng** [comment]
I got it. Thanks for your response.
