### ISSUE TITLE
Some examples under the demo folder don't work

### ISSUE THREAD

**Issue by pablopareja** [clientIO/joint#157]
They seem to be trying to load resources such as `jquery.js`, `backbone.js` from a non existing folder named **lib** ...

**Comment by chill117** [comment]
This has been fixed by PR #159.

**Comment by pablopareja** [comment]
There still is the same problem...
Have a look for instance at this demo: https://github.com/clientIO/joint/blob/master/demo/links.html
It's trying to load resources from a **lib** folder that does not exist on the **master** branch...

**Comment by chill117** [comment]
The libs directory is created by running `bower install` from the project root. But there are some demos that aren't working, as I've been making changes to build processes and the build files (in the `dist` directory). I have been working on this the last couple days. I will update this issue again once I am sure that all demos are functioning properly again.

**Comment by pablopareja** [comment]
cool thanks ;)
