### ISSUE TITLE
PhantomJS 2.1.1 > util.breakText hyphen FAILED

### ISSUE THREAD

**Issue by VerscheldeAlynne** [clientIO/joint#1577]
It's an assertion that fails, rule 209 from test/jointjs/core/util.js

I found this when running **grunt test**
as in the readme stated i reported this as a bug

![Capture](https://user-images.githubusercontent.com/43439546/141998196-ae9bacb9-3ebb-46a1-9bd6-2f541da9e1d2.PNG)

**Comment by DCMiracle** [comment]
me too,help me

**Comment by VerscheldeAlynne** [comment]
i think for future-proofing sake, the second and third options would be best. For now though i will employ the first one.

**Comment by DCMiracle** [comment]
Have you solved this problem？I installed Courier New font, but it still doesn’t work

**Comment by MartinKanera** [comment]
This issue is caused by how PhantomJS renders text and it will be resolved in the future by migrating to puppeteer.

**Comment by kumilingus** [comment]
Fixed by https://github.com/clientIO/joint/pull/1795.
