### ISSUE TITLE
Support for "jumping lines"

### ISSUE THREAD

**Issue by kmansel** [clientIO/joint#158]
Hi Client.io crew, a feature that we'd love to see is a "line jumping" feature.  Where if a connector crosses another connector, a "line jump" style is applied.  Example shown below.

![image](https://cloud.githubusercontent.com/assets/1252780/8836751/8ffd9c9c-3077-11e5-98d2-b9f0450928c6.png)

**Comment by DavidDurman** [comment]
Hi Kevin, we have this on our list. It will come very soon.

**Comment by kmansel** [comment]
Fantastic David!  Would this be coming on your next release of the joint code base?  I am guessing a new release is not far out?

**Comment by DavidDurman** [comment]
That's the plan. It's definitely not far out. We still have couple features to implement though. The plan is to go out with new JointJS, new Rappid, new site and my.client.io in one go.

**Comment by elyas-bhy** [comment]
For some inspiration, [here is an overview of noflo's old UI](http://bergie.iki.fi/files/noflo-jekyll.png). Love their metro-style routing!

**Comment by DavidDurman** [comment]
Pretty nice indeed. JointJS also has metro style routing. Try this demo: http://jointjs.com/demos/routing and click on Rounded/Metro. It is possible to achieve the same effect as in the noflo's UI by giving the links a bit better look.

**Comment by kumilingus** [comment]
Implemented in 8cb951e391781812e574d9558d979aeea52e75b8.
