### ISSUE TITLE
fromJSON only work once

### ISSUE THREAD

**Issue by rubenyeghikyan-highway** [clientIO/joint#1594]
Hi, I have import functionality in my app which is based on `graph.fromJSON`. The thing is that it doesn't work after the first time, when I do import first time everything works fine, but then it doesn't react. I'm using joint with React.js, I found workaround to use useMemo and update graph instance every-time user hits import

**Comment by kumilingus** [comment]
Hi, you'd need to provide an example. You can import a JSON over and over again with `graph.fromJSON()` under normal circumstances.

**Comment by rubenyeghikyan-highway** [comment]
I don't do anthing special here

I have useEffect which listens to currentAction changes

```
useEffect(() => {
    if (graph && graph.toJSON) {
      if (currentAction === 'export') {
        const dataJSON = graph.toJSON();
        const url =
          'data:text/json;charset=utf-8,' +
          encodeURIComponent(JSON.stringify(dataJSON));
        const a = document.createElement('a');
        a.style.display = 'none';
        a.href = url;
        a.download = 'export.json';
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        dispatch({
          type: WEB_DIAGRAM_IMPORT,
          payload: dataJSON,
        });
      } else if (currentAction === 'import') {
        const data = JSON.parse(jsonToParse as string);
        graph.fromJSON(data);
        // jointjs doesn't reset already existing elements so we need to do it manually
        graph.resetCells(data.cells);
        dispatch({
          type WEB_DIAGRAM_EXPORT,
          payload: jsonToParse,
        });
      }
    }
  }, [currentAction]);
```

**Comment by kumilingus** [comment]
That's a little odd. `graph.fromJSON()` is calling `graph.resetCells()` internally -https://github.com/clientIO/joint/blob/master/src/dia/Graph.mjs#L231-L234.

**Comment by rubenyeghikyan-highway** [comment]
> That's a little odd. `graph.fromJSON()` is calling `graph.resetCells()` internally -https://github.com/clientIO/joint/blob/master/src/dia/Graph.mjs#L231-L234.

I see, In fact it doesn't work, so I have to call it manually. Anyway this is not the main issue, the main issue is that `graph.fromJSON` doesn't work properly

**Comment by rubenyeghikyan-highway** [comment]
here is recording demonstrating that `graph.fromJSON` doesn't work as expected http://recordit.co/zOP5iwK1Ud

**Comment by kumilingus** [comment]
> here is recording demonstrating that `graph.fromJSON` doesn't work as expected http://recordit.co/zOP5iwK1Ud

Is there any error in the console?

**Comment by rubenyeghikyan-highway** [comment]
> > here is recording demonstrating that `graph.fromJSON` doesn't work as expected http://recordit.co/zOP5iwK1Ud
> 
> Is there any error in the console?
no error

**Comment by kumilingus** [comment]
When you debug it, is the JSON passed to the `fromJSON()` always the same as the one in the clipboard? Are you able to reproduce it in any other demo we have?

**Comment by rubenyeghikyan-highway** [comment]
any demo link which has import functionality? couldn't found

**Comment by rubenyeghikyan-highway** [comment]
> When you debug it, is the JSON passed to the `fromJSON()` always the same as the one in the clipboard? Are you able to reproduce it in any other demo we have?


using same JSON every time

**Comment by kumilingus** [comment]
> any demo link which has import functionality? couldn't found

You can open a demo e.g. https://resources.jointjs.com/demos/joint/demo/devs/index.html, open the browser console and do this (and move elements in between commands):
![image](https://user-images.githubusercontent.com/3967880/148800550-65f1d892-dcb0-491e-a52f-53ba67498713.png)

**Comment by rubenyeghikyan-highway** [comment]
demo works perfectly fine, even with my custom JSON. I'm thinking maybe the reason is that I use `useMemo` which memoizes graph instance

```
  const graph: joint.dia.Graph<
    joint.dia.Graph.Attributes,
    joint.dia.ModelSetOptions
  > = useMemo(() => new joint.dia.Graph({}, { cellNamespace: namespace }), []);
```

**Comment by rubenyeghikyan-highway** [comment]
where I can see source code for https://resources.jointjs.com/demos/joint/demo/devs/index.html ?

**Comment by kumilingus** [comment]
> where I can see source code for https://resources.jointjs.com/demos/joint/demo/devs/index.html ?

https://github.com/clientIO/joint/tree/master/demo/devs

**Comment by kumilingus** [comment]
No problem. Feel free to reopen the issue again.

**Comment by rubenyeghikyan-highway** [comment]
UPDATE:
Turned out it was Redux issue, when state is changed, I didn't clean (bring back to initial) state afterwards, so when I was trying to do 2nd, 3rd time state was not changed so callback was not triggered. Turned out pretty dumb mistake actually, my bad
