### ISSUE TITLE
Your website jointjs.com is down . When will be it live again?

### ISSUE THREAD

**Issue by tahirnawaz** [clientIO/joint#161]

**Comment by kumilingus** [comment]
We're working on it as we speak. Bear with us please.

**Comment by kumilingus** [comment]
It's live again. We do apologize for any inconvenience this may have caused.

**Comment by tahirnawaz** [comment]
Thank you.

**Comment by tahirnawaz** [comment]
I know its not relevant here but I have been lingering in a problem related to joint js. Can you  please help me here with this? Really appreciate one of you guys tried to help. But still the solution sugessted is not complete. 
http://stackoverflow.com/questions/31368160/joint-js-add-custom-ports-with-path-class-for-custom-elements?noredirect=1#comment51166890_31368160
