### ISSUE TITLE
How to properly layout a Petri Net in jointjs?

### ISSUE THREAD

**Issue by LordHeImchen** [clientIO/joint#1617]
Hey,
I am struggling to layout an existing graph with places, custom transitions and links on the respective paper. The graph is rendered already, but all places and transitions are clustered in a single place. I tried to reset their position property in a "smart" way, but failed with that as you cannot discover any Petri net afterwards. Furthermore, the position of the places did not automatically update, only when i dragged them a little bit they would jump to their new position.

Anyhow, I found this [demo](https://resources.jointjs.com/demos/directed-graph), last time committed to by @kumilingus and reviewed the corresponding code on Github but didn't quite understand it. Moreover, the example is quite extensive, i do not want to give any options for laying out the Petri net, instead i just want to provide a basic layout which is better than having all places and transitions clustered on a single place.

Can anyone help me to transfer this to an already existing graph?

**Comment by kumilingus** [comment]
The [DirectedGraph](https://resources.jointjs.com/docs/jointjs/v3.4/joint.html#layout.DirectedGraph) is a function you can call on any graph.
```js
joint.layout.DirectedGraph.layout(graph, { /* options */});
```
> I tried to reset their position property in a "smart" way, but failed with that as you cannot discover any Petri net afterwards. Furthermore, the position of the places did not automatically update, only when i dragged them a little bit they would jump to their new position.

You have to provide us with the code.

**Comment by LordHeImchen** [comment]
Oh, i totally missed that link, works like a charm!
Thanks once again.
