### ISSUE TITLE
It is not possible to change arrow to DoubleLink

### ISSUE THREAD

**Issue by Eymerich01** [clientIO/joint#1633]
I try all possible cobinations on attrs but there is not way to change or remove arrow to shapes.standard.DoubleLink

![image](https://user-images.githubusercontent.com/20681683/157931970-84ae2f20-99f8-4655-8b3c-0ea8be8cda20.png)

**Comment by kumilingus** [comment]
```js
// no arrow
const doubleLink1 = new standard.DoubleLink({
    attrs: {
        line: {
            targetMarker: null,
        }
    }
});
```
<img width="49" alt="image" src="https://user-images.githubusercontent.com/3967880/157935988-160d7e9e-5aa9-4b1e-8164-c97d39a0936c.png">

----

```js
// circle arrowhead
const doubleLink2 = new standard.DoubleLink({
    attrs: {
        line: {
            targetMarker: {
                type: 'circle',
                r: 5,
            },
        }
    }
});
```
<img width="40" alt="image" src="https://user-images.githubusercontent.com/3967880/157935923-9720f055-3a7e-4d84-8503-cada4be51896.png">

**Comment by Eymerich01** [comment]
thx a lot
