### ISSUE TITLE
Working with Vite

### ISSUE THREAD

**Issue by panitaxx** [clientIO/joint#1641]
Hello, 

I have a small problem with joint. I am trying to use it with vite to create a vue component. It works perfectly when run with `npm run dev` but it fails with `npm run build`.  An error appears in the console `TypeError: Right-hand side of 'instanceof' is not an object`.  It seems that at some point jquery is being required 
```javascript
      var _2 = underscoreUmdMin.exports, $2;
      try {
        $2 = require("jquery");
      } catch (e) {
      }
      factory(root, exports, _2, $2);
``` 

which of course it does not works on browsers. I tried passing backbone to the commonJS options: 

```javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  build: {
    commonjsOptions:{
      include: ['node_modules/backbone/**','node_modules/jquery/**','node_modules/lodash/**'],
    }
  }
})

``` 

but it didn't work the error now is that it does not find underscore.  If I add that under the commonJS option it stops working with the same message of instanceof. 

I made a small repo with a test case https://github.com/panitaxx/joint-rollup

I am looking for any pointers of how I can modify this to make it work on production. Any help is appreciated

**Comment by kumilingus** [comment]
Hi,

I get the same error when I include `Backbone` only. 

*package.json*
```json
  "dependencies": {
    "backbone": "^1.4.1",
    "vue": "^3.2.6"
  },

```

*component.vue*
```vue
<script setup>
import { ref, onMounted } from 'vue'
import { View } from 'Backbone';

const myDiv = ref(null)

onMounted(() => {

  const view = new View({ el: myDiv.value });

  view.$el.css({
    width: 100,
    height: 100,
    background: 'red'
  });
});
</script>

<template>
  <div ref="myDiv"></div>
</template>
```

Perhaps this issue should be raised at their repository.

**Comment by panitaxx** [comment]
Hello, 

Thanks for your answer. I solve it compiling backbone as an esm module and adding it as an alias in vite config. You can check out the repo I made to see the complete solution. Also here is a direct link to the backbone esm version https://raw.githubusercontent.com/panitaxx/joint-rollup/master/backbone-esm.js
