### ISSUE TITLE
Application not working after migrating to Angular 13

### ISSUE THREAD

**Issue by Taliesin60600** [clientIO/joint#1649]
Hello. 
We have an application using Angular and RappidJs (3.2.0). 
When we tried to update Angular (and all dependencies) to 13, the ng serve not working with error : 
./node_modules/@clientio/rappid/rappid.js:58560:14-28 - Error: Module not found: Error: Can't resolve 'url' in 'C:\Git\UbikeyWeb\node_modules\@clientio\rappid'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

**Comment by kumilingus** [comment]
Hi, did you try to:
- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
- install 'url'
