### ISSUE TITLE
joint.dia.Link with "z" of 0 has "z" incorrectly fixed after moving an arrow head

### ISSUE THREAD

**Issue by rickbutton** [clientIO/joint#171]
One of our clients noticed a bug in an internal tool (using joint.js) with links. Essentially, a link with an original z index of 0 has its z index corrupted after one of the arrowheads of the link is moved.

To reproduce the issue follow the steps in this test: https://jsfiddle.net/rickbutton/zskwLgcd/1/

**Comment by rickbutton** [comment]
I believe that this is the offending line:

https://github.com/clientIO/joint/blob/62cb53bb00913555d16580be4e279e9cedc37fdb/src/joint.dia.link.js#L1153

**Comment by kumilingus** [comment]
Merged.
