### ISSUE TITLE
Not able to set-up JointJS+ on local 

### ISSUE THREAD

**Issue by ShashakSamaiya** [clientIO/joint#1728]
I'm following the tutorial to setup the JointJS+ React app : https://resources.jointjs.com/tutorial/react-ts
But getting the below error when running the demo code: https://github.com/clientIO/rappid-tutorial-react
<img width="601" alt="image" src="https://user-images.githubusercontent.com/48426977/178305153-36cde96b-a689-428f-9955-20e23db82c37.png">
It's looking for rappid.tgz file

 <img width="656" alt="image" src="https://user-images.githubusercontent.com/48426977/178307044-45e1de5b-bf9f-4faa-a2bb-692e99a3d04a.png">
I tried to register for the Free trail on the official site(https://www.jointjs.com/rappid-trial) but after entering the details. the page is getting reloaded.

Please guide if there's any other way to get the "rappid.tgz" package.

**Comment by jamesgeorgewilliams** [comment]
After submitting the form for the free trial you should see the following:
<img width="883" alt="Screenshot 2022-07-12 at 8 28 28" src="https://user-images.githubusercontent.com/42288565/178423822-66e0aa28-5c6f-441f-88aa-ca7298c836e9.png">


If the page is reloading/refreshing, maybe try the process in a different browser to see if the same thing happens.

Also, I would still check your email account(the one used in the form) to see if you have received the trial information anyway. Make sure to check your spam folder too.

If you still have the same problem in a different browser/machine, we can look into it for you, but the trial process is functioning correctly for us at the moment.

**Comment by ShashakSamaiya** [comment]
Thanks James for the info.
I've received the mail to download the JointJS+ rappid file, it was under the Promotions folder.
