### ISSUE TITLE
Grunt-newer doesn't always update changed dist files.

### ISSUE THREAD

**Issue by kumilingus** [clientIO/joint#173]

**Comment by chill117** [comment]
Keep your eyes open for the next time you run into problems with grunt-newer. If I can reproduce the problem, I might be able to find a definitive fix for it.

**Comment by kumilingus** [comment]
Ok, here it is.
1. (bunch of changes, dist files was not updated) d45983f65d02cf10a510a281032848ba2fffce75 the test failed.
2. (only dist updated) bf1c2eb03ecb84b74ce2cd4e8878999b8fc359c5 the test succeed.
