### ISSUE TITLE
unable to run jointJs after integrate rappid_trial_v3_5_0.tgz in reactJs 

### ISSUE THREAD

**Issue by sandeepyaduvanshi** [clientIO/joint#1732]
Hi, I am unable to run jointJs after integrating rappid_trial_v3_5_0.tgz in reactJs. 
when I wrote @import "~@clientio/rappid/rapidd.css"; this give error - 
ERROR in ./src/App.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/App.scss)

**Comment by kumilingus** [comment]
Perhaps `css-loader` is required?
https://stackoverflow.com/a/55652180/2921495

**Comment by sandeepyaduvanshi** [comment]
Thanks, I installed node-sass@latest-version, and the issue was fixed.
