### ISSUE TITLE
No Documentation on 'linkPinning'

### ISSUE THREAD

**Issue by mickeyvip** [clientIO/joint#182]
Hello, 

There is no documentation on `linkPinning` option of `joint.dia.Paper` on the documentation site.

Thank you.

**Comment by kumilingus** [comment]
Thanks for the info. We'll add it ASAP.

https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L89-L91

**Comment by DavidDurman** [comment]
Done. Here's a direct link: http://jointjs.com/api#joint.dia.Paper:options.linkPinning

**Comment by mickeyvip** [comment]
Thank you.
