### ISSUE TITLE
No ports rendered on derived DEV shape

### ISSUE THREAD

**Issue by mickeyvip** [clientIO/joint#184]
I have a derived DEV shape:

```javascript
joint.shapes.devs.SBModel = joint.shapes.devs.Model.extend({
	portMarkup: '<g class="port port<%= id %>"><circle class="port-body"/><text class="port-label"/></g>',
	defaults: joint.util.deepSupplement({
		type: 'devs.SBModel',
		attrs: {
			'.body': {stroke: 'blue', fill: 'lightblue'}
		}
	}, joint.shapes.devs.Model.prototype.defaults)
});
joint.shapes.devs.SBModelView = joint.dia.ElementView.extend(joint.shapes.devs.ModelView);
```

initializing it:
```javascript
var m1 = new joint.shapes.devs.SBModel({
	position: { x: 50, y: 50 },
	size: { width: 90, height: 90 },
	inPorts: ['in1','in2'],
	outPorts: ['out'],
	attrs: {
		'.label': { text: 'Model', 'ref-x': .4, 'ref-y': .2 }
	}
});
graph.addCells([m1]);
```

The ports are not rendered:
![image](https://cloud.githubusercontent.com/assets/220427/9945047/b248ac44-5d93-11e5-9cb2-46dfb1db0e23.png)

and the markup shows that the ports are not rendered at all:
![image](https://cloud.githubusercontent.com/assets/220427/9945067/cb04125a-5d93-11e5-9546-9ba49125d048.png)

Am I doing something wrong? It worked in `v0.9.4`.

Thank you.

**Comment by kumilingus** [comment]
Hi,

could please check out this thread:
https://groups.google.com/forum/#!topic/jointjs/QKSkIKbecSs.

Best,
Roman

On 17 September 2015 at 22:29, Mickey <notifications@github.com> wrote:

> I have a derived DEV shape:
>
> joint.shapes.devs.SBModel = joint.shapes.devs.Model.extend({
>     portMarkup: '<g class="port port<%= id %>"><circle class="port-body"/><text class="port-label"/></g>',
>     defaults: joint.util.deepSupplement({
>         type: 'devs.SBModel',
>         attrs: {
>             '.body': {stroke: 'blue', fill: 'lightblue'}
>         }
>     }, joint.shapes.devs.Model.prototype.defaults)
> });
> joint.shapes.devs.SBModelView = joint.dia.ElementView.extend(joint.shapes.devs.ModelView);
>
> initializing it:
>
> var m1 = new joint.shapes.devs.SBModel({
>     position: { x: 50, y: 50 },
>     size: { width: 90, height: 90 },
>     inPorts: ['in1','in2'],
>     outPorts: ['out'],
>     attrs: {
>         '.label': { text: 'Model', 'ref-x': .4, 'ref-y': .2 }
>     }
> });
> graph.addCells([m1]);
>
> The ports are not rendered:
> [image: image]
> <https://cloud.githubusercontent.com/assets/220427/9945047/b248ac44-5d93-11e5-9cb2-46dfb1db0e23.png>
>
> and the markup shows that the ports are not rendered at all:
> [image: image]
> <https://cloud.githubusercontent.com/assets/220427/9945067/cb04125a-5d93-11e5-9546-9ba49125d048.png>
>
> Am I doing something wrong? It worked in v0.9.4.
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clientIO/joint/issues/184>.
>



-- 
Roman Bruckner, CTO
client IO
http://client.io <http://www.client.io/>
http://jointjs.com
+420 776 504 406 <%2B420%20774%20346%20225>

**Comment by mickeyvip** [comment]
@kumilingus, I have tried it, but it still does not work.

Here is a jsFiddle demosntrating the derived vs original models: https://jsfiddle.net/mickeyvip/g9etgzew/

**Comment by kumilingus** [comment]
Hi,

ok I see.

Backbone.View.extend(function() {}) does not do anything.

try the following:

 joint.shapes.devs.SBModelView = joint.shapes.devs.ModelView;

Best,
Roman


On 17 September 2015 at 22:58, Mickey <notifications@github.com> wrote:

> @kumilingus <https://github.com/kumilingus>, I have tried it, but it
> still does not work.
>
> Here is a jsFiddle demosntrating the derived vs original models:
> https://jsfiddle.net/mickeyvip/g9etgzew/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clientIO/joint/issues/184#issuecomment-141226574>.
>



-- 
Roman Bruckner, CTO
client IO
http://client.io <http://www.client.io/>
http://jointjs.com
+420 776 504 406 <%2B420%20774%20346%20225>

**Comment by mickeyvip** [comment]
@kumilingus, thank you.

This was as a leftover from my error/trials before. Using the ` joint.shapes.devs.SBModelView = joint.shapes.devs.ModelView` did rendered the ports.

And I realized now that I should use `myModel.prop()` instead of `myModel.attr()` in order to update the ports after initializing the model.

```javascript
var sbModel = new joint.shapes.devs.SBModel({
        position: {
            x: 50,
            y: 50
        },
        size: {
            width: 90,
            height: 90
        },
        attrs: {
            '.label': {
                text: 'Model',
                'ref-x': .4,
                'ref-y': .2
            }
        }
    });
sbModel.prop({
   	inPorts: ['in1', 'in2'],
        outPorts: ['out'],
});
```
Now it works.

Thank you.
