### ISSUE TITLE
Access to the graph from an ElementView

### ISSUE THREAD

**Issue by nomeata** [clientIO/joint#186]
In my custom `ElementView`’s initializer, I’d like to be able to listen on attribute changes of the `graph` object, and not just the elements’.

I currently work around the issue by setting the attribute (a simple boolean flag) on *all* elements simultaneously, which feels wrong.

An `ElementView` has access to the graph via `this.paper.model`, but only after the initialization, and does not seem to be the proper way. I’d rather like to see a `graph` attribute on the actual `Cell` object.

**Comment by kumilingus** [comment]
Will be part of the JointJS v0.9.6.
