### ISSUE TITLE
Chatbot can only three outports at most

### ISSUE THREAD

**Issue by BruceChen2017** [clientIO/joint#1870]
### What happened?

When I try to add more item for out port, I can only add three items at most. How can I relax this contraint? I want to add more.
P.S. I play the demo online.

### Version

3.6.2

### What browsers are you seeing the problem on?

Microsoft Edge

### What operating system are you seeing the problem on?

Windows

**Comment by BruceChen2017** [comment]
sorry, this can be solved by changing `MAX_PORT_COUNT`

**Comment by kumilingus** [comment]
If you need to resize the shape based on the number of ports please check out the [list](https://resources.jointjs.com/demos/list) demo (vertical) or this [CodePen](https://codepen.io/jointjs/pen/yLKGgaR) (horizontal).

**Comment by BruceChen2017** [comment]
@kumilingus Thanks. If I have multiple entities to be added, any way to place all entities automatically without overlapping(I mean, this may be called auto-layout)? For example, from backend, I receive multiple entites each having label and desc, then in the ui, I need to add all these cells programmatically.

**Comment by BruceChen2017** [comment]
@kumilingus Thanks. If I have multiple entities to be added, any way to place all entities automatically without overlapping(I mean, this may be called auto-layout)? For example, from backend, I receive multiple entites each having label and desc, then in the ui, I need to add all these cells programmatically.
