### ISSUE TITLE
Fix use of deprecated flags argument for String.prototype.{search,match,replace} methods

### ISSUE THREAD

**Issue by DontShootMe** [clientIO/joint#189]
flags argument of String.prototype.{search,match,replace} is deprecated

https://github.com/clientIO/joint/blob/master/src/joint.dia.element.js#L252

**Comment by chill117** [comment]
Good catch. I'll look into fixing this.

References:
* [String.prototype.replace()](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/String/replace)
* [String.prototype.search()](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/String/search)
* [String.prototype.match()](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/String/match)

**Comment by chill117** [comment]
This has been fixed upstream and will be included in the next release.
