### ISSUE TITLE
bug(dia.Paper): browser context menu appears when using paper events since version 3.6.

### ISSUE THREAD

**Issue by kumilingus** [clientIO/joint#1891]
### Discussed in https://github.com/clientIO/joint/discussions/1890

<div type='discussions-op-text'>

<sup>Originally posted by **chrismag87** November 14, 2022</sup>
Before I upgraded JointJS+ to 3.6, (I was on 3.5) when the user right clicked an element or cell, the browsers' context menu would not appear. This is the code that worked:

    'element:contextmenu': (cellView: any, evt: any) => {
        // The action after right click 
        //  Opens up a mat dialog
    },`
    
 Since this has started happening after the update, I have added this line to try and prevent it from appearing:
    
     'element:contextmenu': (cellView: any, evt: any) => {
        evt.preventDefault();
        
        // The action after right click 
        //  Opens up a mat dialog
    },`
        
  But to no prevail, can anyone add any light to this? 
  
  I cannot guarantee it is rappid but the fact it happens when right clicking the elements/cells leads me to think it is to do with the upgrade.
  
  Thanks   
            </div>

**Comment by kumilingus** [comment]
Can not reproduce. Feel free to provide steps to reproduce and re-open.

**Comment by noemi-salaun** [comment]
I had the same issue with opening a mat-menu. Adding preventDefault anywere did not solve the issue.
Wrapping the mat-menu open inside a setTimeout() did solve it :)
