### ISSUE TITLE
_.templateSettings

### ISSUE THREAD

**Issue by DontShootMe** [clientIO/joint#190]
Using Lodash / underscore as global variable in a project the `_.templateSettings` could be changed in favor of the global project.
So i've spent a moment before found that the `_.templateSettings.data` have been set to ` 'data' ` instead of the default empty value ` "" `.
Maybe it will be preferable to ensure that the settings are good before calling a template that could break the whole part of joint.js

is it really an issue ?

**Comment by chill117** [comment]
Can you provide some sample application code that highlights the specific problem?

**Comment by DontShootMe** [comment]
here [a fiddle](https://jsfiddle.net/x5kh10o2/) where you can see that nothing is rendered because we've changed the `_.templateSettings.variable = 'data'; ` 

***
_Sorry but i haven't seen in my first message i have wrote_ : 
> `_.templateSettings.data`

_but i was talking about_ : 
`_.templateSettings.variable`

**Comment by chill117** [comment]
I looked at the fiddle. I see this error in the console:
```
Uncaught TypeError: Cannot set property 'variable' of undefined
```

Looking at the line that error referenced, I can see this:
```js
_.templateSetting.variable = 'data';
```

This means that `_.templateSetting` is undefined. Which makes sense. If you look at the [lodash documentation](https://lodash.com/docs) you can see that it is supposed to be `_.templateSettings` with an `s` at the end. I made the change to your fiddle and now it works:
https://jsfiddle.net/x5kh10o2/2/
