### ISSUE TITLE
[Bug]: On align center horizontally/vertically, Selections objects gets collapse on each other

### ISSUE THREAD

**Issue by gsnalinkode** [clientIO/joint#1916]
### What happened?

- [Bug]: On align center horizontally/vertically, Selections objects gets collapse on each other
- For Horizontally center alignment
![image](https://user-images.githubusercontent.com/70625179/204516694-26d85336-b920-493b-92e9-727f726d26bd.png)

- After horizontal center alignment, the selected objects get collapse on each other as below.
 ![image](https://user-images.githubusercontent.com/70625179/204517131-3d38cad3-5bb1-4ab7-835a-77b528f128fb.png)
- Same in case with Vertical center alignment
![image](https://user-images.githubusercontent.com/70625179/204517386-fba68c5f-c090-431f-be35-4dcf4c4da8ce.png)
- After vertical center alignment, the selected objects get collapse on each other as below.
 ![image](https://user-images.githubusercontent.com/70625179/204517534-b672a8df-6e81-4764-b5e3-cef2ac3b001a.png)

### Version

3.6.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
What do you think would be the expected behavior?
