### ISSUE TITLE
[Bug]: 'user-drag' is missing vendor prefixes

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#1926]
### What happened?

There is a CSS rule in `rappid.css` which is missing a vendor prefix:

```diff
.joint-element * {
   user-drag: none;
+ -webkit-user-drag: none;
}
```

This is the only rule that is missing it; all other places where 'user-drag' is used have the vendor prefix.

### Version

3.6.2

**Comment by kumilingus** [comment]
Is this causing any issues?

**Comment by alexandernst** [comment]
Hard to say, given that the selector is very broad. I noticed it accidentally while debugging something unrelated. But since the fix is very simple, I'd rather put it.
