### ISSUE TITLE
joint.dia.cell.getView ?

### ISSUE THREAD

**Issue by DontShootMe** [clientIO/joint#193]
There is a function in [joint.dia.cell](https://github.com/clientIO/joint/blob/master/src/joint.dia.cell.js#L658) called `findView` : 
```javascript
    // A shortcut for an equivalent call: `paper.findViewByModel(cell)`
    // making it easy to create constructs like the following:
    // `cell.findView(paper).highlight()`
    findView: function(paper) {

        return paper.findViewByModel(this);
    },
```
Using this function we need to have access to / know  `paper` !
Is it possible to add a function `getView` which return the correct view directly ( without parameter ) ?
How ?

By modifying `createViewForModel` from [joint.dia.paper](https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L420)
At the end before returning the view :
```javascript
        //return new ViewClass({
        var currentView = new ViewClass({
            model: cell,
            interactive: this.options.interactive
        });
        if(! cell.getView ){
            cell.getView = function( ){ return currentView; };
        }
        return currentView;
```
Or maybe attach the view directly
``` javascript 
    if( ! cell.view ) cell.view = currentView ;
```

This will increase the possibility to interact between the model and the view more easily.

**Comment by kumilingus** [comment]
Not possible. Note that one cell can have multiple views.

e.g. http://jointjs.com/tutorial#multiple-papers
You have to explicitly tell which view do you want to find.

**Comment by DontShootMe** [comment]
Ha ok !  I understand now !
Thanks.
