### ISSUE TITLE
Error while retrieving shape(pool) from database in jointjs

### ISSUE THREAD

**Issue by kiriti999** [clientIO/joint#195]
I am able to retrieve all the shapes properly except swimlane pool. I tried with jointjs 0.9.5 and also 0.9.3. Both of them throw similar error:

Uncaught Error: dia.ElementView: reference does not exists 
@ joint_0.9.5.js:5286

**Using jointjs 0.9.3 gives error at this line**

**Uncaught TypeError: Cannot read property 'bbox' of undefined**

if (ref) {
  // Get the bounding box of the reference element relative to the root `<g>` element.
    bbox = V(this.findBySelector(ref)[0]).bbox(false, this.el);
  }

I checked it so many times. **This problem occurs only whlie retrieving from Database, jointjs is not able to get bounding box of the following:**

**console.log(V(this.findBySelector(ref)[0]).bbox(false, this.el)); // Joint js 0.9.3**
I checked it manually and here is the error. Because of this error, the pool header is not displayed and the shape itself looks distorted

joint.shapes.devs.Container = joint.shapes.devs.Model.extend(_.extend({}, joint.plugins.TooledModelInterface, {
    markup:
       ```  [```
              ```  '<g class="rotatable">',```
               ``` '<g class="scalable">',```
              ```  '<rect class="body"/>',```
               ``` '</g>',```
               ``` '<rect class="pool_header"/>',```
               ``` '<text class="t"/>',```
               ``` '<g class="inPorts"/>',```
               ``` '<g class="outPorts"/>',```
               ``` '<g class="moveTool"/>',```
               ``` '<g class="resizeTool"/>',```
               ``` '<g class="portsTool"/>',```
                ```'</g>'```
           ``` ].join(''),```
   ``` defaults: joint.util.deepSupplement({```
        ```type: 'devs.TooledModel',```
       ``` position: {x: 200, y: 100},```
        ```size: {width: 71, height: 625},```
        ```attrs:```
               ``` {```
                   ``` '.body': {fill: '#ffffff', stroke: '#000000', width: 500, height: 200, 'pointer-events': 'stroke'},```
                    ```'.pool_header': {fill: '#fff', stroke: '#000', width: 30, ref: '.body', 'ref-height': 1, 'pointer-events': 'visiblePainted'},```
                   ``` '.t': {transform: 'rotate(-90)', ref: '.pool_header', dx: '-0.1%', dy: '50%', 'x-alignment': 'middle', 'text-anchor': 'middle'},```
                   ``` rect: {stroke: '#000000', fill: '#EEEEEE', 'stroke-width': 2}, '.': {magnet: false},```
                   ``` '.inPorts circle': {type: 'input'},```
                    ```'.outPorts circle': {type: 'output'},```
                    ```'.port-body': {r: 3}```
               ``` }```
   ``` }, joint.shapes.devs.Model.prototype.defaults)```
```}```

Here is the Screenshot:

![wf](https://cloud.githubusercontent.com/assets/13074074/10450391/9f00e696-71b7-11e5-934c-9b3026ef1233.png)

**Comment by kumilingus** [comment]
Could you please try to change `type` attribute of the `joint.shapes.devs.Container` to `devs.Container` (not to `devs.TooledModel`).
