### ISSUE TITLE
[Unexpected behavior]: CommandManager.fromJSON() will modify source data

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#1950]
### What happened?

I just got hit by an unexpected behavior in the CommandManager. It seems that `fromJSON` will feed the data structure passed as parameter to the CommandManager and then, when deltas get pushed to the undo/redo stack, the original data structure will be affected.

The workaround is to deep clone the data passed to `fromJSON`, but I thought I'd report this as it's not something I (as a user) would expect.

### Version

3.6.4

### What browsers are you seeing the problem on?

Safari

### What operating system are you seeing the problem on?

Mac

**Comment by zbynekstara** [comment]
Fixed in JointJS+ version 3.7.0
