### ISSUE TITLE
[Bug]: cannot open contexttoollbar on fullscreen using util.toggleFullscreen or toolbar fullscreen type

### ISSUE THREAD

**Issue by Vishal-Patil-Gslab** [clientIO/joint#1959]
### What happened?

we are not able to open context toolbar in fullscreen, we are doing fullscreen using` util.toggleFullscreen() `and also we are using toolbar `fullscreen type` to view our page in fullscreen. but somehow contexttoolbar is not opening when we are doing fullscreen by pressing a button but the context toolbar is working in  fullscreen that is enabled using` F11` button  

following is the code pen where i have added the fullscreen button
https://codepen.io/Vishal-patil-gslab/pen/dyjPmdx

Note: please use debug mode to enable fullscreen on codepen

### Version

3.3.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Windows, Mac

**Comment by kumilingus** [comment]
If I open the CodePen provided (https://cdpn.io/Vishal-patil-gslab/fullpage/dyjPmdx), switch to fullscreen using the toolbar button, the contextmenu opens as expected.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/3967880/208904846-e500a83d-77fd-44ca-a51d-299343e48bf0.png">

*Note: the example provided is using JointJS+ `v3.6`*

**Comment by Vishal-Patil-Gslab** [comment]
thanks @kumilingus after adding `root` to `ui.ContextToolbar` and appending it is working.
thanks for the quick response
