### ISSUE TITLE
USING HTML IN JOINTJS ELEMENTS does not work.

### ISSUE THREAD

**Issue by ophite** [clientIO/joint#198]
In your example http://www.jointjs.com/tutorial/html-elements used old version of jointjs (0.9.3), when i used last version 0.9.5  i have the same result as in this link http://codegur.com/32949736/using-html-in-jointjs-elements-does-not-work.

This is a bug? Or i am doing something wrong. Thnx

**Comment by kumilingus** [comment]
please try to instantiate the paper after you define all your custom elementViews.

e.g.

     var paper = new joint.dia.Paper({ ... });
     joint.shapes.html.ElementView = joint.dia.ElementView.extend({ ... });

replace with

    joint.shapes.html.ElementView = joint.dia.ElementView.extend({ ... });
    var paper = new joint.dia.Paper({ ... });


This bug was introduces in `0.9.5`. Will be fixed in the following release.

**Comment by ophite** [comment]
Thanks. All worked.

**Comment by ttcpu** [comment]
Thanks, I suffer for the same problem, I suggest to update the document http://www.jointjs.com/tutorial/html-elements
