### ISSUE TITLE
[Bug]: jointjs does not build with angular15

### ISSUE THREAD

**Issue by thomaspeugeot** [clientIO/joint#2017]
### What happened?

Sequence:

```
git clone https://github.com/thomaspeugeot/jointjsng.git
cd jointjsng
npm i
ng build
```

Problem

```
Error: node_modules/jointjs/dist/joint.d.ts:1322:87 - error TS2344: Type 'A' does not satisfy the constraint 'ObjectHash'.

1322     class Graph<A = Graph.Attributes, S = dia.ModelSetOptions> extends Backbone.Model<A, S> {

....
```

Note that ng 15 uses  "typescript": "~4.9.5"

### Version

3.6.5

### What browsers are you seeing the problem on?

Firefox

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
- Does adding `skipLibCheck: true` option to your `tsconfig` help ([docs](https://www.typescriptlang.org/tsconfig#skipLibCheck))?
- Did it work with Angular 14 without `skipLibCheck: true`?

**Comment by thomaspeugeot** [comment]
> * Does adding `skipLibCheck: true` option to your `tsconfig` help ([docs](https://www.typescriptlang.org/tsconfig#skipLibCheck))?

Yes, it solves the issue



> * Did it work with Angular 14 without `skipLibCheck: true`?

Yes, the package.json file with 2 commits before

https://github.com/thomaspeugeot/jointjsng/blob/111ce42ffcca18506f75f7e96384c9510bcb03f3/package.json

**Comment by jamesgeorgewilliams** [comment]
Hi,

After looking into the issue further, we found it is related to enabling the rule `strict: true` in `tsconfig`. If you change the rule to `false` in your repo, the issue resolves too.

I will close this issue, and I have created a new issue to fix the errors. You can track it here:
https://github.com/clientIO/joint/issues/2018

Thanks very much for reporting.
