### ISSUE TITLE
`evt.stopPropagation()` has no effect causing many events to fire

### ISSUE THREAD

**Issue by mickeyvip** [clientIO/joint#202]
There are several events that are supported:
- `cell:pointerdown`
- `cell:pointerup`
- `cell:pointerclick`
- `cell:pointerdblclick`

The problem in my opinion is that all that events are fired as a result of mouse clicks and it seems that  `evt.stopPropagation()` has no effect.

For example: 

I have `evt.stopPropagation()` in each of the event handlers.
### click

1 `cell:pointerdown`
2 `cell:pointerup`
3 `cell:pointerclick`
### double click

1 `cell:pointerdown`
2 `cell:pointerup`
3 `cell:pointerclick`
4 `cell:pointerdown`
5 `cell:pointerup`
6 `cell:pointerclick`
7 `cell: pointerdblclick`

Also sometimes I see that for a single click there are only `cell:pointerdown` and `cell:pointerup` fired.

**Comment by kumilingus** [comment]
In JointJS `v1.0.2` it should be possible to simulate `stopPropagation` by setting `evt.data.guarded = true`.

https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L1008-L1010

**Comment by kumilingus** [comment]
Fixed by 48db61cd85b9360558e365263fcaf0164908d1ff.
