### ISSUE TITLE
Examples are broken on the official website

### ISSUE THREAD

**Issue by mickeyvip** [clientIO/joint#203]
Hello,

For some time now the examples on the official website are broken.

This exception seen in the console may have something to do with that:

```
Uncaught TypeError: this.node.getTransformToElement is not a function
```
![image](https://cloud.githubusercontent.com/assets/220427/11748529/634df0f0-a031-11e5-92b8-440471b07292.png)

**Comment by kumilingus** [comment]
Hi,
Unfortunately, a new version of Chrome (48) removes a feature that is core to JointJS/Rappid. We prepared a polyfill to make sure your applications will work with all future versions of Chrome. Before we release a new version of JointJS/Rappid, please include the following lines before you load your application JavaScript:

SVGElement.prototype.getTransformToElement = SVGElement.prototype.getTransformToElement || function(toElement) {
    return toElement.getScreenCTM().inverse().multiply(this.getScreenCTM());
};

You can alternatively use the most recent version of JointJS from the GitHub repository ('dist' folder).

**Comment by clthck** [comment]
Tried with the latest `joint.core.min.js` and it works now :)

**Comment by codeHatcher** [comment]
yeah, funny how in the past couple release chrome as been "breaking" a few things from different libraries
