### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token 'export'. import { dia, ui, shapes } from '@clientio/rappid'

### ISSUE THREAD

**Issue by LesiaMat95** [clientIO/joint#2046]
### What happened?

I deployed Chatbot locally(JointJS+ v3.5.0). I wrote the first jest test and faced a problem that exists only at the time of testing the project.
the Chatbot code is derived from JointJS+. This code hasn't even changed yet. The project is launched, everything works personally, but with unit tests trouble. I tried to mock svg since you have already discussed this topic but it did not help me.
![image](https://user-images.githubusercontent.com/125379772/218775170-11b763a5-ce13-4f4f-bd82-6657cf022c0b.png)

### Version

3.5.0

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by jamesgeorgewilliams** [comment]
Closing as problem is discussed in the following github discussion:
https://github.com/clientIO/joint/discussions/2045
