### ISSUE TITLE
Lot of elements

### ISSUE THREAD

**Issue by shivkoirala** [clientIO/joint#206]
HI,

I have lot of elements like 50 in number. The complete diagram is looking cramped. I know i can adjust X and Y and make them look clean. Is there something ready made in framework to acheive the same.

Thanks and congrats for the great framework.

**Comment by Botev** [comment]
I think this would require an algorithm for graph visualization, similar to the one found in Graphviz. This is not so trivial, but I agree it would be nice if the authors have some time for this.

**Comment by chill117** [comment]
Have a look at the [directed graph plugin](http://jointjs.com/rappid/docs/layout/directedGraph). The site groups it with the Rappid (commercial) plugins, but it's part of JointJS.

**Comment by Botev** [comment]
Mmm that looks very nice. Have you considered #236 ?

**Comment by chill117** [comment]
@Botev Apologies, but I've got a lot on my plate at the moment. I probably won't have time to get to responding to your other issue for a day or two.

**Comment by Botev** [comment]
Sure no problem, just that I'm interested if there would be a progress on the other issue as that is my use case. But no hurry, have plenty of time :)
