### ISSUE TITLE
[Bug]:  Event "ctrl+mouse wheel" can't be catched.

### ISSUE THREAD

**Issue by Particle60** [clientIO/joint#2076]
### What happened?

I want to catch event "ctrl+mouse wheel" and do something. But rappid can't catch that event.  Then I checked the source code and found your code haven't trigger it. 
At last, I changed the code and it works. But I'm sure  if my code met your expection.
So can you fix this issue in next release?
<img width="1039" alt="ctrl+mousewheel" src="https://user-images.githubusercontent.com/6045842/225277039-803b92ee-0302-4574-b877-91f7276116b7.png">

### Version

3.6.1

**Comment by kumilingus** [comment]
It has been already fixed in #2039. It will be part of the next release.
