### ISSUE TITLE
[Bug]:  refHeight has no effect in customed element shape.

### ISSUE THREAD

**Issue by Particle60** [clientIO/joint#2087]
### What happened?

```
        {
                tagName: 'path',
                selector: 'icon',
         },
......    
icon: {
                refY:24,
                refHeight:-24,
                refD: 'm 0,0 h 10 v -12.2 h -10 z m 1,-3 h 2 v -4 h 4 v 4 h 2',
                strokeWidth: 1,
                stroke: black,
                fill: white,
                fillOpacity: 0,
                pointerEvents: 'none',
            },
```
I customed a element with tag "path", I want its size equals "element size - 24". So I used “refHeight:-24”, but it has no effect. But for tag "rect", it works well.
I hope jointjs can improve this feature.
In the following picture, the first element "refY" works well, but "refHeight" didn't work. Second element has no "refY" and "refHeight", so it's size equals element's size. But its icon will be overlapped to its label when its size is small.
![refHight](https://user-images.githubusercontent.com/6045842/226832302-38d572d2-40ce-4bc0-8b3b-b94839058081.gif)

### Version

3.6.1

**Comment by kumilingus** [comment]
It's not how it works.

`refX` sets `x` attribute.
`refWidth` sets `width` attribute.
`refD` sets `d` attribute.

There is no `x` or `width`  on `<path/>` ([SVGPathElement](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path)).
The `x` and `width` is available for `<rect/>` ([SVGRectElement](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect)).

**Note:** the `ref` attributes have been deprecated. Use [calc expressions](https://resources.jointjs.com/docs/jointjs/v3.6/joint.html#dia.attributes.intro) instead.
