### ISSUE TITLE
[Bug]: Unable to find dia.LinkView.prototype.removeRedundantLinearVertices

### ISSUE THREAD

**Issue by nt294** [clientIO/joint#2117]
### What happened?

I am unable to call this method on my linkView object ([as shown in the documentation here](https://resources.jointjs.com/docs/jointjs/v3.6/joint.html#dia.LinkView.prototype.removeRedundantLinearVertices)). All of the other methods are showing and working correctly for me, except this one. I can't seem to find it in the source within the node_modules directory either. 

### Version

3.6.5

**Comment by jamesgeorgewilliams** [comment]
Hi,

Thanks for reporting. It seems this method is not documented in TypeScript. It will be fixed in an upcoming release of JointJS. https://github.com/clientIO/joint/pull/2119

In the meantime, you can temporarily fix the issue in TypeScript with a TS comment:

```js
// @ts-ignore
linkView.removeRedundantLinearVertices();
```
