### ISSUE TITLE
Uncaught TypeError: _.merge is not a function

### ISSUE THREAD

**Issue by jmls** [clientIO/joint#212]
If I "bower install" jointjs when I fire up the project I get the above error. It turns out that both lodash *and* underscore are being loaded 

![image](https://cloud.githubusercontent.com/assets/929523/12532012/002d1342-c201-11e5-8a26-ca7bd7f73110.png)

If I try and remove underscore, bower moans that it is required by backbone. Which was installed by .. jointjs ...

How do I fix this?

edit: I should mention that I am using wiredep and gulp to build my system

**Comment by chill117** [comment]
I don't see any error message. Can you copy/paste the exact error message you're seeing here?

**Comment by jmls** [comment]
it's all to do with bower, and wiredep. If you bower install backbone, it also installs underscore, which then overrides lodash.

You can override the behaviour by changing the order in bower.json.

mine now looks like this

```
  "dependencies": {
    "angular-animate": "~1.4.2",
    "angular-sanitize": "~1.4.2",
    "angular-messages": "~1.4.2",
    "angular-aria": "~1.4.2",
    "angular-resource": "~1.4.2",
    "angular-ui-router": "~0.2.15",
    "angular-material": ">0.11.0",
    "jquery": "~2.2.0",
    "angular": "~1.4.2",
    "lodash": "3.10.1",
    "backbone": "1.2.3",
    "jointjs": "^0.9.7"
    
  },
```

and it seems to fix the problem

**Comment by chill117** [comment]
Closing this issue because it looks like you solved the problem.
