### ISSUE TITLE
[Bug]: Perfomance problem with seperate graph and paper lifecycles and huge diagrams

### ISSUE THREAD

**Issue by EduardHuck** [clientIO/joint#2243]
### What happened?

Hello,

I am using JointJS in an Angular application and since my latest feature I have observed performance problems with very large diagrams(several hundreds of nodes).

The feature introduced was a new text or list based representation of the diagram. To achieve this I have a toggle button that switches between the two views. Since I still want to keep access to the CommandManager and changes in the list should also take place in the graph, I have separated the graph lifecycle from the paper lifecycle. The paper and its components (minimap, paper scroller, stencil) are destroyed when switching to the list view and recreated when returning to the diagram view, while the graph continues to exist in the background the whole time.

In the initialisation of the paper scroller all tools are rendered, graph listeners are added, all nodes (linebreaks) are formatted and again all cells are rendered (this is necessary because the link-anchors are broken if I return to the diagram-view).

After I changed the code so that the graph continues to exist in the background and is not regenerated every time I enter the page, I observe a strongly worse performance when I later enter the paper. When initially loading the paper, the performance is still ok.

My first suspicion was possibly redundant graph listeners or jointJS internal references that remain when only the paper is destroyed and recreated.

I tried adding destroy methods to the minimap and stencil, which are called on destroy, with no performance improvement.

```
 destroy(component: Element): void {
    component.querySelector('.minimap-container').removeChild(this.minimap.el);
    this.minimap.unmount();
  }
```

I tried removing all graph listeners with no effect.
```
 private removeGraphListeners(): void {
    this.graph.off('change');
    this.graph.off('change:target');
    this.graph.off('remove');
    this.graph.off('add');
  }
```

Even if I disable all my custom rendering, formating and styling logic, the performance issue still persists.

That the performance issues do not happen the first time, but only the subsequent times makes me wonder, what the cause could be.

Under Firefox the performance problem is less severe.

I would really appreciate any hints, ideas or possibilities.

### Version

3.6.3

### What browsers are you seeing the problem on?

Chrome
Firefox

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
Did you try to profile the application performance? Please see https://developer.chrome.com/docs/devtools/performance/.

It's hard to say without seeing the source code. It's possible that new listeners are kept being added, but never removed. The profiles should discover this.

> In the initialisation of the paper scroller all tools are rendered, graph listeners are added, all nodes (linebreaks) are formatted and again all cells are rendered (this is necessary because the link-anchors are broken if I return to the diagram-view).

You need to make sure to render the diagram when the paper is in the live DOM (in the render tree - attached & not hidden).
You can create a `frozen` paper and start rendering the diagram cells with `paper.unfreeze()` when the component were mounted.

**Comment by kumilingus** [comment]
**Important note:** to remove the UI JointJS component, the [remove()](https://backbonejs.org/#View-remove) method must be called. e.g. 
```
paper.remove();
paperScroller.remove();
navigator.remove();
stencil.remove();
```
