### ISSUE TITLE
Paper scroller padding getting applied twice on element view

### ISSUE THREAD

**Issue by abd-almofleh** [clientIO/joint#2280]
### Description
If you use the padding int he paperScroller to give some space between the edge of the paper before resizing this padding will be applied to the elements bbox which mean if you have a padding of 20 any object that has the x = 100 in the model the bbox of the view will be x = 120.
To summarize, the padding on the view is applied twice.

**Expected behavior (without scroller padding):** 
![image](https://github.com/clientIO/joint/assets/118676821/5c5f71ae-51a6-458a-a42f-030f0ab63832)
The green rectangle is the BBox of the view of the main container 

**Current behavior (with scroller padding = 20):**
![image](https://github.com/clientIO/joint/assets/118676821/9b0db649-02b1-48fa-98ee-fb342b62c967)
The main container model has padding 20 from the left and the right, but the BBox of the view has padding of 40 from the top and the left

### Reproduce
Configure paper scroller using the padding option:
```js
const paperScroller = new joint.ui.PaperScroller({
      paper: paper,
      autoResizePaper: true,
      scrollWhileDragging: true,
      cursor: 'grab',
      contentOptions: {
        padding: 20,
        allowNewOrigin: 'any',
      },
    })
```

### Version

3.7.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
Could you please share a code example of how to reproduce this?

What is the green rectangle? The bounding box of the model and the view may vary. The model bounding box does not change at different zoom levels, while the view bounding box does. The view bounding box may be slightly larger because it contains DOM elements that may overlap the model rectangle, such as ports.

**Comment by abd-almofleh** [comment]
For the green model I just got the view bbox form the element using 
```js 
element.getBBox()
```
after that, I just draw a rectangle using [Vectorizer](https://resources.jointjs.com/docs/jointjs/v3.7/vectorizer.htm):
```js
    const elementBBox = element.getBBox()
    const rect = Vectorizer('rect', {
          fill: '#adcd93',
          opacity: 0.1,
          x: elementBBox.x,
          y: elementBBox.y,
          width: elementBBox.width,
          height: elementBBox.height,
          display: 'block',
          stroke: '#525252',
    })
    rect.appendTo(this.paper.viewport)
```

**Comment by kumilingus** [comment]
And that's wrong. The `view.getBBox()` is already transformed (scaled + translated) by the paper's current transformation (`paper.matrix()`).

You can do two things.

1. Append the `rect` directly to `svg` (all transformations are applied to `viewport` - a child `<g/>` of `svg`).
```js
const elementViewBBox= view.getBBox()
const rect = Vectorizer('rect', {
      fill: '#adcd93',
      opacity: 0.1,
      x: elementViewBBox.x,
      y: elementViewBBox.y,
      width: elementViewBBox.width,
      height: elementViewBBox.height,
      display: 'block',
      stroke: '#525252',
})
rect.appendTo(this.paper.svg)
```

2. Use model bounding box or convert the view bounding box to local/graph coordinate system.
```js
const elementViewBBox = this.paper.paperToLocalRect(view.model.getBBox());
// or simply
// const elementViewBBox = view.model.getBBox()
const rect = Vectorizer('rect', {
      fill: '#adcd93',
      opacity: 0.1,
      x: elementViewBBox.x,
      y: elementViewBBox.y,
      width: elementViewBBox.width,
      height: elementViewBBox.height,
      display: 'block',
      stroke: '#525252',
})
rect.appendTo(this.paper.viewport)
```

**Comment by abd-almofleh** [comment]
@kumilingus Thanks for the clarification, it helped.
