### ISSUE TITLE
[Bug]: Cache misses because of wrong assumptions in the ordering of hashmap keys

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2297]
### What happened?

I saw that in `src/dia/attributes/index.mjs`, in the `attributesNS` object, the `set` function of the `text` object is doing some sort of hashing / caching using `JSON.stringify` and passing a string and an object to it (`JSON.stringify([text, textAttrs]);`). The problem with this approach is that hashmap keys don't have a guaranteed order, which means that this code is most probably missing the textHash / cache most often than not.

### Version

3.7.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
Looking at the code, it would be relatively easy to store the text attributes one by one in a variable instead of using the `util.pick` method. I'm just trying to guess how critical this problem is.

**Comment by alexandernst** [comment]
Hey! It's not critical at all. In fact, worst case scenario the cache will be missed and the text will be rerendered. I can't create a demo that will reproduce the bug. It did happened to me a couple of times (in the span of a week), but it's very random.

**Comment by kumilingus** [comment]
Fixed in #2333.
