### ISSUE TITLE
[Bug]: Segments tool is broken with manhattan router

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2300]
### What happened?

Segment tool seems to be broken when used with manhattan (and other?) routers.

Demo: https://codesandbox.io/s/joint-link-manhattan-bug-n3v4z4

Instructions: Just hover the link with the cursor, then click on the segment and try to drag it.

### Version

3.7.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
Duplicate of https://github.com/clientIO/joint/issues/2044.

**Comment by alexandernst** [comment]
Ooh, I see 🤔. Indeed using segments with a manhattan router is a little bit weird. 🙏
