### ISSUE TITLE
[Bug]: Multiple inheritance with custom shapes not working (as expected?)

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2302]
### What happened?

I'm playing with the examples at https://resources.jointjs.com/tutorial/ts-shape and I figured out I'd try to create a `Base` shape that extends from `dia.Link`, which then I'd use to create `MyLink`. It turns out this doesn't work.

I'm not really sure why (maybe it has something to do with the way `defaults` is being called?).

Demo: https://codesandbox.io/s/joint-custom-link-extend-playground-ngs9zn

Note that

```js
class CLink extends CBase {                       // <--- doesn't render the link

class CLink extends joint.shapes.standard.Link {  // <--- renders the link
```

### Version

3.7.5

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
It is the `defaults` :)
- wrong order of `merge` arguments
- `super.default` is a function in `CBase`

```js
class CLink extends CBase {
  defaults() {
    return joint.util.merge(
      {},
      super.defaults(),
      {
        type: "CLink",
        attrs: {
          line: {
            stroke: "#ccc",
            strokeWidth: 2
          }
        }
      },
    );
  }
}
```

**Comment by alexandernst** [comment]
Ooohh! 🤔

Ok, I have another questions. Why `CBase` is merging `super.defaults`, but `CLink` is merging `super.defaults()`? What is the difference between using `super.defaults` as a value and calling `super.defaults()` as a function?

**Comment by kumilingus** [comment]
The [shapes.standard.Link](https://github.com/clientIO/joint/blob/master/src/shapes/standard.mjs#L594-L630) class is defined via the [define](https://github.com/clientIO/joint/blob/master/src/dia/Cell.mjs#L917) method which using the [extend](https://backbonejs.org/#Model-extend) method of _Backbone_. If you create a _`Backbone_ Model` this way (ES5 way), the `defaults` is a property, not a method. Therefore `CBase` needs to access it as a property.

The ES Class `CBase` defines the `defaults` as a method. Therefore `CLink` has to call it as a function.

I recommend reading this [article](https://benmccormick.org/2015/07/06/062222.html) which should explain this in detail. Also reading this [Backbone issue](https://github.com/jashkenas/backbone/issues/3560) might be helpful.

**Comment by alexandernst** [comment]
Oohh, now I get it. Good thing to know :)
Thank you!!

**Comment by alexandernst** [comment]
I have an extra question 🙏

Would it be possible to extend from 2 classes using this method? Lets say that I have `CBaseLinkA` which defines the `stroke` color (using the `defaults()`) and `CBaseLinkB` which defines the `strokeWidth` (also using the `defaults()`) and the `markup` attribute. Would it be possible to do something like

```js
class MyLink extends merge(CBaseLinkA, CBaseLinkB) {
  ...
}
```

**Comment by kumilingus** [comment]
Perhaps you can check this [discussion](https://github.com/clientIO/joint/discussions/2086).
