### ISSUE TITLE
[Docs]: Stencil height inconsistency

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2323]
### What happened?

I have been playing around with the stencil and I found something that might be a bug (or it might be just a wording problem in the docs, which is leading to my confusion).

Docs state the following:

```
# Stencil Configuration

height          the height of the stencil [mandatory]



# Stencil groups

height         [optional] the height of the paper containing the shapes of the group.
If not defined, then the height of the stencil will be used.
If non of these height are defined, the paper will be automatically scaled to fit
its content (recommended).
```

While the first section states that the `height` is mandatory, the second one leads me to believe it is not. In order to find out which one is it I created a small demo. And surely enough, if I create a stencil with one group without specifying the height, I get a stencil as tall as required in order for all the elements to fit (which is what'd expect, good).

![image](https://github.com/clientIO/joint/assets/89727/b954b61f-d467-4e22-bc67-7ee3646e0af2)

However, as soon as I remove the group, the height is set to `800px` (I believe this is the default height, hardcoded in `rappid/plugins/ui/Stencil/Stencil.mjs:79`), instead of being set to whatever value that can fit all the elements.

![image](https://github.com/clientIO/joint/assets/89727/de2a0675-51cc-4b03-9480-75d519523a98)

This behaviour is consistent with the first paragraph from the docs, but it isn't consistent with the second one. IMHO the height should be calculated automatically, but at this point I don't know if this is a bug, a feature request or a "won't fix, works as expected" and I'm just misunderstanding the documentation.

Link to the demo: https://codesandbox.io/s/rappid-stencil-height-bug-l7j2nj?file=/src/index.js

### Version

3.7.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
If the `height` is not defined, it is calculated automatically. The default `height` is indeed set to `800`.

This will calculate the height automatically.
```js
const stencil = new joint.ui.Stencil({
  paper,
  width: 100,
  height: null,
});
```
I think it is the documentation that needs updating.

It's not really mandatory. It has this questionable default. It should be at least clear from the documentation.

The `group` height is only to override the global default on per group basis.

**Comment by kumilingus** [comment]
I agree. Note, that this is something that needs to wait for `v4` as it would be a breaking change.
The docs still needs to be updated as the option is not mandatory.

**Comment by kumilingus** [comment]
The documentation has been updated in `v4`.
