### ISSUE TITLE
[Bug]: Grid layout dx / dy incorrect default values

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2324]
### What happened?

[Grid layout docs](https://resources.jointjs.com/docs/rappid/v3.7/layout.GridLayout.html#layout.GridLayout) state that `dx` and `dy` are set to `0` by default and that they are deprecated, but the actual default values for both attributes are `10`. This can be seen at `rappid/plugins/ui/Stencil/Stencil.mjs:32-33`.

I discovered that while playing around with the Stencil and catching on the fact that the elements are always rendered with a 10px padding on the left. The code that I provided in #2323 can be used as a demo for this bug.

I'm not sure if I should use `dx` and `dy` in my code and set them to `0` (despite the fact that they are deprecated) or if there is another way I can workaround this.

### Version

3.7.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
The `layout.Gridlayout` defaults the `dx` and `dy` values to `0`. The options are deprecated in favor of `marginX`, `marginY`, `rowGap` and `columnGap`.

The `u.Stencil` is calling the `GridLayout` and set the `dx` and `dy` values to `10` if not provided through the `layout` option. This will be removed in the next major (breaking) version.

You should set it explicitly to zeros now and when the `4.0` is out, you can remove it.
```js
  layout: {
    columns: 1,
    rowHeight: "compact",
    rowGap: 10,
    columnWidth: 100,
    marginY: 10,
    // Below only required for versions prior v4.0
    resizeToFit: false,
    dx: 0,
    dy: 0
  }
```

**Comment by alexandernst** [comment]
Oohh, I see. Indeed, it is the Stencil plugin that is passing these values. Thank you!
