### ISSUE TITLE
toSVG, toPNG text color issue

### ISSUE THREAD

**Issue by artificis** [clientIO/joint#234]
I tried `toSVG()` and `toPNG()` methods of format.svg and format.raster, a RappidJS plugin.
Everything looks good except one thing.
I have a label in the link between two cells. It shows properly in grey color on canvas. But after calling `toSVG()` with a new window, it doesn't show up. I inspected the element in the browser and svg element itself (`tspan`) was present. What was missing is its color (`fill` attribute?)

**Comment by kumilingus** [comment]
Does it happen on IE only? It could have something to do with default style attribute values. Setting the text color explicitly should resolve the issue.

```javascript
labels: [{ position: 0.5, attrs: { text: { fill: '#f6f6f6' }}}]
```
