### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ROYopedia** [clientIO/joint#2344]
### What happened?

I am using dagree directed graph algo.
svg tag is properly taking the viewport 
![Screenshot from 2023-09-20 17-57-03](https://github.com/clientIO/joint/assets/22453886/dfb02356-0efd-47b6-8bc8-ac1f1084fa77)
But g tag  inside the svg tag is positioned with extreme left and top value? Why is this happening? 
![Screenshot from 2023-09-20 17-57-14](https://github.com/clientIO/joint/assets/22453886/9a974200-76fe-43d1-a03e-9169f2bf0c61)

All the demos have svg tag  and g tag perfectly alligned.
It is an priority issue for us. Any suggestion or way out?

### Version

3.7

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Linux

**Comment by kumilingus** [comment]
I'm sorry, what exactly are we supposed to be looking at?
What is the problem? The paper does not have to originate at `0x0` for multiple reasons.
What would be the expected result?
How to reproduce it? Providing a code to see the issue always helps.

**Comment by ROYopedia** [comment]
Sorry for the ambiguity. 
SVG tag is positioned from (0,0) in viewport but g tag is positioned way too right. I am not able to figure out what is the root cause of being g tag with classname = "joint-layers" positioned this way instead of (0,0).
Can we force manipulate the position of g tag??
You talked about multiple reason for this. Can you highlight some of them?

It would have been better with a small code demo but I cant share code as it is confidential one.

**Comment by kumilingus** [comment]
What is `graph.getBBox()`? The top left corner of the bounding box is most likely in negative coordinates. So for the paper to display the entire graph, it must change its origin to negative coordinates as well.

But I think you don't like the space around the paper. Not the transformation of the paper (the `transformation` attribute does not change the position of the `<g>` tag within the paper scroller). The space around the paper within the paper scroller is controlled by the `padding` and `borderless` options. I suggest reading the `PaperScroller` [documentation](https://resources.jointjs.com/docs/rappid/v3.7/ui.PaperScroller.html#ui.PaperScroller) first.

**Comment by ROYopedia** [comment]
In this case the graph.getBBox is ->  Rect {x: 55, y: 140, width: 4840, height: 2440}.

Yeah! Space around the paper is not needed. I used padding as well while creating paperscroller. 
const paperScroller = new ui.PaperScroller({
      paper,
     // padding: 0,
      autoResizePaper: true,
      contentOptions: function (paperScroller) {
        var visibleArea = paperScroller.getVisibleArea();
        return {
          padding: {
            bottom: visibleArea.height / 2,
            top: visibleArea.height / 2,
            left: visibleArea.width / 2,
            right: visibleArea.width / 2,
          },
          allowNewOrigin: "any",
        };
      },
      padding: function() {

        var clientSize = this.getClientSize();
        var minVisibleSize = Math.max(this.options.minVisiblePaperSize, 1) || 1;
        var padding:any = {};
    
        padding.left = padding.right = Math.max(clientSize.width - minVisibleSize, 0);
        padding.top = padding.bottom = Math.max(clientSize.height - minVisibleSize, 0);
    
        return padding;
      }
    });
 
 /*
  Example Usage
  padding: 10
  padding: { top: 20, left: 20 }
  padding: function() { return 10; }
*/
  
  But it is the same as I shared in screeshot. Any padding is not affecting the paper.

**Comment by kumilingus** [comment]
Perhaps calling `paperScroller.positionContent('top-left', { padding: 50, useModelGeometry: true })` will do the job?
There are many methods to modify the position of the paper inside the paper scroller (e.g. `scroll()`, `center()`).
