### ISSUE TITLE
Smooth expand and collapse of group of nodes

### ISSUE THREAD

**Issue by botev** [clientIO/joint#236]
By group of nodes I mean when we have some nodes embedded in another, aka inside a larger container. Since when having many nodes(related to #206 ) One of the key for good visualization is to be able to group nodes together. Currently, this is possible via embedding of the nodes in an auxiliary node. However, it would be really great if there is a way to expand/collapse this nodes so that we can clean some of the clutter. This however, require some extra features, as collapsing a group should make new edges, by exchanging the inside nodes with the collapsed group. This can be done via something of the pseudocode: 

```
in_edges = []
out_edges = []
for c in children:
   for e in c.in_edges:
        if(e.target is not in children)
            in_edges.append(e);
   - same for out edges-
   remove(c);
this.addInEdges(in_edges)
this.addOutEdges(out-edges)
```

**Comment by kumilingus** [comment]
Shown in [container](https://github.com/clientIO/joint/tree/master/demo/container) demo.
