### ISSUE TITLE
[Bug]: The direction of the source and target points cannot always run along the center, but will run to the edge

### ISSUE THREAD

**Issue by zhxzhx** [clientIO/joint#2361]
### What happened?

![image](https://github.com/clientIO/joint/assets/15324795/12222637-16ef-49c9-9f5d-aa37edd73f09)

The point is not pointing at the center

![image](https://github.com/clientIO/joint/assets/15324795/d3948e68-0a2a-4bb3-a5d5-6b67cd48d6a6)
Expected results

### Version

Currently running 3.2.0, but upgraded to 3.7.0, the display remains the same

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
It is not clear what configuration we need to reproduce the issue, but my guess would be to stop using the `perpendicular` anchor (use the default `center` anchor instead - please see [docs](https://resources.jointjs.com/docs/jointjs/v3.7/joint.html)).

If you need further help with the issue please create an example that clearly shows the problem and how to reproduce it.

**Comment by zhxzhx** [comment]
谢谢你的邮件……常联系……愿：幸福！！miss you

**Comment by zhxzhx** [comment]
谢谢你的邮件……常联系……愿：幸福！！miss you
