### ISSUE TITLE
[Bug]: RegEx for breakText and textWrap opt.hyphen does not include international characters

### ISSUE THREAD

**Issue by holzmare** [clientIO/joint#2379]
### What happened?

By default breakText and textWrap do not include chraracters from international alphabets leading to strange behaviour when wrapping words containing them. In my opinion the default should include those.

Suggested regex to match them:
`/[^\w\dŽžÀ-ÿ]/`

### Version

3.7.5

### What browsers are you seeing the problem on?

any browser

### What operating system are you seeing the problem on?

any OS

**Comment by kumilingus** [comment]
This might work better `/[^\w\d\u00C0-\u1FFF\u2800-\uFFFD]/` (from [StackOverflow answer](https://stackoverflow.com/a/59828814/2921495)).

The one you provided doesn't work for Czech `ř`, for example.

Note, this should not be a blocker as you can provide a custom `hyphen` to the `textWrap` attribute.
