### ISSUE TITLE
Batch-related API improvements for graph model

### ISSUE THREAD

**Issue by chill117** [clientIO/joint#239]
Currently start/stopping batches of graph changes looks like this:
```js
graph.trigger('batch:start', { batchName: 'some_batch', other: 'info' });
// ..
graph.trigger('batch:stop', { batchName: 'some_batch', other: 'info' });
```

A cleaner looking approach could be:
```js
graph.startBatch('layout', { other: 'info' });
// ..
graph.stopBatch('layout', { other: 'info' });
```
Where..
* the first argument (batch name) is required
* the second argument (batch data) is optional

Under-the-hood, the old way of doing batches (triggering the `batch:start` and `batch:stop` events) could be used. This would be a backwards compatible change.

Also we should add the following method for detecting if there is a batch in progress:
```js
graph.hasActiveBatch([name])
```
Where..
* the `name` argument is optional

**Comment by kumilingus** [comment]
I like that. I would call methods `startBatch()` and `stopBatch()` though (verbs).

**Comment by chill117** [comment]
See [the comment thread on PR #243](https://github.com/clientIO/joint/pull/243) for places that could benefit from these new batch methods.
