### ISSUE TITLE
Missing/hard-to-find docs

### ISSUE THREAD

**Issue by whitelynx** [clientIO/joint#248]
So far, I have been unable to find any documentation of the following files that appear in `joint/dist/`:
- `joint.shapes.chess.js`
- `joint.shapes.devs.js`
- `joint.shapes.erd.js`
- `joint.shapes.fsa.js`
- `joint.shapes.logic.js`
- `joint.shapes.org.js`
- `joint.shapes.pn.js`
- `joint.shapes.uml.js`

There is also no documentation I can find for the shapes in the `joint.shapes.basic` namespace. (which appears to actually be part of `joint.core.js`)

Finally, the `joint.layout.DirectedGraph.js` plugin is included with the `joint` distribution, but its docs appear in the "Rappid API" section of the documentation. (http://jointjs.com/rappid/docs/layout/directedGraph)

**Comment by chill117** [comment]
Thank you for taking the time to put this list together. Re-organizing (and improving) the documentation is definitely on the road map for this year.

**Comment by kumilingus** [comment]
`joint.shapes.basic` will be deprecated soon. Use `joint.shapes.standard` instead.
