### ISSUE TITLE
LinkView tool events does not follow the usual signature.

### ISSUE THREAD

**Issue by B3rn475** [clientIO/joint#251]
The usual signature for events is [source](https://github.com/clientIO/joint/blob/3c737dc051821713565dd3b4a1f4b84a2eca61da/src/joint.dia.cell.js#L707)
`cellView, evt, [, x, y]`
The signature for LinkView tool events is [source](https://github.com/clientIO/joint/blob/3c737dc051821713565dd3b4a1f4b84a2eca61da/src/joint.dia.link.js#L1500)
`targetParentEvent, evt, cellView, x, y`

This does not allow to reuse event listeners.
Should they be normalized?

**Comment by kumilingus** [comment]
Definitely. https://github.com/clientIO/joint/pull/285/files
