### ISSUE TITLE
Magnets are not disabled with interactive = false

### ISSUE THREAD

**Issue by skodape** [clientIO/joint#253]
joint.dia.Paper.interactive = false, does not make the paper really non-interactive .
User can still click on a magnet and draw-add a connection. 

Can https://github.com/skodape/joint/commit/fbe116227a9a925fd1c1a13569ab601d37eda420 be a possible solution?

**Comment by kumilingus** [comment]
Hi Peter,
it's a very good point. I would move [`joint.dia.Link.prototype.can()`](https://github.com/clientIO/joint/blob/master/src/joint.dia.link.js#L1426-L1432) to `joint.dia.Cell` and use it in `joint.dia.Element` as you suggested.
We could also introduce a new feature called e.g. `createLink` just for this case.
```
interactive: { createLink: true, pointerdown: false }
```
That would disables translating but allows link creation.

Best, Roman

**Comment by chill117** [comment]
Fixed.
