### ISSUE TITLE
[Bug]: renderFieldContent Function Not Working as Expected

### ISSUE THREAD

**Issue by peterpeep** [clientIO/joint#2587]
### What happened?

I've been trying to add the custom input field in the Kitchen Sink Demo application. I'm using the trial version. But its not worling as exptedted.

Here's the console error: 

![image](https://github.com/clientIO/joint/assets/63402768/3b01e740-cd5e-4680-bb33-a272837ddc3c)

Here's the code snippet:

![image](https://github.com/clientIO/joint/assets/63402768/d5c3d3e8-d9f3-4a8e-9c50-f0bc1b506919)

### Version

v4.0.0 - 02-02-2024

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Safari on iOS, Android (State browser in description)

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
That's a bug. We'll release a patch soon. Sorry for the inconvenience.

**Comment by zbynekstara** [comment]
Hi @peterpeep, the fix is available now as part of JointJS+ v4.0.1.
