### ISSUE TITLE
Unable to get Selectors to animate my Customized Link

### ISSUE THREAD

**Issue by samiulla1111** [clientIO/joint#2620]
### What happened?

I took help from this demo for creating my customized link:(https://codepen.io/jointjs/pen/oNQpZJV/094b9fea7c7248d1e29a12ffa5b37f55)

In Joint js version 3.7 with the help of this function **const [liquidEl] = this.findBySelector("liquid");** able to get the selector.
But in Joint js 4.0 **this.findBySelector("liquid");** This function is giving me an undefined value due to that I am not able to animate my customized link.

Can you please provide any alternate solution to get selectors in Joint js 4.0?

Thank you
Shaik Samiulla

### Version

v4.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Safari on iOS

### What operating system are you seeing the problem on?

Windows, Mac, Linux

**Comment by kumilingus** [comment]
The `findBySelector()` has been changed to a private method in `v4`. Use `findNode()` / `findNodes()` instead.

For all the breaking changes, please see the migration guide [here](https://changelog.jointjs.com/plus/4.0.0/changelog).

**Comment by samiulla1111** [comment]
Thank you it is working.
