### ISSUE TITLE
How to make that line is always perpendicular to the element?

### ISSUE THREAD

**Issue by pipanchik** [clientIO/joint#266]
Without add new points (I'm using the default routing and html elements)
<img width="358" alt="bad" src="https://cloud.githubusercontent.com/assets/5269409/13426463/92ab6dce-dfbe-11e5-93d5-24df046259eb.png">
<img width="352" alt="good" src="https://cloud.githubusercontent.com/assets/5269409/13426462/9283d8d6-dfbe-11e5-8185-fe4074402c8d.png">

**Comment by kumilingus** [comment]
You might want to use the `oneSide` router. 

```javascript
new joint.dia.Link({ router: { name: 'oneSide', args: { side: 'right' } }});
```
