### ISSUE TITLE
[Bug]: Link anchor not working correctly for custom shape

### ISSUE THREAD

**Issue by ArthurWietzorek** [clientIO/joint#2706]
### Current versus expected behaviour

We are using custom shape definitions in a custom shape namespace in our JointJS Plus application, but some of them display unusual behaviour in regards to anchor placement of links. The links to and from elements of those shape are always anchored on the top left corner, despite us using the default connection strategy.

![image](https://github.com/clientIO/joint/assets/41048767/2dff7e21-7ffa-4b59-a174-5b16c6250af9)

The most confusing thing about this problem, however, is that it is resolved by recreating the graph with `graph.fromJSON(graph.toJSON())` and that the attributes of the element are exactly the same before and after this step.

![image](https://github.com/clientIO/joint/assets/41048767/c18ac62c-9083-4de4-bd6a-a4774449b820)

### Steps to reproduce

Our custom shape definition has the following defaults:

```
  defaults(): mvc.ObjectHash {
    return util.defaultsDeep(
      {
        type: ShapeTypesStartEnd.START,
        markup: [
          {
            tagName: 'rect',
            selector: 'body'
          },
          {
            tagName: 'image',
            selector: 'icon'
          }
        ],
        attrs: {
          icon: {
            href: 'assets/svgs/Start.svg',
            refWidth: '100%',
            refHeight: '100%'
          },
          body: {
            fill: 'white',
            refWidth: '100%',
            refHeight: '100%'
          }
        },
        size: {
          width: 30,
          height: 30
        }
      },
      dia.Element.prototype.defaults
    );
  }
```

For comparison, the other element seen in the screenshots (the blue one), that does not display the problem, has defaults like this:

```
  defaults(): mvc.ObjectHash {
    return util.defaultsDeep(
      {
        type: config.type,
        markup: [
          {
            tagName: 'rect',
            selector: 'body'
          },
          {
            tagName: 'image',
            selector: 'icon'
          },
          {
            tagName: 'text',
            selector: 'label'
          }
        ],
        attrs: {
          icon: {
            href: 'assets/svgs/Question.svg',
            width: 24,
            height: 24,
            x: 5,
            refY: 0.5,
            refY2: -12
          },
          body: {
            refWidth: '100%',
            refHeight: '100%',
            fill: '#0099d4',
            rx: 5,
            ry: 5
          },
          label: {
            fontFamily: 'Roboto',
            fontWeight: 400,
            fontSize: 16,
            fill: '#FFFFFF',
            textVerticalAnchor: 'middle',
            x: 36,
            refY: '50%',
            lineHeight: 18
          }
        },
        size: {
          width: 210,
          height: 30
        }
      },
      dia.Element.prototype.defaults);
  }
```

The paper option `connectionStrategy` is not set, therefore the defaults should be used.

I am still working on reproducing the issue in the kitchensink application and will follow up on that. Until then i'm hoping that you could maybe help me with identifying the cause for this problem with just the given information already?

### Version

4.0.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
Is it related to this https://github.com/clientIO/joint/issues/1264?
ie. the paper element is not in the DOM ([render-tree](https://developer.mozilla.org/en-US/docs/Web/Performance/Critical_rendering_path#render_tree)) at the time of rendering?

**Comment by ArthurWietzorek** [comment]
Thank you very much for the quick response! Yes, it seems to be the same kind of problem. 

Setting the paper option `frozen: true` upon initial creation and unfreezing it on `paper.once('render:done', ...)` solved the issue!
