### ISSUE TITLE
[Bug]: Highlighter path miscalculation with ports (only in Safari)

### ISSUE THREAD

**Issue by alexandernst** [clientIO/joint#2708]
### Current versus expected behaviour

I have a shape with a port attached to its lower **left** corner. If I apply a highlighter stroke to the view of the shape, the path of the shape wrongly takes into account *something* (padding? stroke width? I'm not sure) related to the port. This issue happens only in Safari (tested on Chrome, Safari and FF).

Safari: 

![image](https://github.com/user-attachments/assets/31ab56d0-5a2a-4bbb-ac61-13b0e4d4f032)

Chrome:

![image](https://github.com/user-attachments/assets/d7490b7b-f3d6-433e-b52c-1a2486dfcf7f)

Whats even weirder is that if I move the port to the **right**, the bug doesn't occur:

Safari: 

![image](https://github.com/user-attachments/assets/974c8bb1-39fd-4469-a5f3-c4d44f2575bf)

### Steps to reproduce

1. Open with Safari https://codesandbox.io/p/sandbox/jj4-highlighter-miscalculation-path-bug-tpy5l6
2. Observe the bug

### Version

4.0.4

### What browsers are you seeing the problem on?

Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
The port `<text/>` element has impact on the `root` `<g/>` bounding box in Safari.

Here's how to overcome the issue:

1. Draw the *stroke* around the `body` (`<rect/>`) instead.
```ts
highlighters.stroke.add(cellView, "body", "my-highlighter-id", {});
```

2. Set port text to an empty string (this will set `display: none` on the port `<text/>` element)

```ts
ports: {
    items: [
        {
            group: 'foo',
            attrs: {
                text: {
                    text: '',
                },
            },
        },
    ]
}
```

3. Set display none on empty text in CSS
```css
text:empty { display: none;}
```

**Comment by alexandernst** [comment]
Hi Roman! That fixed it, indeed. Thank you so much! 🙏
