### ISSUE TITLE
Unable to display tooltip when toggle fullscreen

### ISSUE THREAD

**Issue by LeleDallas** [clientIO/joint#2725]
### Current versus expected behaviour

Hello👋!

In **joint plus** I create a fullscreen toggler button. In fullscreen mode I notice that all **Tooltips** are under the canvas even if I set a higher z-index.

How can I solve it?

### Steps to reproduce

1. Create some element with tooltip
2. Create a fullscreen toggler button that call on click the function `util.toggleFullScreen()`
3. Click the Button 
4. Tooltip are not show on hover elements

### Version

^4.0.4+

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
Which element have you set to full screen?
You may need to set the Tooltip [`container`](https://docs.jointjs.com/api/ui/Tooltip#container) option to the element that is the element (or its descendants) that was displayed full screen.

**Comment by LeleDallas** [comment]
Right now I'm expanding the _ref_ element:
```tsx
<div ref={ref}>
   {defaultMapControls(logicMap, ref)}
   {<div className="canvas map-container" ref={canvas} style={{ marginTop: '1rem', height: '68vh', overflow: 'auto' }} />}
</div>
```

Inside _defaultMapControls_  I have the toggle button.

Tooltips are set correctly and visible in default view, as you can see here in these screenshot
![image](https://github.com/user-attachments/assets/50a23466-cc65-4d34-9208-9d16c477ddc3)

![image](https://github.com/user-attachments/assets/8686fb04-cde0-471c-9f15-f2d7d3dc65f5)


In fullscreen from inspector I have this view:
![image](https://github.com/user-attachments/assets/75729c68-bfc2-4a51-abc4-7823e408c6df)

I think the #top-layer is above all other elements...

**Comment by kumilingus** [comment]
Sorry, did you use the `container` option or not? You can set the `container` to be the `ref` element.

**Comment by LeleDallas** [comment]
What do you mean? My container is the parent `div` with the ref property

**Comment by kumilingus** [comment]
> You may need to set the Tooltip [container](https://docs.jointjs.com/api/ui/Tooltip#container) option to the element that is the element (or its descendants) that was displayed full screen.

When creating a tooltip, you need to pass the `container` option to tell the tooltip to append to the `ref` element instead of the `body`.

```ts
new ui.Tooltip({
   /* .. */
   container: canvas.nativeElement // your container ref element
})
```

**Comment by LeleDallas** [comment]
> > You may need to set the Tooltip [container](https://docs.jointjs.com/api/ui/Tooltip#container) option to the element that is the element (or its descendants) that was displayed full screen.
> 
> When creating a tooltip, you need to pass the `container` option to tell the tooltip to append to the `ref` element instead of the `body`.
> 
> ```ts
> new ui.Tooltip({
>    /* .. */
>    container: canvas.nativeElement // your container ref element
> })
> ```

Yeah I did this for my icons components and as you can see it works but when I'm in fullscreen mode as I said all tooltip are under the fullscreen element

**Comment by kumilingus** [comment]
Could you please share the code on how you instantiated the tooltip?

What is an icon component?

**Comment by LeleDallas** [comment]
```tsx
const tooltipGenerator: ui.Tooltip[] = [];

const createTooltipGenerator = useCallback(() => new ui.Tooltip(tooltipDefaultOptions), []);


paper 
.on('blank:mouseover', () => tooltipGenerator.length == 0 && tooltipGenerator.push(createTooltipGenerator()))
.on('cell:mouseover', (cellView) => { if (tooltipGenerator.length == 0) { tooltipGenerator.push(createTooltipGenerator()); } if (cellView.model instanceof shapes.standard.Link) { const cellTooltip = document.querySelector('.joint-tooltip.joint-theme-material') ?? undefined; if (cellTooltip) { const cellTooltipStyle = cellTooltip.getAttribute('style') ?? undefined; const leftProperty = _.find(cellTooltipStyle?.split(';'), (prop) => prop.trim().startsWith('left:'))?.trim(); const leftValue = _.first(leftProperty?.match(/\d+\.*\d*/g)); if (cellTooltipStyle && leftProperty && leftValue) { 
const newTooltipPosition = cellTooltipStyle.replace(leftProperty, `left: ${Number(Number(leftValue) - Math.abs(cellView.sourcePoint.x - cellView.targetPoint.x) / 2).toFixed(3)}px`); cellTooltip.setAttribute('style', newTooltipPosition); } } } })
```

**Comment by LeleDallas** [comment]
```tsx
const tooltipGenerator: ui.Tooltip[] = [];

const createTooltipGenerator = useCallback(() => new ui.Tooltip(tooltipDefaultOptions), []);


paper 
.on('blank:mouseover', () => tooltipGenerator.length == 0 && tooltipGenerator.push(createTooltipGenerator()))
.on('cell:mouseover', (cellView) => { if (tooltipGenerator.length == 0) { tooltipGenerator.push(createTooltipGenerator()); } if (cellView.model instanceof shapes.standard.Link) { const cellTooltip = document.querySelector('.joint-tooltip.joint-theme-material') ?? undefined; if (cellTooltip) { const cellTooltipStyle = cellTooltip.getAttribute('style') ?? undefined; 

const leftProperty = _.find(cellTooltipStyle?.split(';'), (prop) => prop.trim().startsWith('left:'))?.trim(); const leftValue = _.first(leftProperty?.match(/\d+\.*\d*/g)); if (cellTooltipStyle && leftProperty && leftValue) { 
const newTooltipPosition = cellTooltipStyle.replace(leftProperty, `left: ${Number(Number(leftValue) - Math.abs(cellView.sourcePoint.x - cellView.targetPoint.x) / 2).toFixed(3)}px`); cellTooltip.setAttribute('style', newTooltipPosition); } } } })
```

**Comment by kumilingus** [comment]
What is `tooltipDefaultOptions`?

**Comment by LeleDallas** [comment]
> What is `tooltipDefaultOptions`?

Look above, it's in the file now

**Comment by kumilingus** [comment]
You need to add the `container` option here.
```ts
const tooltipDefaultOptions = { 
  target: '[data-tooltip]', 
  position: ui.Tooltip.TooltipPosition.Left,
  direction: ui.Tooltip.TooltipArrowPosition.Auto,
  padding: 12,
  theme: 'material' ,
  container: ref.current
};
```

**Comment by LeleDallas** [comment]
> You need to add the `container` option here.
> ```ts
> const tooltipDefaultOptions = { 
>   target: '[data-tooltip]', 
>   position: ui.Tooltip.TooltipPosition.Left,
>   direction: ui.Tooltip.TooltipArrowPosition.Auto,
>   padding: 12,
>   theme: 'material' ,
>   container: ref.current
> };
> ```

Fix it!🎉🎉🎉
Thank you very much for your help! 
I appreciate it!
