### ISSUE TITLE
[Bug]: StrokeDasharray applied to link's arrows on Safari only

### ISSUE THREAD

**Issue by OleksandrOleksyuk** [clientIO/joint#2759]
### Current versus expected behaviour

We have found an issue with the strokeDasharray attribute of our link, we cannot replicate the same issue in your demos, as the arrows are not visible. When we set this attribute, the arrows associated with the link also inherit the style. This strange behavior seems to occur only on Safari.
The current version is 4.0.1 but the issue existed with version 3.7.

Attachments:
https://github.com/user-attachments/assets/f6cfd13b-66bf-4d3c-944c-cce8fc316b56

If you need more information or a reproducible demo, let us know and we will be happy to provide it.

### Steps to reproduce

1. Set the value of strokeDasharray on a link.
2. Note that the arrows inherit the strokeDasharray style on Safari.

### Version

4.0.1

### What browsers are you seeing the problem on?

Safari

### What operating system are you seeing the problem on?

Mac

**Comment by kumilingus** [comment]
Does setting the `stroke-dasharray` to `none` explicitly on the marker help?

```ts
// link is a `standard.Link`
link.attr('line/targetMarker', {  type: 'path',  d: 'M 10 -5 0 0 10 5 z', strokeDasharray: 'none' });
```

**Comment by OleksandrOleksyuk** [comment]
Thanks, but I had already tried this solution. It doesn't seem to work. 

I'll put the screen below for you
![screenshot_2024-09-20_alle_12 42 45_720](https://github.com/user-attachments/assets/e3cd218d-6570-48c3-8ff9-c9ae7620b23e)

**Comment by kumilingus** [comment]
This seems to work:
```js
{ strokeDasharray: "1,0" }
```
Live example: https://jsfiddle.net/shot49cu/

This is yet another bug that needs to be reported to the Safari team (I'll see if this has already been reported, and if not, I'll submit a ticket.)

**Comment by OleksandrOleksyuk** [comment]
Thanks, I just tried it and it works fine
