### ISSUE TITLE
[Bug]: Does jointjs not allow to select pinned links on startSelecting event

### ISSUE THREAD

**Issue by Naveena1321** [clientIO/joint#2774]
### Current versus expected behaviour

On clicking shift and dragging the pointer after click on blank paper

### Steps to reproduce

1. Call startSelecting event
2. Observe 
3. It did not select links 

### Version

4.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by kumilingus** [comment]
This is not a bug. It works as designed.

If you need to select links within a region, you can look at this example: https://jsfiddle.net/kumilingus/bs54Ldvm/.

There will be built-in support for this in an upcoming release (November).
