### ISSUE TITLE
[Bug]: System is not defined on upgrading to V4.0.4

### ISSUE THREAD

**Issue by Sureshc32** [clientIO/joint#2780]
### Current versus expected behaviour

Hi Team, I am upgrading Joint js to 4.0.4 and got an issue with app.js file which was created during building the project. 
![image](https://github.com/user-attachments/assets/0d14b338-6f99-45a0-8fa4-8784f6cb079e)

Angular version - 9
@zbynekstara Can you please check this?

### Steps to reproduce

upgrade to 4.0.4
execute npm run build.
app.js file will be generated
Perform actions that leads us to get this issue..

### Version

4.0.4

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
It says that `System` is not defined. It does not look like this is related to JointJS at all.

Please feel free to provide a CodeSandbox showing the issue (before/after upgrade).
