### ISSUE TITLE
find rendering geometry off-screen?

### ISSUE THREAD

**Issue by mark-hahn** [clientIO/joint#279]
I would like to render a graph off screen and then measure things like total link lengths etc.  This is part of an attempt to develop a simple evolution-based layout that tries different element positions and evaluate some criteria such as total link length mentioned above.

I haven't tried anything yet.  I was hoping someone would suggest a way to do this.  Would just putting a paper in a display:none element suffice or is there a way to avoid the DOM for speed?

**Comment by chill117** [comment]
Currently the DOM is unavoidable (especially when using links). I suggest appending your paper DOM element to the body with the following CSS:
```css
.your-offscreen-paper {
  position: absolute;
  left: -99999em;
  top: 0;
}
```
Setting `display: none` on the paper element doesn't work because then the dimensions of the graph elements/links are not calculated correctly.

**Comment by kumilingus** [comment]
See #407.
