### ISSUE TITLE
[Bug]: Not able to integrate with angular

### ISSUE THREAD

**Issue by darkmnpbox** [clientIO/joint#2819]
### Current versus expected behaviour

it should load without the console error.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8dd46421-c66c-4638-b565-2258272f3ad1)

the error is getting from CellView.mjs
![image](https://github.com/user-attachments/assets/3f1dc96f-4f62-4c86-a121-c5ac519fc83a)
when I put debugger the SVGElement is null.
I don't know what I'm doing wrong here.

These is my code
![image](https://github.com/user-attachments/assets/b6090e46-8619-4c9b-9304-9364c3149898)
![image](https://github.com/user-attachments/assets/6f32e30c-2d6c-4c2f-95f1-b35fd3db3030)

HTML
![image](https://github.com/user-attachments/assets/974bf3f6-03b0-4718-b643-dd62c349728d)

 package.json
![image](https://github.com/user-attachments/assets/f720d423-de7c-4b8a-a5c7-3b82d3602c2d)

tsconfig.josn
![image](https://github.com/user-attachments/assets/8dfd89de-4ec3-4b45-a77d-0dbf7715634f)

### Version

4.0.1

### What browsers are you seeing the problem on?

Chrome

### What operating system are you seeing the problem on?

Windows

**Comment by kumilingus** [comment]
You need to use the `joint-plus.tgz` downloaded from the customer portal.

**Comment by darkmnpbox** [comment]
I'm already using that.
![image](https://github.com/user-attachments/assets/ec68b54b-e1f9-4ba0-9f62-b328ae0d1d73)
![image](https://github.com/user-attachments/assets/5605220c-0078-4e74-b685-7111c7a8ceb1)

**Comment by kumilingus** [comment]
Can you try to delete `node_modules`, `package-lock.json` and re-install again?

**Comment by darkmnpbox** [comment]
I did try delete the node_module files. but the problem still exist.

**Comment by darkmnpbox** [comment]
![image](https://github.com/user-attachments/assets/f421cdfb-a39c-4cfa-b643-b47fb073073e)
I forgot to add "@joint/layout-directed-graph": "4.0.3" to the package.json before. but still problem exist.

**Comment by kumilingus** [comment]
Could you please send the `joint-plus.tgz` file for inspection (to `support[at]jointjs.com`)?

**Comment by darkmnpbox** [comment]
I'm not able to attach .tgz file in gmail. so I forwarded the email.

**Comment by darkmnpbox** [comment]
I used the .tgz file from the getting started joint-plus_trial and it is working fine now.
Thanks for the help.
