### ISSUE TITLE
Pipes demo broken

### ISSUE THREAD

**Issue by dwonisch** [clientIO/joint#282]
Seems like the [Pipes demo](http://jointjs.com/js/blog/pipes.js) is not working with v0.9.6, tried to implement my first LinkView and got an error because el.ToLowerCase() was applied on an anonymous function.

Downgraded my reference to v0.9.3 and it works like in the example.

**Comment by chill117** [comment]
There is a problem in the pipes demo when using a newer version of lodash. Specifically with the following line:
```js
            this.pattern = V(_.template(this.patternMarkup, { id: this.id }));
```

The correct usage (with newer versions of lodash) is this:
```js
            this.pattern = V(_.template(this.patternMarkup)({ id: this.id }));
````

Changing that line only will allow your implementation to work as well.

**Comment by chill117** [comment]
I updated the demo code so that it will work for newer versions of Lodash.
