### ISSUE TITLE
[Bug]: `new dia.Paper()` throws `Cannot read properties of undefined (reading 'apply')`

### ISSUE THREAD

**Issue by SimonSimCity** [clientIO/joint#2824]
### Current versus expected behaviour

I'm trying to write some vite-tests for my jointjs component in react and am getting the following error and stacktrace:

TypeError: Cannot read properties of undefined (reading 'apply')
 ❯ setNodesClass node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/Dom/methods.mjs:191:29
 ❯ Dom.removeClass node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/Dom/methods.mjs:196:5
 ❯ child._ensureElClassName node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/View.mjs:137:22
 ❯ child._ensureElement node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/View.mjs:98:14
 ❯ child.ViewBase node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/ViewBase.mjs:30:10
 ❯ child.constructor node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/View.mjs:31:18
 ❯ new child node_modules/.pnpm/@joint+core@4.0.1/node_modules/@joint/core/src/mvc/mvcUtils.mjs:27:43

I cannot really explain why this error happens, because as of what I see and observe, the function
https://github.com/clientIO/joint/blob/eaa478a7b512dbae1ddaae947d9d14ac3a4cbab4/packages/joint-core/src/mvc/Dom/methods.mjs#L188-L193
is called with the first parameter being set to `removeClass`, which should be provided in `V.prototype` - see:
https://github.com/clientIO/joint/blob/eaa478a7b512dbae1ddaae947d9d14ac3a4cbab4/packages/joint-core/src/V/index.mjs#L112
https://github.com/clientIO/joint/blob/eaa478a7b512dbae1ddaae947d9d14ac3a4cbab4/packages/joint-core/src/V/index.mjs#L1051-L1054

### Steps to reproduce

1. Set up vitest.
2. Use `jsdom` to set up a browser-like environment.
3. Try to create an instance of a paper.

Result: https://stackblitz.com/edit/vitest-dev-vitest-5h1ojd?file=src%2Fbasic.ts

### Version

4.0.1 - 4.1.1

**Comment by kumilingus** [comment]
This is not a bug. It's a lack of SVG support in JSDOM.

You need to mock the SVG API in your tests, for example:

```ts
// setupTests.ts

import { vi } from 'vitest';

// Mock method which is not implemented in JSDOM

global.SVGPathElement = vi.fn();

global.ResizeObserver = vi.fn().mockImplementation(() => ({
    observe: vi.fn(),
    unobserve: vi.fn(),
    disconnect: vi.fn(),
}));

Object.defineProperty(global, 'SVGAngle', {
    writable: true,
    value: vi.fn().mockImplementation(() => ({
        new: vi.fn(),
        prototype: vi.fn(),
        SVG_ANGLETYPE_UNKNOWN: 0,
        SVG_ANGLETYPE_UNSPECIFIED: 1,
        SVG_ANGLETYPE_DEG: 2,
        SVG_ANGLETYPE_RAD: 3,
        SVG_ANGLETYPE_GRAD: 4
    }))
});

const SVGMatrix = ({
    a: 0,
    b: 0,
    c: 0,
    d: 0,
    e: 0,
    f: 0,
    flipX: vi.fn().mockImplementation(() => SVGMatrix),
    flipY: vi.fn().mockImplementation(() => SVGMatrix),
    inverse: vi.fn().mockImplementation(() => SVGMatrix),
    multiply: vi.fn().mockImplementation(() => SVGMatrix),
    rotate: vi.fn().mockImplementation(() => SVGMatrix),
    rotateFromVector: vi.fn().mockImplementation(() => SVGMatrix),
    scale: vi.fn().mockImplementation(() => SVGMatrix),
    scaleNonUniform: vi.fn().mockImplementation(() => SVGMatrix),
    skewX: vi.fn().mockImplementation(() => SVGMatrix),
    skewY: vi.fn().mockImplementation(() => SVGMatrix),
    translate: vi.fn().mockImplementation(() => SVGMatrix),
});

Object.defineProperty(global.SVGSVGElement.prototype, 'createSVGMatrix', {
    writable: true,
    value: vi.fn().mockImplementation(() => SVGMatrix),
});

Object.defineProperty(global.SVGSVGElement.prototype, 'createSVGPoint', {
    writable: true,
    value: vi.fn().mockImplementation(() => ({
        x: 0,
        y: 0,
        matrixTransform: vi.fn().mockImplementation(() => ({
            x: 0,
            y: 0,
        })),
    })),
});

Object.defineProperty(global.SVGSVGElement.prototype, 'createSVGTransform', {
    writable: true,
    value: vi.fn().mockImplementation(() => ({
        angle: 0,
        matrix: {
            a: 1,
            b: 0,
            c: 0,
            d: 1,
            e: 0,
            f: 0,
            multiply: vi.fn(),
        },
        setMatrix: vi.fn(),
        setTranslate: vi.fn(),
    })),
});
```

```ts
// vite.config.ts

export default defineConfig({
  /* ... */
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: './setupTest.ts'
  },
})
```

**Comment by SimonSimCity** [comment]
@kumilingus thanks for the quick answer - I was almost about to answer it for myself yesterday - here now with a feedback on what I got so far. 

At the moment I mentioned `vitest` in the message above, I stopped and started a new research based on the fact that there might be additional things to remember when using jsdom with jointjs - and there it was. 

Issues like #1475 and #520 pointed at https://github.com/clientIO/joint-plus-tutorial-react/pull/3, which also for me gave part of the solution to the problem.

The solution you propose here is in some small (but maybe quite important) details different from the example provided at: https://github.com/clientIO/joint-plus-tutorial-react/blob/main/src/setupTests.ts

1. You changed the return value of the methods on the mock returned by `createSVGMatrix()`, which is correct, according to the docs. Thanks!
2. You've added `global.SVGAngle`, which isn't mentioned in the gist - doesn't seem missing as of now, but doesn't hurt either, I guess.
3. You added a mock for `ResizeObserver`, which was reported missing for me as well.

I am now just facing one problem: When I add the mocks as you proposed, the tests are taking way too long and in the end I get a `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`. Seems like there's a memory leak somewhere.

**Comment by kumilingus** [comment]
Is the issue reproducible in the [react tutorial example](https://github.com/clientIO/joint-plus-tutorial-react) if we update the `setupTests.ts`?

---

> You changed the return value of the methods on the mock returned by createSVGMatrix(), which is correct, according to the docs. Thanks!

The `setupTests.ts` in `joint-plus-tutorial-react` is yet to be updated.

> I could confirm that the component is constantly re-rendering, and the useEffect hook is called every time. 

I asume it constantly re-renders only in the test environment, correct?

> You've added global.SVGAngle, which isn't mentioned in the gist - doesn't seem missing as of now, but doesn't hurt either, I guess.

This is how we determine whether SVG is supported or not: https://github.com/clientIO/joint/blob/master/packages/joint-core/src/V/index.mjs#L11

---

I believe it would be a good idea to create a new package, such as `vite-plugin-joint-svg-mock`, that we can maintain and test against the latest `@joint/plus`. Considering the popularity of `vite`, this package could provide the necessary SVG mocking functionality.



.

**Comment by SimonSimCity** [comment]
@kumilingus Thanks for the rapid response again!

> I asume it constantly re-renders only in the test environment, correct?

Correct.

> Is the issue reproducible in the [react tutorial example](https://github.com/clientIO/joint-plus-tutorial-react) if we update the `setupTests.ts`?

I just discovered that I have to get used to react. The reason I had an endless rendering, was because one of the props on my component had a default value of an object, which `onEffect()` was depending on. This object (of course) is different on every render, if not provided.

When using this component, I provided a value, which meant it was the same on every render:
```tsx
export const MyObject = ({
  myFancyThing = { test: 1 }, // Never set an object here as default! It will be a different object every time this element is rendered!
}: {
  myFancyThing?: { test: number };
}) => {
  useEffect(() => {
    // [...]
  }, [myFancyThing]); // This will always run, because the dependency is always a different object!

  return (
    <...>
  );
};
```

I just have to get used to it... Thanks! So, to get jointjs to work with vitest, one only needs to add the mocks you provided. Maybe in the future, jsdom will also fix some of the issues I mentioned, which would reduce the amount of mocks needed.
