### ISSUE TITLE
Explain relationship between Backbone.js and JointJS in docs

### ISSUE THREAD

**Issue by christopherbauer** [clientIO/joint#283]
Hello JointJS!

This may not be an error rather an action that I was not aware of needed to be taken.

In IE if the container element is removed via jquery the pointerup event is not removed from the events and you have to call paper.remove() manually to clear it up. Caused a bit of a problem in our app because if pointerup is not removed it intercepts all click events and stops propagation at some point down the call chain, so the application just stops working!

**Comment by chill117** [comment]
Hi!

> In IE if the container element is removed via jquery

Which DOM element did you remove exactly?

> .. the pointerup event is not removed from the events and you have to call paper.remove() manually to clear it up

JointJS is built on [Backbone](http://backbonejs.org/), so it expects that you will use the `view.remove()` method to remove a view's DOM element(s). This allows it to automatically unbind all related events for you.

I think the solution here would be to add to the documentation some high-level explanation about the relationship between JointJS and Backbone.

**Comment by christopherbauer** [comment]
>Which DOM element did you remove exactly?

I dynamically loaded the graph on to a popup div on the page, then removed the popup div. The behavior was confusing because Edge, Chrome, and FF all disposed of the events automatically but IE did not.

I agree that perhaps users may not know about the use of backbone or may not be familiar enough with it that they know to call remove without some direct attention being drawn to it.

**Comment by chill117** [comment]
I am closing this issue now because the [JointJS docs](http://jointjs.com/api) do currently explain some of the necessary information about how Backbone.js is used.
