### ISSUE TITLE
Nodes can be dragged with any mouse button

### ISSUE THREAD

**Issue by AsherGlick** [clientIO/joint#296]
Each node can be dragged around with any mouse button not just the left button. I have written a quick patch to prevent this but if it is an intended feature what would be the preferred way to expose this as an option to the user?

**Comment by kumilingus** [comment]
Hi Asher,

you can prevent this by using `guard` paper option. For instance:

```javascript
var paper = new joint.dia.Paper({
    el: $('#paper'),
    width: 650,
    height: 400,
    model: graph,
    guard: function(evt) {
        // guard the event when the second (usually right) button is pressed.
        return evt.button === 2;
    }
});
```

**Comment by AsherGlick** [comment]
The guard attribute works perfectly. I used the following code to limit dragging to only the left mouse button
``` javascript
	guard : function(evt){
		// guard the event when the second (usually right) button is pressed
		evt = evt || window.event;
		if ("buttons" in evt) {
			return evt.buttons !== 1;
		}
		var button = evt.which || evt.button;
		return button !== 1;
	},
```
