### ISSUE TITLE
Text Input selection is being prevented

### ISSUE THREAD

**Issue by AsherGlick** [clientIO/joint#297]
The `preventDefault();` call on pointermove inside of `joint.dia.paper.js` removes the ability to select text via click and drag from any text inputs or textareas that are in a node. 

    ...
    pointermove: function(evt) {
      evt.preventDefault();
    ...
Unlike the pointerdown function above it this does not have a workaround via css `pointer-events`  
Can this line be removed or is there a workaround to allow for text selection within text inputs and textareas?

**Comment by kumilingus** [comment]
Hi Asher,

I think the event default preventing should happen only when there was a preceding `pointerdown` event, that was not guarded. i.e.

```javascript
    pointermove: function(evt) {
        if (this.sourceView) {
            evt.preventDefault();
            evt = joint.util.normalizeEvent(evt);
            // Mouse moved counter.
            this._mousemoved++;
            var localPoint = this.snapToGrid({ x: evt.clientX, y: evt.clientY });
            this.sourceView.pointermove(evt, localPoint.x, localPoint.y);
        }
    },
```javascript

Would that solve your problem? Please note that it might be also necessary to override `user-select` CSS rule on the viewport.

Best,
Roman

**Comment by AsherGlick** [comment]
I made this change locally and text selection works
