### ISSUE TITLE
[QUESTION] Let joint decide where to render elements ?

### ISSUE THREAD

**Issue by quentin-sommer** [clientIO/joint#330]
Hi,

I am wondering if it is possible de let join arrange the elements of the diagram automatically, to visualize the diagram, like in this demo for example: http://www.jointjs.com/demos/javascript-ast or if I have to compute the x and y location of every shape myself ?

Thanks in advance!

**Comment by vtalas** [comment]
Hi, 

you don't have to compute anything `joint.layout.DirectedGraph.layout(graph, opt)` is what you need. For more info visit (http://jointjs.com/rappid/docs/layout/directedGraph)

Vladimir

**Comment by quentin-sommer** [comment]
Thanks!
