### ISSUE TITLE
0.9.9 broken

### ISSUE THREAD

**Issue by dddomin3** [clientIO/joint#333]
ERROR in ./~/jointjs/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/jointjs
 @ ./~/jointjs/index.js 3:9-22

ERROR in ./~/jointjs/Gruntfile.js
Module not found: Error: Cannot resolve module 'cheerio' in /home/USERNAME/projects/my_project/node_modules/jointjs
 @ ./~/jointjs/Gruntfile.js 5:18-36

ERROR in ./~/jointjs/Gruntfile.js
Module not found: Error: Cannot resolve module 'prismjs' in /home/USERNAME/projects/my_project/node_modules/jointjs
 @ ./~/jointjs/Gruntfile.js 7:16-34

ERROR in ./~/jointjs/Gruntfile.js
Module not found: Error: Cannot resolve module 'time-grunt' in /home/USERNAME/projects/my_project/node_modules/jointjs
 @ ./~/jointjs/Gruntfile.js 9:4-25

ERROR in ./~/jointjs/Gruntfile.js
Module not found: Error: Cannot resolve module 'load-grunt-tasks' in /home/USERNAME/projects/my_project/node_modules/jointjs
 @ ./~/jointjs/Gruntfile.js 10:4-31

ERROR in ./~/jointjs/dist/vectorizer.js
Module not found: Error: Cannot resolve module 'g' in /home/USERNAME/projects/my_project/node_modules/jointjs/dist
 @ ./~/jointjs/dist/vectorizer.js 13:8-15:10

ERROR in ./~/jointjs/dist/vectorizer.min.js
Module not found: Error: Cannot resolve module 'g' in /home/USERNAME/projects/my_project/node_modules/jointjs/dist
 @ ./~/jointjs/dist/vectorizer.min.js 13:8-15:10

ERROR in ./~/jointjs/test/geometry/require.js
Module not found: Error: Cannot resolve module 'qunit' in /home/USERNAME/projects/my_project/node_modules/jointjs/test/geometry
 @ ./~/jointjs/test/geometry/require.js 8:0-41:2

ERROR in ./~/jointjs/test/jointjs-nodejs/index.js
Module not found: Error: Cannot resolve module 'should' in /home/USERNAME/projects/my_project/node_modules/jointjs/test/jointjs-nodejs
 @ ./~/jointjs/test/jointjs-nodejs/index.js 1:13-30

ERROR in ./~/jointjs/test/jointjs/require.js
Module not found: Error: Cannot resolve module 'qunit' in /home/USERNAME/projects/my_project/node_modules/jointjs/test/jointjs
 @ ./~/jointjs/test/jointjs/require.js 19:0-59:2

ERROR in ./~/jointjs/test/vectorizer/require.js
Module not found: Error: Cannot resolve module 'qunit' in /home/USERNAME/projects/my_project/node_modules/jointjs/test/vectorizer
 @ ./~/jointjs/test/vectorizer/require.js 11:0-45:2

ERROR in ./~/jointjs/demo/requirejs/main.js
Module not found: Error: Cannot resolve module 'build/joint' in /home/USERNAME/projects/my_project/node_modules/jointjs/demo/requirejs
 @ ./~/jointjs/demo/requirejs/main.js 17:0-35:2

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Bold.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:127-173 6:226-272

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Bold.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:328-376

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Bold.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:413-460

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Bold.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:496-542

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Bold.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:582-628

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-BoldItalic.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:768-820 6:879-931

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-BoldItalic.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:987-1041

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-BoldItalic.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1078-1131

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-BoldItalic.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1167-1219

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-BoldItalic.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1259-1311

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBold.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1457-1508 6:1566-1617

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBold.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1673-1726

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBold.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1763-1815

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBold.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1851-1902

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBold.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:1942-1993

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBoldItalic.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2138-2195 6:2259-2316

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBoldItalic.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2372-2431

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBoldItalic.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2468-2526

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2562-2619

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-ExtraBoldItalic.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2659-2716

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Italic.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:2867-2915 6:2970-3018

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Italic.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3074-3124

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Italic.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3161-3210

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Italic.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3246-3294

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Italic.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3334-3382

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Light.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3524-3571 6:3625-3672

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Light.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3728-3777

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Light.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3814-3862

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Light.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3898-3945

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Light.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:3985-4032

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-LightItalic.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4173-4226 6:4286-4339

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-LightItalic.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4395-4450

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-LightItalic.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4487-4541

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-LightItalic.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4577-4630

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-LightItalic.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4670-4723

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Regular.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:4870-4919 6:4967-5016

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Regular.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5072-5123

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Regular.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5160-5210

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Regular.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5246-5295

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Regular.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5335-5384

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Semibold.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5519-5569 6:5626-5676

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Semibold.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5732-5784

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Semibold.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5821-5872

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Semibold.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5908-5958

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-Semibold.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:5998-6048

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-SemiboldItalic.eot in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:6192-6248 6:6311-6367

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-SemiboldItalic.woff2 in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:6423-6481

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-SemiboldItalic.woff in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:6518-6575

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-SemiboldItalic.ttf in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:6611-6667

ERROR in ./~/css-loader!./~/jointjs/docs/css/api.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/OpenSans/OpenSans-SemiboldItalic.svg in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/css
 @ ./~/css-loader!./~/jointjs/docs/css/api.css 6:6707-6763

ERROR in ./~/jointjs/docs/src/joint/api/util/shapePerimeterConnectionPoint.html
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/joint.util.shapePerimeterConnectionPoint.png in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/src/joint/api/util
 @ ./~/jointjs/docs/src/joint/api/util/shapePerimeterConnectionPoint.html 1:489-553

ERROR in ./~/jointjs/docs/src/joint/api/dia/Graph/prototype/bfs.html
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/joint.dia.Graph.bfs.png in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/src/joint/api/dia/Graph/prototype
 @ ./~/jointjs/docs/src/joint/api/dia/Graph/prototype/bfs.html 1:877-920

ERROR in ./~/jointjs/docs/src/joint/api/dia/Graph/prototype/dfs.html
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/joint.dia.Graph.dfs.png in /home/USERNAME/projects/my_project/node_modules/jointjs/docs/src/joint/api/dia/Graph/prototype
 @ ./~/jointjs/docs/src/joint/api/dia/Graph/prototype/dfs.html 1:872-915

ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/handlebars/lib
 @ ./~/handlebars/lib/index.js 17:11-24

ERROR in ./~/send/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/send
 @ ./~/send/index.js 25:9-22

ERROR in ./~/express/lib/request.js
Module not found: Error: Cannot resolve module 'net' in /home/USERNAME/projects/my_project/node_modules/express/lib
 @ ./~/express/lib/request.js 18:11-25

ERROR in ./~/express/lib/view.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/express/lib
 @ ./~/express/lib/view.js 18:9-22

ERROR in ./~/destroy/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/destroy
 @ ./~/destroy/index.js 14:17-30

ERROR in ./~/etag/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/etag
 @ ./~/etag/index.js 22:12-25

ERROR in ./~/mime/mime.js
Module not found: Error: Cannot resolve module 'fs' in /home/USERNAME/projects/my_project/node_modules/mime
 @ ./~/mime/mime.js 2:9-22

**Comment by dddomin3** [comment]
WARNING in ./~/jointjs/index.js
Critical dependencies:
25:17-34 the request of a dependency is an expression
 @ ./~/jointjs/index.js 25:17-34

WARNING in ./~/jointjs/CHANGELOG
Module parse failed: /home/my_username/projects/my_project/node_modules/jointjs/CHANGELOG Invalid number (1:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Invalid number (1:3)
    at Parser.pp.raise (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.readNumber (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2951:146)
    at Parser.pp.getTokenFromCode (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2768:19)
    at Parser.pp.readToken (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2508:15)
    at Parser.pp.nextToken (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2500:71)
    at Parser.pp.next (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2449:8)
    at Parser.pp.parseExprOp (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:168:12)
    at Parser.pp.parseExprOps (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:153:15)
    at Parser.pp.parseMaybeConditional (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1753:23)
    at Parser.pp.parseTopLevel (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/home/my_username/projects/my_project/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/home/my_username/projects/my_project/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/my_username/projects/my_project/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/my_username/projects/my_project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/my_username/projects/my_project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/my_username/projects/my_project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/my_username/projects/my_project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/my_username/projects/my_project/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
 @ ./~/jointjs ^\.\/.*$


This is probably why actually

**Comment by chill117** [comment]
What version of node and npm are you using? And when are you seeing the above errors - during `npm install`, `npm update`, or when using JointJS in a node script (ie. via `require('jointjs')`?

**Comment by dddomin3** [comment]
Sorry for the lack of information! I've tried it on 4.1.2, and 6.2 i believe. Using Webpack, and 
'import joint from 'jointjs'' (ES6)

I saw jQuery dependency go away during the npm update.

**Comment by chill117** [comment]
So the errors are happening when you try to use webpack to create a bundle including JointJS?

**Comment by bhoriuchi** [comment]
working with @dddomin3 on this.

we are using a vue-cli webpack template with no grunt/gulp

the main source for errors seems to be the new index.js code in the root of the module. if we replace that file with the older version that simply exports ./dist/joint webpack packages everything w/o error

for the current index.js code a few things happen in our environment. First, we get an error that the fs module cannot be resolved which is strange since it is included with node. it is looking for the module in the jointjs node_modules directory so myproject/node_modules/jointjs/node_modules/fs

it also seems that the file path is not being found as even when installing fs manually into jointjs/node_modules we still get all the same errors except the one about not being able to resolve fs

version 0.9.7 gives us no issue.

Thanks,

Branden

**Comment by chill117** [comment]
Great to hear that you got it resolved. I think it might be a good idea for us to include the webpack bundle use-case in the documentation somewhere. I'll create an issue :)
