### ISSUE TITLE
 Cannot read property 'deep' of undefined

### ISSUE THREAD

**Issue by edi9999** [clientIO/joint#342]
With webpack, doing : 

npm install jointjs
`require("jointjs")` 

it gives the following error : 

`Cannot read property 'deep' of undefined`

Here is the full stacktrace : 

```
(anonymous function)    @   joint.js:2800
(anonymous function)    @   lodash.js:4411
baseForOwn  @   lodash.js:2654
(anonymous function)    @   lodash.js:4380
forEach @   lodash.js:8634
mixin   @   joint.js:2798
deepSupplement  @   joint.js:2852
(anonymous function)    @   joint.js:10197
(anonymous function)    @   joint.js:18
g   @   joint.js:19
(anonymous function)    @   joint.js:44
__webpack_require__ @   bootstrap d4f91c7…:555
fn  @   bootstrap d4f91c7…:86
(anonymous function)    @   topology_builder_jointjs.js:1
__webpack_require__ @   bootstrap d4f91c7…:555
fn  @   bootstrap d4f91c7…:86
(anonymous function)    @   init.js:52
__webpack_require__ @   bootstrap d4f91c7…:555
fn  @   bootstrap d4f91c7…:86
(anonymous function)    @   index.js:1
__webpack_require__ @   bootstrap d4f91c7…:555
fn  @   bootstrap d4f91c7…:86
(anonymous function)    @   bootstrap d4f91c7…:578
__webpack_require__ @   bootstrap d4f91c7…:555
(anonymous function)    @   bootstrap d4f91c7…:578
(anonymous function)    @   bootstrap d4f91c7…:578
```

The part of the corresponding code in joint.js is : 

```
        mixin: function() {

            var target = arguments[0];

            for (var i = 1, l = arguments.length; i < l; i++) {

                var extension = arguments[i];

                // Only functions and objects can be mixined.

                if ((Object(extension) !== extension) &&
                    !_.isFunction(extension) &&
                    (extension === null || extension === undefined)) {

                    continue;
                }

                _.each(extension, function(copy, key) {

                    if (this.mixin.deep && (Object(copy) === copy)) {

                        if (!target[key]) {

                            target[key] = _.isArray(copy) ? [] : {};
                        }

                        this.mixin(target[key], copy);
                        return;
                    }
```

Any idea ?

**Comment by chill117** [comment]
I was not able to reproduce your issue. Can you provide the following information?
* Node version
* Exact usage of webpack (the command used)

**Comment by edi9999** [comment]
```
$ node -v
v6.2.1
```

The webpack command : 

`NODE_ENV=development webpack-dev-server -d --inline --hot --progress`

**Comment by chill117** [comment]
I am still not able to reproduce your error. Can you provide a full example app that reproduces the error?

**Comment by DontShootMe** [comment]
@edi9999 
You should check your LoDash Version, i think your problem is linked to a new version of LoDash.js.
If you use JointJs 0.9.6 try with LoDash 3.10.1 !

**Comment by edi9999** [comment]
Ok, probably, we have decided to use an other library for our diagrams now.

Thanks for the help anyway @DontShootMe .

It would be good for jointjs to be compatible with lodash 4.0

**Comment by magnushenning** [comment]
@edi9999 ;

I currently had a similar issue with lodash, and created a workaround:
https://github.com/entro-js/jointadapter/tree/master

However, I have not tested this with module loaders like AMD / CommonJS / NodeJS.

**Comment by bcarson1** [comment]
Had the same problem.  Its probably a Lodash version problem, I just switched from 4.13.1 to 3.10.1 and it worked.

**Comment by chill117** [comment]
We don't have any plans to migrate JointJS to Lodash 4.x. I have been pushing the team to move towards bundling all of JointJS' dependencies (including Lodash 3.x) so that these version conflicts aren't an issue anymore.

**Comment by sbowler** [comment]
We have also been stuck using 3.10 because of this dependency. It would be great to remove it or bundle it so there's not version conflicts like this. IMO, there should probably be a new issue created to do one or the other so people interested can follow what is happening regarding it.

**Comment by devalfrz** [comment]
JointJS is an awesome library and I have been using it for a while now. Updating it has been troublesome, so I hope this gets fixed soon. While this happens, this is the setup that works for me now:
jquery v2.2.4
backbone v1.3.3
lodash v3.10.1
jointjs v0.9.10

**Comment by GeorgiyZhuravlev** [comment]
having the same problem on an empty project with `rapid.js`

bower.json
```
  "dependencies": {
    "jquery": "2.2.4",
    "backbone": "1.3.3",
    "lodash": "3.10.1",
    "angular": "1.5.8"
  }
```

index.html
```
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/lodash/lodash.js"></script>
<script src="bower_components/backbone/backbone.js"></script>
<script src="jointjs/js/rappid.js"></script>
<script src="bower_components/angular/angular.js"></script>
```
Rappid v1.7.0

<img width="476" alt="222" src="https://cloud.githubusercontent.com/assets/14068189/20040058/28577ae8-a459-11e6-91d1-fff1a9ab3d75.png">

**Comment by kumilingus** [comment]
@GeorgiyZhuravlev do you experience the same problems with Rappid `v1.7.2`?

@sbowler yes, we would be open to a PR (lodash `v4.x`). Note there is a Dagre fork repository (DirectedGraph plugin dependency) that uses also `v4.x` that might be needed. Bundling should still take a place afterwards though.

**Comment by kumilingus** [comment]
JointJS/Rappid is now compatible with lodash v4. For the integration details please see https://github.com/clientIO/joint/tree/master/demo/lodash4.
