### ISSUE TITLE
Update typescript definition file

### ISSUE THREAD

**Issue by 40rn05lyv** [clientIO/joint#345]
Typescript definition file at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/jointjs is for v0.6 and lacks lots of existing functionality. It needs to be updated.

**Comment by chill117** [comment]
I think that typescript definition was created by someone outside of the JointJS team.

**Comment by Supamiu** [comment]
see https://github.com/clientIO/joint/issues/396, shows a better definition files in the comment.
