### ISSUE TITLE
Smart router overlapping ports

### ISSUE THREAD

**Issue by tianxu0836** [clientIO/joint#348]
I have customized port size. it is much larger than the default port.

If I use smart router, the link will overlap the port.

I want to increase the padding of the smart router's link

I wonder if there is any configuration or any walk around?

Here is what I'm doing:

[http://jsfiddle.net/tianxu0836/L2f73cbf/55/](http://jsfiddle.net/tianxu0836/L2f73cbf/55/)

**Comment by vtalas** [comment]
Hi,

I affraid there is no such a padding optioin for router, however setting
the option 'startDirections', 'endDirections' in your case might improve
you graph a bit.

http://jsfiddle.net/L2f73cbf/58/

Regards,



2016-06-23 2:18 GMT+02:00 Naiyin <notifications@github.com>:

**Comment by vtalas** [comment]
sorry for disinformation, there is such an option - paddingBox, it's
padding applied on the element bounding boxes, used as follows

http://jsfiddle.net/L2f73cbf/59/

Regards,

Vladimir

2016-06-23 7:16 GMT+02:00 Vladimir Talas <vladimir.talas@gmail.com>:

**Comment by tianxu0836** [comment]
This solution seems like it is working for metro router, but doesn't work well for manhattan router.

**Comment by vtalas** [comment]
Should be working, as the metro is extended from manhattan, both paddingBox and start/end directions are defined there, in manhattan router. Manhattan/metro could deal with edge cases differently. I updated the padding box, it's looks better, doesn't it ? http://jsfiddle.net/L2f73cbf/60/
