### ISSUE TITLE
(Doc) Incorrect documention in paper options guard

### ISSUE THREAD

**Issue by CaselIT** [clientIO/joint#350]
In the documentation of the [guard paper option](http://jointjs.com/api#joint.dia.Paper:options.guard) the return values are inverted. It should return true to stop the event handling, false otherwise.
[Code](https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L1001) of the guard call.
I hope it this is the correct place for this issue.

**Comment by kumilingus** [comment]
This is the place. Thank You! Fixed in 9368a96404e7979fc31de0a9b233f770b33a1e57.
