### ISSUE TITLE
ElementView HTML always appears over Element SVG

### ISSUE THREAD

**Issue by Jesus89** [clientIO/joint#352]
Hello, I am trying to create Custom Elements with a dynamic PortInterface and also Custom ElementViews with some HTML content (select, textarea,...) for the same cells.

The issue is that HTML elements always appear over SVG (Rect, text, ports). Functions like .toFront() or .toBack() simply don't work with HTML.

Is there any solution or I must redraw all the SVG components in the ElementView?

Thanks!

**Comment by kumilingus** [comment]
Hi,

you can use `foreignObject` in the markup to render HTML inside the SVG elements (not supported in IE).

Other than that HTML can be either above or under the SVG. i.e. some of the HTML components could be appended and the others prepended (https://github.com/clientIO/joint/blob/master/demo/html/html.js#L74).
