### ISSUE TITLE
Ports lose styling when adding additional ports.

### ISSUE THREAD

**Issue by matthewatabet** [clientIO/joint#355]
Hello!

I've found an issue where adding ports to an Element seems to undo styling previously applied to other ports. Here's an example:

```
elem.attr('[port="port_a"]/fill', 'rgb(200, 200, 0)')
elem.set('inPorts', [...elem.get('inPorts'), 'port_b'])
```

The styling on `port_a` will go away.

Thanks!

EDIT: updating ports after styling is import for the application I'm working on because we deal with a lot of dynamic ports.

**Comment by matthewatabet** [comment]
Any suggestions here? Let me know if you need more details. Thanks!

**Comment by matthewatabet** [comment]
Ping :) Thanks. This is becoming a critical issue and any advice would be appreciated. Let me know if you need any info from me.

**Comment by kumilingus** [comment]
Hi Matthew, any chance you start using the latest JointJS (the Master branch) ? There is a brand new API for ports, that would definitely solve the problem. You would need to build the documentation and learn it from there though.

Using `[port=<port_id>]` in selectors seems not to be reliable right now (ports DOM Elements does not have `port` attribute at the time of querying). We need to take a deeper look into it. I can think of some workarounds how to set a single port color, but they are no good. 
- using a class name in the selector instead i.e. `elem.attr('.port1 circle/fill', 'rgb(200,200,0)');`. (bad if you add & remove ports) 
- create a style tag dynamically and append it to the DOM `<style>[model-id="<model.id>"] [port="<port.id>"] { fill: rgba(200,200,0); }</style>`.

What is your use-case?

Thank You,
Roman

**Comment by matthewatabet** [comment]
Thanks! I think we can do that. I'll look into the latest port api this week and let you know how it goes. Cheers!

**Comment by matthewatabet** [comment]
p.s. More details about the use case:

I'm building support on our application for nested subnetworks. The user can assemble select a group of nodes and collapse them into a subnetwork which appears as a single node in the parent network. This node then has a dynamic set of ports -- as the topology of the contained network changes, the dynamic ports on the parent node need to update to reflect the new inputs and outputs of the subnetwork.

**Comment by matthewatabet** [comment]
So, so far so good. The latest jointjs dropped in easily with just a few tweaks to css selectors.

Re the port api -- I read through the api but it wasn't clear how to designate a port as an input or an output. Any pointers?

Previously, this was done by setting 'inPorts' and 'outPorts.' Thanks!

**Comment by vtalas** [comment]
Good to hear it's going well. You can define your own groups easily like this: 
```
var rect = new joint.shapes.basic.Rect({
    position: { x: 425, y: 60 },
    size: { width: 200, height: 100 },
    attrs: {
        text: { text: 'left', fill: '#6a6c8a' },
        rect: { stroke: '#31d0c6', 'stroke-width': 2 }
    },
    ports: {
        groups: {
            'in': {
                position: 'left',
                label: {
                    position: 'left'
                },
                attrs: {
                    text: { fill: '#000000' },
                    circle: { fill: '#ffffff', stroke: 'green', 'stroke-width': 2, r: 10, magnet: 'passive' }
                }
            },
            'out': {
                position: 'right',
                label: {
                    position: 'right'
                },
                attrs: {
                    text: { fill: '#000000' },
                    circle: { fill: '#ffffff', stroke: 'red', 'stroke-width': 2, r: 10, magnet: true }
                }
            }
        }
    }
});

rect.addPort({ group: 'in', attrs: { text: { text: 'in1' } } });
rect.addPort({ group: 'in', attrs: { text: { text: 'in2' } } });

rect.addPort({ group: 'out', attrs: { text: { text: 'out1' } } });
rect.addPort({ group: 'out', attrs: { text: { text: 'out2' } } });
rect.addPort({ group: 'out', attrs: { text: { text: 'out3' } } });

```

**Comment by vtalas** [comment]
you can pass ports directly throuht the constructor as well ....  
```javascript
var rect = new joint.shapes.basic.Rect({
    position: { x: 425, y: 60 },
    size: { width: 200, height: 100 },
    attrs: {
        text: { text: 'left', fill: '#6a6c8a' },
        rect: { stroke: '#31d0c6', 'stroke-width': 2 }
    },
    ports: {
        groups: {
            // groups definition 
        },
        items: [
            { group: 'in', attrs: { text: { text: 'in1' } } },
            { group: 'in', attrs: { text: { text: 'in2' } } },

            { group: 'out', attrs: { text: { text: 'out1' } } }
        ]
    }
});
```

**Comment by matthewatabet** [comment]
I'm getting an error stating `this.addPort` is not a function. I'm using ES6 and inheriting from joint.shapes.devs.Model. I've verified that `this` is scoped correctly and points to the Model instance.

**Comment by matthewatabet** [comment]
Found a workaround to the `this.addPort` is not a function error. I'm using ES6 and Webpack and needed to import the built jointjs library:

`import joint from "jointjs/build/joint.js";`

It looks like `ports.js` is not run if the import is:

`import joint from "jointjs";`

If `ports.js` is not run, then the Element class is never augmented with the new port api.

Hope this is helpful to others! Thanks.

**Comment by matthewatabet** [comment]
Is it possible to use the new ports api with `joints.shapes.devs.Model`? This comment seems to indicate that it's not:

https://github.com/clientIO/joint/blob/master/plugins/shapes/joint.shapes.basic.js#L257

Thanks!

**Comment by matthewatabet** [comment]
Hello! I've gotten enough code converted over to the new api to confirm that this fixes the port coloring problem I was having. Thanks a bunch!

I'm going to close this ticket. When should this new api be available via npm? Thanks!

**Comment by rahuljhawar** [comment]
This is still not fixed

**Comment by kumilingus** [comment]
It won't be fixed for `devs` shapes. Please use Element Port API instead.
