### ISSUE TITLE
Usage of ref-dx and ref-dy attributes is not obvious

### ISSUE THREAD

**Issue by 40rn05lyv** [clientIO/joint#363]
**Steps:**
Try to create some `Rect`element with following defaults:

```
{ 
  attrs : { 
    text : {
      'ref' : 'rect',
      'ref-dx' : -10,
      'ref-dy' : -10
    }
  }
}
```

**Expected result:** text position is located 10 pixels relative to the right and bottom sides or rectangle.
**Actual result:** text position is as default.

The problem is in `positionRelative` function.

Workaround:

```
{ 
  attrs : { 
    text : {
      'ref' : 'rect',
      'ref-dx' : -10,
      'ref-dy' : -10,
      'ref-x': 'notanumber',
      'ref-y': 'notanumber'
    }
  }
}

```

**If it's not a defect, proper usage of ref-dx and ref-dy should be described in API page (http://www.jointjs.com/api#SpecialAttributes).**

**Comment by kumilingus** [comment]
Hi, it was indeed a defect. You never knew which attribute would be used if both `ref-x` and `ref-dx` were used at the same time. They now add up instead (none of them being ignored).
