### ISSUE TITLE
React/Redux

### ISSUE THREAD

**Issue by matthewatabet** [clientIO/joint#369]
Hi there,

It would be amazing if JointJS used React and Redux. I love JointJS. I love React and Redux. Are there plans to combine these technologies?

JointJS + React/Redux === chocolate + peanut butter.

Thanks!

**Comment by chill117** [comment]
Could you elaborate on this? I don't quite understand how JointJS could use "React and Redux".

**Comment by matthewatabet** [comment]
Sure -- this might not be practical, but I've been looking for a node graph which uses React for rending components and Redux for storing the graph topology. IMHO, this could allow for much simpler client code. I say this might not be practical because such a thing would require migration away from backbone. But, I at least wanted to open an issue so folks would know there was interest in such a thing.

**Comment by chill117** [comment]
Hmmm. Ok. That would require quite a bit of work. And I am not sure I see much benefit. Is there a specific use-case that is not possible for you right now?

**Comment by kumilingus** [comment]
There are no plans migrating JointJS to React/Redux. We might create some examples showcasing integration between JointJS and React though (or make the integration smoother, if there are any issues).

**Comment by moebiusmania** [comment]
@kumilingus I agree with maitaning JointJS "standalone", but it would be great to see some examples of integrations with JS framework, in first instance React.

Ora maybe to publish some wrappers for frameworks.

**Comment by kumilingus** [comment]
KitchenSink application along with React is part of Rappid `v2.4.0`.
