### ISSUE TITLE
joint.webpack-bundle.js should be distributed with non-minified sources

### ISSUE THREAD

**Issue by 40rn05lyv** [clientIO/joint#376]
Right now, v.0.9.10 (https://github.com/clientIO/joint/releases/tag/v0.9.10) has `joint.webpack-bundle.js`, that contains all javascript required for jointjs.
However, the `joint.js` sources are minified, that makes it impossible to debug error if it happens.

I think, it's better to distribute `joint.webpack-bundle.js` with non-minified sources, and `joint.webpack-bundle.min.js` with minified sources.

**Comment by chill117** [comment]
Good idea. I think having both minified and un-minified versions of the bundle(s) would be a good approach here.
