### ISSUE TITLE
Defect: "V" and "g" variables are undefined in joint.webpack-bundle.js 

### ISSUE THREAD

**Issue by 40rn05lyv** [clientIO/joint#377]
In the latest distribution - v.0.9.10 (https://github.com/clientIO/joint/releases/tag/v0.9.10) - joint.webpack-bundle.js doesn't define "V" and "g" variables.

**joint.js:**
**V** - ok
**g** - ok
**joint.V** - ok
**joint.g** - ok

**joint.webpack-bundle.js** 
**V** - undefined
**g** - undefined
**joint.V** - ok
**joint.g** - ok

In the API page (http://www.jointjs.com/api) it's stated:

> JointJS library exports three global variables: joint, V and g.

**Comment by chill117** [comment]
I don't think this is a defect with the bundle(s). The entire point of the bundle files is to only expose a single variable (`joint`) to the global scope. Perhaps this could somehow be made clearer in the documentation instead?
