### ISSUE TITLE
Create complete typings.

### ISSUE THREAD

**Issue by Supamiu** [clientIO/joint#396]
Some of us may need to integrate joint.js with angular2 (which is what I'm currently doing).

Problem is that the only typings available at the moment (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jointjs/jointjs.d.ts) are incomplete (no devs, missing shapes, etc) and they are causing several typescript compilation issues (even if the js works fine).

**Comment by Siriah** [comment]
I'd be really excited about more complete Typescript definitions for JointJS. When searching for jointjs Typescript definitions using the 'typings' tool, these show up as well: https://github.com/CaselIT/typings-jointjs They are more complete than what's available in the DefinitelyTyped repository, but there are still some bits missing.

**Comment by kumilingus** [comment]
Fixed.
