### ISSUE TITLE
ERD problem rendering on Safari

### ISSUE THREAD

**Issue by miltonbsn** [clientIO/joint#404]
Hi, I noticed links on ERD library are not working on Safari. Even the demo.

Could you help me?

![image](https://cloud.githubusercontent.com/assets/881231/18536458/df969c34-7ad3-11e6-838c-409479f102b8.png)

**Comment by kumilingus** [comment]
Hi, this was already fixed in the master branch of the repository (Please see `demos/erd/index.html`). In an older version you should avoid using `joint.util.shapePerimeterConnectionPoint` for the `linkConnectionPoint` paper option.

**Comment by miltonbsn** [comment]
Thank you @kumilingus
