### ISSUE TITLE
Nested Elements

### ISSUE THREAD

**Issue by abhijith-gururaj** [clientIO/joint#427]
Hi,
Is there any way we can include two or more elements in a single element. I am not talking about HTML inside an element. I am talking about a situation where there a groups of elements and one element in a particular group can be connected to an element in another group. (Considering that the group is also an element like Rect,Model etc)

**Comment by kumilingus** [comment]
Hi
Yes, we call it `embedding` in JointJS. Please see `joint.dia.Element.prototype.embed` / `joint.dia.Link.prototype.embed` docs for more info.

[DEMO](https://github.com/clientIO/joint/tree/master/demo/devs)
