### ISSUE TITLE
Moving link vertices does not work well on touch devices

### ISSUE THREAD

**Issue by mperktold** [clientIO/joint#428]
Just access the [Finite State Machines Demo](http://resources.jointjs.com/demos/fsa) via some (reasonably big) touch device, create a link vertex, and try to move it around.

If you create and move the vertex without releasing the finger, everything works fine.
However, if you try to move an existing vertex, it just moves a small distance and stands still immediately.

Even stranger, when after this you tap on the blank paper and move your finger, the vertex jumps to that position and then follows the finger's movements.

**Comment by kumilingus** [comment]
`joint.dia.Link` is deprecated. Use `joint.shapes.standard.Link` together with `joint.linkTools` (touch events for Vertices tool works as expected now).
