### ISSUE TITLE
Links are not drawn when elements are positioned with percentages.

### ISSUE THREAD

**Issue by brassard** [clientIO/joint#433]
The elements are being defined as:
```
var box = new joint.shapes.html.Element({
  position: {x: '68%', y: '35%'},
  size: {width: '25%', height: '50%'}
}
```

The links are being defined as:
```
var link1 = new joint.dia.Link({
  source: {id: box.id},
  target: {id: otherBox.id}
});
```

The boxes are drawn properly and in the correct positions, but there are no lines drawn between them.

Console error messages look like: 
```joint.js:2136 Error: <text> attribute transform: Expected number, "translate(NaN,0)".```
```joint.js:2136 Error: <g> attribute transform: Expected number, "scale(NaN,NaN)".```
```joint.js:2136 Error: <g> attribute transform: Expected ')', "translate(68%,35%)".```

----
**Edit:** Here is a simpler example...
```
var rect = new joint.shapes.basic.Rect({
  position: { x: '10%', y: '10%' },
  size: { width: 100, height: 30 },
  attrs: { rect: { fill: 'blue' }, text: { text: 'my box', fill: 'white' } }
});

var rect2 = new joint.shapes.basic.Rect({
  position: { x: '40%', y: '30%' },
  size: { width: 100, height: 30 },
  attrs: { rect: { fill: 'blue' }, text: { text: 'my box', fill: 'white' } }
});

var link = new joint.dia.Link({
  source: { id: rect.id },
  target: { id: rect2.id }
});

graph.addCells([rect, rect2, link]);
```

**Comment by kumilingus** [comment]
Hi, using percentages for element `position` or `size` is not supported. What is your use-case? Can you use numbers instead?

**Comment by brassard** [comment]
Oh... interesting. It works to position them. I am trying to layout a non-interactive flow-chart style diagram.

I switched over to numbers for now, basically calculating the percentage positions manually. I was trying to use percentages so that the objects would scale when the page is resized, which seems to work, albeit without any lines present.

I can work around it in general. Is there an easy way to make all elements redraw themselves? Is there a call like `paper.redraw()` or something?

Thanks for the response.

**Comment by brassard** [comment]
Was just thinking... I guess I may just need to track the window resizing and change the sizes of the graph's elements when it happens. Will changing those elements' dimensions, just automatically update the paper's view?

**Comment by kumilingus** [comment]
> Oh... interesting. It works to position them. I am trying to layout a non-interactive flow-chart style diagram.

Well, it does not even position elements (it might position the HTML elements rendered above the paper, but definitely not the SVG elements - that's why you saw console errors).

> Will changing those elements' dimensions, just automatically update the paper's view?

Right. ElementViews listen to their underlaying models and updates automatically.


Another option is to use `html.Element` definition from this [demo](https://github.com/clientIO/joint/tree/master/demo/html) and zoom the paper based on the window size.
Note that there is no `html.Element` defined in JointJS itself, so the implementations might vary.

**Comment by brassard** [comment]
Thanks. I ended up just clearing the graph and redrawing when I needed to adjust for window size changes.
