### ISSUE TITLE
classNamePrefix is not added to SVG elements

### ISSUE THREAD

**Issue by HiaslTiasl** [clientIO/joint#436]
The `joint.config.className` only gets added to the HTML element wrapping the paper, but not to SVG elements, i.e. neither to elements nor to links.

The problem is in `_ensureElClassName` of `joint.mvc.View`.
There, jQuery is used to change the class name, which does not work for SVG elements.

**Comment by HiaslTiasl** [comment]
After checking the website again, I noticed that now jQuery version 2.4.4 should be used, which fixes the above issue.

Maybe this should be mentioned in the changelog or some migration guide...

**Comment by kumilingus** [comment]
Right. jQuery `v2.4.4` can not handle setting classNames on SVGElements.
