### ISSUE TITLE
Treeview using Jointjs or rappid

### ISSUE THREAD

**Issue by sastrygunnu** [clientIO/joint#437]
We are trying to develop tree like this below layout using jointjs is this possible with this plugin can you any one help us ?  We are going to buy licensed version of this soon once we did this rnd.
![tree_view](https://cloud.githubusercontent.com/assets/2316655/19151603/34a3a9b0-8beb-11e6-91fc-eb44a63d8907.png)

**Comment by kumilingus** [comment]
Hi, the `TreeLayout` plugin (part of the Rappid) is capable of laying out elements this way. I'm using `bottom-right (BR)` layout in the image below.

![image](https://cloud.githubusercontent.com/assets/3967880/19152455/5ad53626-8bd2-11e6-92b4-fdbbc2725d8f.png)

Note that hiding links or having buttons as part of the shape is also possible in JointJS. 

http://resources.jointjs.com/demos/tree
http://resources.jointjs.com/demos/orgchart

Additionally you can integrate the `TreeLayoutView` plugin to enable drag & drop functionality.

**Comment by sastrygunnu** [comment]
Can i use Json to generate this tree?

**Comment by sastrygunnu** [comment]
Basically we are trying to build layout like this below I'm stile not sure this is possible with this or not just today i started working with this frame work .. your help really appreciate to decide and buy
![finaltree](https://cloud.githubusercontent.com/assets/2316655/19155654/d99d45fa-8bfc-11e6-98b6-a71ab9b11e6b.png)

**Comment by kumilingus** [comment]
> Can i use Json to generate this tree?

Yes. Please see `graph.toJSON()` & `graph.fromJSON()`.


> ![](https://cloud.githubusercontent.com/assets/2316655/19155654/d99d45fa-8bfc-11e6-98b6-a71ab9b11e6b.png)

This use-case is well supported by JointJS.
