### ISSUE TITLE
Horizontally center ports

### ISSUE THREAD

**Issue by doender** [clientIO/joint#448]
In previous versions of JointJS, ports were automatically centered when defined as follows:

```
ports: {
            groups: {
                in: {
                    position: 'top'
                },
                out: {
                    position: 'bottom'
                }
            },
            items: [
                {
                    id: 'in1',
                    group: 'in'
                },
                {
                    id: 'out1',
                    group: 'out'
                }
            ]
        }
```

In JointJS 1.0.1, I changed `{position: 'top'}` to `position: {name: 'top'}` as per the docs, but now the ports are moved to the left. How can I have the ports centered on the element (without manually changing the x position)

**Comment by vtalas** [comment]
Hi, 

hm interesting.. seems it took the default (left). Both definitions are valid, `position: 'top'` as well as the `position: { name: 'bottom' }`  Here is a prepared fiddle you can play with 

https://jsfiddle.net/vtalas/scw093tv/

**Comment by doender** [comment]
I have the feeling that the positioning doesn't work in my code (as opposed to the fiddle) because there is something off with the scaling. If I define a module like this:
```
var m = new joint.shapes.basic.Rect({
       size: {width: 120, height: 60}
}
```
I get a gigantic rectangle. It seems the numbers aren't interpreted as pixel sizes. This is the resulting html (in Chrome dev tools):
```
<g class="rotatable" id="v-6" transform="">
   <g class="scalable" id="v-7" transform="scale(120,60)">
      <rect id="v-8" fill="#4db6ac" stroke="#000000" width="100" height="60"></rect>
   </g>
</g>
```
So the width/height are interpeted as scaling factors instead of pixel sizes. 
How can I fix this?

**Comment by doender** [comment]
Ah, I just found out that it's due to this bug: https://github.com/clientIO/joint/issues/262
