### ISSUE TITLE
DirectedGraph layouting does not take paper size into account

### ISSUE THREAD

**Issue by norm2782** [clientIO/joint#45]
DirectedGraph layouting does not take paper size into account. I currently have a 600x300 paper, but the DirectedGraph layout algorithm lays my objects out vertically, causing them to fall off the paper. Rather than rendering vertically, it would be ideal if the layout algorithm could use the empty horizontal space as well.

**Comment by kumilingus** [comment]
Won't fix as the DirectedGraph plugin works with `dia.Graph` not with `dia.Paper`.
Note that you can set the paper dimensions based on the layouted graph content size once layout done.
