### ISSUE TITLE
link:disconnect event not triggered

### ISSUE THREAD

**Issue by doender** [clientIO/joint#452]
When adding/removing links between nodes, the `link:connect` event gets triggered correctly, but the the `link:disconnect` does not.

```
this.paper.on('link:connect', (linkView) => {
    console.log("Link connected", linkView.model.attributes);
});

this.paper.on('link:disconnect', (linkView) => {
    console.log("Link disconnected", linkView.model.attributes);
});
```

I need to be able to respond to link disconnects. Any idea how this could be done?

**Comment by vtalas** [comment]
`link:disconnect` is triggered only when the link is disconnected from the element and stays is graph (e.g. when you change source/target).  In other words, when you delete the link you need to listen the `remove` event on the `graph` 
```
graph.on('remove', function (cell) {

    if (cell.isLink()) {
        // ...
    }
});
```

**Comment by doender** [comment]
Thanks, just found the same solution a minute ago :)
