### ISSUE TITLE
Elements inside of lane

### ISSUE THREAD

**Issue by alirezamirzaeiyan** [clientIO/joint#454]
I'm using BPMN plugin to draw pool with different lanes. How can i add elements inside of specific lane and bound them to it. I'll appreciate your assistance ;)

**Comment by kumilingus** [comment]
For the bounding I suggest to use the paper `restrictTranslate` option. Here you can return a rectangle in which the element can move.
In Rappid `v2.0.0` there is `data-lane-path` attribute added to every lane SVGElement. You can for instance store the path (e.g. `lanes/sublanes/1`) to the lane on each element you'd like to restrict its movement and implement `restrictTranslate` using this path like below.

```javascript
paper.options.restrictTranslate = function(cellView) {

  var cell = cellView.model;  
  var embeddedInLane = cell.get('embeddedInLane'); // for example "lanes/sublanes/1"
  var parentId = cell.get('parent');
  if (!embeddedInLane || !parentId) return false; // no restriction

  // find the parent view (pool)
  var paper = cellView.paper;
  var parentView = paper.model.getCell(parentId).findView(paper);
  // find the lane node
  var vLane = parentView.vel.findOne('[data-lane-path="' + embeddedInLane + '"]');
  
  // restrict translate to the bounding box of the lane
  return vLane.bbox(false, paper.viewport);
}
```

Similary for the element positioning inside a specific lane.

**Comment by alirezamirzaeiyan** [comment]
Much obliged! :+1: 
This approach works without any problem :)
