### ISSUE TITLE
Possible defect: Joint doesn't load graphlib and dagre using requireJS

### ISSUE THREAD

**Issue by javitank** [clientIO/joint#465]
Hi,

I managed to load jointjs using requireJS following http://resources.jointjs.com/tutorial/requirejs

**But when I need to use Automatic layout It doesn't work because Joint doesn't load graphlib and dagre as "require modules", as it does with Backbone, Lodash or jQuery.**

Looking at the code, I think it should work for commonJS modules, but not AMD/requireJS:

```
if (typeof exports === 'object') {
    var graphlib = require('graphlib');
    var dagre = require('dagre');
}

// In the browser, these variables are set to undefined because of JavaScript hoisting.
// In that case, should grab them from the window object.
graphlib = graphlib || (typeof window !== 'undefined' && window.graphlib);
dagre = dagre || (typeof window !== 'undefined' && window.dagre);
```

Could this be a defect? 
Perhaps this could somehow be made clearer in the documentation.

As a workarournd I can load graphlib and dagre with a script tag previously but it would be definitely better to do it with requireJS.

Thanks.

**Comment by discoverrajeev** [comment]
I am also facing the same issue.
I tried even using script but no success.
Any clue to make it success?

Thanks

**Comment by javitank** [comment]
Hi @discoverrajeev,

I'll tell you how I've done it, by taking advantage of 'map' option of requireJS. 

You can tell requireJS that instead of loading, for example, the backbone dependency of jointjs, to load another module, so I made a tiny module that returns the real backbone while loading graphlib and dagre in the window object.

That is something like:

Example of my requireJS config:
```
{
    paths: {
        'lodash-3.10.1': 'path/to/lodash-3.10.1',
        'backbone': 'path/to/backbone-1.3.3',
        'graphlib': 'path/to/graphlib-2.1.1',
        'dagre': 'path/to/dagre-0.7.4',
        'jointjs': 'path/to/joint-1.0.3',
        'jointjs-loader-hack': '../scripts/connectivity/jointjs-loader-hack',

    },
    map: {
        'jointjs': {
            'backbone': 'jointjs-loader-hack',
            'lodash': 'lodash-3.10.1',
        }
    }
}
```

And the module jointjs-loader-hack.js

```
define(['backbone', 'graphlib', 'dagre'], function(backbone, graphlib, dagre) {
    window.graphlib = graphlib;
    window.dagre = dagre;

    return backbone;
});
```

Notice I use a recent version of graphlib, because the recommended by jointjs gives an error that I don't remember now.

**Comment by discoverrajeev** [comment]
Thanks javitank for the solution.

I am currently using graphlib which is there in Rappid version 2.0.1

**Comment by discoverrajeev** [comment]
Thanks javitank for the solution.

Currently I am using graphlib which comes with the Rappid version 2.0.1

**Comment by kumilingus** [comment]
What do we need to change in JointJS to make `DirectedGraph` play well with `AMD/RequireJS`? Cheers.

**Comment by javitank** [comment]
> What do we need to change in JointJS to make DirectedGraph play well with AMD/RequireJS? Cheers.

Not completely sure, but I think is missing a define block for 'graphlib' and 'dagre', similar to the one used for backbone, lodash, etc., in https://github.com/clientIO/joint/blob/v1.0.3/dist/joint.js#L14

**Comment by steve-heine** [comment]
this still seems to be broken
