### ISSUE TITLE
Run examples local

### ISSUE THREAD

**Issue by Abrissirba** [clientIO/joint#474]
Is it possible to run the demo or docs local part from open the html file in the browser?

**Comment by kumilingus** [comment]
Yes. Please run `npm install; grunt build:all` first.
Demos - just open the html file in a demo directory (usually `index.html`).
Docs - start a web server (e.g. `http-server` from NPM) on port 8080 from the JointJS root directory. Open `http://localhost:8080/build/docs/joint.html`.
