### ISSUE TITLE
Run DirectedGraph in a web worker

### ISSUE THREAD

**Issue by Abrissirba** [clientIO/joint#475]
The DirectedGraph layout is quite cpu intensive and freezes the ui. It would be nice if it was possible to run it in a web worker (if available in the browser) to keep the ui responsive.

**Comment by kumilingus** [comment]
Closing as "should be addressed by [dagre](https://github.com/dagrejs/dagre)".

Alternatively, use [elkjs](https://github.com/kieler/elkjs) lib. Here's a demo using web workers: https://www.jointjs.com/demos/eclipse-kernel-layout
