### ISSUE TITLE
Listening for cell:pointerup stops firing for cell:pointerclick

### ISSUE THREAD

**Issue by AuHau** [clientIO/joint#484]
Hey there,

I am listening for both cell:pointerup event and for cell:pointerclick on the same paper, and when the cell:pointerup is active, the cell:pointerclick event won't fire. 
When I comment out the cell:pointerup handler, then the cell:pointerclick works.

Is this desired behavior? Because to me, it doesn't sound logical...

**Comment by altersign** [comment]
Has passed quite a while, but if it's still an issue for you, at least a temporary solution can be found on [Stackoverflow](http://stackoverflow.com/questions/35443524/jointjs-why-pointerclick-event-doesnt-work-only-pointerdown-gets-fired).

I would also note that I had similar issue in Chrome only. In Firefox it works for me without any changes in constructor arguments.

**Comment by AuHau** [comment]
I already solved it in different way, but thanks for heads up!

**Comment by kumilingus** [comment]
Related to https://bugs.chromium.org/p/chromium/issues/detail?id=5212. Fixed by emitting a syntetic click event on pointerup.
