### ISSUE TITLE
Link is blocked by an unseen bounded rectangle

### ISSUE THREAD

**Issue by sacheth003** [clientIO/joint#486]
This bug seems to only be reproducible on Safari, not Chrome or Firefox.

When clicking on a Node and moving the cursor around, the link seems to be hidden under an invisible bounded box. This seems to occur with all versions of joint. See images below (nodes have been blacked out):

When I move my cursor to the node on the right, it is cutoff and the link isn't complete.
<img width="763" alt="rightcutoff" src="https://cloud.githubusercontent.com/assets/1834801/21089420/e1455a12-c005-11e6-8d9d-dce780c0e4ed.png">

The same thing occurs on the bottom (my cursor was at the bottommost point of the screen):
<img width="654" alt="bottomcutoff" src="https://cloud.githubusercontent.com/assets/1834801/21089433/fc3a9346-c005-11e6-8533-028e6b5b2ed1.png">

However, when I connect both nodes, the link appears fine:
<img width="566" alt="connectednodes" src="https://cloud.githubusercontent.com/assets/1834801/21089448/21836952-c006-11e6-815c-66ce42aa1e61.png">

**Comment by kumilingus** [comment]
Hi, could you please create a JSFiddle which demonstrate the issue? Do you use anything unusual in your shape definition ( filters, gradients )? Is this happening also in any of our online demos?
Thank You,
Roman

**Comment by sacheth003** [comment]
@kumilingus I unfortunately can't create a JSFiddle as it's part of a more complex project, but I'll see what I can do. Meanwhile, are you aware of anything that may cause issues on Safari and not on Chrome and Firefox?

**Comment by kumilingus** [comment]
Hi, I am now able to reproduce the issue (or similar) in our KitchenSink online demo (http://resources.jointjs.com/demos/rappid/apps/KitchenSink/index.html).  We'll look into it.

**Comment by kumilingus** [comment]
Not 100% sure that's related but in Safari one have to wait for document ready event before rendering the paper (especially when some external resources (fonts) are included on the page).
