### ISSUE TITLE
navigator doesn't work with chrome

### ISSUE THREAD

**Issue by issacjxjx** [clientIO/joint#487]
The words crowd together in chrome(both Windows and Linux version) while it works fine in Firefox and Chromium. The screenshot is from [http://resources.jointjs.com/demos/kitchensink](http://resources.jointjs.com/demos/kitchensink)
![chrome](https://cloud.githubusercontent.com/assets/24741389/21464974/2dbd6066-c9c9-11e6-84bc-4aba7d81506a.png)

**Comment by kumilingus** [comment]
Hi, what version of chrome do you use? What shapes (types) are in the graph at the time of taking the screenshot?

**Comment by issacjxjx** [comment]
Chrome version is 55.0.2883.87 (64-bit). Sorry for the wrong link, you can go [here](http://resources.jointjs.com/demos/kitchensink) to see the graph.

**Comment by kumilingus** [comment]
Hi Issac, we are not able to reproduce it using the exact same version of Chrome. Could you try to remove the `shape-rendering` attribute on the Navigator SVG document and see if it helps?

![image](https://cloud.githubusercontent.com/assets/3967880/21521985/ee933438-cd01-11e6-9ec3-fcc9fd183575.png)

**Comment by issacjxjx** [comment]
Actually the document does not have this attribute. I'll look into the source code.

**Comment by kumilingus** [comment]
I am sorry @issacjxjx for the delay. Is this still an issue?

**Comment by issacjxjx** [comment]
No. I modified the content of the svg and it was ok. Thank you!
