### ISSUE TITLE
Incorrect documentation of jumpover arg

### ISSUE THREAD

**Issue by klenium** [clientIO/joint#488]
From [the documentation](http://resources.jointjs.com/docs/jointjs/v1.0/joint.html#dia.Link.prototype.presentation):
>  It accepts the following options.
>    type - the style of the jump.

Look at `joint.connectors.jumpover@return`  in joint.js v1.0.3:
<code>var jumpType = opts.jump && ('' + opts.jump).toLowerCase();</code>

So that the documentation or the source code is wrong, one uses `jump`, the other says `type`. I guess this options's name should be `type`.

**Comment by kumilingus** [comment]
Fixed in #491. We keep the `jump` naming to maintain the  backwards compatibility.
