### ISSUE TITLE
Support for custom labelMarker

### ISSUE THREAD

**Issue by B3rn475** [clientIO/joint#489]
In file
https://github.com/clientIO/joint/blob/a2fcd07eda2f4737f361e5c9ae922cdaec09a8d0/src/joint.dia.link.js
the attrs are fixed to rect and text making impossible to change the structure to the label

**Comment by kumilingus** [comment]
Changing the markup and using special attributes will be possible in the next release. See https://github.com/clientIO/joint/pull/502.
