### ISSUE TITLE
Joint JS 0.9.10 - joint.util.breakText not working when the font-size is changed

### ISSUE THREAD

**Issue by FelipePiacsek** [clientIO/joint#493]
Changed the font-size of my text element to 16px and this happened:

![image](https://cloud.githubusercontent.com/assets/9383701/21618623/f6d2c930-d1d2-11e6-8fa5-a6c28f117b08.png)

**Comment by kumilingus** [comment]
What type of element do you use? How do you call the `breakText` method. Are you passing the `font-size` attribute within the `styles` parameter?
