### ISSUE TITLE
Connector cannot able to render the link.

### ISSUE THREAD

**Issue by nishantshahakar** [clientIO/joint#507]
Hi,

I'm using jointjs to create a basic flow chart. If I use smart routing in links it breaks. I'm using Angularjs 1.6. Attached a screenshot for reference .
![screen shot 2017-01-31 at 7 20 15 pm](https://cloud.githubusercontent.com/assets/18656669/22467502/ef5012de-e7ea-11e6-9e1c-f3853e9aed28.png)

**Comment by kumilingus** [comment]
Hi, please make sure you have `joint.css` stylesheet linked to your HTML document.

**Comment by nishantshahakar** [comment]
My bad , using jquery version 2.1.1 instead of 2.2.4

**Comment by kumilingus** [comment]
I see. jQuery `v2.1.1` does not handle setting classNames on SVGElements. Thanks.
