### ISSUE TITLE
[RAPPID 2.0.1] Paper Scroller with Grid after migrating to rappid 2.0.1

### ISSUE THREAD

**Issue by luis-carlos-campos** [clientIO/joint#514]
Hi guys,

Im facing some problems using grid with paper scroller since I updated my rappid version, sometimes the grid disappear when paper is being auto resized or when the origin of the paper is changed.

I was taking a look in drawGrid function and I noticed something that seems to be an issue.

e.g.
gridSize = 10
scale=1
originY=-700

First you create a canvas 10(width)x10(height).
Then you try to find the position where you are going to draw a rect.
In case the y origin is negative(-700 for instance), the y for the new rect will be 10(gridSize) + (-700 % 10), which results in a y position equals to 10.
This y (10) is outside the canvas.

Shouldn't the negative condition be something like (gridSize - 1) + (originY % gridY)

Note: Same applies for X position*

Thanks in advance,

**Comment by kumilingus** [comment]
Hi Luis, I believe this is not an issue anymore. The grid calculation has been rewritten recently (https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L1543-L1572).

**Comment by luis-carlos-campos** [comment]
Hi @kumilingus,

I noticed this fixed but it's not included in the latest stable release.
Is there any plan to release a new version with this fix?

Thanks again,
