### ISSUE TITLE
upgrading rapid 1.7.0 to 2.0.1 do not show  Halo  options  around element.

### ISSUE THREAD

**Issue by sshelake123** [clientIO/joint#516]
#am trying to upgrading rapid 1.7.0 to 2.0.1  halo is not seen around element.
updated jQuery 2.1.1 -> 2.2.4
Backbone 1.2.1 -> 1.2.3
rappid 1.7.0 -> 2.0.1

It does not show any error, hence not able to find actual caused of  it.

My code for rendering it. 

var halo = new joint.ui.Halo({
                                graph: graph,
                                paper: paper,
                                cellView: cellView
                            });

                            halo.render();

can anyone please help me.

**Comment by kumilingus** [comment]
Hi, sorry for the delay. Is the Halo rendered in the DOM? Try `document.querySelectorAll('.joint-halo')`. Does it exists? If so could you check the CSS applied. Are the buttons hidden or not rendered at all?
