### ISSUE TITLE
Uncaught TypeError: html.replace is not a function

### ISSUE THREAD

**Issue by madasaca29** [clientIO/joint#527]
I'm migrating from .5 to .9, but it gives me that error on versions >= joint-0.9.9, 
I have solved it with String(html). replace, but i dont know if is ok.
 any idea why?

```

        /*
            Pre-compile the HTML to be used as a template.
        */
        template: function(html) {

            /*
                Must support the variation in templating syntax found here:
                https://lodash.com/docs#template
            */
            var regex = /<%= ([^ ]+) %>|\$\{ ?([^\{\} ]+) ?\}|\{\{([^\{\} ]+)\}\}/g;

            return function(data) {

                return  String(html).replace(regex, function(match) {
```

**Comment by kumilingus** [comment]
Hi, Could you send us the stack trace? It seems there is a place in your application when an SVG markup is not defined as a string. When the error occurs what is the `html` value?

**Comment by madasaca29** [comment]
Hello, I found the error in the application, it is not an issue, sorry, it's right the SVG markup was not defined as a string, the .join ('') was missing  in the labelMarkup.
Thank you very much for your help!
