### ISSUE TITLE
Impossible to set y coordinate for a text

### ISSUE THREAD

**Issue by laurentj** [clientIO/joint#53]
In a custom element view, I have a ```<text x="10" y="100"`>``` in the markup. however, after displaying the element, I see in the DOM that ```y="0.8"``` for **all** ```<text>``` node. Because of [this line of code](https://github.com/DavidDurman/joint/blob/master/src/vectorizer.js#L350)

This is very very annoying.

**Comment by kumilingus** [comment]
Let's say that was fixed https://github.com/clientIO/joint/blob/master/src/vectorizer.js#L372-L375
