### ISSUE TITLE
JointJS port positioning is broken in Chrome 57.

### ISSUE THREAD

**Issue by chihuahua** [clientIO/joint#535]
Visit any JointJS demo involving ports (such as this one) in Chrome 57 or higher.
http://resources.jointjs.com/demos/devs

You expect to see the ports positioned as expected like this:
![good](https://cloud.githubusercontent.com/assets/4221553/23726834/9b1989b6-040a-11e7-9ba2-859f9264c8ca.png)

Instead, you see this. I am using Chrome 58.0.3029.6 here. 
![bad](https://cloud.githubusercontent.com/assets/4221553/23726806/7e4699aa-040a-11e7-9ff1-9a5b8e710a9a.png)

A glance via dev tools reveals that the ports all stack atop each other on the top left corner.

I just want to actively raise this bug because ports seem like a pretty crucial feature to JointJS (for both free tier and paying Rappid users). Once Chrome 57 enters stable, this bug might wreak a little havoc.

Some of my friends' and my own projects are affected by this bug.

**Comment by chihuahua** [comment]
Fyi, it seems like JointJS JS logic is generating bad SVG transforms in Chrome > 57.

I made a JS fiddle out of the above demo's SVG: https://jsfiddle.net/fcufnyj8/3/

Notice that the fiddle's output looks the same in both Chrome 56 and 57. This points to some JointJS JS logic that differs between 56 and 57 as the culprit. The SVG itself is rendering as expected.

**Comment by kumilingus** [comment]
The `SVGTransformList` API is broken in Chrome Canary and here is a workaround for now. It'll be handled in the next release (March).

```javascript
V.matrixToTransformString = function(matrix) {
        matrix || (matrix = true);
        return 'matrix(' + [
            matrix.a || 1,
            matrix.b || 0,
            matrix.c || 0,
            matrix.d || 1,
            matrix.e || 0,
            matrix.f || 0
        ] + ')';
    };

V.prototype.transform = function(matrix, opt) {

        var node = this.node;
        if (V.isUndefined(matrix)) {
            return (node.parentNode)
                ? this.getTransformToElement(node.parentNode)
                : node.getScreenCTM();
        }

        if (opt && opt.absolute) {
            return this.attr('transform', V.matrixToTransformString(matrix));
        }

        var svgTransform = V.createSVGTransform(matrix);
        node.transform.baseVal.appendItem(svgTransform);
        return this;
};
```

Google Group conversation: https://groups.google.com/forum/#!searchin/jointjs/canary%7Csort:relevance/jointjs/RsTRa2ICSYY/TPFNxQ8KBAAJ

**Comment by chihuahua** [comment]
Thank you! That workaround seems to nicely suffice for now.

**Comment by ram4nd** [comment]
ETA on the release?

**Comment by kumilingus** [comment]
Next week.

**Comment by arifhussain353** [comment]
I did change these lines of code in `joints.js` but still not working.Is there any other file need to be change ?

**Comment by danbilauca** [comment]
For me it worked like a charm. I've added the `matrixToTransformString` to V and the `if` default jointjs transform function.

**Comment by arifhussain353** [comment]
Right now i am using `joints.js version 1.0.3` and my old code lines 
```javascript
   V.prototype.transform = function (matrix, opt) {

            if (V.isUndefined(matrix)) {
                return (this.node.parentNode)
                    ? this.getTransformToElement(this.node.parentNode)
                    : this.node.getScreenCTM();
            }

            var transformList = this.node.transform.baseVal;
            if (opt && opt.absolute) {
                transformList.clear();
            }

            var svgTransform = V.createSVGTransform(matrix);
            transformList.appendItem(svgTransform);
            return this;
        };
```
Replaced above lines of code with below lines of code  and also added `matrixToTransformString`  with jointjs transform function.Not working for me chrome 57.

```javascript

V.matrixToTransformString = function(matrix) {
        matrix || (matrix = true);
        return 'matrix(' + [
            matrix.a || 1,
            matrix.b || 0,
            matrix.c || 0,
            matrix.d || 1,
            matrix.e || 0,
            matrix.f || 0
        ] + ')';
    };

V.prototype.transform = function(matrix, opt) {

        var node = this.node;
        if (V.isUndefined(matrix)) {
            return (node.parentNode)
                ? this.getTransformToElement(node.parentNode)
                : node.getScreenCTM();
        }

        if (opt && opt.absolute) {
            return this.attr('transform', V.matrixToTransformString(matrix));
        }

        var svgTransform = V.createSVGTransform(matrix);
        node.transform.baseVal.appendItem(svgTransform);
        return this;
};
```

**Comment by kumilingus** [comment]
It's been confirmed @arifhussain353 case was not related to this issue.
