### ISSUE TITLE
node.set('position', {...}) doesn't move embedded shapes

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#557]
The call `node.set('position', {..})` moves the shape but leaves the embedded shapes at the old positions... I had to call `node.translate(x,y)` to move the shape properly. That was with `1.0.3`
Perhaps `dagre` integration for the layout should call `node.translate(x,y)`rather than `node.set('position', {..})`

**Comment by kumilingus** [comment]
This could be overriden with `setPosition` option.
```javascript
joint.layout.DirectedGraph.layout(graph, {
  setPosition: function(el, bbox) {
    el.translate(bbox.x, bbox.y);
    // el.position(bbox.x, bbox.y, { deep: true }); v1.2+
  }
});
```

**Comment by hijoncon** [comment]
@kumilingus is there a way I can position each node by category let say I want to position "all reds" in left, "all yellow" center and "all greens" to right while preserving the DirectedGraph layout. By default, its positions based on rank.

`all reds | all yellow | all green`

![Screen Shot 2020-12-07 at 3 06 22 AM](https://user-images.githubusercontent.com/556139/101343658-30ec0e80-3839-11eb-88d0-71f2b6ebfffd.png)

**Comment by kumilingus** [comment]
Hi @hijoncon, based on your other question I guess you have figured this out. The only option I can think of is to put the elements with the same color to a container element (embed them).

**Comment by hijoncon** [comment]
thank you for your reply @kumilingus, that what I did. I group them. But right now open a ticket related browser freeze in embed.
