### ISSUE TITLE
label: only one label is displayed after updating to latest version

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#562]
I was using an old version of rappid/jointjs and recently updated to the latest versions.

Now, my links only display one label, although several have been set.

Calling `graph.getCell('7ae74634-1d15-4531-ab4f-ab31cda37728').prop('labels')` clearly shows that there are 3 labels for example:

    [Object, Object, Object]

What could be wrong?

**Comment by kumilingus** [comment]
Hi, what is `graph.getCell('7ae74634-1d15-4531-ab4f-ab31cda37728').toJSON()` ?

**Comment by nico-onmap** [comment]
Actually all 3 labels are present, but get overwritten by the previous one.

I was using this to add my labels:

            cell.label(i, {
                position: .5,
                attrs: {
                    rect: { fill: 'white', class: 'link-title' },
                    text: { fill: 'black', text: label || '', y: y }
                }
            });

Incrementing y for each label so that a label do not overwrite the previous oen. It seems this doesn't work anymore: y property is set on the text element but it seems the label tag gets a transform property which basically inverts the value of y I have set so every label appear at the same y position.

**Comment by kumilingus** [comment]
You might try to position the label via `offset` property instead.
```
   cell.label(i, {
            position: {
                distance: .5,
                offset: { y: y }
            },
            attrs: {
                rect: { fill: 'white', class: 'link-title' },
                text: { fill: 'black', text: label || '' }
            }
        });
```
I'll take a look at the changes in the meantime.

Best,
Roman

**Comment by nico-onmap** [comment]
Thanks, that fixes the problem.
