### ISSUE TITLE
V.prototype.bbox does not return svg element after upgrade to joint 1.10

### ISSUE THREAD

**Issue by alp82** [clientIO/joint#565]
In `V.prototype.bbox` we got:

    if (!this.node.ownerSVGElement) return { x: 0, y: 0, width: 0, height: 0 };
    
This is a bug imo because it happens that objects return by `bbox` seem to require an svg element. For example in the `updateRelativeAttributes` method in the following line:

    var setResult = def.set.call(this, attrVal, refBBox.clone(), node, rawAttrs);

`refBBox.clone` is undefined because `refBBox` is a simple object that does not provide a clone function.

A simple fix would be to replace the first line with:

    if (!this.node.ownerSVGElement) return g.Rect(0, 0, 0, 0);

Tested on Windows 10, Chrome 57

**Comment by kumilingus** [comment]
Thank you. Fixed in https://github.com/clientIO/joint/pull/567.
