### ISSUE TITLE
Errors with TypeScript `--noImplicitAny`

### ISSUE THREAD

**Issue by andy-ms** [clientIO/joint#575]
To verify:

```sh
cd dist
tsc --noImplicitAny joint.d.ts
```

This can be fixed by adding type annotations in all the places the compiler gives you errors.
We'd like to deprecate `@types/jointjs` and just use `joint` (DefinitelyTyped/DefinitelyTyped#15561), but can't do that yet as we get `--noImplicitAny` errors in packages that depend on it.

**Comment by CaselIT** [comment]
I've added a pr to fix this issue so the DT types can be deprecated
