### ISSUE TITLE
Remove connect button after attached

### ISSUE THREAD

**Issue by wizardnet972** [clientIO/joint#577]
How to hide the button after link is attached?

![image](https://cloud.githubusercontent.com/assets/4997825/25117925/b634a780-241c-11e7-9ad9-68df2ece39a1.png)

**Comment by kumilingus** [comment]
The Halo plugin triggers various events. One of them is `action:link:add` that can be used here.
```javascript
    var halo = new joint.ui.Halo();
    halo.on('action:link:add', function(link) {
        if (link.graph) {
            // link is part of a graph i.e. was sucesfully added
            halo.removeHandle('link');
        }
    });
```
