### ISSUE TITLE
double click event doesn't fire after change the 'z' attribute on pointerup event (only Chrome 58)

### ISSUE THREAD

**Issue by franzzegarra** [clientIO/joint#585]
The double click event doesn't fire anymore once we change the 'z' attribute of an element (this change is made in the pointerup event). 

The error occurs only on Chrome 58. Works fine for other browsers.

I attached an example based on the last version of Joint.

[joint test.zip](https://github.com/clientIO/joint/files/970672/joint.test.zip)

**Comment by dorsha** [comment]
We got the same issue.
After upgraded to chrome 58 (windows machine), any click on the element doesn't work.

**Comment by kumilingus** [comment]
Related to https://bugs.chromium.org/p/chromium/issues/detail?id=5212.

**Comment by kumilingus** [comment]
Fixed in Chrome.
