### ISSUE TITLE
TS error: Property 'toggleClass' does not exist on type 'Vectorizer'.

### ISSUE THREAD

**Issue by FBeuselinck** [clientIO/joint#587]
The TypeScript definition for the 'Vectorizer' class is missing a property 'toggleClass'.
I could fix this by manually adding the property:
`toggleClass(className: string, toggle: boolean): Vectorizer;`

Can you guy's add this into one of your next builds or should i open a pull request for this?

**Comment by vtalas** [comment]
It's already there, waiting for the next release. It's fixed in the [master](https://github.com/clientIO/joint) branch.

**Comment by FBeuselinck** [comment]
Oh, i didn't notice this. I was using the version from the NPM repository. As i understand this is not the same as the version on Github (I'm quite new to all of this).
If i use the Github version and manually build the dist folder, the issue is indeed fixed. So all should be good with the next release.

Thank you for the quick response and keep up the good work!
