### ISSUE TITLE
Possible bug in LinkView.pointerup

### ISSUE THREAD

**Issue by jnbarchan** [clientIO/joint#589]
I wanted to draw your attention to _potentially_ nasty/bugged code in `LinkView.pointerup`.  I do not know whether the behaviour is safe/intended, it's worth a developer checking the logic.

`LinkView.pointerup` checks whether the source/destination of the link is acceptable.  If it is not, it either removes the link (if it is a new one being created) or reverts it to original (if it is an existing one being dragged).  The code looks "dangerous" particularly in the `remove` case.

            if (!paper.linkAllowed(this)) {

                switch (this._whenNotAllowed) {

                    case 'remove':
                        this.model.remove();
                        break;

                    case 'revert':
                    default:
                        this.model.set(arrowhead, initialEnd, { ui: true });
                        break;
                }
            }

`Paper.linkAllowed()` can return `false` if you have either `Paper.options.multiLinks = false` or `Paper.options.linkPinning = false`.

Taking the case of a newly-created link failing one of these tests, the code will execute `this.model.remove()`  That's fine, but are you aware that the code then _continues_ in this function rather than returning, with what is now a removed link?  This means, for example, that it may execute `this.model.reparent()`, and will still raise a notification via `this.notify('link:connect', ...)`.  I have had to write into my code handling of receiving a `link:connect` notification when in fact the link is no longer on the paper, when I'm (fairly) sure no such notification should be sent.

I am unsure of the implication for the `revert` case.

When a link is removed or reverted in this way, should the code be re-examined?

**Comment by kumilingus** [comment]
It should. Good catch!

**Comment by kumilingus** [comment]
Note for PR #626: When the link is removed or reverted we still have to clean other elementViews in the paper (in case `magnetAvailibility`/`elementAvailibility` option set to `true`).  Triggering of `link:pointerup` event stay untouched - even if the link is not part of the graph anymore.
