### ISSUE TITLE
DirectedGraph freezes in chrome

### ISSUE THREAD

**Issue by rovrov** [clientIO/joint#59]
Taking the example from this link and replacing joint and DirectedGraph with the 0.7.0 version (0.6.0 works fine):
http://www.daviddurman.com/automatic-graph-layout-with-jointjs-and-dagre.html

Firefox can layout the graph below but Chrome (31.0.1650.63) freezes, seemingly somewhere in the event handling code...

{"004408": ["004412", "004411", "004413"], "004409": ["004415", "004414"], "004406": ["004410", "004408"], "004407": ["004408", "004409"], "004405": ["004406", "004407"], "003302": [], "003311": [], "003291": [], "003307": [], "003308": [], "003309": [], "003298": [], "003299": [], "003296": [], "003297": [], "003306": [], "003295": [], "003292": ["003298", "003299", "003297", "003296", "003295"], "003293": [], "003290": [], "003303": [], "003285": [], "004415": ["003285"], "004414": ["003290", "003292", "003294", "003286", "003287", "003293", "003289", "003288", "003291"], "004416": [], "004411": ["003313", "003314", "003316", "003312", "003315"], "004410": ["004416"], "004413": ["003303", "003306", "003304", "003305", "003307", "003301", "003302", "003308", "003300"], "004412": ["003309", "003310", "003311"], "003304": [], "003305": [], "003294": [], "003310": [], "003300": [], "003301": [], "003289": [], "003288": [], "003313": [], "003312": [], "003287": [], "003286": [], "003316": [], "003315": [], "003314": []}

**Comment by kumilingus** [comment]
Can not be reproduced anymore.
