### ISSUE TITLE
Event handler in typescript

### ISSUE THREAD

**Issue by alialrabi** [clientIO/joint#599]
I'm trying to add event handler for jointjs paper in typescript,But don't found a way to implement it with joint js definition file. 
 
I have trying 

             this.paper.mouseclick(){}   

but get    TS2346: Supplied parameters do not match any signature of call target.

How to add event handler for rect and lines with typescript?

**Comment by kumilingus** [comment]
`this.paper.mouseclick()` is protected method not meant to be called directly. To attach event handlers please use `paper.on('cell:pointerclick', function() { /* your handler */ });`.
