### ISSUE TITLE
Errors in TypeScript definitions with `strict` enable

### ISSUE THREAD

**Issue by vhiairrassary** [clientIO/joint#600]
I am just trying the new TypeScript definitions and I have found more than 50 errors when adding `--strict` in my [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) (`tsc --version` 2.3.2):

You can easily reproduce the problem with `tsc --strict ./node_modules/jointjs/dist/joint.d.ts` (generated warnings are due to `--noImplicitAny` and `--strictNullChecks`).

```
ERROR in /opt/app/node_modules/jointjs/dist/joint.d.ts
(49,21): error TS7006: Parameter 'c' implicitly has an 'any' type.

ERROR in /opt/app/node_modules/jointjs/dist/joint.d.ts
(49,24): error TS7006: Parameter 'a' implicitly has an 'any' type.

[...]

ERROR in /opt/app/node_modules/jointjs/dist/joint.d.ts
(1210,13): error TS2411: Property 'circle' of type 'LogicAttrs | undefined' is not assignable to string index type 'CSSSelector'.

ERROR in /opt/app/node_modules/jointjs/dist/joint.d.ts
(1234,13): error TS2411: Property 'image' of type 'Image | undefined' is not assignable to string index type 'string | number | Object'.
```

Hope this report will be able to improve JointJS!

EDIT: TypeScript version & reproduction step have been added.

**Comment by vtalas** [comment]
fixed by #608
