### ISSUE TITLE
The ERD view rendering failed after jquery upgrade to 3.2.1

### ISSUE THREAD

**Issue by ylzsmallsun** [clientIO/joint#603]
version info:
joint.js: 0.9.6   backbone: 1.2.3   lodash: 3.10.1
In our project, the last jquery version is 2.2.3 . It works well with this version.
But it seems doesn't work with jquery 3.2.1. What's the cause? What should I do?
Below is the error info:
joint.js:formatted:3282 Uncaught TypeError: Cannot read property 'ref' of undefined
    at s.positionRelative (joint.js:formatted:3282)
    at s.<anonymous> (joint.js:formatted:3277)
    at lodash.js:23
    at lodash.js:25
    at Function.<anonymous> (lodash.js:30)
    at s.update (joint.js:formatted:3274)
    at s.r [as update] (lodash.js:26)
    at s.render (joint.js:formatted:3342)
    at s.renderView (joint.js:formatted:4643)
    at lodash.js:23

**Comment by kumilingus** [comment]
You have to update the JointJS or downgrade the jQuery I'm afraid.  `v0.9.6` is not compatible with newest jQuery because of the `selector` property being removed for jQuery object.

> .selector property on jQuery objects
> 
> The remaining purpose of the deprecated .selector property on a jQuery object is to support the deprecated .live() event. In 1.9, jQuery no longer attempts to maintain this property in chained methods, since the use of chained methods was never supported with .live(). Do not use the .selector property on a jQuery object. The jQuery Migrate plugin does not attempt to maintain this property.

**Comment by ylzsmallsun** [comment]
Got it. Thank you kumilingus so much!
