### ISSUE TITLE
Possibility to export jointJS graph to Microsoft Visio

### ISSUE THREAD

**Issue by fbrillante** [clientIO/joint#618]
Hi it would be useful to have an export of the graph in a Microsoft Visio format as enhancement to JointJS / Rappid tool, in addition to PNG and SVG export.

**Comment by fandomfilms** [comment]
Would like this as  well

**Comment by GeorgiyZhuravlev** [comment]
+1

**Comment by kumilingus** [comment]
Available in Rappid `v3.3`.
