### ISSUE TITLE
Type checking/casting in Angular 4/TypeScript

### ISSUE THREAD

**Issue by bayy** [clientIO/joint#620]
I started using jointJS in an app with Angular 4/Typescript. After some trial and error and I got it working. One of the first problem I got is the type checking error. For example, when trying the custom html element (https://resources.jointjs.com/tutorial/html-elements) with 

`joint.shapes.html.Element = joint.shapes.basic.Rect.extend({`
I got errors:
> Property 'html' does not exist on type 'typeof shapes'
> Property 'extend' is private and only accessible within class 'Model'.

To get around this, I change the code to the following 
`(joint.shapes as any).html.Element = (joint.shapes.basic.Rect as any).extend({`

Is this the right approach? What is the recommended approach to get around type checking with jointJs+Angular 4/Typescript?

**Comment by Shadowlauch** [comment]
+1 Same issue here.

**Comment by sunrock** [comment]
Same issue. I extend a custom shape

export class myElem extends joint.shapes.basic.Rect {
}

but I don't know how to define the ElementView of myElem.

**Comment by claymfinley** [comment]
instead of (joint.shapes as any).html.Element
you can always do: joint.shapes['html'].Element

**Comment by vtalas** [comment]
from the JointJS v2.0 you can use the static method `define` in typescript as well: 

```
import * as joint from "../../build/joint";

// declare a new shape using the `define`
var Html = joint.shapes.basic.Rect.define('html.Rect', {
    attrs: {
        rect: {fill: 'purple'}
    }
});

```
The `define` extends the namespace `shapes` and you can use the `Html` shape right away: 

```
let rect = new Html()
    .position(150, 50)
    .size(50, 50)
    .addTo(graph);
```
This step is not neccesary, but you can also let TS know about this change on the `shapes` namespace: 

```
declare module '../../build/joint' {
    namespace shapes {
        namespace html {
            class Rect extends joint.shapes.basic.Rect {}
        }
    }
}
```
Then, you're able to us the shape as `let recX = new joint.shapes.html.Rect()` without TS compilation errors
