### ISSUE TITLE
Not getting desired routing.

### ISSUE THREAD

**Issue by Marais** [clientIO/joint#623]
This is more of a question than an actual bug. If this is the wrong place, let me know where to log the issue/question:

Metro and Manhattan gives undesired results, e.g.:
![image](https://user-images.githubusercontent.com/1055516/29003939-b5dd91f4-7ac8-11e7-9201-79c64f284571.png)

I am trying to find a routing option that will do the following more or less:
![image](https://user-images.githubusercontent.com/1055516/29003937-9e44d912-7ac8-11e7-8d70-5b4d55a06ee3.png)
Any Idea how I can achieve this in jointjs?

**Comment by kumilingus** [comment]
You are going to need to add some vertices to the links (force them to route the desired way) or create a custom router (https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#routers.custom).
