### ISSUE TITLE
Cannot create links in capybara

### ISSUE THREAD

**Issue by p-salido** [clientIO/joint#624]
I have a Rails project that uses Joint and we have a view where a user creates a link between two elements by dragging. This functionality works in a real browser but fails in a capybara test with both current firefox and current chrome.

The test does:

```
        browser.action.
          move_to(from_element.native, 10, 10).
          click_and_hold.
          move_to(to_element.native, 10, 10).
          release.
          perform
```

... to simulate dragging a link from first to second element.

What happens in the test is this link does not get created.

If I change the test to:

```
        browser.action.
          move_to(from_element.native, 10, 10).
          click_and_hold.
          move_to(to_element.native, 10, 10).
          click.
          perform
```

... the link is created from the source element to a point in the background (paper?) rather than the destination element. Since the link is not to an element our subsequent JS code breaks. (Note: in a real browser a link must be to an element, one cannot create a link to background.)

Initially discovered on 0.9.6, I tried current master (1.1.1-alpha1) and it behaves the same way.

A fix or any thoughts regarding how to make the links in the tests are appreciated.

https://github.com/clientIO/joint/blob/master/test/e2e/links.js does not appear to cover link creation.

**Comment by kumilingus** [comment]
Any luck with this one?

**Comment by p-salido** [comment]
No change on my end so far.
