### ISSUE TITLE
Update to lodash 4 and rely on ciena-dagre instead

### ISSUE THREAD

**Issue by vspinu** [clientIO/joint#631]
graphlib moved to `lodash 4.11.1` and `dagre` is no longer maintained. New fork [ciena-dagre](https://github.com/ciena-blueplanet/dagre) seems to be the way to go. Would it be hard to bump the dependencies?

**Comment by sdiemert** [comment]
I was able to fix this issue for my own application by falling back on [Graphlib 1.0.7](https://github.com/cpettitt/graphlib/releases/tag/v1.0.7). 

Adjusting the layout to work with Graphlib 2.0.0 would be nice to avoid this issue for others in the future.

**Comment by kumilingus** [comment]
JointJS is now compatible with lodash v4. Here's an example how to integrate the `ciena-dagre` with `lodash v4` - https://github.com/clientIO/joint/tree/master/demo/lodash4

**Comment by vspinu** [comment]
Perfect. Thanks!
