### ISSUE TITLE
Typescript defintion discrepencies

### ISSUE THREAD

**Issue by coroiu** [clientIO/joint#647]
There seems to be a typo in the typescript defintions file where ```joint.shapes.logic.Not``` is defined as ```joint.shapes.logic.Note```. I was about to create a pull request but I wasn't sure about any testing routines, so I thought I'd create this issue instead.

**Comment by coroiu** [comment]
Apparently the are some other TS definition discrepancies. There are some missing member variables like ```joint.dia.Cell.graph``` that are available in the chrome inspector but not in TS. ```joint.dia.Cell.ports``` is also missing but that one seems to (?) be accessible through a ```joint.dia.Cell.getPorts``` method. However, I'm not sure if these are supposed to be private variables, but in that case, having a ```getGraph()``` method would be nice. Or maybe adding them to the definition as 'private' so that there is no confusion.

**Comment by mmacfadden** [comment]
There seem to be a lot of missing things in the Typescript definitions. I contributed the original attempt at them (which had several issues). There seems to have been a lot of refactoring that removed some functionality.

**Comment by vtalas** [comment]
@coroiu  `joint.shapes.logic.Note` is totally a bug, missing `cell.graph` as well, thank you for reporting it. The definition file is still not in good shape, but thanks to people like you, it's getting better and better. We appreciate your feedback! 

`cell.ports` is part of the deprecated functionality, this property is subject to removal. It will be removed most likely in the v2. There is an api for the ports: http://resources.jointjs.com/docs/jointjs/v1.1/joint.html#dia.Element.ports

**Comment by kumilingus** [comment]
TS definitions improved in JointJS `v2.0`. Please feel free reopen the issue if you find any definition missing/inaccurate in the current implementation.
