### ISSUE TITLE
Manhattan routing / DirectedGraph autolayout producing overlapped elements on programmatically created graph

### ISSUE THREAD

**Issue by elmart** [clientIO/joint#678]
I'm creating a graph programmatically, and then applying DirectedGraph autolayout. I am using 'manhattan' router for my links without specifying any `excludedTypes`. Therefore, I would expect no elements to be overlapped if possible. But I'm getting this after applying autolayout:

![autolayout](https://user-images.githubusercontent.com/135757/30688332-245609fe-9ebe-11e7-8eac-34f14f931650.png)

While I would expect this:

![expected](https://user-images.githubusercontent.com/135757/30688382-467a6aa2-9ebe-11e7-9fa4-8585469a3ef0.png)

The strange thing is that if i delete the wrong link (the one overlapping an element), and create it manually, I get the expected result.

I suppose the difference could be that when autolayout is first run, all node positions are [0, 0], and that somehow makes so that the link is set wrong (maybe because the overlapped node is positioned *after* the overlapping link).

Any ideas to avoid this?

**Comment by elmart** [comment]
It seems like a view refresh issue.
If I do `graph.fromJSON(graph.toJSON())` after relayout, everything gets as expected.

**Comment by kumilingus** [comment]
Hi, how do you load cells into the graph when the error occurs? `graph.fromJSON()` ?

**Comment by elmart** [comment]
Sorry I didn't answer before. For some reason, I didn't receive a notification on your answer, and I haven't manually looked until now.

No, I'm not using `graph.fromJSON()` to load cells initially. I don't have the json to load from.
I'm automatically generating a graph from a more abstract structure which I call serverModel by using a builder which first clears the graph then adds units, then adds links. This is:
```javascript
loadContext(serverModel) {
          new ServerModelGraphBuilder().buildGraph(this.graph, serverModel);
          this.layoutDirectedGraph();
}

class ServerModelGraphBuilder {
  buildGraph(graph, serverModel) {
    graph.clear();

    graph.set({
      id: serverModel.id,
      name: serverModel.name,
      type: 'app.Context',
      templateFormat: serverModel.templateFormat
    });

    this._buildUnits(graph, serverModel);
    this._buildLinks(graph, serverModel);
  }

  _buildUnits(graph, serverModel) {
    for (const unit of serverModel.units) {
      graph.addCell(_.assign({}, shapes[unit.type], {
        name: unit.name,
        unitConf: _.merge(
          getUnitTypeDefaultConf(unit.type),
          this._transformServerConfToClientConf(unit.conf)
        )
      }));
    }
  }

  _transformServerConfToClientConf(conf) {
    return _.cloneDeep(conf, (value, key) => {
      if (_.isString(key) && (key.match(/^(inPorts|outPorts|bounds)$/))) {
        const result = {};
        result[key] = _.cloneDeep(value);
        return result;
      }
    });
  }

  _applyBinding(binding, model) {
    if (binding.op == 'pluck') {
      const list = model.prop(binding.fromPath);
      const propName = binding.params[0];
      const initialValues = binding.params[1] || [];
      const result = [...list.map(item => item[propName]), ...initialValues];
      model.prop(binding.path, result);
      return;
    }

    throw new Error(`Unknown binding operation: ${binding.op}.`);
  }

  _buildLinks(graph, serverModel) {
    const elements = graph.getElements();

    for (const link of serverModel.links) {
      graph.addCell({
        type: 'app.Link',
        source: {
          id: elements.find(
            element => element.get('name') == link.source.name
          ).get('id'),
          port: `out-${link.source.port}`
        },
        target: {
          id: elements.find(
            element => element.get('name') == link.target.name
          ).get('id'),
          port: `in-${link.target.port}`
        }
      });
    }
  }
}
```

As I said before, the strange thing dissappear if after loading this way, I do `graph.fromJSON(graph.toJSON())`.

**Comment by kumilingus** [comment]
It seems, the problem will be in the DirectedGraph layout positioning elements one by one. At the time the link between `Evaluator` and `TextFormatter` is being updated (calculates manhattan) the `SingleKeyMemory` element has the default position (0,0) i.e. it's not an obstacle for the link yet.

Here's what I suggest.

```javascript
var tmpGraph = new joint.dia.Graph;
tmpGraph.addCells([el1, el2, ..., elN]);
tmpGraph.addCells([l1, l2, ..., lM])
joint.ui.DirectedGraph.layout(tmpGraph);
graph.resetCells(tmpGraph.getCells());
```

**Comment by elmart** [comment]
I understand why a first layout would fail (when positioning the wrong link, there are some units that will become obstacles that are not still there). Why I don't understand is why running layout a second time (once all nodes are already positiones) doesn't fix the wrong link.
What is it that gets done differently between running layout a second time, and resetting cells?

**Comment by kumilingus** [comment]
As JointJS is built on Backbone, setting the attribute value that is already stored on the model triggers no events.
```javascript
var model = new Model({ x: 5 });
model.set('x', 6); // triggers `change:x` and `change`
model.set('x', 6); // triggers no events
```
In your case the second layout sets the same elements' `position` as the first layout. Therefore no events are triggered and LinkViews do not update.

This should also do the trick (manually update the LinkViews).
`graph.getLinks().map(paper.findViewByModel, paper).forEach(view => view.update());`

**Comment by elmart** [comment]
Exactly. That's why I [said](https://github.com/clientIO/joint/issues/678#issuecomment-331399854) this seemed to be a view refresh issue.
To me, the ideal solution would be for link elements to change some attribute (so that their view refreshes) when the physical routing path would change, even if source and destination remain the same.
Do you think that's feasible?

**Comment by kumilingus** [comment]
Maybe something like below would work (not tested).

1. A naive solution
```javascript
joint.layout.DirectedGraph.layout(graph, {
  setPosition: function(element, glNode) {
      element.set({
        position: {
          x: glNode.x - glNode.width / 2,
          y: glNode.y - glNode.height / 2
        },
        refresher:  (element.get('refresher') || 0) + 1
     });
  }
});
```

2. Hacky, but performant solution.
```javascript
joint.layout.DirectedGraph.layout(graph, {
  setPosition: function(element, glNode) {
      element.set('position', {
         x: glNode.x - glNode.width / 2,
         y: glNode.y - glNode.height / 2
      }, { cacheOnly: true /* will not update links yet */ });
  },
  setVertices: function(link, points) {
      var vertices = points.slice(1, points.length - 1);
      // trigger view update manually 
      link.unset('vertices', { silent: true });
      link.set('vertices', vertices);
  }
})
```
This scenario is definitely something to have in mind when we work on refactoring the links (after `v1.2` JointJS release). To define better control of how/when links are updated.

**Comment by elmart** [comment]
None of the above approaches worked.
First one didn't produce any noticeable change.
Second produced the following:
<img width="993" alt="screen shot 2017-10-23 at 14 30 53" src="https://user-images.githubusercontent.com/135757/31889174-1cdf6440-b7ff-11e7-86a2-d18102c4ebb9.png">

In any case, it's ok for me by now, as far as this is taken into account for 1.2 release, as you indicated. Do you want me to add some kind of tag so that it doesn't get forgotten?

**Comment by WaldoJr24** [comment]
Years later, and I have exactly the same problem, have you found a solution?
![Screenshot 2024-11-05 170318](https://github.com/user-attachments/assets/859bc224-a558-4d19-b5c0-527f8a993a27)

**Comment by kumilingus** [comment]
How is this picture related to this thread?
If you are looking for a solution that prevents links from overlapping other links, please see: https://www.jointjs.com/demos/libavoid-standalone-link-routing

**Comment by WaldoJr24** [comment]
I just wanted to show how the links lie on each other. 
Thanks thats what i searched for.

**Comment by WaldoJr24** [comment]
Your routing works perfectly, thanks for the good implementation.

I have one more question: do you know why the links always have a small gap to the port itself? Depending on the width of the label or its bbox.

Do you know how I can leave the labels out of the bbox calculation?

Here is a picture to show you what I mean:

![image](https://github.com/user-attachments/assets/c47f77b9-14dd-4b73-8042-f4186551b8fc)
