### ISSUE TITLE
Error invalid value for transform

### ISSUE THREAD

**Issue by gcharpentier** [clientIO/joint#68]
I have this error : 
Error: Invalid value for <text> attribute transform=" " joint.nojquery.js:8622

This test in setAttribute correct the error but i don't if is the good way :+1: 

 if(name=="transform" && value == " ")
            value='';

Thanks

**Comment by umaire313** [comment]
Hi,
i am new in joint.js and i need help.
i want to resize the elment same as in this link

http://jointjs.com/rappid#2b1874b1-ff72-4d97-ae8e-6ad978369b3e

click on rectangle rectangle become in editable form user can resize it rotate it draw link etc.
