### ISSUE TITLE
problems with highlight event/validateConnection in new jointjs

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#687]
I'm trying to update to latest jointjs version and it seems there is a change in the way highlight event is called.

What happened before:
--
If I start drawing a link, the highlight event is sent once I hover elements.

What seems to happen after updating:
--
Once I the mouse button is down on the arrow to draw a link, the highlight event is sent once to *all* the elements found in my graph. Then, if I hover an element, it receives the highlight event (that's expected).

What happened? Note that the same problem happens with the validateConnection() method that's called on each element of the graph.

**Comment by kumilingus** [comment]
It sounds like the `markAvailable` [paper option](https://resources.jointjs.com/docs/jointjs/v1.1/joint.html#dia.Paper.prototype.options.markAvailable) was switched on. Could you please double check?

**Comment by nico-onmap** [comment]
Yes, I had `markAvailable` enabled.

The question is: has the behavior of this option changed? In the previous jointjs version this didn't call highlight on each element.

**Comment by kumilingus** [comment]
As far as I know, there were no changes to this feature. What version are you trying to upgrade from?

**Comment by nico-onmap** [comment]
I'm updating from `rappid 1.7.0`.

**Comment by kumilingus** [comment]
The highlighting of elements/links was changed in `v2.0`. It's now calling `highlight` for every available-to-connect element with `{ magnetAvailability: true }` flag to enable you to choose a custom highlight method vs. adding hard-coded class name prior `v2.0`.
