### ISSUE TITLE
Depth problem when adding a child before its parent

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#688]
If I create two cells: a child and a parent, embed the child into the parent, then add both elements into my graph using the following code:
```graph.addCells([child, parent]);```

The children will be drawn behind the parent, until the parent is grabbed and moved using the mouse.

To reproduce the problem, simply open the [bpmn demo](https://resources.jointjs.com/demos/rappid/apps/BPMNEditor/index.html), open the devtools, and type the following into the console:

```javascript
var chore = new joint.shapes.bpmn.Choreography(); chore.prop({position: { x: 20, y: 240 } });
var pool = new joint.shapes.bpmn.Pool(); pool.prop({position: { y: 200 } });
pool.embed(chore);
graph.addCells([chore, pool]);
```

*What happens?*
The chore object is not visible (it's drawn behing the pool).

*What should happen?*
Since the chore object is embbeded into the pool, it should be drawn above the pool.

Note: the problem happens with latest public release (`Rappid 2.1`).

**Comment by kumilingus** [comment]
The stack control in JointJS can be controlled via `z` attribute (A cell with greater stack order is always in front of an element with a lower stack order). In case 2 cells shares the same `z` value, the cell added later to the graph will be in front of the other.

You have several options here.
```javascript
// 1. adding cells in proper order
graph.addCells([pool, chore]);
// 2. using `z` attribute.
var chore = new joint.shapes.bpmn.Choreography(); chore.prop({position: { x: 20, y: 240 }, z: 2 });
var pool = new joint.shapes.bpmn.Pool(); pool.prop({position: { y: 200 }, z: 1 });
pool.embed(chore);
graph.addCells([chore, pool]);
// 3. calling `toFront()`
pool.toFront({ deep: true })
```
Note, that in the embedding paper mode (`{ embeddingMode: true }`) the elements along with their descendants are brought to front automatically when the user drags them.

**Comment by nico-onmap** [comment]
> Note, that in the embedding paper mode ({ embeddingMode: true }) the elements along with their descendants are brought to front automatically when the user drags them.
I think that if this option is set, elements should be brought to front automatically when dragging them, but also on the initial rendering of the graph.

I already tried to call toFront on each direct children of my graph but it was slowing down the rendering too much. I'll see if updating the z property instead is enough.

**Comment by ujjawalhub** [comment]
Use fitEmbeds() instead of toFront().
My case ->
`rect.embed(child);`
`let id = e_rect.id;`
`graph.addCell(rect, child);`
`rect.position(10,10, { parentRelative: true });`
`rect.fitEmbeds({deep : true ,padding: { top: 30, left: 10, right: 10, bottom: 10 }});`

**Comment by kumilingus** [comment]
This should fix the issue with the performance. Freeze it, so the paper does not sort elements multiple times and does unnecessary updates.
```
var paper = new joint.dia.Paper({ frozen: true, model: graph, sorting: joint.dia.Paper.sorting.APPROX });
// 1. load element and links
// 2. call toFront() on elements
paper.unfreeze();
```
