### ISSUE TITLE
TypeScript definitions problem

### ISSUE THREAD

**Issue by dragosbulugean** [clientIO/joint#690]
I have a TS project which depends on jointjs.
My TS projects is strict in the sense that it doesn't allow implicit 'any'.
But the d.ts of this library has types 'any' so my project doesn't compile.
What would be a solution to this?

**Comment by vtalas** [comment]
hi this already fixed in the master branch, it will also be part of the JointJS v1.2.

**Comment by dragosbulugean** [comment]
Ok. For anyone else encountering this problem, you can have a npm postinstall script - rm node_modules/jointjs/dist/joint.d.ts to temporarily fix until the release comes through, and import using require('jointjs'). Closing this.
