### ISSUE TITLE
joint.mvc.View missing from typescript definitions

### ISSUE THREAD

**Issue by mmacfadden** [clientIO/joint#694]
We have code that uses this class, but it is now missing from the tsd files. This is causing compile errors in our code.

**Comment by mmacfadden** [comment]
I also noticed that the paper class's type definition actually looks like this:

`class Paper extends Backbone.View<Graph>`

But this is not actually true, since the actual code is like this:

`joint.dia.Paper = joint.mvc.View.extend({`

So there is inconsistency between the type defs and the code.  We had been extending joint.mvc.View in our code so that we could render items onto the paper with support for theming. Simply extending Backbone.View would cause problems.

**Comment by kumilingus** [comment]
Fixed in `v2.0.0`.
