### ISSUE TITLE
Typescript definitions incorrectly use 'Object' type

### ISSUE THREAD

**Issue by mmacfadden** [clientIO/joint#703]
There are several places where the Typescript definitions use the `Object` type.  For example:

```
class Link extends Cell {
        markup: string;
        labelMarkup: string;
        toolMarkup: string;
        vertexMarkup: string;
        arrowHeadMarkup: string;

        constructor(attributes?: LinkAttributes, options?: Object);
...
```

This is incorrect.  In JavaScript the Object constructor is a specific object type that has a fixed set of methods (toString(), etc.). If you define an input argument as Object, then you are telling the compiler that the thing that will be EXACTLY an Object and nothing more. So for example, when creating a Link, the way it is defined you could not do this:

```JavaScript
const link: Link = new Link({}, {myOption: "foo"));
```

A vanilla Object does not have the `myOption` property, and so the compiler will complain. You can read more about this here: https://stackoverflow.com/questions/18961203/typescript-any-vs-object/18961903

We have a few options as to what we could put here instead of `Object`:
* **any**: This would allow any typescript type. Even primitives like numbers, booleans, etc. If you do not want to allow primitives, any might be a bad choice. This does not give the user a hint has to what they are supposed to pass in.
* **object**: (note the lower case ‘o’) This allows any type EXCEPT primitives. So now you can’t pass in numbers and Booleans. You can pass any arbitrary object so `{foo: 1}` will work just fine. The down side here is that technically passing in `new Date()` would also still work; we are better off but still don’t tell the user what to pass in.
* **{[key: string]: any}**: Now we are saying that we are expecting a generic javascript object with strings as properties and anything for a value. This is what I think we want in most cases if we are expecting people to pass in json objects. It’s fairly explicit. The only down side here is that I assume in at least some of the places we are doing this there is actually some “shape” to the object, some options that actually are expected. If that is the case we should define an interface. But this would be better than where we are today.

I wanted to get thoughts on this. If we agree, then I am happy to make the changes and issue a PR.

Thoughts?

**Comment by kumilingus** [comment]
Hi Michael, I also like the 3rd option the most.Where it makes sense we can define options more precisely as shown below.
```javascript
position(x: number, y: number, options?: { parentRelative?: boolean, deep?: boolean, [key: string]: any }): this;
```

**Comment by mmacfadden** [comment]
@kumilingus I agree. I think if we start by just replacing `Object` with `[key: string]: any`, then things will "work" for now. Then we can circle back to create more specific options when we have time.

**Comment by kumilingus** [comment]
@mmacfadden I am happy with this. Feel free to make the changes. Thank you.

**Comment by vtalas** [comment]
It turns out that even with type `[key: string]: any` you'd be able to pass an instance e.g. `new Date()` etc.  `object` and `[key: string]: any` seems the same for me.

**Comment by mmacfadden** [comment]
@vtalas you are correct from a compiler error stand point. Just about anything you could call an `object` can be passed in to a {[key: string]: any} argument. This is because ALL javascript objects are essential string-to-any maps. 

However, the intent of the function is much clearer to the developer using the index signature approach. If I say `object` to the user it is not clear how I am intending on using that object. If you pass in `new Date()` to `options`, perhaps somehow the date itself is used as the option. When you specify the index signature approach you are more clearly telling the user you are expecting something like `{foo: bar}`. They can still pass any other kind of non-primitive value in, but I have told them I am going to treat that thing like a JSON object and just look at the key value pairs, rather than care about the type of the object or use any "prototype" functions.

That said, if the TS Defs had used object, I probably would not have bothered changing them since they are similar as you say. But they were using "Object" which wasn't working :-)

I suppose we can close this issue now?

**Comment by vtalas** [comment]
It totally makes sense. Also the `Object` wasn't god choice at all. I'm closing the issue, thanks for your help.
