### ISSUE TITLE
Port custom properties are lost when json formatted graph is imported.

### ISSUE THREAD

**Issue by fullammo** [clientIO/joint#709]
Hello!

I am using the devs plugin and i came across an issue. When i export my graph to JSON, my custom properties that i added to every single ports attributes are present in the file , but when i import it again its going to erase it, and only presents the port's label in the 'attrs' array.

Is there any way to tweak this?
Thanks in advance,
Bende

**Comment by kumilingus** [comment]
Hi, you can use the Port API directly on arbitrary shape. Do not use `devs` plugin.

Docs: https://resources.jointjs.com/docs/jointjs/v2.0/joint.html#dia.Element.ports

```javascript
var YourElement = joint.dia.Element.define('your.Element', {
  attrs: {
    rect: {
      refWidth: '100%',
      refHeight: '100%',
      stroke: 'black',
      fill: 'lightblue'
    }
  }  
}, {
  markup: 'rect'
});

var el = new YourElement;
el.resize(200,200);
el.position(100, 100);
el.addPort({
  attrs: {
    circle: {
      'magnet': true,
      'stroke': '#31d0c6',
      'stroke-width': 2,
      'fill': '#ffffff'
    }
  },
  yourData: {
    x: 'y'
  }
});
el.addTo(graph);
