### ISSUE TITLE
Paper doesn't render existing graph cells

### ISSUE THREAD

**Issue by mmacfadden** [clientIO/joint#716]
I have a utility that turns some arbitrary JSON content into a Graph. I then construct a Paper passing it said graph as a model. The Paper does not render any of the cells in the Graph. It seems that you have to add the objects to the graph AFTER it is put into the Paper. The Paper constructor adds listeners to the graph, but does not seem to look at the current contents. Perhaps this is by design.

I have figured out a workaround for now, but it looks somewhat ugly.

```TypeScript
const paper: joint.dia.Paper = new joint.dia.Paper({
  el: this.$element,
  model: this.graph, // existing graph
  gridSize: 1,
  interactive: false
});

// without this line, the current graph contents are not rendered
this.graph.getCells().forEach(cell => paper.renderView(cell));
```
Would it make sense to do something like this in the Paper constructor directly?

**Comment by kumilingus** [comment]
The problem is that we don't know if the paper element is in the DOM (it's currently required for the elements and links to be correctly rendered).
```
const paper: joint.dia.Paper = new joint.dia.Paper({
  model: this.graph, // existing graph
  gridSize: 1,
  interactive: false
});
// cellViews are rendered incorrectly now
paper.$el.appendTo(document.body);
```
We are currently investigate the way to measure DOM elements in pure javascript (no need for cellViews to be in the DOM).
There is also an API proposal that would fix this issue by moving the paper off-screen during init phase (https://github.com/clientIO/joint/issues/407).

**Comment by mmacfadden** [comment]
I see. Couldn't you use something like:

```JavaScript
document.body.contains(this.$el);
```
inside the paper to determine if the element is in the current DOM?

**Comment by kumilingus** [comment]
We could. This does not help in the example I provided though. The existing graph cells end up not being rendered again. So it'd be only a partial solution for this issue.

**Comment by mmacfadden** [comment]
True.

**Comment by kumilingus** [comment]
Solution for `v3.0.0`.

```javascript
const paper: joint.dia.Paper = new joint.dia.Paper({
  model: this.graph, // existing graph
  gridSize: 1,
  interactive: false,
  frozen: true // prevent rendering for now
});
// cellViews would be rendered incorrectly at this point if no `frozen` option used
paper.$el.appendTo(document.body);
// It's now ok to start rendering the cellViews
paper.unfreeze();
```
