### ISSUE TITLE
Natural arrow head direction using "smooth" connector with vertices option

### ISSUE THREAD

**Issue by kiikura** [clientIO/joint#72]
Now, arrow head rotation is decided by previous vertex location.
In using the smooth connector, we should use the neighbor bezier reference point than the through vertex (or route) point. 

```
_translateAndAutoOrientArrows: function(sourceArrow, targetArrow) {
    ...
    if (sourceArrow) {
        sourceArrow.translateAndAutoOrient(
            this.sourcePoint,
            _.first(this.route) || this.targetPoint, // Here
            this.paper.viewport
        );
    }
   ...
```

**Comment by kumilingus** [comment]
An option for now is to use SVGMarkers for the arrowheads. Please see this [JSFiddle](http://jsfiddle.net/kumilingus/fjzvqhhk/).

**Comment by kumilingus** [comment]
`v1.1` will have built-in markers. Please refer to `sourceMarker` and `targetMarker` attributes.
