### ISSUE TITLE
Scale is 0 after Paper.scaleContentToFit();

### ISSUE THREAD

**Issue by mmacfadden** [clientIO/joint#751]
I am having an issue where after calling `Paper.scaleContentToFit()` the scale of the paper is set to `{sx: 0, sy: 0}`. I am still working on reproducing the issue in a snippet, but am having trouble doing so. This is mainly happening inside the application we are developing. I was wondering if anyone has seen this before?

In the meantime I will work on a snippet to reproduce.

**Version**: 1.1.0
**Browser**: Chrome
**OS**: OSX

**Steps:**
1. Create a new Graph / Paper and add some shapes to it.
1. Call `paper.scaleContentToFit();`
1. Call `const scale = paper.scale();`

**Actual Result:**
The scale variable will be: `{sx: 0, sy: 0}`.

**Expected Result:**
The scale should be the actual scale of the paper.

**Comment by mmacfadden** [comment]
It turns out that this happens if the `fittingBox` option is not provided AND the paper's options does not contain a heigh and width value. The width of the box to find winds up being non-sensical in the code. Scaling does occur but the sx/sy values wind up 0 some how. I might recommend adding some error checking somewhere for this.

**Comment by kumilingus** [comment]
How comes that the paper's options does not contain the height and width value? There are some default values set at init https://github.com/clientIO/joint/blob/master/src/joint.dia.paper.js#L8-L9.
It makes kind of sense that scale returned is 0,0 if he paper has zero dimension.

**Comment by mmacfadden** [comment]
I took a look at the code and somehow the height and width were set to undefined.  Interestingly if you do this: 

```JavaScript
const paper = new joint.dia.Paper({});
```
the paper will have the default height and widths.  If you do this:

```JavaScript
const paper = new joint.dia.Paper({height: null, width: null});
```

I think you get an error.  However, if you do this:

```JavaScript
const paper = new joint.dia.Paper({height: undefined, width: undefined});
```

```JavaScript
let height; // somehow these variable wind up undefined.
let width;
const paper = new joint.dia.Paper({height: height, width: width});
```
There is no error and the paper winds up having no height or width, however CSS can actually still cause the paper to be a certain dimension, so things still render fine, but you have an odd situation.  If you omit a key, Backbone uses the default.  However it seems like when the key is in the attributes passed in, but is undefined, it still replaces the default value, but with undefined.

**Comment by kumilingus** [comment]
Added minimum scale value in f40c4f2fe0e344afed759e5c964deb0f466583d7 (1e-6).
