### ISSUE TITLE
Rappid 2.2 Typescript type definitions file issues

### ISSUE THREAD

**Issue by randy-stad** [clientIO/joint#754]
I've found a couple of issues with the type definition file for Rappid 2.2, a missing function definition for Navigator and highlighting options misspelling for Paper.  Here is a diff:

```
2424c2424
<         options?: HighlighterArgumentsMap[K];
---
>         opt?: HighlighterArgumentsMap[K];
3260,3261d3259
< 
<         updateCurrentView(): void;

```

**Comment by kumilingus** [comment]
Hi Randy,
1. Here's fix for the highlighters typo https://github.com/clientIO/joint/pull/755
2. Navigator's `updateCurrentView()` method is not meant to be public. Is there any specific case where calling this method is necessary?

Thank You.

**Comment by randy-stad** [comment]
Thanks Roman.

The use case for needing updateCurrentView() is I need to programmatically
change the size of the PaperScroller associated with the Navigator (I have
a slider that allows the user to change the size of the paperscroller and a
sidebar).  If I do not call updateCurrentView() on the Navigator, it
doesn't recognize the new size of the PaperScroller (I programmatically set
left and right values).

Randy

**Comment by kumilingus** [comment]
I see, that make completely sense. We'll make the method public. Thank You.
