### ISSUE TITLE
LinkView: disallow changing link source/target

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#756]
Is there a way other than using `css/pointer-events:none` to prevent the user from changing the source of target of a link once it has been created?

I could not find anything in the JointJS documentation.

**Comment by kumilingus** [comment]
Please use the paper's `interactive`option `{ arrowheadMove: false }`.
http://resources.jointjs.com/docs/jointjs/v2.0/joint.html#dia.Paper.prototype.options.interactive

**Comment by kumilingus** [comment]
Check out `v2.1.0` where is up to you to decide what tools (arrowheads, vertices, segments you wish to make available for your users).
