### ISSUE TITLE
How to highlight all element relative to a cell on diagram

### ISSUE THREAD

**Issue by andRave** [clientIO/joint#773]
I'm implementing a task relative to draw the diagram. It requires that when the user hovers on a cell of the diagram, it will highlight all preceding and subsequent of that cell and links. I found just how to highlight one element by clicking it. Is it possible to do?

**Comment by andRave** [comment]
I have solved this but there another problem with link highlighters.
<img width="704" alt="2017-12-01 13 59 12" src="https://user-images.githubusercontent.com/15156046/33482370-61913724-d6a1-11e7-9365-d0235d4c7391.png">
Have you any idea how to solve it?

**Comment by kumilingus** [comment]
You need to specify a particular `SVGPath` to be highlighted (by default it highlights the entire view i.e. `SVGGroup`) .

`linkView.highlight('.connection');`

**Comment by andRave** [comment]
Thanks a lot! It works fine.
