### ISSUE TITLE
I want to use Vue to do a flowchart demo with the joint js. but i have a question

### ISSUE THREAD

**Issue by blacklisten** [clientIO/joint#774]
The paperScroller package g is defined in the rappid what i used,
but I have import the jointjs in this file,
for example, 'var g = joint.g the result is undefined'.
I import the module by require;
It cause an error :'You can't find the jointjs in the source file';
I do not find the  operation in the source demo.
I just replaced the HTML file with the Vue file but I don't know why not?
Please let me know:Better support for Vue. Js about this  ,or there are better configurations elsewhere to solve the problem of introducing the jointjs in the source code.
pelase tell me ,thank you!

**Comment by kumilingus** [comment]
Here's an example of how to integrate JointJS with VueJS - https://github.com/JoseGoncalves/vue-jointjs.
