### ISSUE TITLE
Halo: right-clicking on halo triggers the action

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#777]
Right-clicking on an halo handle should not trigger the action.

To reproduce, open the [bpmn demo](https://resources.jointjs.com/demos/bpmn), click on an element, and right-click on the `x` button.

This happens with the latest version.

**Comment by kumilingus** [comment]
It will be resolved in the upcoming patch release.

**Comment by kumilingus** [comment]
Fixed in Rappid `v2.3.2`.
