### ISSUE TITLE
transform attr is error when the scalableBBox.width is 0

### ISSUE THREAD

**Issue by xunonxyz** [clientIO/joint#780]
transform attr is error when the scalableBBox.width is 0
and my code is(in the resize function):

 var sx = scalableBBox && scalableBBox.width? (size.width / scalableBBox.width) : 1;
 var sy = scalableBBox && scalableBBox.height? (size.height / scalableBBox.height) : 1;
 scalable.attr('transform', 'scale(' + sx + ',' + sy + ')');

**Comment by kumilingus** [comment]
Hi, how is this different from the [current code](https://github.com/clientIO/joint/blob/master/src/joint.dia.element.js#L523-L525) ?
