### ISSUE TITLE
Incompatible typescript definitions

### ISSUE THREAD

**Issue by doender** [clientIO/joint#781]
After upgrading to jointjs 2.0 and using typescript, I came across 2 errors:

-  `'position' does not exist in type 'Port'`
- When using `"100%"` as value for paper width: `Types of property 'width' are incompatible. Type 'string' is not assignable to type 'number'.`

**Comment by vtalas** [comment]
Thank you for pointing this out, we've updated the ts definition file (#785 ) for ports and port groups. 

The paper width, however, remains with the numeric type as the width defined in percentage is not fully supported - e.g. `paper.getArea()` doesn't give the right values.
