### ISSUE TITLE
Performance of setting position dependent on position

### ISSUE THREAD

**Issue by doender** [clientIO/joint#782]
When using DirectedGraph's auto-layout feature, we have found that the time `element.position(x,y)` takes is dependent on the values of `x` and `y`. 

For example, setting a node to `element.position(0,0)` takes almost no time, whereas setting a single node to `element.position(5000, 5000)` can take up to 2 seconds!

I have found this in jointjs 1.0.2 as well as version 2.

What is causing this and can it be fixed?

**Comment by kumilingus** [comment]
It does not depend on values of `x` and `y`. Maybe `element.position(0, 0)` did nothing because the position was already set at `0,0`? Note that a single change of the position can trigger multiple views to update (e.g. element view itself and all the link views connected updates).

**Comment by doender** [comment]
In my app, this code
```
joint.layout.DirectedGraph.layout(this.graph, {
   setPosition: (el, bbox) => el.position(0.1 * bbox.x, 0.1 * bbox.y);
});
```
runs 100 times slower as this:
```
joint.layout.DirectedGraph.layout(this.graph, {
   setPosition: (el, bbox) => el.position(10 * bbox.x, 10 * bbox.y);
});
```

Maybe somehow in my particular app updating the position does (somehow) depend on the position itself, although I cannot see how. For now I have the following workaround:

```
joint.layout.DirectedGraph.layout(cells.concat(links), {
   setPosition: (el, bbox) => {
      // Instead of setting position, set attributes directly and then reset cells afterwards
      el.attributes.position.x = bbox.x;
      el.attributes.position.y = bbox.y;
   }
});
this.graph.resetCells(cells.concat(links));
```

**Comment by doender** [comment]
It seems the above fix is not the way to go, as subsequent `cell.remove()` calls don't have any effect when the graph is drawn in this way.

**Comment by kumilingus** [comment]
`freezing`/`unfreezing` the paper should ultimately resolve the issue. This way you get the minimal number of DOM updates.
```javascript
paper.freeze();
joint.layout.DirectedGraph.layout(this.graph, {
   setPosition: (el, bbox) => el.position(0.1 * bbox.x, 0.1 * bbox.y);
});
paper.unfreeze();
```
