### ISSUE TITLE
Slow performance while dragging

### ISSUE THREAD

**Issue by Luiz-N** [clientIO/joint#784]
When multiple nodes are selected and a user attempts to drag them around the paper there is a very noticeable lag. It is worse if there are links and enough nodes being dragged around can completely lock up the the browser until the user stops.

Not sure the cause but we are using custom svg icons with the default settings for the "manhattan" smart router. I thought this router might be the issue but it is slow even when dragging around nodes with no links.

Are there any "best practices" for speeding up performance of dragging around large number of nodes?

**Comment by jmesa-sistel** [comment]
When do you update links?
I update links on cell:pointerup and I have no performance issues
Also the best browser for svg is a chromiun based one.

**Comment by kumilingus** [comment]
Here are the tips.
1. Use paper `async` mode.
2. use or inherit from `joint.shapes.standard.Link` (do not use `joint.dia.Link`) together with `dia.linkTools`.
3. The `manhattan` router is not meant to be used with large graphs.
