### ISSUE TITLE
Smart routing manhattan not giving orthogonal lines 

### ISSUE THREAD

**Issue by pathikdevani** [clientIO/joint#786]
Two ``React`` element with ``top, bottom, right, left`` ports and elements are connected via link. Here i am using ``manhattan`` router.  But i am not getting line segment 100% vertically & horizontally.

Elements port configuration
```javascript
...
ports: {
    groups: {
        'left': {
            position: {
                name: 'left'
            }
        },
        'bottom': {
            position: {
                name: 'bottom'
            }
        },
        'top': {
            position: {
                name: 'top'
            }
        },
        'right': {
            position: {
                name: 'right'
            }
        }
    }
}
...
```

Link configugration
```javascript
...
source: {
    id: iBlock.id,
    port: 'top'
},
target: {
    id: bBlock.id,
    port: 'right'
},
router: {
    name: 'manhattan',
}
...
```

Demo: [https://jsfiddle.net/pathikdevani/8qkLbxad/](https://jsfiddle.net/pathikdevani/8qkLbxad/)
Expected result: link should be collection of orthogonal(horizontal & vertical) segments.

JointJS version: 2.0.1
Browser : Google Chrome, Mozilla Firefox

**Comment by vtalas** [comment]
Hi,

this can be sorted out by setting the right options, for more information
visit this thread
https://groups.google.com/forum/#!msg/jointjs/KdtV-jWT3k4/31H9iy6_BwAJ

In short: try to match the values of `gridSize` on paper and `step` for the
manhattan router :


router: {
                name: 'manhattan', args: {step: 5}
            }

then set the `gridSize: 5`. You'll see an instant improvement.

Regards,

Vladimir


2018-01-05 12:16 GMT+01:00 PathikDevani <notifications@github.com>:

**Comment by pathikdevani** [comment]
Hi Vladimir,

It is exactly what I need.

Thanks

**Comment by pathikdevani** [comment]
Still getting the same issue.

check link between node id 1 and 5, 1 and 6. Also, a link is not started and ended from center of port (a link between 1 and 7).

[https://jsfiddle.net/pathikdevani/8qkLbxad/](https://jsfiddle.net/pathikdevani/8qkLbxad/)

**Comment by vtalas** [comment]
I forgot to mention one more thing... In your example, there are node positions off the grid. When you have the grid size === 10, then you should have the nodes positions dividable by 10 as well. 

You don't need to care about this, just call the `paper.snapToGrid` function, it will adjust the position to be on the actual grid. So in your code, you would have: 

(~line 380)
`block.set("position", paper.snapToGrid(node.position.x , node.position.y));`

also, you can visualize the grid - check the http://resources.jointjs.com/docs/jointjs/v2.0/joint.html#dia.Paper.prototype.options.drawGrid

**Comment by pathikdevani** [comment]
``paper.snapToGrid``  is working fine in this problem. 

Thanks @vtalas
