### ISSUE TITLE
TextBlock foreignObject adds multiple body tags.

### ISSUE THREAD

**Issue by mmacfadden** [clientIO/joint#787]
I am currently using JointJS 1.1.0 and the most recent version of Chrome.

I have run into this issue when using JointJS and JSTree together: https://github.com/vakata/jstree/issues/1920

The crux of the issue is that JSTree append a `<ul>` element to the `<body>` element of the page in order to display a context menu.  When using a TextBlock, a foreignObject is inserted into the page, and the resulting HTML looks something like this:

```HTML
<foreignObject class="fobj" id="v-9" width="120" height="80">
  <body xmlns="http://www.w3.org/1999/xhtml">
    <div class="content" id="v-8" y="0.8em" display="none" xml:space="preserve" style="width: 120px; height: 80px;">
      <div>Some HTML</div>
    </div>
  </body>
</foreignObject>
```

The issue is the `body` tag inside the foreignObject. To my knowledge a single Document is really only supposed to have one body tag. I do notice the xmlns attribute that potentially would separate them.  JSTree is using a JQuery selector to append a ul element.  Something like this:

```JavaScript
myUlElement.appendTo('body');
```

The UL is getting appended oto the body element in the foreignObject tab. The bug report I have filed with them is requesting that they make the selector more specific. Something like:

```JavaScript
myUlElement.appendTo(myUlElement.document.body);
```

However, I wanted to cross post this here, because of the following. In trying to reproduce the error, we noticed that when you actually put a foreignObject into an HTML file directly, when the browser renders the element it seems to remove the extra body tag. As seen here:

http://jsfiddle.net/jfcqa8pf/3/

This is the reason why this probably has not come up before. I am not sure why when you put the HTML directly in, the browser removes the body tag, but with JointJS it does not.  I am not sure this is a bug with JointJS at all, I just wanted to run it by the team.

One more thing to note, when you load the second fiddle, you will see that the xmlns from the body tag has mysteriously moved to the root body tag.

One possible recommendation might be to use a div tag as the root and just omit the body tag. The other option might be to actually namespace the body tag.  Something along the lines of:

```HTML
<foreignObject class="fobj" id="v-9" width="120" height="80" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xhtml:body>
    <div class="content" id="v-8" y="0.8em" display="none" xml:space="preserve" style="width: 120px; height: 80px;">
      <div>Some HTML</div>
    </div>
  </xhtml:body>
</foreignObject>
```

I am not really sure if either are exactly right or viable, but they might avoid this weirdness.

**Comment by kumilingus** [comment]
Hi Michael,

right, the `body` tag is not needed indeed. A single `<div/>` with the following CSS also centres the text inside the `div` both horizontally and vertically (I think that was the reason, we used the  `body` tag - extra container - in the first place).

```css
div {
    width: 100%;
    height: 100%;
    position: static;
    background-color: transparent;
    text-align: center;
    margin: 0px;
    padding: 0px 5px;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    justify-content: center;
}
```

**Comment by mmacfadden** [comment]
@kumilingus , thanks!  In fact, in our element I over road the "markup" property to basically do just that and it resolved our issue. So I can verify that, that would work, but there is work around for now!

```
export const TextBlockMarkup: string = [
  `<g class="rotatable">`,
  `<g class="scalable"><rect/></g>`,
  (joint as any).env.test(`svgforeignobject`) ?
    `<foreignObject class="fobj"><div xmlns="http://www.w3.org/1999/xhtml"><div class="content"/></div></foreignObject>` :
    `<text class="content"/>`,
  `</g>`
].join(``);
```

**Comment by kumilingus** [comment]
Please use [`standard.TextBlock`](https://github.com/clientIO/joint/blob/master/plugins/shapes/joint.shapes.standard.js#L472-L519) or the workaround @mmacfadden suggested above. Won't fix in `basic.TextBlock`.
