### ISSUE TITLE
link:disconnect event callback doesn't include old port id

### ISSUE THREAD

**Issue by jwmao** [clientIO/joint#788]
After I added a link by connecting two ports, I changed the link target to a different port by dragging the link arrowhead. 

From the link:disconnect event call back, I'd like to retrieve the old port id, but both link._previousAttributes and link.attributes don't include the new port id. See below debug console:

![screen shot 2018-01-05 at 5 16 46 pm](https://user-images.githubusercontent.com/4739720/34632622-2978915a-f23c-11e7-8d53-07269b0e8256.png)

Please advise. 

JointJS 1.1.0 Chrome: 63.0.3239.84

**Comment by kumilingus** [comment]
You can get the previous port id from the magnet element the link was disconnected from.
```javascript
paper.on('link:disconnect', function(linkView, evt, elementView, magnet) {
    var portId = magnet && magnet.getAttribute('port');
    if (portId) console.log('previous port:', portId);
});

paper.on('link:connect', function(linkView, evt, elementView, magnet) {
    var portId = magnet && magnet.getAttribute('port');
    if (portId) console.log('new port:', portId);
});
```
