### ISSUE TITLE
Hover on a Link

### ISSUE THREAD

**Issue by bolognesi** [clientIO/joint#791]
Hello,

when I connect two elements with a Link (directly, without adding vertex) the "focus" on the link is correct.
Meaning: the mouseover event is launched only when I am over the link.

Instead, when I add a vertex (i.e. no more a simple direct line), the focus is not only on the link.
The focus seems to be in an area bigger of the link.

This is a problem with large diagram, because it is not possible to select Elements.

Any hint?

Thanks
Thomas

**Comment by kumilingus** [comment]
It might have something to do with `fill="none"` attribute on the connection path. E.g.`fill="none"` does not capture pointer events as oppose to `fill="transparent"`.

Does the link look ok visually?
Did you customize the look of the link in any way?
Do you apply some custom CSS rules to the paper?

**Comment by bolognesi** [comment]
Thanks for the answer.
Yes, I applied a custom CSS rule on paper ( **paper.$el.css('pointer-events', 'all');** ), for enable users to play with elements of the diagram (previously the diagram was only read-only (paper.$el.css('pointer-events', 'none'); ).
I used this new rule:  **paper.$el.css('pointer-events', 'all');**  and all it is works.

Thanks
