### ISSUE TITLE
request(package): lodash

### ISSUE THREAD

**Issue by cojack** [clientIO/joint#794]
Hi,
Could you bump version of lodash up to ^4.x? 
Thanks in advance.

**Comment by jpsfs** [comment]
Hi!

This is indeed very important for security reasons. Related with #945.
@kumilingus can you please help?

Best,
jpsfs

**Comment by kumilingus** [comment]
Hi, sure, we'll upgrade Lodash version for the upcoming release.

**Comment by kumilingus** [comment]
Fixed in `v2.2.0`.
