### ISSUE TITLE
Incompatible TypeScript definitions in jointjs 2.0.1

### ISSUE THREAD

**Issue by noemi-salaun** [clientIO/joint#797]
Same issue as #582

The issue #582 is closed, but I still get the same error when using the NPM package `jointjs@2.0.1`

I copied the code of the example http://resources.jointjs.com/demos/devs

If I ignore the TypeScript compilation errors, this code works.

```typescript
import { dia, shapes } from 'jointjs'

const graph = new dia.Graph()

const paper = new dia.Paper({

  el           : document.getElementById('paper'),    // <- ERROR 1
  width        : 800,
  height       : 400,
  gridSize     : 1,
  model        : graph,    // <- ERROR 2
  snapLinks    : true,
  linkPinning  : false,
  embeddingMode: true,
  highlighting : {
    'default'  : {
      name   : 'stroke',
      options: {    // <- ERROR 3
        padding: 6,
      },
    },
    'embedding': {
      name   : 'addClass',
      options: {    // <- ERROR 3 bis
        className: 'highlighted-parent',
      },
    },
  },

  validateEmbedding: function (childView, parentView) {

    return parentView.model instanceof shapes.devs.Coupled    // <- ERROR 4
  },

  validateConnection: function (sourceView, sourceMagnet, targetView, targetMagnet) {

    return sourceMagnet !== targetMagnet
  },
})

// ... some code without errors ...

const c1 = new shapes.devs.Coupled({

  position: {
    x: 230,
    y: 50,
  },
  size    : {
    width : 300,
    height: 300,
  },
})

c1.set('inPorts', ['in'])    // <- ERROR 5
c1.set('outPorts', ['out 1', 'out 2'])    // <- ERROR 5 bis
```

- **Error 1:** `Object literal may only specify known properties, and 'el' does not exist in type 'Options'.`
- **Error 2:** `Object literal may only specify known properties, and 'model' does not exist in type 'Options'.`
- **Error 3:** `Object literal may only specify known properties, and 'options' does not exist in type 'GenericHighlighterJSON<HighlighterType>'.`
- **Error 4:** `Property 'model' does not exist on type 'ElementView'.`
- **Error 5:** `Property 'set' does not exist on type 'Coupled'.`

**Comment by noemi-salaun** [comment]
Maybe I can help and submit a PR. Your types are writed by hand ? Or are they generated from the JS code automatically ?
All your types are in the **types** directory ?
Do you use external types, for Backbones or other libraries for example ?

**Comment by noemi-salaun** [comment]
It looks like every Backbone types are ignored.

`Property 'on' does not exist on type 'Paper'.`

**Comment by noemi-salaun** [comment]
Installing the Backbone typings `npm install --save-dev @types/backbone` seems to solve the problem.
I'll continue my test, and close this issue if it solves all the problem.

**Comment by mmacfadden** [comment]
Yes, you definitely need to install the backbone types. We should probably put this in the dev dependencies of the npm package or something.

**Comment by noemi-salaun** [comment]
So, there is still some little incompatibility.

## ModelAttributes

`Object literal may only specify known properties, and 'id' does not exist in type 'shapes.devs.ModelAttributes'.`

## Paper.Options

The signature of `Options.interactive` is 

```ts
interactive?: ((cellView: CellView, event: string) => boolean) | boolean | CellView.InteractivityOptions
```

But in the case of interactive being a function, its return can be a `CellView.InteractivityOptions` too

**Comment by Siddharth-dubey** [comment]
@vtalas @mmacfadden Hey , the project is still not having compatible Typescript definitions

Getting same error as the OP:

> Argument of type '{ el: any; width: number; height: number; gridSize: number; model: Graph; }' is not assignable to parameter of type 'Options'.
>   Object literal may only specify known properties, and 'el' does not exist in type 'Options'.

Both el and model don`t exists in typings file.

Is there any expected ETA for this issue? or I can have a PR for the same?

**Comment by kumilingus** [comment]
> Both el and model don`t exists in typings file.

These are inherited from the Backbone's typings (`Backbone.View`).

**Comment by Siddharth-dubey** [comment]
@kumilingus  Thanks . 

`npm install @types/backbone --save-dev`

solves the issue. You can close it

**Comment by peisenmann** [comment]
Just came across this with a latest build, and I didn't especially notice any improvements to documentation to indicate it was needed.
