### ISSUE TITLE
Resize shape at the edges

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#801]
Hello,

**Goal:**
I would like to change the size of a shape by click-drag from any of its edges. 

**What I think would work?**
I think I need to write a custom HTML shapes for this and manually added div/span that users can click-drag to resize the shape.
- Need to write dragMoveListeners for each edge. 

**Question**
I am wondering if jointjs provides any resizable on shapes. 
I feel like I might have missed some key fields
For example,
 .resizable({
 edges: { left: true, right: true, bottom: true, top: true },
});

Any help is appreciated.

**Comment by Paul-Kijtapart** [comment]
Solved by creating a custom HTML ["https://resources.jointjs.com/tutorial/custom-elements"]

**Comment by pellmann** [comment]
@Paul-Kijtapart - Is it possible to see the solution with your custom HTML somewhere?

**Comment by DariaKalinina** [comment]
@pellmann Are you have the solution for resize the shape by user actions?
