### ISSUE TITLE
is the cell class have a 'render' function

### ISSUE THREAD

**Issue by xunonxyz** [clientIO/joint#803]
`    onChangeAttrs: function(cell, attrs, opt) {

        if (opt.dirty) {

            // dirty flag could be set when a model attribute was removed and it needs to be cleared
            // also from the DOM element. See cell.removeAttr().
            return this.render();
        }

        return this.update(cell, attrs, opt);
    },
`
i can not find where the render function is define

**Comment by kumilingus** [comment]
It's defined on the `Backbone.View`. The `CellView` is an abstract class. The actual `render()` methods are implement on the `LinkView` and `ElementView`.

**Comment by xunonxyz** [comment]
@kumilingus  but the cell class is not inhereit from the Backbone.View class, it is inhereit from the Backbone.model, so i think maybe there have a bug

**Comment by kumilingus** [comment]
The `onChangeAttrs()` method is defined on `joint.dia.CellView` and not on `joint.dia.Cell`.

**Comment by kumilingus** [comment]
Can we close the issue?
