### ISSUE TITLE
Workaroud on vector-effect="non-scaling-stroke" in IE11

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#817]
Browser version: Internet Explorer 11

**Goal**
When element size gets updated via model.set("size", newSize), the width of the stroke should not get updated.

**Current bahavior**
Given a shape with "<g class="scalable"><path></g>", when I set the size of the shape model.set("size", newSize), I notice that jointjs will update "transform:scale(newX, newY)"  on the <g class="scalable"> based on updated size.
This works very well in chrome, since 'vector-effect="non-scaling-stroke"' is working.
However, in Internet Explorer 11, vector-effect is not compatible, which results in a change in shape size causing changing stroke-width as well.

**Possible workarounds:**
(1) I am looking for some polyfill that will enable 'vector-effect="non-scaling-stroke"' in IE11
(2) I think I should look to update behavior of how jointjs works with "scalable" class to modify the size of its content instead of appending transform:scale(newX, newY) as this would results in change in size of path only.
(3) Set listener on "change:size" to 
3.1 remove scale attribute
3.2 used newSize to update shapes inside <g class="scalable"></g>

Currently, I cannot get (1) to work yet, so I decides to start working with (3) since that does not require change to jointjs.
I am wondering if there is other alternative to fix this issue.

Thank you very much.

**Comment by kumilingus** [comment]
Hi Paul, no. 2 is correct. We are currently in the process of dropping the scalable group usage in favour of special attributes (`refWidth`, `refHeight`,`refRx`, `refRy`, `refD`. `refPoint`, ...).

You can check out new shape definitions using this approach in the master branch (https://github.com/clientIO/joint/blob/master/plugins/shapes/joint.shapes.standard.js).

**Comment by Paul-Kijtapart** [comment]
Thank kumilingus for the quick response. I will check your link right away.

**Comment by Paul-Kijtapart** [comment]
**Install joint.shapes.standard**
I noticed that jointjs "^2.0.1" from "yarn add jointjs or npm install jointjs" does not come with plugins "joint.shapes.standard.js".

So I decide to copy the joint.shapes.standard.js file from the master branch and import it in.
I am able to create a shape from joint.shapes.stand (e.g. new joint.shapes.standard.Rectangle() works properly.)

**Issue**
However, when I tries to add the shape to the paper (i.e. graph.addCell(new joint.shapes.standard.Rectangle()), i run into  "TypeError: html.replace is not a function" from joint.js.

Could this be caused by markup in standard plugin (jointjs is not able to parse this markup)?
Could the solution be to, instead of using jointjs from npm, I need to build dist jointjs from the master branch to ensure jointjs is at latest version?

Again, thank you for your help.

**Comment by Paul-Kijtapart** [comment]
Updated:
joint.shapes.standard is amazing. 
The shapes are now updated without scaling the strokes.

Thank kumilingus for pointing this out.

**Comment by kumilingus** [comment]
The new `standard` shapes use JSON markup (this is a new feature for the next release). If you replace the markup with serialized XML and CSS selectors inside attrs, you can make it work (with one exception `shapes.Circle`, which uses a new `refR` attribute).
