### ISSUE TITLE
typescript error in version 2.0.0, 2.0.1 and a possible fix :)

### ISSUE THREAD

**Issue by fingerartur** [clientIO/joint#823]
```
(939,13): Property ''.connection'' of type 'SVGPathAttributes | undefined'
// is not assignable to string index type 'SVGAttributes'.
```
This is the error i get when trying to use jointjs in a react project with TypeScript (more specifically a facebook/create-react-app project).

I actually managed to work around it by going to node_modules/jointjs/dist/joint.d.ts at line 739 and changing the code from
```
interface Selectors {
            [selector: string]: attributes.SVGAttributes;
}
```
to
```
interface Selectors {
            [selector: string]: attributes.SVGAttributes | undefined;
}
```

I do not know whether is the correct way to fix it, so I am leaving that up to you guys, but it certainly allowed me to compile my code and use jointjs, which is probably good enough for me.

**Comment by melbourne2991** [comment]
Same error in 2.7.2

**Comment by kumilingus** [comment]
@fingerartur  It's good enough also for us :)  https://github.com/clientIO/joint/pull/853
