### ISSUE TITLE
Typescript definitions for DirectedLayout LayoutOptions incorrect

### ISSUE THREAD

**Issue by randy-stad** [clientIO/joint#829]
In Rappid 2.2 the typescript definitions for LayoutOptions on DirectedLayout have resizeCluster when it should be resizeClusters.  A diff from index.d.ts:

diff --git a/local/@types/rappid/index.d.ts b/local/@types/rappid/index.d.ts
index b107320e..489f7728 100644
--- a/local/@types/rappid/index.d.ts
+++ b/local/@types/rappid/index.d.ts
@@ -2227,7 +2227,7 @@ export namespace layout {
             rankSep?: number;
             marginX?: number;
             marginY?: number;
-            resizeCluster?: boolean;
+            resizeClusters?: boolean;
             clusterPadding?: dia.Padding;
             setPosition?: (element: dia.Element, position: dia.BBox) => void;
             setVertices?: boolean | ((link: dia.Link, vertices: dia.Point[]) => void);

**Comment by kumilingus** [comment]
Thank you @randy-stad, fixed in https://github.com/clientIO/joint/pull/834.
