### ISSUE TITLE
Html inside joint.shapes.devs.Model

### ISSUE THREAD

**Issue by Eymerich01** [clientIO/joint#840]
I should like insert HML inside joint.shapes.devs.Model but starting from release 1.0 seem to be joint.shapes.devs.ModelView missing.

**Comment by vtalas** [comment]
Hi, yes, the `devs.ModelView` has been removed as the shape `dev.Model` has been rewritten using the port API. With this API you don't need to define a custom view - ports can be added to any shape. 

If you need a custom view, you can still create one: 
```
joint.shapes.devs.ModelView = joint.dia.ElementView.extend({

});
```
