### ISSUE TITLE
How to create Element based on joint.shapes.devs.Model in TypeScript way?

### ISSUE THREAD

**Issue by MrBra1nwash** [clientIO/joint#843]
Hi. Awesome library. I try to build application based on JointJS and Angular 5. I am trying to create element with ports using `joint.shapes.devs.Model`. The main problem is with extending. I need to create basic class of the element and then inherit it in sub classes. 
When i am using `define`, for example: `BasicElement = joint.shapes.devs.Model.define(...)` and then i am trying to extend it with `SomeElement =BasicElement .define(...)` i am getting a TypeScript error `Property 'define' does not exist on type 'Constructor<Element>'.`
 I also tried to make it in class-oriented way, like:
`class BasicElement extends  joint.shapes.devs.Model {
  markup = <g class="scalable">
        <rect class="body"/>
    </g>;
  inPorts =  ['in'],
  ports = { ... }
}`
But it didn't work. How could i achieve class-oriented inheritance for element with ports? Thank you

**Comment by vtalas** [comment]
Hi, check the `ts-demo` app in the demo folder, it covers this. Extending is described in the `custom.ts`  (https://github.com/clientIO/joint/blob/master/demo/ts-demo/custom.ts)

Using the define is not enough, you also need to declare a new type:

implementation using `define`
```typescript
joint.shapes.basic.Rect.define('app.CustomRect', {
    attrs: {
        rect: {
            fill: 'red'
        }
    }
}, {
    test: function () {
        console.log("test");
    }
}, {
    staticTest: function () {
        console.log('staticTest');
    }
});
```
and "tell" the typescript about the new implementation of `app.CustomRect`

```typescript
declare module './build/joint' {
    namespace shapes {
        namespace app {
            class CustomRect extends joint.shapes.basic.Rect {
                test(): void;

                static staticTest(): void;
            }

            class Link extends joint.dia.Link {
            }
        }
    }
}
```

then you should be able to use the `joint.shapes.app.CustomRect` without TS error
