### ISSUE TITLE
Incorrect rounding of bounding boxes

### ISSUE THREAD

**Issue by vprus** [clientIO/joint#85]
In the implementation of VElement.bbox, on line 296 (https://github.com/DavidDurman/joint/blob/master/src/vectorizer.js#L296) there is this code:

    		// Opera returns infinite values in some cases.
		// Note that Infinity | 0 produces 0 as opposed to Infinity || 0.
		// We also have to create new object as the standard says that you can't
		// modify the attributes of a bbox.
		box = { x: box.x | 0, y: box.y | 0, width: box.width | 0, height: box.height | 0};

Since "|" is a bitwise operator, it appears Javascript first rounds up box.y and others. Suppose I have a circle with center y of 200.5, radius of 2 and stroke width of 1. Then, it spawn y coordiates from 198 through 201, exactly 5 pixels. However, the above code makes bbox y be 197.5. The same problem with x as well. The final consequence is that my connectors point just slightly off the center of the circle, and the connector lines end up between the pixels, and become blurry.

Could that line be modified to only invoked on Opera?

Thanks in advance.

**Comment by kumilingus** [comment]
Rounding remove in 2a5cc19d9845c7a2c7b4e3a13bef8ca743f8836a.
