### ISSUE TITLE
Prevent rappid from embeding link into common ancestor?

### ISSUE THREAD

**Issue by nico-onmap** [clientIO/joint#850]
I have a graph like this:

 - at the root of the graph there is one container: C1
 - C1 contains two containers: C2 & C3
 - C2 contains an element: E1
 - C3 contains an element: E2

If I have a link between E1 & E2 (which are in a separate container C2 & C3, and have C1 as common ancestor), clicking on C1 will call reparent() on the link, which will cause it to be embeded into C1 (the common ancestor of C2 & C3).

C2 & C3 will then visually cover the link which will appear hidden bellow these two containers.

See:

![links](https://user-images.githubusercontent.com/26772786/38261953-14c92a88-376c-11e8-8647-fe82aa80288f.png)

What could I do to make the link appear above C2 & C3 and not behind?

Chaning its z property will not work because once the user clicks on C1, the link gets embeded into C1 so its z property is modified.

**Comment by kumilingus** [comment]
Hi, I think the logic [here](https://github.com/clientIO/joint/blob/master/src/joint.dia.element.js#L736-L744) is wrong. We should bring links to front based on the elements they were connected to.

**Comment by nico-onmap** [comment]
@kumilingus any update on this?

**Comment by kumilingus** [comment]
@nico-onmap this [PR](https://github.com/clientIO/joint/pull/885) should resolve the issue.

**Comment by kumilingus** [comment]
Fixed with https://github.com/clientIO/joint/commit/a2375aa876b6887857b01833d9e5f4c6b8640a23.
