### ISSUE TITLE
"Discrete Event System Specification" demo buggy

### ISSUE THREAD

**Issue by mindplay-dk** [clientIO/joint#851]
I don't know if this is a bug in JointJS itself or just in the demo, but this looks wrong:

![coupled-routing](https://user-images.githubusercontent.com/103348/38493166-7e9fcfdc-3bf1-11e8-9835-d17f24d6d50c.gif)

That is, I'd expect connectors inside a coupled diagram to follow their parent - but as soon as you add anchor points to the connectors, they no longer follow their parent.

**Comment by kumilingus** [comment]
Hi Rasmus, a possible fix can be found [here](https://github.com/clientIO/joint/pull/884). Requires further testing though.

**Comment by kumilingus** [comment]
Fixed in https://github.com/clientIO/joint/pull/890.
