### ISSUE TITLE
ToFront & ToBack Not working when initialize shape/link with z value

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#862]
First of all, thank you for this amazing library. It is really fun to play with.

**Problem**
when a shape/link is created with default 'z' value, 'toFront' and 'toBack' will not work on them (i.e. unable to modify the 'z' values of those shapes)

**What I expect**
'toFront' and 'toBack' methods of dia.Element.prototype should works with/without initializing 'z' value of a shape.

JointJS version: JointJS v2.0.1 (2018-04-19)

**How to replicate steps:**
1. Get latest joint js file ( April 19, 2018)
- This is because I want to use joint.shapes.standard.js 

2. Build Distribution files:
```
grunt dist
```
we will get the latest JointJS distribution files.

3. Go to 'root_dir/demo/shapes/standard.html'

4. Make the following changes to 'standard.js'  (Working version)
```js
var graph = new dia.Graph();
var paper = new dia.Paper({
    el: document.getElementById('paper'),
    width: 650,
    height: 800,
    gridSize: 1,
    model: graph
});

var rectangle = new standard.Rectangle();
rectangle.resize(100, 100);
rectangle.position(50, 10); 
rectangle.attr('root/tabindex', 1);
rectangle.attr('root/title', 'joint.shapes.standard.Rectangle');
rectangle.attr('body/fill', '#FF0000');
rectangle.attr('label/fill', '#ffffff');
rectangle.attr('label/text', 'Rectangle');
rectangle.addTo(graph);

var circle = new standard.Circle();
circle.resize(100, 100);
circle.position(50, 10); // same position as rect to make circle on top of rect
circle.attr('root/tabindex', 2);
circle.attr('root/title', 'joint.shapes.standard.Circle');
circle.attr('body/fill', '#001fd0');
circle.attr('label/fill', '#ffffff');
circle.attr('label/text', 'Circle');
circle.addTo(graph);

// Move Circle to Back here
circle.toBack({deep: true}); // move Circle behind Rectangle above
```
The above code will results in Circle moving behind the Rectangle as expected.

**However,**  
if I initialize both Circle and Rectangle with { z : 1, and angle : 0 } as can be seen below: (Not-working version)
```js
var rectangle = new standard.Rectangle({
    // CHANGE here
    z: 1,
    angle: 0
});
rectangle.resize(100, 100);
rectangle.position(50, 10);
rectangle.attr('root/tabindex', 1);
rectangle.attr('root/title', 'joint.shapes.standard.Rectangle');
rectangle.attr('body/fill', '#FF0000');
rectangle.attr('label/fill', '#ffffff');
rectangle.attr('label/text', 'Rectangle');
rectangle.addTo(graph);

var circle = new standard.Circle({
   // CHANGE here
    z: 1,
    angle: 0
});
circle.resize(100, 100);
circle.position(50, 10); // same position as rect to make circle on top of rect
circle.attr('root/tabindex', 2);
circle.attr('root/title', 'joint.shapes.standard.Circle');
circle.attr('body/fill', '#001fd0');
circle.attr('label/fill', '#ffffff');
circle.attr('label/text', 'Circle');
circle.addTo(graph);

// Move Circle to Back here => This code will no longer work
circle.toBack({deep: true}); 
```
From above, neither 'toFront' or 'toBack' works. I believe this is because 'toFront' and 'toBack' are no longer able to modify the 'z' field of the Rectangle and Circle.

In addition to that, graph.fromJSON({ cells: [ {...} ]}) may not work as expected, when there is a cell with 'z' value. Since when a shape/link is created with 'z' value, 'toFront' or 'toBack' will not work.

**Current workaround**
I reverts jointjs to JointJS v2.0.1 i built in Feb 2018 and it does not have this behavior.
'toFront' and 'toBack' are always able to modify the 'z' value of a shape/link with or with out initialized 'z' value.
Please see toFront and toBack below (Old version)
```js
toFront: function(opt) {

        if (this.graph) {

            opt = opt || {};

            var z = (this.graph.getLastCell().get('z') || 0) + 1;

            this.startBatch('to-front').set('z', z, opt);

            if (opt.deep) {

                var cells = this.getEmbeddedCells({ deep: true, breadthFirst: true });
                cells.forEach(function(cell) { cell.set('z', ++z, opt); });

            }

            this.stopBatch('to-front');
        }

        return this;
    },

    toBack: function(opt) {

        if (this.graph) {

            opt = opt || {};

            var z = (this.graph.getFirstCell().get('z') || 0) - 1;

            this.startBatch('to-back');

            if (opt.deep) {

                var cells = this.getEmbeddedCells({ deep: true, breadthFirst: true });
                cells.reverse().forEach(function(cell) { cell.set('z', z--, opt); });
            }

            this.set('z', z, opt).stopBatch('to-back');
        }

        return this;
    },
```

**Comment by Paul-Kijtapart** [comment]
**Update**
After looking at joint.dia.Cell.js, this is what i found:
By setting 'z' value when creating a shape/link, even thought the shape is displayed correctly on the graph, its 'z' value does not change. 

Use Case:
1. create A at (0,0) with z = 1
2. create B at (0,0) with z = 1
3. B is on top of A since it is created after.
- At this point, the highest z should be 2 (since there are only 2 shapes)
- However, even though B is on top of A, both shapes have z = 1
- so, this.graph.maxZIndex() returns 1 instead of 2

4. this, then, make 'shouldUpdate' flag = false => No toFront action

**Expect solution**
From above use case, at step 3 when B is created on top of A, I was hoping that the 'z' value of B will be updated instead of using the passed-in 'z' value.

**Current solution**
I comment out the 'shouldUpdate' flag to ensure that toFront and toBack are always triggered.

**Comment by kumilingus** [comment]
Hi Paul,

good catch! Here's a [PR](https://github.com/clientIO/joint/pull/863) which should resolve the issue.

**Comment by Paul-Kijtapart** [comment]
Thank @kumilingus  for the quick response. 

**Update**
I have just done manual tests for both creating shape/link and graph.fromJSON(). 
toFront and toBack are now working for both cases.
