### ISSUE TITLE
Manhattan Routing + linkConnectionPoint

### ISSUE THREAD

**Issue by luis-carlos-campos** [clientIO/joint#880]
Are they expected to work together?

By default my links do not have a routing and I use linkConnectionPoint function to define a specific x,y for target/source points of the link.

However, I have a feature that calls manhattan so as to rearrange the links. When I execute it, manhattan always calculates the route based on the view and just ignores my x,y defined in linkConnectionPoint

![screen shot 2018-05-14 at 1 13 50 pm](https://user-images.githubusercontent.com/13797951/40009631-fc9a955a-5778-11e8-9b6c-484d2fd153c1.png)

Is it an expected behavior?

Thanks in advance!

**Comment by kumilingus** [comment]
It's been fixed in `v2.1`. Also `linkConnectionPoint` is now deprecated. Please use `defaultAnchor` and `defaultConnectionPoint` instead.

**Comment by luis-carlos-campos** [comment]
Thank you Roman
