### ISSUE TITLE
`link:disconnect` event not fired on link removal

### ISSUE THREAD

**Issue by MRxiongyu** [clientIO/joint#892]
I checked the official demo and used ‘link:disconnect’ when disconnected. The event did not fire and the  ‘link:connectt’  was normal. I hope to answer this question for me.

I use jointjs@2.1.2 
Chrome @66

This is my demo in the JSFiddle
[https://jsfiddle.net/quhxk6yc/](url)

**Comment by kumilingus** [comment]
I've replaced `alert()` calls with `console.log()` in your fiddle and I can see both events to trigger as expected. What is the scenario to see the event not to fire? Thank You.

**Comment by MRxiongyu** [comment]
link:disconnect  event can't trigger

**Comment by kumilingus** [comment]
What are your steps to reproduce? https://jsfiddle.net/quhxk6yc/1/
For instance, if I grab a link and reconnect it from a port to another both events were fired.

**Comment by MRxiongyu** [comment]
1. Click the link to delete the button
2. paper.on('link:disconnect', function(evt, x, y) {
  console.log('link:disconnect')
})  
No trigger

**Comment by kumilingus** [comment]
For the time being please listen to the graph instead.

```javascript
graph.on('remove', function(cell) {
  if (cell.isLink()) { /* do your logic */ }
});
```

**Comment by MRxiongyu** [comment]
ok , thank you

**Comment by Zilvinaskli** [comment]
same issue for me

**Comment by slavik-chapelskyi** [comment]
Still, reproduce for me. Is there any plan to fix this behavior?

**Comment by kumilingus** [comment]
If you use `joint.shapes.standard.Link` and `linkTools` you can override remove action as shown below.
```
new joint.linkTools.Remove({
            action: function(evt) {
                this.model.remove({ ui: true });
                // Note: `this.el` is not in the DOM anymore
                if (this.sourceView) {
                    this.notify('link:disconnect', evt, this.sourceView, this.sourceMagnet, 'source');
                }
                if (this.targetView) {
                    this.notify('link:disconnect', evt, this.targetView, this.targetMagnet, 'target');
                }
            }
});
```

If you use `joint.dia.Link` you need to override the `event` property on the `.tool-remove` node.
```
link.attr({ '.tool-remove': { event: 'link:remove' }});

paper.on('link:remove', function(view, evt) {
        view.model.remove({ ui: true });
        // Note: `this.el` is not in the DOM anymore
        if (view.sourceView) {
             view.notify('link:disconnect', evt, view.sourceView, view.sourceMagnet, 'source');
        }
        if (view.targetView) {
              view.notify('link:disconnect', evt, view.targetView, view.targetMagnet, 'target');
        }
});

**Comment by slavik-chapelskyi** [comment]
@kumilingus Thank for the solution.
