### ISSUE TITLE
Uncaught TypeError: Cannot set property '$' of undefined

### ISSUE THREAD

**Issue by Thaval** [clientIO/joint#907]
Hi,

I'm JointJS for my Angular 5. Unfortunately, I couldn't get this run without any errors yet.
Until now, I tried the Hello World example from the JointJS Website (which works flawless), but trying to get the "HTML Element within JS Element" example gives me headache (https://resources.jointjs.com/tutorial/html-elements). 

The error message is "Uncaught TypeError: Cannot set property '$' of undefined" and occurs in line 37.
The full context looks like this (reference name for further purpose: error context code):

```
var Backbone = root.Backbone;
       var _ = root._;
       var $ = Backbone.$ = root.jQuery || root.$;
```

root seems to be of type window, but it does not have any Backbone property.

Within my angular component, I do import the following:
`import * as $ from 'jquery';`
`import * as _ from 'lodash';`
`import * as Backbone from 'backbone';`
`const joint = require('../../../../../node_modules/jointjs/dist/joint.js');`

Creating the graph looks like this (which is the same as in the example from the website):
```
 let graph = new joint.dia.Graph;
    let paper = new joint.dia.Paper({
      el: $('#paper'),
      height: $('#graphContainer').height(),
      width: $('#graphContainer').width(),
      model: graph,
      gridSize: 10,
      background: {
        color: 'white'
      }
    });
    this.setGrid(paper, 15, 'black'); //needed as showGrid:true doesn't work

//Creating paper, define elements and element views
//......

//Create concrete html objects
var el1 = new joint.shapes.html.Element({
      position: { x: 80, y: 80 },
      size: { width: 170, height: 100 },
      label: 'I am HTML',
      select: 'one'
    });
```
My dependencies inside of the package.json file are:

```
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "jointjs": "~2.1.2",
    "jquery": "~3.3.1",
    "backbone": "~1.3.3",
    "lodash": "^3.10.1"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/jquery": "~3.3.4",
    "@types/lodash": "^3.10.1",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
```

Although Backbone is imported in my component, it is undefined in the error context code because root is a window object. The breakpoint that I set at line 37 (var Backbone = root.Backbone;) is hit when the application is loading. The webpack ClientApp folder in the dev tools is nearly empty.

Nevertheless, something is going on wrong and I dont know why, but I'm bound to that library.

The example of defining own html elements (or extend them), results in the following:
[Click here to see](http://fs1.directupload.net/images/180622/kxnbxkue.png), although it should like as shown [here](https://resources.jointjs.com/tutorial/html-elements).

Can you please me figuring out the problem?

**Comment by bidatacoder** [comment]
I have similar issue. If I follow the instruction to use node_modules file:
```npm
npm init
npm i -S jquery lodash backbone joint

...
+ backbone@1.3.3
+ jquery@3.3.1
+ lodash@4.17.10
+ jointjs@2.1.3
...
```

I cannot run the installation tutorial examples with errors (from Chrome Developer Tool):

```
Uncaught ReferenceError: module is not defined
    at index.js:1
backbone.js:382 Uncaught TypeError: Cannot read property 'extend' of undefined
    at backbone.js:382
    at backbone.js:31
    at backbone.js:34
joint.js:37 Uncaught TypeError: Cannot set property '$' of undefined
    at joint.js:37
    at joint.js:44
(index):28 Uncaught ReferenceError: joint is not defined
    at (index):28
```

-----------------------------------
But if I replace with cdn files such as the following, both examples run well.

```html
    <link rel="stylesheet" type="text/css"
                href="https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.1.3/joint.css" />

  <script src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
       crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.10/lodash.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.1.3/joint.js"></script>
```

**Comment by zbynekstara** [comment]
@Thaval I'm investigating your problem. I suspect there is a similar conflict between the dependencies installed and expected by `npm install --save jointjs` and dependencies you installed otherwise. Try to `require` the other dependencies from `node_modules` similarly to how you require jointjs:

```
const $ = require('../../../../../node_modules/jquery/dist/jquery.js');
const _ = require('../../../../../node_modules/lodash/index.js');
const Backbone = require('../../../../../node_modules/backbone/backbone.js');
const joint = require('../../../../../node_modules/jointjs/dist/joint.js');
```

Let me know if that helps.

**Comment by rostrowicki** [comment]
An angular-cli.json file should contains following declarations. I bet @Thaval had it without backbone related part because it leads to reported issue.

"scripts": [
    "../node_modules/jquery/dist/jquery.js",
    "../node_modules/lodash/index.js",
    "../node_modules/backbone/backbone.js",
    "../node_modules/jointjs/dist/joint.js"
  ]

Please have a look: https://stackoverflow.com/a/44175354/737602
