### ISSUE TITLE
Make links "stick" to complex object edges instead of only bounding box

### ISSUE THREAD

**Issue by DavidDurman** [clientIO/joint#91]
Currently, links "stick" to the bounding box of their associated elements. When paths/circles or other non-rectangular objects are used to render elements, there is a gap between the connection points of links and the non-rectangular objects. This effect can be eliminated by calculating the intersection point of the non-rectangular object and take this point as the connection point for the associated link.

**Comment by kumilingus** [comment]
Fixed with `joint.util.shapePerimeterConnectionPoint(linkView, view, magnet, ref)`.
