### ISSUE TITLE
[Question] Size of JointJS min

### ISSUE THREAD

**Issue by BoykoAlex** [clientIO/joint#911]
The size of `jointjs.min.js` grew to 384Kb from 258Kb in version 1.0.3.. Was there that much code added? Wonder if any of the optional JS can be omitted when i import `jointjs` package such as `.shapes.` modules.

**Comment by kumilingus** [comment]
Hi Alex,

looking at the changelog, there was indeed plenty of new code added (e.g. geometry 11Kb -> 50Kb).

You can use `joint.core.min.js` (287Kb), which contains only basic and standard shapes.

**Comment by BoykoAlex** [comment]
Thanks!-)
I consume `jointjs` as npm package dependency... It's unclear how to point to a `joint.core` in npm world... There is no `jointjs-core` package (or similar) published on npm, right?

**Comment by yfwz100** [comment]
@BoykoAlex Hi, you can use `resolve` feature in webpack to make alias to jointjs. 

The sample webpack.config.js looks like:

```js
module.exports = {
  // entry: { ... },
  // module: { ... }
  resolve: {
    jointjs$:
          mode != "production"
            ? "jointjs/dist/joint.js"
            : "jointjs/dist/joint.min.js",
  }
};
```
