### ISSUE TITLE
Unable to export to PNG custom icons

### ISSUE THREAD

**Issue by orius123** [clientIO/joint#913]
When I try to export to PNG graphs that contain custom font icons all I get is rectangles (unknown character..).
I have graph that have `text` elements with font-awesome unicode chars, I set the font-family attribute using CSS and in the html page it looks fine, but when exporting it to PNG/JPEG/SVG the icons are not there (just empty rectangles).
Tried to add font-family attribute to elements, to include font-face in the paper defs ref, and didn't get it to work.
Would appreciate your help very much!

**Comment by orius123** [comment]
## Expected:
<img width="389" alt="screen shot 2018-07-16 at 10 17 53" src="https://user-images.githubusercontent.com/4418018/42746811-573f799a-88e2-11e8-9a60-e4434b574af7.png">

## Actual:
![inv-116-canvas_mon_jul_16_2018](https://user-images.githubusercontent.com/4418018/42746829-661b5d76-88e2-11e8-96d0-d839517a1f6f.png)

**Comment by kumilingus** [comment]
Hi Eliya,

Export the PNG with a stylesheet including the font converted to data URI.

https://stackoverflow.com/a/11438280/2921495

```
paper.toPNG(callback, {
  stylesheet: '@font-face {  font-family: "My Font";  src: url("data:application/octet-stream;base64,BASE64FONT") format("svg");'
}
```

**Comment by orius123** [comment]
Works like a charm!
Thanks for the help!!
