### ISSUE TITLE
Resize an element with its embeded elements proportionally 

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#922]
Hello,

**Question**
I am wondering if there is a suggested way on how to resize an element with all its embeded elements proportionally

I expect embed elements to work similar to how each element treats its 'scalable group (<g class"scalable"/> group), where i can make use of refWidth and refHeight to auto-scale label inside an element.

**Goal**
I was playing with the [demo](https://resources.jointjs.com/demos/kitchensink). 
I found that when you make a selection (shift + click) with multiple elements, you can resize all of them proportionally.

**My current approach**
According to the tutorial on [hierarchy](https://resources.jointjs.com/tutorial/hierarchy), i believe i have to track the change in size of a parentElement (i.e. element that has embeded elemented).

```javascript
// if width increase by 5
widthChange = 5

// if height decreases by 2
heightChange = -2
```
Then, I will be able to update the size of all embeded elements based on the change in size of the parentElement.

**However**
Seeing that joint.dia.Element provides 'parentRealtive' for positioning embed elements, I wonder if there is something similar for resizing embed elements.

**jsfiddle**
In the following jsFiddle, you can click the parent element or child element to see how resize.
https://jsfiddle.net/coolbean/2zrtuqbm/31/

Any help is greatly appreciated.

**Comment by kumilingus** [comment]
Have you tried the `joint.dia.Graph.prototype.resizeCells()` yet? You pass `cells` you wish to resize (in your case an element with its embeds) and desired `width` and `height`.

**Comment by Paul-Kijtapart** [comment]
Hi @kumilingus ,

Thank you again for taking the time to help.

Yes, joint.dia.Graph.prototype.resizeCells() is definitely what i was looking for. 

in case anyone runs into similar issue:
```javascript
graph.resizeCells(width, height, cells, opt); // will resize all selected cells proportionally
```
