### ISSUE TITLE
click-move embeded element with z-index lower than its parent

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#923]
Hello,

**Given that:**
1. we have 3 elements Overlay, ChildA, and ChildB.
2. Overlay embed both Children.
3. Overlay has higher 'z' value than both Children.
4. As a result, a click on either child will trigger graph.on('cell:pointerdown', ...) with cell being the Overlay

**Question**
Is it possible to delegate the pointerdown event to ChildA even though ChildA has lower 'z' value than the Overlay?
(i.e. can i click and move ChildA under the Overlay?)

I am trying to do something similar to how PowerPoint works with specific element.

**jsFiddle**
https://jsfiddle.net/2zrtuqbm/61/

**Possible solution**
1. If i want to move ChildA, i have to do:
- db click ChildA to move it to front AND store orginal 'z' value of ChildA.
- Now that ChildA has higher 'z' value than that of the Overlay, graph.on('cell:pointerdown', ...) will now work on ChildA instead of the Overlay.
- after the move is completed, revert 'z' value of ChildA back to the original.

I am curious to know your thoughts.

Any help is greatly appreciated.

**Comment by kumilingus** [comment]
Does the overlay need to be interactive? You could set `pointer-events="none"` on the overlay.

**Comment by Paul-Kijtapart** [comment]
Hi @kumilingus ,

Thank you for the quick response.

**My goal** is to make the interaction with an Parent element with some children (i.e. embedded elements) to be similar to the interaction used in **PowerPoint**.

Referring to this jsFiddle, https://jsfiddle.net/2zrtuqbm/61/, 
please notice that a click-move on child will actually move the whole group. This is because the Parent element has higher 'z' value than the child. This is an expected behavior, as I want a regular click on any child to be delegated to the parent.

**However**, if user instead perform double-click, I hope that the action will now be on the child. 
Currently , this can be done via 
1. adjusting 'z' value (as described in the first post)

2. apply 'pointer-events="none"' on the parent. 
- i believe i need to add field 'isClicked' to my custom parent element.
- the action double-click = first pointerdown will toggle this 'isClicked' and apply 'pointer-events="none"'. This would allow later clicks on this groups to be on the children.
- if a user click on other elements/blank outside of this group, i just have to toggle the 'isClicked' status of the parent to make parent be interactive again ( 'pointer-events="auto"')
- the 'z' values of all elements in the group would remain the same.

**Thought**
the 2nd way seems simple and makes more sense to me.

**Comment by Paul-Kijtapart** [comment]
solved with 2nd way
