### ISSUE TITLE
'fitEmbeds' does not wrap rotated embedded elements properly.

### ISSUE THREAD

**Issue by Paul-Kijtapart** [clientIO/joint#924]
Hello,

**jsFiddle**
https://jsfiddle.net/coolbean/ebq62Lv0/26/

From the jsFiddle, you can see that the parent element is adjusting itself properly for position/size changes. However, if you move an element to a corner and rotates it, the parent does not adjust its size to wrap around that corner.

**What I expect?**
Element's 'fitEmbeds' method should take embedded element's angle into account to wrap around it.

**What actually happens?**
While 'fitEmbeds' method behaves perfectly for change in size/position of embedded children, 'fitEmbeds' does not seem to take change in angle into account.

Any help is greatly appreciated.

**Comment by kumilingus** [comment]
Hi Paul,

please try to override the `getCellsBBox()` graph method as follows.
```
joint.dia.Graph.prototype.getCellsBBox =  function(cells, opt) {

        return joint.util.toArray(cells).reduce(function(memo, cell) {
            if (cell.isLink()) return memo;
            var rect = cell.getBBox(opt);
            var angle = cell.angle();
            if (angle) rect = rect.bbox(angle);
            if (memo) {
                return memo.union(rect);
            } else {
                return rect;
            }
        }, null);
    };
```

**Comment by Paul-Kijtapart** [comment]
Hi @kumilingus,

Thank you very much!

it's working perfectly. 
The parent element is now wrapping around its embedded components after change in size/position/rotate.
