### ISSUE TITLE
Error update RAPPID 2.3.0 to 2.3.3

### ISSUE THREAD

**Issue by FrancoisJULIENNE** [clientIO/joint#937]
Hi,

i'm update RAPPID 2.3.0 to 2.3.3, and i have this error : 
`ERROR in rappid/build/rappid.min.d.ts(5142,34): error TS2503: Cannot find namespace 'jQuery'.`

In "Build/rappid.min.d.ts" : 
`    class TextEditor extends mvc.View<undefined> `

thx for your help !

Francois

**Comment by kumilingus** [comment]
Hi Francois,  try to find and replace all `jQuery` with `JQuery` in the `rappid.mind.d.ts`. We have to address this issue in the very next patch release. I'm sorry for inconveniences.

**Comment by kumilingus** [comment]
Fixed in `Rappid v2.4.0`.
