### ISSUE TITLE
gap between background image and bounding box

### ISSUE THREAD

**Issue by wwshunan** [clientIO/joint#938]
Following the below code
"var image = new joint.shapes.basic.Image({
    position : {
        x : 50,
        y : 40
    },
    size : {
        width : 16,
        height : 16
    },
    attrs : {
        image : {
            "xlink:href" : "images/background.png",
            width : 16,
            height : 16
        }
    }
});
", certainly there is a gap between image and bounding box. Links are "sticked" to the bounding box, and how to make links "stick" to the image? Can the end points of links move freely(not stick at the edge centers, for example)?

**Comment by kumilingus** [comment]
> certainly there is a gap between image and bounding box

There is a gap if the image ratio does not match the model's size and `preserveAspectRatio` SVG attribute is set to something other than `none`.

> Links are "sticked" to the bounding box, and how to make links "stick" to the image? Can the end points of links move freely(not stick at the edge centers, for example)?

Yes, it's possible.

```javascript
// connection point is at always at the anchor point
joint.paper.defaultConnectionPoint = { name: 'anchor' }
// an example of a custom position of the anchor
joint.paper.defaultAnchor = { name: 'left', { args: { dx: 10 }}}
```

The anchor point can be also changed via UI with Source Anchor link tool (https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#linkTools.SourceAnchor).

**Comment by wwshunan** [comment]
var image = new joint.shapes.basic.Image({
position : {
x : 50,
y : 40
},
size : {
width : 16,
height : 16
},
**preserveAspectRatio:** "xMidYMax meet",
attrs : {
image : {
"xlink:href" : "images/background.png",
width : 16,
height : 16
}
}
});
Thanks for your reply.  I add preserveAspectRatio like above and the gap still exist. Could you correct the error of the above code?

**Comment by kumilingus** [comment]
`preserveAspectRatio` is an SVG attribute (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio). Maybe you don't actually want the image to loose its aspect ratio? Could you send some screenshot?

```
var image = new joint.shapes.basic.Image({
position : {
x : 50,
y : 40
},
size : {
width : 16,
height : 16
},
attrs : {
  image : {
    "xlink:href" : "images/background.png",
    preserveAspectRatio: "none",
    width : 16,
    height : 16
  }
}
});
```

**Comment by wwshunan** [comment]
![screenshot from 2018-08-27 17-24-50](https://user-images.githubusercontent.com/7390307/44652413-6c72be00-aa1e-11e8-9b34-5ee665491c42.png)
{
                position: {
                    x: start,
                    y: 10
                },
                size: {
                    width: 100,
                    height: 100,
                },
                attrs: {
                    image: {
                        'xlink:href': 'RFQ.jpg',
                        width: 100,
                        height: 100,
                        preserveAspectRatio: "xMidYMid meet",
                    },
                },
            },

**Comment by wwshunan** [comment]
Sorry, I mislead you meaning. After I set preserveAspectRatio to none. It's correct now. Thank you!

**Comment by kumilingus** [comment]
That was just an example. See more about anchors [here](https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#anchors.intro) and connection points [here](https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#connectionPoints.intro).

**Comment by wwshunan** [comment]
Hi kumilingus, I finally get it work by appling link.source and link.target. Thank you!
