### ISSUE TITLE
Link area filled in black

### ISSUE THREAD

**Issue by candronikos** [clientIO/joint#944]
Same as issue #568 except using:

* `import 'jointjs/dist/joint.css';` - Makes the whole area go blank.
* `<link rel="stylesheet" href="%PUBLIC_URL%/joint.css" />` - In `index.html` makes the whole area go blank
* `import 'jointjs/css/themes/default.css';` - only fixes the arrow head colour. But the nodes still show

Is there something I'm missing here about using jointjs with jsx?

**Comment by kumilingus** [comment]
The CSS styles are not loaded. Could you create a JSFiddle that demonstrates the issue?
Also if possible use `joint.shapes.standard.Link` over `joint.dia.Link` (legacy). These require no external stylesheet and are much faster.

**Comment by candronikos** [comment]
I was able to use the `joint.shapes.standard.Link` as you suggested and that did fix the issue since it doesn't rely on CSS.

Not sure how to reproduce since I was using [create-react-app](https://github.com/facebook/create-react-app) to begin development. From there, importing the other CSS files seems to work, it's just that it fails when using `import 'jointjs/dist/joint.css';` in the waydescribed above

**Comment by kumilingus** [comment]
I am not really a `react` guy. I hoped the community can help here.
You said that `import 'jointjs/css/themes/default.css';` was applied correctly (default.css  contains only colours). Why is the whole area blank when you use  `import 'jointjs/dist/joint.css';`? Can you investigate (see the web inspector and check the DOM)? Thanks

**Comment by zncolaco** [comment]
@candronikos Given it's breaking when importing css via the import statements, it is possible that local css scoping([css-modules](https://github.com/css-modules/css-modules)) is throwing off the css class names for JointJS (e.g. via Webpack's css-loader, or similar).

I'm not sure about the exact setup of the create-react-app project, however this might be something worth looking in to. You can usually tell this by looking at the class names of other elements on your page and seeing whether an autogenned prefix/suffix has been added. If this does turn out to be the case, the fix may be as simple as adding an exclude rule for JointJS css files in your webpack configuration.

**Comment by candronikos** [comment]
I checked and I don't see any extra tag prefixes from react.

This is just an FYI. While I can't make the grid visible, I'm able to add custom nodes and select the routing strategy among other things.

**Comment by LordHeImchen** [comment]
I have the same issue, when downloading the graph displayed on the canvas as SVG.
As long as my links do not contain any vertices, everything works fine. As soon as vertices are added, the whole link area is rendered black (only in the downloaded SVG-file). The following picture displays the issue:

<img width="215" alt="Bildschirmfoto 2022-03-24 um 13 19 47" src="https://user-images.githubusercontent.com/72173812/159914873-c0a9ea3a-5b23-4db0-98a4-6b3a3024cf96.png">

I am using the following code to create a link:
```
new joint.shapes.pn.Link({
        source: { id: a.id, selector: '.root' },
        target: { id: b.id, selector: '.root' },
        // creates little jumps over other links
        connector: { name: 'jumpover',
                     args: { size: 5 }
        },
        z: -1,
        attrs: { 
          text: {
            fill: '#000000',
            fontSize: 10,
            textAnchor: 'middle',
            textVerticalAnchor: 'middle',
            yAlignment: 'bottom',
            pointerEvents: 'cell:pointerdblclick',
            cursor: "move",
          },
          '.connection': {
              'fill': 'none',
              'stroke-linejoin': 'round',
              'stroke-width': '2',
              'stroke': '#4b4a67', // '#7a7e9b'
          },
        },
        // Hides the standard background-rect of the label
        defaultLabel: {
          markup: [{ tagName: 'text', selector: 'text' }],
          attrs: {
              text: {
                  fill: '#000000',
                  fontSize: 10,
                  textAnchor: 'middle',
                  textVerticalAnchor: 'middle',
                  yAlignment: 'bottom',
                  pointerEvents: 'none'
              }
          },
        },
        labels: [
          {
            attrs: {text: { text: "1.00" }}, 
            position: {args: { keepGradient: true, ensureLegibility: true }}
          }
        ]
    });
```

And that is the way I am downloading the SVG:

```
    let svg = (<Node> document.querySelector('svg'));
    if (svg == null) {
      console.log("There is no SVG to be saved.");
    } else {
      let data = (new XMLSerializer()).serializeToString(svg);
      let blob = new Blob([data], {type: 'image/svg+xml;charset=utf-8'});
      let url = URL.createObjectURL(blob);
      let a = document.createElement('a');

      a.setAttribute('download', 'image.svg');
      a.setAttribute('href', url);
      a.setAttribute('target', '_blank');
      a.click();
    }
```

Does anyone have an idea how to resolve this?

**Comment by kumilingus** [comment]
You are missing CSS rules (https://github.com/clientIO/joint/blob/master/css/layout.css#L101-L104) in the exported SVG.

1. Add the missing `fill: none` to `.connection-wrap` to the shape definition.
```
 attrs: { 
  text: {
    fill: '#000000',
    fontSize: 10,
    textAnchor: 'middle',
    textVerticalAnchor: 'middle',
    yAlignment: 'bottom',
    pointerEvents: 'cell:pointerdblclick',
    cursor: "move",
  },
  '.connection': {
      'fill': 'none',
      'stroke-linejoin': 'round',
      'stroke-width': '2',
      'stroke': '#4b4a67', // '#7a7e9b'
  },
  '.connection-wrap': {
     'fill': 'none'
  }
},
```
2. Export the missing CSS as part of the paper
``` js
const linkStyle = V.createSVGStyle(`
  .joint-link .connection-wrap,
  .joint-link .connection {
    fill: red;
  }
`);
paper.svg.prepend(linkStyle);
// export the SVG
```

**Comment by LordHeImchen** [comment]
Well, I defined that part in an overall basic CSS-file which is imported at the beginning.
But the second part (red exchanged with none, obviously) resolved my problem.

Thanks a lot for the quick response!

**Comment by kumilingus** [comment]
The external CSS is not exported when you serialize a DOM node with XMLSerializer. That's why no. 1 added `fill: none` as an SVG DOM attribute to every link and no 2. inserted `<style>` tag inside the exported SVG.
