### ISSUE TITLE
Update dependencies for security

### ISSUE THREAD

**Issue by kadosh1000** [clientIO/joint#945]
Since npm 6, now npm alters the users about known security vulnerabilities in used packages.
It seems that because jointjs uses an old and not secured version of lodash,  it reports it during the dependencies installation.

I would very much appreciate if you can update the dependencies.

Thanks

**Comment by telmotrooper** [comment]
I'd like to reiterate @kadosh1000's question, since anyone would like to avoid introducing vulnerabilities in their applications, especially through code they haven't written themselves and don't have the understanding to easily fix...

**Comment by kumilingus** [comment]
Fixed in `v2.2.0`.
