### ISSUE TITLE
Conflict between click event and element.toFront()

### ISSUE THREAD

**Issue by MarcDelp** [clientIO/joint#958]
Hello,

I have a Rappid component that embeds different sub-components to have multiple answer in a dialog.

Here is the component:

![image](https://user-images.githubusercontent.com/11720439/45671400-a454b900-bb25-11e8-8139-6762cacec3cc.png)

When you click on the "+" button, you can add a new answer in the component. This is the event I am listening to in my component view:

```javascript
events: {
  'click .btn-add-answer': 'onAddAnswer',
}
```

It seems that this action conflicts with the action of putting the element to the front of the graph. I have this kind of code:

```javascript
paper.on('cell:pointerdown', (cellView, evt, x, y) => {
  let cell = cellView.model;
  cell.toFront({ ignoreCommandManager: true });
}
```

In fact, if the component is already in the front view, it has the expected behaviour (I can add the new answer in the component). But if the component is not in the front view, for example if I have answer components embedded in it and at the front view, i need to double click on the "+" button to be able to add a new answer.

Is this a known / wanted behaviour from JointJS ? If so, how can I avoid this behaviour to be able to always add new answer when clicking on the "+" button ?

Thanks

**Comment by kumilingus** [comment]
try to call `evt.stopPropagation()` inside the `onAddAnswer` handler.

**Comment by MarcDelp** [comment]
It does not work.

In fact, the `onAddAnswer` method is not even called when I am doing a single click on the "+" button.

**Comment by kumilingus** [comment]
I see. Try to listen to `mousedown` and `touchstart` in the `events` object (`click` comes after pointerdown). I bet, this is happening in the Chrome browser only (
https://bugs.chromium.org/p/chromium/issues/detail?id=5212). Altenatively, you can use the `event` attribute (https://resources.jointjs.com/docs/jointjs/v2.1/joint.html#dia.attributes.event).

**Comment by MarcDelp** [comment]
You are right, it only happens on Chrome.

Thank you, changing the events listened to in my view solved the problem.
