### ISSUE TITLE
Can't access elements attributes after they have been rendered

### ISSUE THREAD

**Issue by jtwnel** [clientIO/joint#961]
Hi, 

I'm using JointJS along with React/Redux. I have a problem when trying to access my elements attributes after I've added them to the Graph. When I create the element I can access its attributes just fine, but I dont understands what happens when the graph has it, I use graph.getCell(id) to obtain the element but its like the attributes were not there altough I see the values on screen. 
Are there any known issues when using JointJS with React/Redux? especially on the inmutability side

Thanks!

**Comment by kumilingus** [comment]
Hi, could you send us an example of how you use it?

**Comment by Priyansh121096** [comment]
@jtwnel Are you setting custom attributes? If so, could you try using `Element.prop` instead of `Element.attr`? Ignore if you're already doing that.
