### ISSUE TITLE
Removing Elements

### ISSUE THREAD

**Issue by tahirnawaz** [clientIO/joint#97]
I want to implement a functionality in which when I click on joint.js node extended by backbone view a div should appear around this element which will contain cross button and arrow button. When clicked on cross the node should be removed from paper of joint js when clicked on arrow user should be able to draw arrow. when click on other part of paper that div around element should disappear. I am following this link http://jointjs.com/tutorial/html-elements. what is the best approach of implementing this functionality as my own approach of hiding and showing divs around element is not working.

**Comment by kumilingus** [comment]
Please use Google Groups or Stackoverflow in order to get an advice on this. Cheers.
