### ISSUE TITLE
Async option

### ISSUE THREAD

**Issue by ReccaFlames** [clientIO/joint#980]
Async option in paper can't be set but is used in code

**Comment by ReccaFlames** [comment]
joint.dia.Paper in options doesn't have async parameter. When i add it manually functionality related to this option starts work.

`
    className: 'paper',

    options: {

        width: 800,
        height: 600,
        .
        .
        .
        //Async render
        async: null
    },`

This is how I used it

`var paper = new joint.dia.Paper({
  el: document.getElementById('myholder'),
  model: graph,
  width: 600,
  height: 100,
  gridSize: 1,
  async: true,
  interactive: true,
  background: {
  	color: "#eee",
  },
});`

I am using joint.js version v2.1.4

**Comment by kumilingus** [comment]
What error do you see, when you use `async` option? Is that a Typescript error?

**Comment by ReccaFlames** [comment]
I have no error occurring when I am setting this property to true or false. I diagnoze that because when I try to catch event _render:done_ with a _async_ property set to _true_, according to the documentation, It doesn't fire anyway.

**Comment by ReccaFlames** [comment]
Here is an example 
https://jsfiddle.net/rahdpkw6/16/

**Comment by kumilingus** [comment]
`render:done` is triggered after `addCells()` and `resetCells()` as mentioned in the  [docs](http://resources.jointjs.com/docs/jointjs/v2.1/joint.html#dia.Paper.prototype.options.async).

https://jsfiddle.net/kumilingus/5esyt7hn/
